const rums = [
  {
    id: 1,
    name: "Bacardi Superior Rum",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bacardi-superior.jpg",
    description: "Smooth and clean with subtle notes of almond and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Bacardi",
    rating: 4.5,
    reviews: "A versatile white rum perfect for cocktails.",
    origin: "Puerto Rico",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Captain Morgan Original Spiced Rum",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/captain-morgan.jpg",
    description: "Bold and spicy with a blend of Caribbean spices.",
    category: "Rum",
    abv: 35,
    size: "750ml",
    brand: "Captain Morgan",
    rating: 4.7,
    reviews: "A popular spiced rum perfect for mixing.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Mount Gay Eclipse Rum",
    price: 29.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/mount-gay.jpg",
    description: "Smooth and aromatic with notes of banana and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Mount Gay",
    rating: 4.8,
    reviews: "A classic rum with a rich heritage.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Havana Club Anejo 3 Anos",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/havana-club.jpg",
    description: "Smooth and mellow with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Havana Club",
    rating: 4.6,
    reviews: "A premium Cuban rum perfect for cocktails.",
    origin: "Cuba",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Appleton Estate Signature Blend",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/appleton-estate.jpg",
    description: "Rich and complex with notes of fruit and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Appleton Estate",
    rating: 4.8,
    reviews: "A premium Jamaican rum with a distinctive flavor.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Ron Zacapa Centenario 23",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/ron-zacapa.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Zacapa",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Guatemala",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Plantation 3 Stars White Rum",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/plantation-3-stars.jpg",
    description: "Smooth and clean with notes of citrus and vanilla.",
    category: "Rum",
    abv: 41.2,
    size: "750ml",
    brand: "Plantation",
    rating: 4.7,
    reviews: "A versatile white rum perfect for cocktails.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Diplomatico Reserva Exclusiva",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/diplomatico.jpg",
    description: "Rich and complex with notes of toffee and orange peel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Diplomatico",
    rating: 4.8,
    reviews: "A premium Venezuelan rum with a distinctive flavor.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Kraken Black Spiced Rum",
    price: 26.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/kraken.jpg",
    description: "Bold and spicy with notes of cinnamon and vanilla.",
    category: "Rum",
    abv: 47,
    size: "750ml",
    brand: "Kraken",
    rating: 4.7,
    reviews: "A popular spiced rum with a unique flavor profile.",
    origin: "Trinidad and Tobago",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Flor de Cana 12 Year Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/flor-de-cana.jpg",
    description: "Smooth and rich with notes of vanilla and honey.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Flor de Cana",
    rating: 4.8,
    reviews: "A premium Nicaraguan rum with a complex flavor.",
    origin: "Nicaragua",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Don Q Cristal Rum",
    price: 19.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/don-q-cristal.jpg",
    description: "Smooth and clean with a crisp finish.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Don Q",
    rating: 4.5,
    reviews: "A versatile white rum perfect for mixing.",
    origin: "Puerto Rico",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Gosling's Black Seal Rum",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/goslings.jpg",
    description: "Rich and complex with notes of caramel and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Gosling's",
    rating: 4.7,
    reviews: "A popular dark rum with a distinctive flavor.",
    origin: "Bermuda",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Angostura 1919 Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/angostura.jpg",
    description: "Smooth and aromatic with notes of vanilla and toffee.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Angostura",
    rating: 4.7,
    reviews: "A premium Trinidadian rum with a rich flavor profile.",
    origin: "Trinidad and Tobago",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Pyrat XO Reserve Rum",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pyrat.jpg",
    description: "Rich and smooth with notes of orange and honey.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Pyrat",
    rating: 4.6,
    reviews: "A premium rum with a distinctive citrus flavor.",
    origin: "Guyana",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Barbancourt 5 Star Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/barbancourt.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Barbancourt",
    rating: 4.8,
    reviews: "A premium Haitian rum with a rich flavor profile.",
    origin: "Haiti",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Chairman's Reserve Spiced Rum",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chairmans.jpg",
    description: "Bold and spicy with notes of cinnamon and nutmeg.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Chairman's Reserve",
    rating: 4.7,
    reviews: "A premium spiced rum with a distinctive flavor.",
    origin: "Saint Lucia",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "El Dorado 12 Year Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/el-dorado.jpg",
    description: "Rich and smooth with notes of caramel and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "El Dorado",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Guyana",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Atlantico Reserva Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/atlantico.jpg",
    description: "Smooth and rich with notes of toffee and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Atlantico",
    rating: 4.7,
    reviews: "A premium rum with a distinctive flavor.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Blackwell Black Gold Rum",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/blackwell.jpg",
    description: "Rich and bold with notes of chocolate and coffee.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Blackwell",
    rating: 4.6,
    reviews: "A distinctive dark rum with a unique flavor profile.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Clément VSOP Rhum Agricole",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/clement.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Clément",
    rating: 4.8,
    reviews: "A premium aged rhum agricole with a rich flavor profile.",
    origin: "Martinique",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Rhum Barbancourt 3 Star",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/rhum-barbancourt.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Rhum Barbancourt",
    rating: 4.7,
    reviews: "A premium Haitian rum with a distinctive flavor.",
    origin: "Haiti",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Bayou Spiced Rum",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bayou.jpg",
    description: "Bold and spicy with notes of cinnamon and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Bayou",
    rating: 4.6,
    reviews: "A distinctive spiced rum with a rich flavor profile.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Pusser's British Navy Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pussers.jpg",
    description: "Rich and bold with notes of caramel and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Pusser's",
    rating: 4.7,
    reviews: "A classic navy rum with a distinctive flavor.",
    origin: "British Virgin Islands",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Don Papa Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-papa.jpg",
    description: "Smooth and rich with notes of vanilla and honey.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Don Papa",
    rating: 4.8,
    reviews: "A premium Filipino rum with a distinctive flavor.",
    origin: "Philippines",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Santa Teresa 1796 Rum",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/santa-teresa.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Santa Teresa",
    rating: 4.8,
    reviews: "A premium Venezuelan rum with a rich flavor profile.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Banks 5 Island Rum",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banks.jpg",
    description: "Smooth and aromatic with notes of fruit and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Banks",
    rating: 4.7,
    reviews: "A premium white rum with a distinctive flavor profile.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Zaya Gran Reserva Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/zaya.jpg",
    description: "Rich and smooth with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Zaya",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Trinidad and Tobago",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Rhum J.M VSOP",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/rhum-jm.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Rhum J.M",
    rating: 4.8,
    reviews: "A premium aged rhum agricole with a rich flavor profile.",
    origin: "Martinique",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Stolen Smoked Rum",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/stolen.jpg",
    description: "Bold and smoky with notes of coffee and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Stolen",
    rating: 4.6,
    reviews: "A distinctive smoked rum with a unique flavor profile.",
    origin: "Trinidad and Tobago",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Real McCoy 12 Year Rum",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/real-mccoy.jpg",
    description: "Smooth and rich with notes of vanilla and toffee.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Real McCoy",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Ron Abuelo 12 Year Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ron-abuelo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Abuelo",
    rating: 4.8,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Panama",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Kirk and Sweeney 12 Year Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/kirk-sweeney.jpg",
    description: "Smooth and complex with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Kirk and Sweeney",
    rating: 4.8,
    reviews: "A premium aged rum with a rich flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Rum Fire White Overproof Rum",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/rum-fire.jpg",
    description: "Bold and fiery with a high alcohol content.",
    category: "Rum",
    abv: 63,
    size: "750ml",
    brand: "Rum Fire",
    rating: 4.6,
    reviews: "A distinctive overproof rum with a unique flavor profile.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Brugal 1888 Rum",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/brugal.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Brugal",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Rhum Clément Select Barrel",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/rhum-clement.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Rhum Clément",
    rating: 4.7,
    reviews: "A premium aged rhum agricole with a rich flavor profile.",
    origin: "Martinique",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Papa's Pilar Dark Rum",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/papas-pilar.jpg",
    description: "Smooth and rich with notes of caramel and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Papa's Pilar",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Bayou Select Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/bayou-select.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Bayou",
    rating: 4.7,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Ron Matusalem Gran Reserva 15",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ron-matusalem.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Matusalem",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Plantation Original Dark Rum",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/plantation-dark.jpg",
    description: "Rich and complex with notes of banana and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Plantation",
    rating: 4.7,
    reviews: "A premium dark rum with a distinctive flavor profile.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Mount Gay Black Barrel Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/mount-gay-black-barrel.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Mount Gay",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Ron Centenario 20 Year Rum",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/ron-centenario.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Centenario",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Costa Rica",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Rhum J.M XO",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/rhum-jm-xo.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 45,
    size: "750ml",
    brand: "Rhum J.M",
    rating: 4.9,
    reviews: "A premium aged rhum agricole with a rich flavor profile.",
    origin: "Martinique",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "St. Lucia Distillers 1931",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/st-lucia.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "St. Lucia Distillers",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Saint Lucia",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Foursquare Rum Distillery",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/foursquare.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Foursquare",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Ron Barcelo Imperial",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ron-barcelo.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Barcelo",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Rhum Barbancourt Estate Reserve 15 Year",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/rhum-barbancourt-15.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Rhum Barbancourt",
    rating: 4.9,
    reviews: "A premium aged rum with a rich flavor profile.",
    origin: "Haiti",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Ron Matusalem Solera 23",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/ron-matusalem-23.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Matusalem",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Don Q Gran Anejo Rum",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-q-gran-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Don Q",
    rating: 4.8,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Puerto Rico",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Flor de Cana 18 Year Rum",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/flor-de-cana-18.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Flor de Cana",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Nicaragua",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "El Dorado 15 Year Rum",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/el-dorado-15.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "El Dorado",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Guyana",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Ron Abuelo Centuria",
    price: 89.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/ron-abuelo-centuria.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Abuelo",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Panama",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Plantation XO 20th Anniversary",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/plantation-xo.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Plantation",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Zafra 21 Year Rum",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/zafra.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Zafra",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Panama",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Mount Gay XO Rum",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/mount-gay-xo.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Mount Gay",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Clément XO Rhum Agricole",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clement-xo.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Rum",
    abv: 42,
    size: "750ml",
    brand: "Clément",
    rating: 4.9,
    reviews: "A premium aged rhum agricole with a rich flavor profile.",
    origin: "Martinique",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Havana Club Selección de Maestros",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/havana-club-maestros.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 45,
    size: "750ml",
    brand: "Havana Club",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Cuba",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Barceló Imperial Onyx",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/barcelo-onyx.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Barceló",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Appleton Estate 21 Year",
    price: 119.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/appleton-21.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Appleton Estate",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Dictador 20 Year Rum",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dictador.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Dictador",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Colombia",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Diplomatico Ambassador Selection",
    price: 199.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/diplomatico-ambassador.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 47,
    size: "750ml",
    brand: "Diplomatico",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Brugal 1888 Doblemente Anejado",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/brugal-1888.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Brugal",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Ron Cartavio XO",
    price: 69.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/cartavio-xo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Cartavio",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Peru",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "English Harbour 1981 Vintage",
    price: 119.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/english-harbour.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "English Harbour",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Antigua",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Foursquare 2004 Vintage",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/foursquare-2004.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 59,
    size: "750ml",
    brand: "Foursquare",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Ron Quorhum 30 Aniversario",
    price: 149.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/ron-quorhum.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Quorhum",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Appleton Estate Joy Anniversary Blend",
    price: 199.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/appleton-joy.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 45,
    size: "750ml",
    brand: "Appleton Estate",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "El Dorado 21 Year Rum",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-dorado-21.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "El Dorado",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Guyana",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Dictador Best of 1977",
    price: 399.99,
    quantity: 2,
    imageUrl: "https://www.example.com/images/dictador-1977.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 42,
    size: "750ml",
    brand: "Dictador",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Colombia",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Pusser's 15 Year",
    price: 69.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/pussers-15.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Pusser's",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "British Virgin Islands",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Brugal Papa Andres",
    price: 799.99,
    quantity: 1,
    imageUrl: "https://www.example.com/images/brugal-papa.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Brugal",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Mount Gay 1703 Master Select",
    price: 149.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/mount-gay-1703.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Mount Gay",
    rating: 5.0,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Diplomatico Single Vintage",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/diplomatico-vintage.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Diplomatico",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Ron Millonario XO",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/ron-millonario-xo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Millonario",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Peru",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Barceló Imperial Premium Blend 30 Aniversario",
    price: 149.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/barcelo-premium.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Barceló",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Flor de Cana V Generaciones",
    price: 399.99,
    quantity: 2,
    imageUrl: "https://www.example.com/images/flor-de-cana-generaciones.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Flor de Cana",
    rating: 5.0,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Nicaragua",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Papa's Pilar Sherry Cask",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/papas-pilar-sherry.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Papa's Pilar",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Ron Abuelo XV Napoleon",
    price: 89.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/ron-abuelo-xv.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Abuelo",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Panama",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Plantation Stiggins' Fancy Pineapple Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/plantation-pineapple.jpg",
    description: "Smooth and rich with notes of pineapple and vanilla.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Plantation",
    rating: 4.8,
    reviews: "A distinctive flavored rum with a unique flavor profile.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Diplomatico Planas",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/diplomatico-planas.jpg",
    description: "Smooth and clean with notes of coconut and vanilla.",
    category: "Rum",
    abv: 47,
    size: "750ml",
    brand: "Diplomatico",
    rating: 4.7,
    reviews: "A premium white rum with a distinctive flavor profile.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Plantation 5 Year Barbados Rum",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/plantation-5-year.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Plantation",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Havana Club 7 Year",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/havana-club-7.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Havana Club",
    rating: 4.8,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Cuba",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Plantation O.F.T.D. Overproof Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/plantation-oftd.jpg",
    description: "Bold and rich with notes of caramel and spice.",
    category: "Rum",
    abv: 69,
    size: "750ml",
    brand: "Plantation",
    rating: 4.8,
    reviews: "A distinctive overproof rum with a unique flavor profile.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Brugal Extra Viejo",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/brugal-extra-viejo.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Brugal",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "El Dorado 8 Year Rum",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/el-dorado-8.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "El Dorado",
    rating: 4.8,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Guyana",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Appleton Estate Rare Blend 12 Year",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/appleton-12.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Appleton Estate",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Jamaica",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Rhum Barbancourt White",
    price: 19.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/rhum-barbancourt-white.jpg",
    description: "Smooth and clean with notes of vanilla and spice.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Rhum Barbancourt",
    rating: 4.7,
    reviews: "A premium white rum with a distinctive flavor profile.",
    origin: "Haiti",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Ron Diplomático Mantuano",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/diplomatico-mantuano.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Diplomatico",
    rating: 4.7,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Ron Abuelo Anejo",
    price: 19.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/ron-abuelo-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Abuelo",
    rating: 4.7,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Panama",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Plantation Grand Reserve 5 Year",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/plantation-grand-reserve.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Plantation",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Kirk and Sweeney 18 Year Rum",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/kirk-sweeney-18.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Kirk and Sweeney",
    rating: 4.9,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Dominican Republic",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Ron Cartavio XO",
    price: 69.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/ron-cartavio-xo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Cartavio",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Peru",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Bacardi Gold Rum",
    price: 19.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/bacardi-gold.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Bacardi",
    rating: 4.7,
    reviews: "A popular gold rum with a distinctive flavor profile.",
    origin: "Puerto Rico",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Diplomatico Reserva Exclusiva",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/diplomatico-reserva.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Diplomatico",
    rating: 4.8,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Venezuela",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Zaya Gran Reserva",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/zaya-gran-reserva.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Zaya",
    rating: 4.8,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Trinidad and Tobago",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Mount Gay XO Triple Cask Blend",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/mount-gay-xo-triple.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Mount Gay",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Ron Abuelo 7 Year",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/ron-abuelo-7.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Ron Abuelo",
    rating: 4.8,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Panama",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Plantation XO 20th Anniversary",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/plantation-xo-20th.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Plantation",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Flor de Cana 25 Year",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/flor-de-cana-25.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 40,
    size: "750ml",
    brand: "Flor de Cana",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Nicaragua",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Mount Gay Extra Old",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/mount-gay-extra-old.jpg",
    description: "Smooth and rich with notes of vanilla and caramel.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "Mount Gay",
    rating: 4.9,
    reviews: "A premium aged rum with a complex flavor profile.",
    origin: "Barbados",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "El Dorado 25 Year",
    price: 199.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/el-dorado-25.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Rum",
    abv: 43,
    size: "750ml",
    brand: "El Dorado",
    rating: 5.0,
    reviews: "A premium aged rum with a distinctive flavor profile.",
    origin: "Guyana",
    availability: "In Stock",
  },
];

module.exports = rums;
