const redWines = [
  {
    id: 1,
    name: "Cabernet Sauvignon",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/cabernet-sauvignon.jpg",
    description: "Rich and full-bodied with notes of dark fruit and oak.",
    category: "Red Wine",
    brand: "Napa Valley Vineyards",
    rating: 4.8,
    reviews: "A classic red wine, perfect for pairing with steak.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Merlot",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/merlot.jpg",
    description: "Smooth and velvety with notes of plum and chocolate.",
    category: "Red Wine",
    brand: "Sonoma Valley Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Pinot Noir",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pinot-noir.jpg",
    description: "Light and elegant with notes of cherry and raspberry.",
    category: "Red Wine",
    brand: "Willamette Valley Vineyards",
    rating: 4.9,
    reviews: "A delightful wine, perfect for poultry and light pasta dishes.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Syrah",
    price: 22.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/syrah.jpg",
    description: "Bold and spicy with notes of blackberry and pepper.",
    category: "Red Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews: "A robust wine, ideal for hearty meat dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Zinfandel",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/zinfandel.jpg",
    description: "Fruity and jammy with notes of blackberry and spice.",
    category: "Red Wine",
    brand: "Lodi Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, great with barbecue and grilled meats.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Malbec",
    price: 18.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/malbec.jpg",
    description: "Rich and dark with notes of plum, black cherry, and cocoa.",
    category: "Red Wine",
    brand: "Mendoza Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Sangiovese",
    price: 23.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/sangiovese.jpg",
    description: "Medium-bodied with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Tuscany Vineyards",
    rating: 4.8,
    reviews: "An elegant wine, excellent with pasta and Italian cuisine.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Grenache",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grenache.jpg",
    description: "Fruity and fresh with notes of red berries and herbs.",
    category: "Red Wine",
    brand: "Priorat Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Tempranillo",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tempranillo.jpg",
    description: "Earthy and rich with notes of cherry, leather, and tobacco.",
    category: "Red Wine",
    brand: "Rioja Vineyards",
    rating: 4.8,
    reviews: "A complex wine, perfect for roasted meats and aged cheeses.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Barbera",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/barbera.jpg",
    description: "Bright and lively with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Piedmont Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Carmenere",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/carmenere.jpg",
    description: "Rich and smooth with notes of dark fruit and pepper.",
    category: "Red Wine",
    brand: "Colchagua Valley Vineyards",
    rating: 4.8,
    reviews: "A bold wine, perfect for grilled meats and spicy dishes.",
    origin: "Chile",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Petit Verdot",
    price: 27.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/petit-verdot.jpg",
    description:
      "Deep and complex with notes of blackberry, violet, and spice.",
    category: "Red Wine",
    brand: "Bordeaux Vineyards",
    rating: 4.7,
    reviews: "A robust wine, great with hearty meat dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Cabernet Franc",
    price: 26.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cabernet-franc.jpg",
    description: "Elegant and aromatic with notes of red fruit and herbs.",
    category: "Red Wine",
    brand: "Loire Valley Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Shiraz",
    price: 25.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/shiraz.jpg",
    description: "Bold and spicy with notes of dark fruit and pepper.",
    category: "Red Wine",
    brand: "Barossa Valley Vineyards",
    rating: 4.9,
    reviews: "A robust wine, perfect for grilled meats and spicy dishes.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Nero d'Avola",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/nero-davola.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Sicily Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Touriga Nacional",
    price: 23.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/touriga-nacional.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and floral.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Montepulciano",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montepulciano.jpg",
    description: "Rich and fruity with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Abruzzo Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Petite Sirah",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/petite-sirah.jpg",
    description: "Bold and intense with notes of dark fruit and pepper.",
    category: "Red Wine",
    brand: "California Vineyards",
    rating: 4.8,
    reviews: "A robust wine, perfect for grilled meats and spicy dishes.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Gamay",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/gamay.jpg",
    description: "Light and fruity with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Beaujolais Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with poultry and light pasta dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Tannat",
    price: 27.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/tannat.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Uruguay Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Uruguay",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Mourvedre",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/mourvedre.jpg",
    description: "Rich and earthy with notes of dark fruit and spice.",
    category: "Red Wine",
    brand: "Bandol Vineyards",
    rating: 4.7,
    reviews: "A robust wine, perfect for grilled meats and hearty dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Cinsault",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/cinsault.jpg",
    description: "Light and fruity with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Provence Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with poultry and light pasta dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Carignan",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/carignan.jpg",
    description: "Rich and earthy with notes of dark fruit and spice.",
    category: "Red Wine",
    brand: "Languedoc Vineyards",
    rating: 4.8,
    reviews: "A robust wine, perfect for grilled meats and hearty dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Aglianico",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aglianico.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Bobal",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bobal.jpg",
    description: "Fruity and fresh with notes of red berries and herbs.",
    category: "Red Wine",
    brand: "Utiel-Requena Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Dolcetto",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/dolcetto.jpg",
    description: "Light and fruity with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Piedmont Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with poultry and light pasta dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Primitivo",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/primitivo.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Puglia Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Zweigelt",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/zweigelt.jpg",
    description: "Fruity and fresh with notes of red berries and spice.",
    category: "Red Wine",
    brand: "Burgenland Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Austria",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Lambrusco",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/lambrusco.jpg",
    description: "Light and fizzy with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Emilia-Romagna Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with charcuterie and light dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Refosco",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/refosco.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Friuli-Venezia Giulia Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Negroamaro",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/negroamaro.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Puglia Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Frappato",
    price: 23.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/frappato.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Sicily Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Valpolicella",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/valpolicella.jpg",
    description: "Light and fruity with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Veneto Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Lagrein",
    price: 25.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/lagrein.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Tinta de Toro",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tinta-de-toro.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Toro Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Sagrantino",
    price: 26.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sagrantino.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Umbria Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Blaufrankisch",
    price: 23.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/blaufrankisch.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Burgenland Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Austria",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Agiorgitiko",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/agiorgitiko.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Nemea Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Listan Negro",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/listan-negro.jpg",
    description: "Fruity and fresh with notes of red berries and herbs.",
    category: "Red Wine",
    brand: "Canary Islands Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Mencia",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/mencia.jpg",
    description: "Rich and earthy with notes of dark fruit and spice.",
    category: "Red Wine",
    brand: "Bierzo Vineyards",
    rating: 4.8,
    reviews: "A robust wine, perfect for grilled meats and hearty dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Xinomavro",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/xinomavro.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Naoussa Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Counoise",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/counoise.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Schiava",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/schiava.jpg",
    description: "Light and fruity with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with poultry and light pasta dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Corvina",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/corvina.jpg",
    description: "Bright and lively with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Veneto Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Barbera d'Asti",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/barbera-dasti.jpg",
    description: "Bright and lively with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Piedmont Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Touriga Franca",
    price: 25.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/touriga-franca.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Trousseau",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/trousseau.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Jura Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Teroldego",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/teroldego.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Piedirosso",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/piedirosso.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Tintilia",
    price: 25.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tintilia.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Molise Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Marselan",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/marselan.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Languedoc Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Plavac Mali",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/plavac-mali.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Dalmatia Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Croatia",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Monastrell",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/monastrell.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Jumilla Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Bonarda",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/bonarda.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Mendoza Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Aleatico",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aleatico.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Elba Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Parraleta",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/parraleta.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Somontano Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Negramoll",
    price: 25.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/negramoll.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Canary Islands Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Susumaniello",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/susumaniello.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Puglia Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Kotsifali",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/kotsifali.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Crete Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Trincadeira",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/trincadeira.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Alentejo Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Listan Prieto",
    price: 25.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/listan-prieto.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Canary Islands Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Tinta Barroca",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tinta-barroca.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Baga",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/baga.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Bairrada Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Tintilla de Rota",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tintilla-de-rota.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Andalusia Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Marzemino",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/marzemino.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Tannat",
    price: 24.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/tannat.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Madiran Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Mandilaria",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/mandilaria.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Santorini Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Touriga Nacional",
    price: 26.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/touriga-nacional.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Bonarda",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/bonarda.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Mendoza Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Agiorgitiko",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/agiorgitiko.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Nemea Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Listan Negro",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/listan-negro.jpg",
    description: "Fruity and fresh with notes of red berries and herbs.",
    category: "Red Wine",
    brand: "Canary Islands Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Mencia",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/mencia.jpg",
    description: "Rich and earthy with notes of dark fruit and spice.",
    category: "Red Wine",
    brand: "Bierzo Vineyards",
    rating: 4.8,
    reviews: "A robust wine, perfect for grilled meats and hearty dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Xinomavro",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/xinomavro.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Naoussa Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Counoise",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/counoise.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Schiava",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/schiava.jpg",
    description: "Light and fruity with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with poultry and light pasta dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Corvina",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/corvina.jpg",
    description: "Bright and lively with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Veneto Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Barbera d'Asti",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/barbera-dasti.jpg",
    description: "Bright and lively with notes of red cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Piedmont Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with a variety of dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Touriga Franca",
    price: 25.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/touriga-franca.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Trousseau",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/trousseau.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Jura Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Teroldego",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/teroldego.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Piedirosso",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/piedirosso.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Tintilia",
    price: 25.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tintilia.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Molise Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Marselan",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/marselan.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Languedoc Vineyards",
    rating: 4.7,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Plavac Mali",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/plavac-mali.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Dalmatia Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Croatia",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Monastrell",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/monastrell.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Jumilla Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Bonarda",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/bonarda.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Mendoza Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Aleatico",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aleatico.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Elba Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Parraleta",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/parraleta.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Somontano Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Negramoll",
    price: 25.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/negramoll.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Canary Islands Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Susumaniello",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/susumaniello.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Puglia Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Kotsifali",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/kotsifali.jpg",
    description: "Fruity and fresh with notes of red berries and floral.",
    category: "Red Wine",
    brand: "Crete Vineyards",
    rating: 4.7,
    reviews:
      "A delightful wine, great with grilled vegetables and lighter meats.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Trincadeira",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/trincadeira.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Alentejo Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Listan Prieto",
    price: 25.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/listan-prieto.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Canary Islands Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Tinta Barroca",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tinta-barroca.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Baga",
    price: 22.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/baga.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Bairrada Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Tintilla de Rota",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tintilla-de-rota.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Andalusia Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Marzemino",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/marzemino.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Tannat",
    price: 24.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/tannat.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Madiran Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Mandilaria",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/mandilaria.jpg",
    description: "Rich and dark with notes of black cherry, plum, and spice.",
    category: "Red Wine",
    brand: "Santorini Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for beef and lamb dishes.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Touriga Nacional",
    price: 26.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/touriga-nacional.jpg",
    description:
      "Deep and complex with notes of dark fruit, spice, and tannins.",
    category: "Red Wine",
    brand: "Douro Valley Vineyards",
    rating: 4.8,
    reviews: "A bold wine, great with hearty meat dishes.",
    origin: "Portugal",
    availability: "In Stock",
  },
];

module.exports = redWines;
