const users = [
  {
    username: "whiskeylover01",
    email: "whiskeylover01@example.com",
    password: "password123",
    full_name: "John Doe",
    address: "123 Bourbon St, Louisville, KY",
    phone_number: "502-555-1234",
    is_admin: false,
  },
  {
    username: "bourbonfanatic22",
    email: "bourbonfanatic22@example.com",
    password: "password123",
    full_name: "Jane Smith",
    address: "456 Whiskey Ln, Frankfort, KY",
    phone_number: "502-555-5678",
    is_admin: false,
  },
  {
    username: "whiskeyenthusiast",
    email: "whiskeyenthusiast@example.com",
    password: "password123",
    full_name: "Michael Johnson",
    address: "789 Rye Rd, Bardstown, KY",
    phone_number: "502-555-8765",
    is_admin: false,
  },
  {
    username: "bourbonhunter",
    email: "bourbonhunter@example.com",
    password: "password123",
    full_name: "Sarah Davis",
    address: "321 Barrel St, Louisville, KY",
    phone_number: "502-555-4321",
    is_admin: false,
  },
  {
    username: "whiskeyaddict",
    email: "whiskeyaddict@example.com",
    password: "password123",
    full_name: "Chris Brown",
    address: "654 Distillery Rd, Frankfort, KY",
    phone_number: "502-555-9876",
    is_admin: false,
  },
  {
    username: "singlemaltfan",
    email: "singlemaltfan@example.com",
    password: "password123",
    full_name: "Patricia Wilson",
    address: "987 Scotch St, Bardstown, KY",
    phone_number: "502-555-6543",
    is_admin: false,
  },
  {
    username: "whiskeyconnoisseur",
    email: "whiskeyconnoisseur@example.com",
    password: "password123",
    full_name: "James Taylor",
    address: "432 Rye Rd, Louisville, KY",
    phone_number: "502-555-3456",
    is_admin: false,
  },
  {
    username: "bourboncollector",
    email: "bourboncollector@example.com",
    password: "password123",
    full_name: "Linda Martinez",
    address: "876 Malt St, Frankfort, KY",
    phone_number: "502-555-2345",
    is_admin: false,
  },
  {
    username: "whiskeyaficionado",
    email: "whiskeyaficionado@example.com",
    password: "password123",
    full_name: "David Anderson",
    address: "123 Scotch Ln, Bardstown, KY",
    phone_number: "502-555-7890",
    is_admin: false,
  },
  {
    username: "bourbonlover",
    email: "bourbonlover@example.com",
    password: "password123",
    full_name: "Barbara Thomas",
    address: "456 Rye St, Louisville, KY",
    phone_number: "502-555-6789",
    is_admin: false,
  },
  {
    username: "whiskeytaster",
    email: "whiskeytaster@example.com",
    password: "password123",
    full_name: "Daniel White",
    address: "789 Bourbon Rd, Frankfort, KY",
    phone_number: "502-555-5674",
    is_admin: false,
  },
  {
    username: "bourbonexpert",
    email: "bourbonexpert@example.com",
    password: "password123",
    full_name: "Nancy Harris",
    address: "321 Malt St, Bardstown, KY",
    phone_number: "502-555-9870",
    is_admin: false,
  },
  {
    username: "whiskeydrinker",
    email: "whiskeydrinker@example.com",
    password: "password123",
    full_name: "Matthew Clark",
    address: "654 Scotch Rd, Louisville, KY",
    phone_number: "502-555-8760",
    is_admin: false,
  },
  {
    username: "bourbonlover123",
    email: "bourbonlover123@example.com",
    password: "password123",
    full_name: "Donna Lewis",
    address: "987 Rye St, Frankfort, KY",
    phone_number: "502-555-7654",
    is_admin: false,
  },
  {
    username: "whiskeyenthusiast456",
    email: "whiskeyenthusiast456@example.com",
    password: "password123",
    full_name: "Paul Walker",
    address: "432 Barrel Ln, Bardstown, KY",
    phone_number: "502-555-6540",
    is_admin: false,
  },
  {
    username: "bourboncollector789",
    email: "bourboncollector789@example.com",
    password: "password123",
    full_name: "Michelle Hall",
    address: "876 Malt Rd, Louisville, KY",
    phone_number: "502-555-5432",
    is_admin: false,
  },
  {
    username: "whiskeyaddict101",
    email: "whiskeyaddict101@example.com",
    password: "password123",
    full_name: "Andrew Allen",
    address: "123 Bourbon Ln, Frankfort, KY",
    phone_number: "502-555-4320",
    is_admin: false,
  },
  {
    username: "bourbonfanatic202",
    email: "bourbonfanatic202@example.com",
    password: "password123",
    full_name: "Jessica Young",
    address: "456 Rye Rd, Bardstown, KY",
    phone_number: "502-555-3210",
    is_admin: false,
  },
  {
    username: "whiskeylover303",
    email: "whiskeylover303@example.com",
    password: "password123",
    full_name: "Joshua King",
    address: "789 Scotch Ln, Louisville, KY",
    phone_number: "502-555-2109",
    is_admin: false,
  },
  {
    username: "bourbonhunter404",
    email: "bourbonhunter404@example.com",
    password: "password123",
    full_name: "Emily Wright",
    address: "321 Barrel St, Frankfort, KY",
    phone_number: "502-555-1098",
    is_admin: false,
  },
  {
    username: "whiskeyenthusiast505",
    email: "whiskeyenthusiast505@example.com",
    password: "password123",
    full_name: "Ryan Lopez",
    address: "654 Distillery Ln, Bardstown, KY",
    phone_number: "502-555-0987",
    is_admin: false,
  },
  {
    username: "bourboncollector606",
    email: "bourboncollector606@example.com",
    password: "password123",
    full_name: "Laura Hill",
    address: "987 Malt St, Louisville, KY",
    phone_number: "502-555-9871",
    is_admin: false,
  },
  {
    username: "whiskeyconnoisseur707",
    email: "whiskeyconnoisseur707@example.com",
    password: "password123",
    full_name: "Kevin Scott",
    address: "432 Rye Rd, Frankfort, KY",
    phone_number: "502-555-8762",
    is_admin: false,
  },
  {
    username: "bourbonlover808",
    email: "bourbonlover808@example.com",
    password: "password123",
    full_name: "Sarah Green",
    address: "876 Malt Ln, Bardstown, KY",
    phone_number: "502-555-7653",
    is_admin: false,
  },
  {
    username: "whiskeyaficionado909",
    email: "whiskeyaficionado909@example.com",
    password: "password123",
    full_name: "Tyler Adams",
    address: "123 Scotch Rd, Louisville, KY",
    phone_number: "502-555-6541",
    is_admin: false,
  },
  {
    username: "bourbonexpert010",
    email: "bourbonexpert010@example.com",
    password: "password123",
    full_name: "Kelly Baker",
    address: "456 Rye St, Frankfort, KY",
    phone_number: "502-555-5430",
    is_admin: false,
  },
  {
    username: "whiskeytaster111",
    email: "whiskeytaster111@example.com",
    password: "password123",
    full_name: "Brandon Carter",
    address: "789 Barrel Rd, Bardstown, KY",
    phone_number: "502-555-4329",
    is_admin: false,
  },
  {
    username: "bourboncollector212",
    email: "bourboncollector212@example.com",
    password: "password123",
    full_name: "Rachel Turner",
    address: "321 Malt Ln, Louisville, KY",
    phone_number: "502-555-3218",
    is_admin: false,
  },
  {
    username: "whiskeylover313",
    email: "whiskeylover313@example.com",
    password: "password123",
    full_name: "Justin Parker",
    address: "654 Scotch St, Frankfort, KY",
    phone_number: "502-555-2107",
    is_admin: false,
  },
  {
    username: "bourbonfanatic414",
    email: "bourbonfanatic414@example.com",
    password: "password123",
    full_name: "Brittany Collins",
    address: "987 Barrel Rd, Bardstown, KY",
    phone_number: "502-555-1096",
    is_admin: false,
  },
];

module.exports = users;
