const nonAlcoholicSpirits = [
  {
    id: 1,
    name: "Seedlip Garden 108",
    price: 32.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/seedlip-garden-108.jpg",
    description:
      "Herbal and floral blend of hand-picked peas and homegrown herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Seedlip",
    rating: 4.8,
    reviews:
      "A refreshing non-alcoholic spirit with a delightful herbal taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Seedlip Spice 94",
    price: 32.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/seedlip-spice-94.jpg",
    description: "Aromatic blend of allspice, cardamom, and citrus.",
    category: "Non-Alcoholic Spirit",
    brand: "Seedlip",
    rating: 4.7,
    reviews: "Perfect for creating sophisticated non-alcoholic cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Seedlip Grove 42",
    price: 32.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/seedlip-grove-42.jpg",
    description: "Citrus blend of bitter orange, lemongrass, and ginger.",
    category: "Non-Alcoholic Spirit",
    brand: "Seedlip",
    rating: 4.9,
    reviews: "A bright and zesty non-alcoholic spirit, great with tonic.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Lyre's American Malt",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/lyres-american-malt.jpg",
    description: "Classic bourbon-style non-alcoholic spirit.",
    category: "Non-Alcoholic Spirit",
    brand: "Lyre's",
    rating: 4.8,
    reviews: "Rich and complex, ideal for non-alcoholic cocktails.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Lyre's Italian Orange",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/lyres-italian-orange.jpg",
    description: "Bitter citrus non-alcoholic spirit, perfect for Negroni.",
    category: "Non-Alcoholic Spirit",
    brand: "Lyre's",
    rating: 4.7,
    reviews:
      "Vibrant and bold, captures the essence of a classic Italian aperitif.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Lyre's Dry London Spirit",
    price: 34.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/lyres-dry-london-spirit.jpg",
    description:
      "Gin-style non-alcoholic spirit with juniper and citrus notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Lyre's",
    rating: 4.9,
    reviews: "A perfect gin alternative for non-alcoholic cocktails.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Lyre's Coffee Originale",
    price: 34.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lyres-coffee-originale.jpg",
    description: "Non-alcoholic coffee liqueur with rich espresso notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Lyre's",
    rating: 4.8,
    reviews: "Perfect for non-alcoholic espresso martinis.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Ceder's Classic",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/ceders-classic.jpg",
    description: "Blend of classic gin botanicals with juniper and citrus.",
    category: "Non-Alcoholic Spirit",
    brand: "Ceder's",
    rating: 4.6,
    reviews: "A refreshing and well-balanced non-alcoholic gin alternative.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Ceder's Crisp",
    price: 29.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/ceders-crisp.jpg",
    description: "Non-alcoholic spirit with notes of cucumber and chamomile.",
    category: "Non-Alcoholic Spirit",
    brand: "Ceder's",
    rating: 4.7,
    reviews: "Light and refreshing, great with tonic and a slice of cucumber.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Ceder's Wild",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ceders-wild.jpg",
    description: "Botanical blend with ginger, clove, and rooibos.",
    category: "Non-Alcoholic Spirit",
    brand: "Ceder's",
    rating: 4.8,
    reviews: "Spicy and aromatic, perfect for non-alcoholic cocktails.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Ritual Zero Proof Whiskey Alternative",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/ritual-zero-proof-whiskey.jpg",
    description:
      "Non-alcoholic whiskey alternative with caramel and oak notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Ritual Zero Proof",
    rating: 4.7,
    reviews: "Perfect for creating non-alcoholic whiskey cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Ritual Zero Proof Gin Alternative",
    price: 34.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/ritual-zero-proof-gin.jpg",
    description: "Non-alcoholic gin alternative with juniper and cucumber.",
    category: "Non-Alcoholic Spirit",
    brand: "Ritual Zero Proof",
    rating: 4.8,
    reviews: "A great gin substitute for non-alcoholic G&Ts.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Ritual Zero Proof Tequila Alternative",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/ritual-zero-proof-tequila.jpg",
    description: "Non-alcoholic tequila alternative with agave and lime.",
    category: "Non-Alcoholic Spirit",
    brand: "Ritual Zero Proof",
    rating: 4.7,
    reviews: "Perfect for non-alcoholic margaritas.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Monday Zero Alcohol Gin",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/monday-zero-alcohol-gin.jpg",
    description: "Non-alcoholic gin with juniper, citrus, and spice.",
    category: "Non-Alcoholic Spirit",
    brand: "Monday",
    rating: 4.8,
    reviews:
      "A premium gin alternative for sophisticated non-alcoholic cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Monday Zero Alcohol Whiskey",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/monday-zero-alcohol-whiskey.jpg",
    description: "Non-alcoholic whiskey with oak, caramel, and vanilla notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Monday",
    rating: 4.9,
    reviews: "Ideal for creating non-alcoholic whiskey cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Free Spirits The Spirit of Bourbon",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/free-spirits-bourbon.jpg",
    description: "Non-alcoholic bourbon with caramel, vanilla, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Free Spirits",
    rating: 4.7,
    reviews: "Perfect for non-alcoholic old fashioneds.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Free Spirits The Spirit of Gin",
    price: 34.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/free-spirits-gin.jpg",
    description: "Non-alcoholic gin with juniper, citrus, and botanicals.",
    category: "Non-Alcoholic Spirit",
    brand: "Free Spirits",
    rating: 4.8,
    reviews: "A delightful gin alternative for non-alcoholic cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Free Spirits The Spirit of Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/free-spirits-tequila.jpg",
    description: "Non-alcoholic tequila with agave, citrus, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Free Spirits",
    rating: 4.9,
    reviews: "Ideal for non-alcoholic margaritas and palomas.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Three Spirit Social Elixir",
    price: 39.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/three-spirit-social-elixir.jpg",
    description: "Non-alcoholic spirit with cacao, coffee, and adaptogens.",
    category: "Non-Alcoholic Spirit",
    brand: "Three Spirit",
    rating: 4.8,
    reviews: "A unique blend for a social and uplifting experience.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Three Spirit Nightcap",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/three-spirit-nightcap.jpg",
    description: "Non-alcoholic spirit with vanilla, maple, and valerian.",
    category: "Non-Alcoholic Spirit",
    brand: "Three Spirit",
    rating: 4.7,
    reviews: "Perfect for winding down and relaxing.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Kin Euphorics High Rhode",
    price: 42.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/kin-euphorics-high-rhode.jpg",
    description: "Non-alcoholic spirit with hibiscus, citrus, and adaptogens.",
    category: "Non-Alcoholic Spirit",
    brand: "Kin Euphorics",
    rating: 4.8,
    reviews: "Uplifting and refreshing, great for social gatherings.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Kin Euphorics Dream Light",
    price: 42.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/kin-euphorics-dream-light.jpg",
    description:
      "Non-alcoholic spirit with reishi, melatonin, and warm spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Kin Euphorics",
    rating: 4.7,
    reviews: "Perfect for a calming and relaxing nightcap.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Kin Euphorics Kin Spritz",
    price: 42.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/kin-euphorics-kin-spritz.jpg",
    description:
      "Non-alcoholic sparkling beverage with adaptogens and nootropics.",
    category: "Non-Alcoholic Spirit",
    brand: "Kin Euphorics",
    rating: 4.8,
    reviews: "Refreshing and uplifting, perfect for any occasion.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Æcorn Aperitifs Dry",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/aecorn-dry.jpg",
    description: "Non-alcoholic aperitif with citrus, herbs, and bitter notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Æcorn Aperitifs",
    rating: 4.6,
    reviews: "Great for a refreshing non-alcoholic spritz.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Æcorn Aperitifs Bitter",
    price: 29.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/aecorn-bitter.jpg",
    description:
      "Non-alcoholic aperitif with bitter orange, quassia, and bay leaf.",
    category: "Non-Alcoholic Spirit",
    brand: "Æcorn Aperitifs",
    rating: 4.7,
    reviews: "Perfect for non-alcoholic Negroni and other cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Æcorn Aperitifs Aromatic",
    price: 29.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/aecorn-aromatic.jpg",
    description:
      "Non-alcoholic aperitif with smoked cherrywood, cloves, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Æcorn Aperitifs",
    rating: 4.8,
    reviews: "Rich and complex, perfect for non-alcoholic cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Everleaf Forest",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/everleaf-forest.jpg",
    description: "Non-alcoholic aperitif with saffron, vanilla, and cassia.",
    category: "Non-Alcoholic Spirit",
    brand: "Everleaf",
    rating: 4.7,
    reviews: "A complex and aromatic alternative to traditional spirits.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Everleaf Marine",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/everleaf-marine.jpg",
    description:
      "Non-alcoholic aperitif with sea buckthorn, dulse, and bergamot.",
    category: "Non-Alcoholic Spirit",
    brand: "Everleaf",
    rating: 4.8,
    reviews: "Refreshing and unique, great for non-alcoholic cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Everleaf Mountain",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/everleaf-mountain.jpg",
    description:
      "Non-alcoholic aperitif with juniper, myrtle, and cherry blossom.",
    category: "Non-Alcoholic Spirit",
    brand: "Everleaf",
    rating: 4.9,
    reviews: "Perfect for creating sophisticated non-alcoholic drinks.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Proteau Ludlow Red",
    price: 36.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/proteau-ludlow-red.jpg",
    description:
      "Non-alcoholic botanical drink with blackberry, violet, and black pepper.",
    category: "Non-Alcoholic Spirit",
    brand: "Proteau",
    rating: 4.7,
    reviews: "Rich and complex, great for non-alcoholic cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Proteau Rivington Spritz",
    price: 36.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/proteau-rivington-spritz.jpg",
    description:
      "Non-alcoholic botanical drink with hibiscus, chamomile, and strawberry.",
    category: "Non-Alcoholic Spirit",
    brand: "Proteau",
    rating: 4.8,
    reviews: "Light and refreshing, perfect for any occasion.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Pentire Adrift",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pentire-adrift.jpg",
    description:
      "Non-alcoholic spirit with coastal botanicals, sage, and rock samphire.",
    category: "Non-Alcoholic Spirit",
    brand: "Pentire",
    rating: 4.9,
    reviews: "A unique and refreshing alternative to traditional spirits.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Pentire Seaward",
    price: 39.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/pentire-seaward.jpg",
    description: "Non-alcoholic spirit with grapefruit, sea rosemary, and bay.",
    category: "Non-Alcoholic Spirit",
    brand: "Pentire",
    rating: 4.8,
    reviews: "Bright and zesty, perfect for non-alcoholic cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Ghia Non-Alcoholic Apéritif",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ghia.jpg",
    description: "Non-alcoholic apéritif with citrus, rosemary, and ginger.",
    category: "Non-Alcoholic Spirit",
    brand: "Ghia",
    rating: 4.7,
    reviews: "A sophisticated and aromatic alternative to traditional spirits.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Amass Riverine",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/amass-riverine.jpg",
    description: "Non-alcoholic spirit with juniper, coriander, and sumac.",
    category: "Non-Alcoholic Spirit",
    brand: "Amass",
    rating: 4.8,
    reviews: "A complex and botanical alternative to gin.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Optimist Bright",
    price: 44.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/optimist-bright.jpg",
    description: "Non-alcoholic spirit with citrus, jasmine, and basil.",
    category: "Non-Alcoholic Spirit",
    brand: "Optimist",
    rating: 4.9,
    reviews: "Bright and refreshing, perfect for non-alcoholic cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Optimist Fresh",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/optimist-fresh.jpg",
    description: "Non-alcoholic spirit with mint, cucumber, and lemongrass.",
    category: "Non-Alcoholic Spirit",
    brand: "Optimist",
    rating: 4.8,
    reviews: "Cool and refreshing, ideal for summer drinks.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Optimist Smokey",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/optimist-smokey.jpg",
    description: "Non-alcoholic spirit with ginger, turmeric, and cayenne.",
    category: "Non-Alcoholic Spirit",
    brand: "Optimist",
    rating: 4.7,
    reviews: "Warm and spicy, great for non-alcoholic cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Gnista Floral Wormwood",
    price: 42.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gnista-floral-wormwood.jpg",
    description: "Non-alcoholic spirit with wormwood, rosemary, and hibiscus.",
    category: "Non-Alcoholic Spirit",
    brand: "Gnista",
    rating: 4.6,
    reviews: "A unique and aromatic alternative to traditional spirits.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Gnista Barreled Oak",
    price: 42.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/gnista-barreled-oak.jpg",
    description: "Non-alcoholic spirit with oak, caramel, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Gnista",
    rating: 4.7,
    reviews: "Rich and complex, perfect for non-alcoholic whiskey cocktails.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Strykk Not Gin",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/stryyk-not-gin.jpg",
    description: "Non-alcoholic gin with juniper, basil, and rosemary.",
    category: "Non-Alcoholic Spirit",
    brand: "Strykk",
    rating: 4.7,
    reviews: "A great alternative to gin for non-alcoholic cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Strykk Not Rum",
    price: 29.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/stryyk-not-rum.jpg",
    description: "Non-alcoholic rum with vanilla, raisin, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Strykk",
    rating: 4.8,
    reviews: "Perfect for non-alcoholic rum cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Strykk Not Vodka",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/stryyk-not-vodka.jpg",
    description: "Non-alcoholic vodka with a clean and crisp profile.",
    category: "Non-Alcoholic Spirit",
    brand: "Strykk",
    rating: 4.7,
    reviews: "A versatile alternative to vodka for any non-alcoholic cocktail.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Jubilant Juniper",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/jubilant-juniper.jpg",
    description: "Non-alcoholic gin with juniper, cardamom, and citrus.",
    category: "Non-Alcoholic Spirit",
    brand: "Jubilant",
    rating: 4.8,
    reviews: "Perfect for non-alcoholic gin and tonics.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Melancholy Mule",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/melancholy-mule.jpg",
    description: "Non-alcoholic spirit with ginger, lime, and mint.",
    category: "Non-Alcoholic Spirit",
    brand: "Melancholy",
    rating: 4.9,
    reviews: "Great for creating non-alcoholic Moscow mules.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Pensive Paloma",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/pensive-paloma.jpg",
    description: "Non-alcoholic spirit with grapefruit, lime, and agave.",
    category: "Non-Alcoholic Spirit",
    brand: "Pensive",
    rating: 4.8,
    reviews: "Ideal for non-alcoholic Paloma cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Sober Sangria",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sober-sangria.jpg",
    description: "Non-alcoholic spirit with red fruit, citrus, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Sober",
    rating: 4.7,
    reviews: "A refreshing and fruity alternative to traditional sangria.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Courageous Cosmo",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/courageous-cosmo.jpg",
    description: "Non-alcoholic spirit with cranberry, lime, and orange.",
    category: "Non-Alcoholic Spirit",
    brand: "Courageous",
    rating: 4.8,
    reviews: "Perfect for non-alcoholic Cosmopolitan cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Hopeful Hibiscus",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/hopeful-hibiscus.jpg",
    description: "Non-alcoholic spirit with hibiscus, lemon, and ginger.",
    category: "Non-Alcoholic Spirit",
    brand: "Hopeful",
    rating: 4.9,
    reviews: "A delightful and floral alternative to traditional spirits.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Brave Bourbon",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/brave-bourbon.jpg",
    description: "Non-alcoholic bourbon with caramel, vanilla, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Brave",
    rating: 4.8,
    reviews: "Ideal for creating non-alcoholic whiskey cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Stalwart Scotch",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/stalwart-scotch.jpg",
    description: "Non-alcoholic scotch with smoky, peaty, and caramel notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Stalwart",
    rating: 4.7,
    reviews: "A rich and complex alternative to traditional scotch.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Gallant Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gallant-gin.jpg",
    description: "Non-alcoholic gin with juniper, coriander, and citrus.",
    category: "Non-Alcoholic Spirit",
    brand: "Gallant",
    rating: 4.8,
    reviews: "A refreshing and versatile alternative to gin.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Resolute Rum",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/resolute-rum.jpg",
    description: "Non-alcoholic rum with vanilla, caramel, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Resolute",
    rating: 4.9,
    reviews: "Perfect for non-alcoholic rum cocktails.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Dignified Daiquiri",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/dignified-daiquiri.jpg",
    description: "Non-alcoholic spirit with lime, sugar, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Dignified",
    rating: 4.8,
    reviews: "Ideal for creating non-alcoholic daiquiris.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Luminous Limoncello",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/luminous-limoncello.jpg",
    description: "Non-alcoholic spirit with lemon zest, sugar, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Luminous",
    rating: 4.7,
    reviews: "A bright and zesty alternative to traditional limoncello.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Vigorous Vodka",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/vigorous-vodka.jpg",
    description: "Non-alcoholic vodka with a clean and neutral profile.",
    category: "Non-Alcoholic Spirit",
    brand: "Vigorous",
    rating: 4.9,
    reviews: "A versatile alternative to vodka for any non-alcoholic cocktail.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Fiery Fireball",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fiery-fireball.jpg",
    description: "Non-alcoholic spirit with cinnamon, sugar, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Fiery",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic hot toddies.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Gentle Ginger",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gentle-ginger.jpg",
    description: "Non-alcoholic spirit with ginger, lemon, and honey.",
    category: "Non-Alcoholic Spirit",
    brand: "Gentle",
    rating: 4.7,
    reviews: "A warm and spicy alternative to traditional spirits.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Calm Campari",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/calm-campari.jpg",
    description: "Non-alcoholic spirit with bitter orange, rhubarb, and herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Calm",
    rating: 4.9,
    reviews: "Great for creating non-alcoholic Negroni cocktails.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Noble Negroni",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/noble-negroni.jpg",
    description: "Non-alcoholic spirit with juniper, orange, and bitter herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Noble",
    rating: 4.8,
    reviews: "A perfect alternative for non-alcoholic Negronis.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Brilliant Bitter",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/brilliant-bitter.jpg",
    description: "Non-alcoholic spirit with bitter herbs, citrus, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Brilliant",
    rating: 4.7,
    reviews: "A complex and aromatic alternative to traditional bitters.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Peaceful Pisco",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/peaceful-pisco.jpg",
    description: "Non-alcoholic spirit with grape, lemon, and floral notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Peaceful",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic pisco sours.",
    origin: "Peru",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Placid Paloma",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/placid-paloma.jpg",
    description: "Non-alcoholic spirit with grapefruit, lime, and agave.",
    category: "Non-Alcoholic Spirit",
    brand: "Placid",
    rating: 4.9,
    reviews: "Ideal for non-alcoholic Paloma cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Radiant Rosé",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/radiant-rose.jpg",
    description:
      "Non-alcoholic spirit with red fruit, floral, and citrus notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Radiant",
    rating: 4.7,
    reviews: "A refreshing and fruity alternative to traditional rosé.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Lively Lime",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/lively-lime.jpg",
    description: "Non-alcoholic spirit with lime, mint, and cucumber.",
    category: "Non-Alcoholic Spirit",
    brand: "Lively",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic mojitos.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Sunny Sangria",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sunny-sangria.jpg",
    description: "Non-alcoholic spirit with red fruit, citrus, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Sunny",
    rating: 4.9,
    reviews: "A refreshing and fruity alternative to traditional sangria.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Bold Brandy",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bold-brandy.jpg",
    description: "Non-alcoholic brandy with caramel, vanilla, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Bold",
    rating: 4.8,
    reviews: "A rich and complex alternative to traditional brandy.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Majestic Martini",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/majestic-martini.jpg",
    description: "Non-alcoholic spirit with juniper, vermouth, and lemon.",
    category: "Non-Alcoholic Spirit",
    brand: "Majestic",
    rating: 4.7,
    reviews: "Perfect for creating non-alcoholic martinis.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Royal Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/royal-rum.jpg",
    description: "Non-alcoholic rum with vanilla, caramel, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Royal",
    rating: 4.9,
    reviews: "A great alternative to rum for non-alcoholic cocktails.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Splendid Spritz",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/splendid-spritz.jpg",
    description: "Non-alcoholic spirit with bitter orange, rhubarb, and herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Splendid",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic spritz cocktails.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Dynamic Daiquiri",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/dynamic-daiquiri.jpg",
    description: "Non-alcoholic spirit with lime, sugar, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Dynamic",
    rating: 4.7,
    reviews: "Ideal for creating non-alcoholic daiquiris.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Energetic Espresso",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/energetic-espresso.jpg",
    description: "Non-alcoholic spirit with espresso, vanilla, and chocolate.",
    category: "Non-Alcoholic Spirit",
    brand: "Energetic",
    rating: 4.9,
    reviews: "Perfect for creating non-alcoholic espresso martinis.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Luminous Lemonade",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/luminous-lemonade.jpg",
    description: "Non-alcoholic spirit with lemon, sugar, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Luminous",
    rating: 4.8,
    reviews: "A bright and refreshing alternative to traditional lemonade.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Radiant Rum",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/radiant-rum.jpg",
    description: "Non-alcoholic rum with vanilla, caramel, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Radiant",
    rating: 4.9,
    reviews: "A great alternative to rum for non-alcoholic cocktails.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Vibrant Vodka",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/vibrant-vodka.jpg",
    description: "Non-alcoholic vodka with a clean and neutral profile.",
    category: "Non-Alcoholic Spirit",
    brand: "Vibrant",
    rating: 4.8,
    reviews: "A versatile alternative to vodka for any non-alcoholic cocktail.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Gentle Gin",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gentle-gin.jpg",
    description: "Non-alcoholic gin with juniper, coriander, and citrus.",
    category: "Non-Alcoholic Spirit",
    brand: "Gentle",
    rating: 4.7,
    reviews: "A refreshing and versatile alternative to gin.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Calm Campari",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/calm-campari.jpg",
    description: "Non-alcoholic spirit with bitter orange, rhubarb, and herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Calm",
    rating: 4.9,
    reviews: "Great for creating non-alcoholic Negroni cocktails.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Majestic Martini",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/majestic-martini.jpg",
    description: "Non-alcoholic spirit with juniper, vermouth, and lemon.",
    category: "Non-Alcoholic Spirit",
    brand: "Majestic",
    rating: 4.7,
    reviews: "Perfect for creating non-alcoholic martinis.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Noble Negroni",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/noble-negroni.jpg",
    description: "Non-alcoholic spirit with juniper, orange, and bitter herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Noble",
    rating: 4.9,
    reviews: "A perfect alternative for non-alcoholic Negronis.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Stalwart Scotch",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/stalwart-scotch.jpg",
    description: "Non-alcoholic scotch with smoky, peaty, and caramel notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Stalwart",
    rating: 4.8,
    reviews: "A rich and complex alternative to traditional scotch.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Resolute Rum",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/resolute-rum.jpg",
    description: "Non-alcoholic rum with vanilla, caramel, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Resolute",
    rating: 4.9,
    reviews: "Perfect for non-alcoholic rum cocktails.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Gallant Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gallant-gin.jpg",
    description: "Non-alcoholic gin with juniper, coriander, and citrus.",
    category: "Non-Alcoholic Spirit",
    brand: "Gallant",
    rating: 4.8,
    reviews: "A refreshing and versatile alternative to gin.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Dynamic Daiquiri",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/dynamic-daiquiri.jpg",
    description: "Non-alcoholic spirit with lime, sugar, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Dynamic",
    rating: 4.7,
    reviews: "Ideal for creating non-alcoholic daiquiris.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Hopeful Hibiscus",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/hopeful-hibiscus.jpg",
    description: "Non-alcoholic spirit with hibiscus, lemon, and ginger.",
    category: "Non-Alcoholic Spirit",
    brand: "Hopeful",
    rating: 4.9,
    reviews: "A delightful and floral alternative to traditional spirits.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Lively Lime",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/lively-lime.jpg",
    description: "Non-alcoholic spirit with lime, mint, and cucumber.",
    category: "Non-Alcoholic Spirit",
    brand: "Lively",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic mojitos.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Gentle Ginger",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gentle-ginger.jpg",
    description: "Non-alcoholic spirit with ginger, lemon, and honey.",
    category: "Non-Alcoholic Spirit",
    brand: "Gentle",
    rating: 4.9,
    reviews: "A warm and spicy alternative to traditional spirits.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Brave Bourbon",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/brave-bourbon.jpg",
    description: "Non-alcoholic bourbon with caramel, vanilla, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Brave",
    rating: 4.8,
    reviews: "Ideal for creating non-alcoholic whiskey cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Radiant Rosé",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/radiant-rose.jpg",
    description:
      "Non-alcoholic spirit with red fruit, floral, and citrus notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Radiant",
    rating: 4.7,
    reviews: "A refreshing and fruity alternative to traditional rosé.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Bold Brandy",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/bold-brandy.jpg",
    description: "Non-alcoholic brandy with caramel, vanilla, and oak.",
    category: "Non-Alcoholic Spirit",
    brand: "Bold",
    rating: 4.9,
    reviews: "A rich and complex alternative to traditional brandy.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Calm Campari",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/calm-campari.jpg",
    description: "Non-alcoholic spirit with bitter orange, rhubarb, and herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Calm",
    rating: 4.8,
    reviews: "Great for creating non-alcoholic Negroni cocktails.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Noble Negroni",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/noble-negroni.jpg",
    description: "Non-alcoholic spirit with juniper, orange, and bitter herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Noble",
    rating: 4.7,
    reviews: "A perfect alternative for non-alcoholic Negronis.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Brilliant Bitter",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/brilliant-bitter.jpg",
    description: "Non-alcoholic spirit with bitter herbs, citrus, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Brilliant",
    rating: 4.9,
    reviews: "A complex and aromatic alternative to traditional bitters.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Peaceful Pisco",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/peaceful-pisco.jpg",
    description: "Non-alcoholic spirit with grape, lemon, and floral notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Peaceful",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic pisco sours.",
    origin: "Peru",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Placid Paloma",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/placid-paloma.jpg",
    description: "Non-alcoholic spirit with grapefruit, lime, and agave.",
    category: "Non-Alcoholic Spirit",
    brand: "Placid",
    rating: 4.7,
    reviews: "Ideal for non-alcoholic Paloma cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Radiant Rosé",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/radiant-rose.jpg",
    description:
      "Non-alcoholic spirit with red fruit, floral, and citrus notes.",
    category: "Non-Alcoholic Spirit",
    brand: "Radiant",
    rating: 4.8,
    reviews: "A refreshing and fruity alternative to traditional rosé.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Lively Lime",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/lively-lime.jpg",
    description: "Non-alcoholic spirit with lime, mint, and cucumber.",
    category: "Non-Alcoholic Spirit",
    brand: "Lively",
    rating: 4.9,
    reviews: "Perfect for creating non-alcoholic mojitos.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Energetic Espresso",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/energetic-espresso.jpg",
    description: "Non-alcoholic spirit with espresso, vanilla, and chocolate.",
    category: "Non-Alcoholic Spirit",
    brand: "Energetic",
    rating: 4.8,
    reviews: "Perfect for creating non-alcoholic espresso martinis.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Dynamic Daiquiri",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/dynamic-daiquiri.jpg",
    description: "Non-alcoholic spirit with lime, sugar, and vanilla.",
    category: "Non-Alcoholic Spirit",
    brand: "Dynamic",
    rating: 4.7,
    reviews: "Ideal for creating non-alcoholic daiquiris.",
    origin: "Caribbean",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Noble Negroni",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/noble-negroni.jpg",
    description: "Non-alcoholic spirit with juniper, orange, and bitter herbs.",
    category: "Non-Alcoholic Spirit",
    brand: "Noble",
    rating: 4.9,
    reviews: "A perfect alternative for non-alcoholic Negronis.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Radiant Rum",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/radiant-rum.jpg",
    description: "Non-alcoholic rum with vanilla, caramel, and spices.",
    category: "Non-Alcoholic Spirit",
    brand: "Radiant",
    rating: 4.8,
    reviews: "A great alternative to rum for non-alcoholic cocktails.",
    origin: "Caribbean",
    availability: "In Stock",
  },
];
