const domesticBeers = [
  {
    id: 1,
    name: "Budweiser",
    price: 9.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/budweiser.jpg",
    description: "A classic American lager with a smooth, clean finish.",
    category: "Lager",
    abv: 5,
    size: "12oz",
    brand: "Budweiser",
    rating: 4.5,
    reviews: "A reliable and refreshing beer for any occasion.",
    origin: "USA",
    pairing: "Burgers, pizza",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Miller Lite",
    price: 8.99,
    quantity: 120,
    imageUrl: "https://www.example.com/images/miller-lite.jpg",
    description: "A light and crisp American pilsner with a smooth finish.",
    category: "Pilsner",
    abv: 4.2,
    size: "12oz",
    brand: "Miller",
    rating: 4.4,
    reviews: "Perfect for those who prefer a lighter beer.",
    origin: "USA",
    pairing: "Salads, chicken",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Coors Light",
    price: 8.99,
    quantity: 150,
    imageUrl: "https://www.example.com/images/coors-light.jpg",
    description: "A refreshing and light beer with a crisp, clean taste.",
    category: "Lager",
    abv: 4.2,
    size: "12oz",
    brand: "Coors",
    rating: 4.3,
    reviews: "A go-to choice for a cold, refreshing drink.",
    origin: "USA",
    pairing: "Grilled meats, nachos",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Samuel Adams Boston Lager",
    price: 10.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/samuel-adams-boston-lager.jpg",
    description: "A rich and balanced lager with caramel and floral notes.",
    category: "Lager",
    abv: 5,
    size: "12oz",
    brand: "Samuel Adams",
    rating: 4.6,
    reviews: "A well-crafted beer with a full, complex flavor.",
    origin: "USA",
    pairing: "Steak, seafood",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Blue Moon Belgian White",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/blue-moon-belgian-white.jpg",
    description:
      "A wheat beer brewed with Valencia orange peel for a subtle sweetness.",
    category: "Wheat",
    abv: 5.4,
    size: "12oz",
    brand: "Blue Moon",
    rating: 4.7,
    reviews: "A refreshing and flavorful beer with a hint of citrus.",
    origin: "USA",
    pairing: "Seafood, salads",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Sierra Nevada Pale Ale",
    price: 12.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/sierra-nevada-pale-ale.jpg",
    description: "A bold and hop-forward pale ale with pine and citrus aromas.",
    category: "Pale Ale",
    abv: 5.6,
    size: "12oz",
    brand: "Sierra Nevada",
    rating: 4.8,
    reviews: "A classic craft beer with a distinctive flavor.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Yuengling Traditional Lager",
    price: 9.99,
    quantity: 110,
    imageUrl: "https://www.example.com/images/yuengling-traditional-lager.jpg",
    description: "A rich amber lager with a well-balanced taste.",
    category: "Lager",
    abv: 4.5,
    size: "12oz",
    brand: "Yuengling",
    rating: 4.5,
    reviews: "A solid lager with a satisfying flavor.",
    origin: "USA",
    pairing: "Burgers, wings",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Dogfish Head 60 Minute IPA",
    price: 13.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/dogfish-head-60-minute-ipa.jpg",
    description: "A continually hopped IPA with a balanced bitterness.",
    category: "IPA",
    abv: 6,
    size: "12oz",
    brand: "Dogfish Head",
    rating: 4.7,
    reviews: "A hop lover's dream with a crisp finish.",
    origin: "USA",
    pairing: "Spicy foods, cheeses",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Lagunitas IPA",
    price: 12.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/lagunitas-ipa.jpg",
    description: "A well-rounded IPA with a distinct hop character.",
    category: "IPA",
    abv: 6.2,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.6,
    reviews: "A refreshing IPA with a smooth finish.",
    origin: "USA",
    pairing: "BBQ, spicy foods",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "New Belgium Fat Tire",
    price: 10.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/new-belgium-fat-tire.jpg",
    description:
      "A well-balanced amber ale with a toasty, biscuit-like malt flavor.",
    category: "Amber Ale",
    abv: 5.2,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.5,
    reviews: "A smooth and easy-drinking amber ale.",
    origin: "USA",
    pairing: "Pizza, roasted meats",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Bell's Two Hearted Ale",
    price: 14.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/bells-two-hearted-ale.jpg",
    description: "An IPA with intense hop aromas of pine and citrus.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "Bell's",
    rating: 4.8,
    reviews: "A highly regarded IPA with a balanced bitterness.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Shiner Bock",
    price: 9.99,
    quantity: 105,
    imageUrl: "https://www.example.com/images/shiner-bock.jpg",
    description:
      "A smooth and easy-drinking dark lager with a hint of roasted malt.",
    category: "Dark Lager",
    abv: 4.4,
    size: "12oz",
    brand: "Shiner",
    rating: 4.6,
    reviews: "A unique and flavorful dark lager.",
    origin: "USA",
    pairing: "BBQ, sausages",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Founders All Day IPA",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/founders-all-day-ipa.jpg",
    description: "A session IPA with balanced hop flavors and a clean finish.",
    category: "IPA",
    abv: 4.7,
    size: "12oz",
    brand: "Founders",
    rating: 4.7,
    reviews: "A great IPA for any time of day.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Anchor Steam Beer",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/anchor-steam-beer.jpg",
    description:
      "A California common beer with a rich, malty flavor and a smooth finish.",
    category: "California Common",
    abv: 4.9,
    size: "12oz",
    brand: "Anchor",
    rating: 4.6,
    reviews: "A unique and flavorful beer with a distinct character.",
    origin: "USA",
    pairing: "Burgers, BBQ",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Michelob Ultra",
    price: 8.99,
    quantity: 130,
    imageUrl: "https://www.example.com/images/michelob-ultra.jpg",
    description: "A light beer with a clean, crisp taste and low calories.",
    category: "Light Beer",
    abv: 4.2,
    size: "12oz",
    brand: "Michelob",
    rating: 4.3,
    reviews: "Perfect for those looking for a low-calorie option.",
    origin: "USA",
    pairing: "Salads, light appetizers",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Goose Island IPA",
    price: 11.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/goose-island-ipa.jpg",
    description: "A hoppy and balanced IPA with citrus and floral notes.",
    category: "IPA",
    abv: 5.9,
    size: "12oz",
    brand: "Goose Island",
    rating: 4.6,
    reviews: "A refreshing IPA with a smooth finish.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Pabst Blue Ribbon",
    price: 7.99,
    quantity: 150,
    imageUrl: "https://www.example.com/images/pabst-blue-ribbon.jpg",
    description: "A classic American lager with a crisp, clean taste.",
    category: "Lager",
    abv: 4.7,
    size: "12oz",
    brand: "Pabst",
    rating: 4.2,
    reviews: "An iconic and affordable beer.",
    origin: "USA",
    pairing: "Burgers, pizza",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Brooklyn Lager",
    price: 11.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/brooklyn-lager.jpg",
    description:
      "A flavorful amber lager with a caramel malt and hop bitterness.",
    category: "Lager",
    abv: 5.2,
    size: "12oz",
    brand: "Brooklyn",
    rating: 4.5,
    reviews: "A well-balanced and enjoyable lager.",
    origin: "USA",
    pairing: "Steak, BBQ",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "New Belgium Voodoo Ranger IPA",
    price: 12.99,
    quantity: 75,
    imageUrl:
      "https://www.example.com/images/new-belgium-voodoo-ranger-ipa.jpg",
    description: "A bold IPA with juicy tropical and citrus flavors.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.7,
    reviews: "A flavorful and aromatic IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Deschutes Black Butte Porter",
    price: 12.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/deschutes-black-butte-porter.jpg",
    description: "A rich and creamy porter with chocolate and coffee notes.",
    category: "Porter",
    abv: 5.2,
    size: "12oz",
    brand: "Deschutes",
    rating: 4.7,
    reviews: "A well-crafted porter with a smooth finish.",
    origin: "USA",
    pairing: "BBQ, desserts",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Great Lakes Edmund Fitzgerald Porter",
    price: 12.99,
    quantity: 65,
    imageUrl:
      "https://www.example.com/images/great-lakes-edmund-fitzgerald-porter.jpg",
    description:
      "A robust porter with roasted malt flavors and a hint of chocolate.",
    category: "Porter",
    abv: 6,
    size: "12oz",
    brand: "Great Lakes",
    rating: 4.8,
    reviews: "A rich and flavorful porter with a smooth finish.",
    origin: "USA",
    pairing: "BBQ, desserts",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Stone IPA",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/stone-ipa.jpg",
    description: "A hop-forward IPA with intense citrus and pine flavors.",
    category: "IPA",
    abv: 6.9,
    size: "12oz",
    brand: "Stone",
    rating: 4.8,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Allagash White",
    price: 13.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/allagash-white.jpg",
    description:
      "A Belgian-style wheat beer with a balance of citrus and spice.",
    category: "Wheat",
    abv: 5.2,
    size: "12oz",
    brand: "Allagash",
    rating: 4.7,
    reviews: "A refreshing and flavorful wheat beer.",
    origin: "USA",
    pairing: "Seafood, salads",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Left Hand Milk Stout",
    price: 12.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/left-hand-milk-stout.jpg",
    description: "A rich and creamy stout with notes of chocolate and coffee.",
    category: "Stout",
    abv: 6,
    size: "12oz",
    brand: "Left Hand",
    rating: 4.8,
    reviews: "A smooth and flavorful stout.",
    origin: "USA",
    pairing: "BBQ, desserts",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Firestone Walker 805",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/firestone-walker-805.jpg",
    description: "A light and refreshing blonde ale with a smooth finish.",
    category: "Blonde Ale",
    abv: 4.7,
    size: "12oz",
    brand: "Firestone Walker",
    rating: 4.6,
    reviews: "A perfect beer for a hot day.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Odell 90 Shilling Ale",
    price: 11.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/odell-90-shilling-ale.jpg",
    description:
      "A smooth and balanced amber ale with caramel and malt flavors.",
    category: "Amber Ale",
    abv: 5.3,
    size: "12oz",
    brand: "Odell",
    rating: 4.7,
    reviews: "A well-balanced and flavorful amber ale.",
    origin: "USA",
    pairing: "Roasted meats, pizza",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Founders Breakfast Stout",
    price: 14.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/founders-breakfast-stout.jpg",
    description: "A rich and complex stout with chocolate and coffee flavors.",
    category: "Stout",
    abv: 8.3,
    size: "12oz",
    brand: "Founders",
    rating: 4.9,
    reviews: "A bold and flavorful stout perfect for sipping.",
    origin: "USA",
    pairing: "BBQ, desserts",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "New Belgium Ranger IPA",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/new-belgium-ranger-ipa.jpg",
    description: "A hop-forward IPA with pine and citrus notes.",
    category: "IPA",
    abv: 6.5,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.7,
    reviews: "A bold and refreshing IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Samuel Adams Summer Ale",
    price: 10.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/samuel-adams-summer-ale.jpg",
    description:
      "A light and refreshing ale with lemon peel and grains of paradise.",
    category: "Ale",
    abv: 5.3,
    size: "12oz",
    brand: "Samuel Adams",
    rating: 4.6,
    reviews: "A perfect summer beer with a crisp finish.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Deschutes Fresh Squeezed IPA",
    price: 12.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/deschutes-fresh-squeezed-ipa.jpg",
    description: "A juicy IPA with bold citrus and tropical fruit flavors.",
    category: "IPA",
    abv: 6.4,
    size: "12oz",
    brand: "Deschutes",
    rating: 4.8,
    reviews: "A refreshing and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Dogfish Head SeaQuench Ale",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/dogfish-head-seaquench-ale.jpg",
    description: "A session sour ale with lime, black lime, and sea salt.",
    category: "Sour Ale",
    abv: 4.9,
    size: "12oz",
    brand: "Dogfish Head",
    rating: 4.6,
    reviews: "A tart and refreshing ale perfect for hot days.",
    origin: "USA",
    pairing: "Seafood, salads",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Sierra Nevada Hazy Little Thing IPA",
    price: 12.99,
    quantity: 90,
    imageUrl:
      "https://www.example.com/images/sierra-nevada-hazy-little-thing-ipa.jpg",
    description: "A hazy IPA with juicy hop flavors and a smooth finish.",
    category: "IPA",
    abv: 6.7,
    size: "12oz",
    brand: "Sierra Nevada",
    rating: 4.7,
    reviews: "A deliciously hazy and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Lagunitas Little Sumpin' Sumpin' Ale",
    price: 12.99,
    quantity: 80,
    imageUrl:
      "https://www.example.com/images/lagunitas-little-sumpin-sumpin-ale.jpg",
    description: "A hoppy pale wheat ale with a smooth and refreshing finish.",
    category: "Pale Wheat Ale",
    abv: 7.5,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.8,
    reviews: "A unique and flavorful ale with a hoppy kick.",
    origin: "USA",
    pairing: "BBQ, spicy foods",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Brooklyn Summer Ale",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/brooklyn-summer-ale.jpg",
    description: "A light and refreshing ale with a crisp finish.",
    category: "Ale",
    abv: 5,
    size: "12oz",
    brand: "Brooklyn",
    rating: 4.6,
    reviews: "A perfect summer beer for any occasion.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Samuel Adams OctoberFest",
    price: 10.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/samuel-adams-octoberfest.jpg",
    description: "A rich and malty Märzen with caramel and toffee notes.",
    category: "Märzen",
    abv: 5.3,
    size: "12oz",
    brand: "Samuel Adams",
    rating: 4.7,
    reviews: "A perfect beer for the fall season.",
    origin: "USA",
    pairing: "Roasted meats, sausages",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "New Belgium Trippel",
    price: 14.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/new-belgium-trippel.jpg",
    description:
      "A Belgian-style ale with a balance of fruity esters and spicy phenols.",
    category: "Belgian Ale",
    abv: 8.5,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.8,
    reviews: "A strong and flavorful Belgian-style ale.",
    origin: "USA",
    pairing: "Cheeses, roasted meats",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Firestone Walker Union Jack IPA",
    price: 12.99,
    quantity: 75,
    imageUrl:
      "https://www.example.com/images/firestone-walker-union-jack-ipa.jpg",
    description: "A hop-forward IPA with bold citrus and tropical flavors.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "Firestone Walker",
    rating: 4.7,
    reviews: "A flavorful and aromatic IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Deschutes Mirror Pond Pale Ale",
    price: 11.99,
    quantity: 85,
    imageUrl:
      "https://www.example.com/images/deschutes-mirror-pond-pale-ale.jpg",
    description: "A classic pale ale with a balanced malt and hop character.",
    category: "Pale Ale",
    abv: 5,
    size: "12oz",
    brand: "Deschutes",
    rating: 4.6,
    reviews: "A well-balanced and refreshing pale ale.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Founders Solid Gold",
    price: 10.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/founders-solid-gold.jpg",
    description: "A premium lager with a crisp, clean taste.",
    category: "Lager",
    abv: 4.4,
    size: "12oz",
    brand: "Founders",
    rating: 4.5,
    reviews: "A refreshing and easy-drinking lager.",
    origin: "USA",
    pairing: "Pizza, seafood",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Anchor Liberty Ale",
    price: 12.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/anchor-liberty-ale.jpg",
    description: "A hoppy and balanced ale with citrus and floral notes.",
    category: "Ale",
    abv: 5.9,
    size: "12oz",
    brand: "Anchor",
    rating: 4.6,
    reviews: "A flavorful and aromatic ale.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Sierra Nevada Torpedo Extra IPA",
    price: 13.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/sierra-nevada-torpedo-extra-ipa.jpg",
    description: "A bold and hop-forward IPA with pine and citrus flavors.",
    category: "IPA",
    abv: 7.2,
    size: "12oz",
    brand: "Sierra Nevada",
    rating: 4.7,
    reviews: "A strong and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Great Lakes Dortmunder Gold Lager",
    price: 11.99,
    quantity: 80,
    imageUrl:
      "https://www.example.com/images/great-lakes-dortmunder-gold-lager.jpg",
    description: "A smooth and balanced lager with a slightly sweet finish.",
    category: "Lager",
    abv: 5.8,
    size: "12oz",
    brand: "Great Lakes",
    rating: 4.6,
    reviews: "A well-crafted and refreshing lager.",
    origin: "USA",
    pairing: "Burgers, chicken",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Lagunitas DayTime IPA",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/lagunitas-daytime-ipa.jpg",
    description: "A light and refreshing IPA with a low ABV.",
    category: "IPA",
    abv: 4,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.5,
    reviews: "A great IPA for any time of day.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Samuel Adams Winter Lager",
    price: 10.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/samuel-adams-winter-lager.jpg",
    description: "A rich and malty lager with spices and a hint of citrus.",
    category: "Lager",
    abv: 5.6,
    size: "12oz",
    brand: "Samuel Adams",
    rating: 4.7,
    reviews: "A perfect beer for the winter season.",
    origin: "USA",
    pairing: "Roasted meats, desserts",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Dogfish Head 90 Minute IPA",
    price: 14.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/dogfish-head-90-minute-ipa.jpg",
    description: "A bold and hoppy IPA with a balanced bitterness.",
    category: "IPA",
    abv: 9,
    size: "12oz",
    brand: "Dogfish Head",
    rating: 4.8,
    reviews: "A strong and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "New Belgium Fat Tire Amber Ale",
    price: 10.99,
    quantity: 90,
    imageUrl:
      "https://www.example.com/images/new-belgium-fat-tire-amber-ale.jpg",
    description:
      "A balanced amber ale with a toasty, biscuit-like malt flavor.",
    category: "Amber Ale",
    abv: 5.2,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.5,
    reviews: "A smooth and easy-drinking amber ale.",
    origin: "USA",
    pairing: "Pizza, roasted meats",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Stone Delicious IPA",
    price: 13.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/stone-delicious-ipa.jpg",
    description: "A gluten-reduced IPA with citrus and pine flavors.",
    category: "IPA",
    abv: 7.7,
    size: "12oz",
    brand: "Stone",
    rating: 4.7,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Sierra Nevada Kellerweis",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/sierra-nevada-kellerweis.jpg",
    description:
      "A traditional Bavarian-style hefeweizen with banana and clove aromas.",
    category: "Hefeweizen",
    abv: 4.8,
    size: "12oz",
    brand: "Sierra Nevada",
    rating: 4.6,
    reviews: "A refreshing and flavorful wheat beer.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Founders Centennial IPA",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/founders-centennial-ipa.jpg",
    description: "A well-balanced IPA with citrus and floral hop aromas.",
    category: "IPA",
    abv: 7.2,
    size: "12oz",
    brand: "Founders",
    rating: 4.7,
    reviews: "A smooth and refreshing IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Firestone Walker Pivo Pils",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/firestone-walker-pivo-pils.jpg",
    description: "A crisp and refreshing pilsner with floral and spicy notes.",
    category: "Pilsner",
    abv: 5.3,
    size: "12oz",
    brand: "Firestone Walker",
    rating: 4.6,
    reviews: "A perfect pilsner for any occasion.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
];

module.exports = domesticBeers;
