const brandies = [
  {
    id: 1,
    name: "Hennessy VS Cognac",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/hennessy-vs.jpg",
    description:
      "A popular cognac with rich flavors of oak, vanilla, and fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A smooth and versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Remy Martin VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/remy-martin-vsop.jpg",
    description:
      "A fine cognac with notes of apricot, vanilla, and floral aromas.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A sophisticated cognac with a smooth and well-balanced taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Courvoisier VS Cognac",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs.jpg",
    description:
      "A classic cognac with flavors of dried fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A well-rounded cognac that is perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Martell VS Cognac",
    price: 32.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/martell-vs.jpg",
    description: "A smooth cognac with notes of fresh fruit and rich oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.6,
    reviews: "A versatile cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "E&J VS Brandy",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/ej-vs.jpg",
    description:
      "A smooth and affordable brandy with notes of sweet fruit and vanilla.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "E&J",
    rating: 4.5,
    reviews: "A popular brandy that is great for mixing or sipping.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Paul Masson VS Brandy",
    price: 13.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/paul-masson-vs.jpg",
    description: "A rich and smooth brandy with notes of caramel and vanilla.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Paul Masson",
    rating: 4.4,
    reviews: "A great value brandy that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Hennessy XO Cognac",
    price: 199.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/hennessy-xo.jpg",
    description:
      "A luxurious cognac with deep and complex flavors of oak, spices, and dark fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Remy Martin XO Cognac",
    price: 229.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo.jpg",
    description:
      "An exquisite cognac with rich and complex flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A high-end cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Courvoisier XO Cognac",
    price: 179.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/courvoisier-xo.jpg",
    description:
      "A refined cognac with flavors of vanilla, dried fruit, and chocolate.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Martell Cordon Bleu Cognac",
    price: 169.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/martell-cordon-bleu.jpg",
    description:
      "A classic cognac with rich and complex flavors of fruit and spice.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Camus VSOP Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/camus-vsop.jpg",
    description: "A smooth cognac with flavors of apricot, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Camus",
    rating: 4.7,
    reviews: "A versatile cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Hine Rare VSOP Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-vsop.jpg",
    description: "A fine cognac with notes of vanilla, honey, and dried fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A sophisticated cognac with a smooth and well-balanced taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Pierre Ferrand Ambre Cognac",
    price: 49.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/pierre-ferrand-ambre.jpg",
    description: "A smooth cognac with flavors of vanilla, pear, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Pierre Ferrand",
    rating: 4.7,
    reviews: "A versatile cognac that is perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "D'Usse VSOP Cognac",
    price: 49.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/dusse-vsop.jpg",
    description:
      "A fine cognac with notes of cinnamon, honey, and dried fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "D'Usse",
    rating: 4.7,
    reviews: "A smooth cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Hennessy Black Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/hennessy-black.jpg",
    description:
      "A smooth cognac with rich flavors of oak, vanilla, and fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.6,
    reviews: "A versatile cognac that is perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Louis Royer VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/louis-royer-vsop.jpg",
    description: "A smooth cognac with flavors of apricot, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Louis Royer",
    rating: 4.7,
    reviews: "A versatile cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Hennessy Paradis Cognac",
    price: 799.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/hennessy-paradis.jpg",
    description:
      "A luxurious cognac with deep and complex flavors of oak, spices, and dark fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Remy Martin Louis XIII Cognac",
    price: 3499.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/remy-martin-louis-xiii.jpg",
    description:
      "An exquisite cognac with rich and complex flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A high-end cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Courvoisier Napoleon Cognac",
    price: 99.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/courvoisier-napoleon.jpg",
    description:
      "A refined cognac with flavors of vanilla, dried fruit, and chocolate.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Martell XO Cognac",
    price: 179.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/martell-xo.jpg",
    description:
      "A classic cognac with rich and complex flavors of fruit and spice.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Camus XO Elegance Cognac",
    price: 139.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/camus-xo.jpg",
    description: "A smooth cognac with flavors of apricot, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Camus",
    rating: 4.7,
    reviews: "A versatile cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Hine Antique XO Cognac",
    price: 159.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hine-antique-xo.jpg",
    description: "A fine cognac with notes of vanilla, honey, and dried fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A sophisticated cognac with a smooth and well-balanced taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Pierre Ferrand Reserve Cognac",
    price: 79.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/pierre-ferrand-reserve.jpg",
    description: "A smooth cognac with flavors of vanilla, pear, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Pierre Ferrand",
    rating: 4.7,
    reviews: "A versatile cognac that is perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "D'Usse XO Cognac",
    price: 149.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dusse-xo.jpg",
    description:
      "A fine cognac with notes of cinnamon, honey, and dried fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "D'Usse",
    rating: 4.7,
    reviews: "A smooth cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Hennessy Paradis Imperial Cognac",
    price: 2599.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/hennessy-paradis-imperial.jpg",
    description:
      "A luxurious cognac with deep and complex flavors of oak, spices, and dark fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Asbach Uralt Brandy",
    price: 29.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/asbach-uralt.jpg",
    description:
      "A smooth German brandy with rich flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 38,
    size: "750ml",
    brand: "Asbach",
    rating: 4.7,
    reviews: "A versatile brandy that is perfect for sipping or cocktails.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Cardenal Mendoza Solera Gran Reserva Brandy",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cardenal-mendoza.jpg",
    description:
      "A Spanish brandy with rich and complex flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Cardenal Mendoza",
    rating: 4.8,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Torres 10 Gran Reserva Brandy",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/torres-10.jpg",
    description: "A Spanish brandy with flavors of vanilla, nuts, and spices.",
    category: "Brandy",
    abv: 38,
    size: "750ml",
    brand: "Torres",
    rating: 4.6,
    reviews: "A well-rounded brandy that is great for sipping or mixing.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Fundador Solera Reserva Brandy",
    price: 19.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/fundador-solera.jpg",
    description:
      "A smooth Spanish brandy with notes of caramel, vanilla, and oak.",
    category: "Brandy",
    abv: 36,
    size: "750ml",
    brand: "Fundador",
    rating: 4.5,
    reviews: "A great value brandy that is perfect for cocktails.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Carlos I Solera Gran Reserva Brandy",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/carlos-i.jpg",
    description:
      "A rich and smooth Spanish brandy with flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Carlos I",
    rating: 4.7,
    reviews: "A versatile brandy that is perfect for sipping or cocktails.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Metaxa 7 Star Brandy",
    price: 27.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/metaxa-7-star.jpg",
    description:
      "A Greek brandy with rich flavors of fruit, honey, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Metaxa",
    rating: 4.7,
    reviews: "A smooth and versatile brandy perfect for sipping or mixing.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Ararat 10 Year Old Brandy",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ararat-10-year.jpg",
    description:
      "An Armenian brandy with complex flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Ararat",
    rating: 4.8,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "Armenia",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "St-Rémy VSOP Brandy",
    price: 21.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/st-remy-vsop.jpg",
    description:
      "A French brandy with smooth flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "St-Rémy",
    rating: 4.6,
    reviews: "A versatile brandy that is perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Raynal VSOP Brandy",
    price: 19.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/raynal-vsop.jpg",
    description:
      "A smooth and affordable French brandy with notes of fruit and vanilla.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Raynal",
    rating: 4.5,
    reviews: "A popular brandy that is great for mixing or sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Almendrado Brandy",
    price: 14.99,
    quantity: 120,
    imageUrl: "https://www.example.com/images/almendrado-brandy.jpg",
    description:
      "A Mexican brandy with sweet almond flavors and smooth finish.",
    category: "Brandy",
    abv: 35,
    size: "750ml",
    brand: "Almendrado",
    rating: 4.4,
    reviews: "A unique brandy that is perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Kelt XO Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/kelt-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Kelt",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Kavalan Distillery Select Brandy",
    price: 69.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/kavalan-brandy.jpg",
    description:
      "A Taiwanese brandy with smooth flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Kavalan",
    rating: 4.8,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "Taiwan",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Osborne Carlos III Brandy",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/osborne-carlos-iii.jpg",
    description:
      "A Spanish brandy with rich flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 36,
    size: "750ml",
    brand: "Osborne",
    rating: 4.6,
    reviews: "A versatile brandy that is perfect for sipping or mixing.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Soberano Brandy",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/soberano-brandy.jpg",
    description:
      "A smooth and affordable Spanish brandy with notes of fruit and vanilla.",
    category: "Brandy",
    abv: 36,
    size: "750ml",
    brand: "Soberano",
    rating: 4.5,
    reviews: "A popular brandy that is great for mixing or sipping.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Kweichow Moutai Prince Brandy",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/kweichow-moutai.jpg",
    description:
      "A Chinese brandy with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Kweichow Moutai",
    rating: 4.7,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "China",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "A. de Fussigny XO Cognac",
    price: 159.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/de-fussigny-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "A. de Fussigny",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Armenian Ararat Brandy",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/armenian-ararat.jpg",
    description:
      "An Armenian brandy with complex flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Ararat",
    rating: 4.8,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "Armenia",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Cles des Ducs XO Armagnac",
    price: 69.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cles-des-ducs-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Cles des Ducs",
    rating: 4.8,
    reviews: "A sophisticated Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Baron de Sigognac 10 Year Old Armagnac",
    price: 49.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/baron-de-sigognac-10.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Baron de Sigognac",
    rating: 4.8,
    reviews: "A sophisticated Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Château de Laubade XO Armagnac",
    price: 89.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/chateau-de-laubade-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Château de Laubade",
    rating: 4.9,
    reviews: "A premium Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Cerbois XO Armagnac",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cerbois-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Cerbois",
    rating: 4.8,
    reviews: "A sophisticated Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Comte de Lauvia XO Armagnac",
    price: 69.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/comte-de-lauvia-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Comte de Lauvia",
    rating: 4.8,
    reviews: "A sophisticated Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Delord 25 Year Old Bas Armagnac",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/delord-25-year.jpg",
    description:
      "A luxurious French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Delord",
    rating: 4.9,
    reviews: "A premium Bas Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Domaine de Menard 10 Year Old Bas Armagnac",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/domaine-de-menard-10.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Domaine de Menard",
    rating: 4.8,
    reviews: "A sophisticated Bas Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Janneau XO Armagnac",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/janneau-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Janneau",
    rating: 4.8,
    reviews: "A premium Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Lhéraud XO Carafe Charles VII",
    price: 159.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/lheraud-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Lhéraud",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Marie Duffau Napoléon Bas Armagnac",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/marie-duffau-napoleon.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Marie Duffau",
    rating: 4.8,
    reviews: "A sophisticated Bas Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Samalens 15 Year Old Bas Armagnac",
    price: 59.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/samalens-15-year.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Samalens",
    rating: 4.8,
    reviews: "A sophisticated Bas Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Tariquet XO Bas Armagnac",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/tariquet-xo.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Tariquet",
    rating: 4.8,
    reviews: "A premium Bas Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Château de Laubade XO Armagnac",
    price: 89.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/chateau-de-laubade-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Château de Laubade",
    rating: 4.9,
    reviews: "A premium Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Armenian Ararat Brandy",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/armenian-ararat.jpg",
    description:
      "An Armenian brandy with complex flavors of fruit, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Ararat",
    rating: 4.8,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "Armenia",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Soberano Brandy",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/soberano-brandy.jpg",
    description:
      "A smooth and affordable Spanish brandy with notes of fruit and vanilla.",
    category: "Brandy",
    abv: 36,
    size: "750ml",
    brand: "Soberano",
    rating: 4.5,
    reviews: "A popular brandy that is great for mixing or sipping.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Delamain Pale & Dry XO Cognac",
    price: 129.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/delamain-pale-dry-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Delamain",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Hardy XO Rare Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/hardy-xo-rare.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hardy",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Jean-Luc Pasquet L'Organic 10 Cognac",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/jean-luc-pasquet-10.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Jean-Luc Pasquet",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Jean Fillioux La Pouyade Cognac",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jean-fillioux-la-pouyade.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Jean Fillioux",
    rating: 4.8,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Kelt XO Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/kelt-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Kelt",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Meukow XO Cognac",
    price: 129.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/meukow-xo.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Meukow",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Paul Giraud VSOP Cognac",
    price: 49.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/paul-giraud-vsop.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Paul Giraud",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Pierre Ferrand 1840 Original Formula Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/pierre-ferrand-1840.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 45,
    size: "750ml",
    brand: "Pierre Ferrand",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Prunier VSOP Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/prunier-vsop.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Prunier",
    rating: 4.7,
    reviews: "A sophisticated cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Richard Delisle XO Cognac",
    price: 109.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/richard-delisle-xo.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Richard Delisle",
    rating: 4.8,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Tesseron Lot No 90 XO Cognac",
    price: 159.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/tesseron-lot-90.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Tesseron",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Vallein Tercinier XO Vieille Reserve Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vallein-tercinier-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Vallein Tercinier",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Hennessy VSOP Privilege Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop.jpg",
    description:
      "A French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Remy Martin XO Cognac",
    price: 229.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo.jpg",
    description:
      "An exquisite cognac with rich and complex flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A high-end cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Hennessy XO Cognac",
    price: 199.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/hennessy-xo.jpg",
    description:
      "A luxurious cognac with deep and complex flavors of oak, spices, and dark fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Courvoisier XO Cognac",
    price: 179.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/courvoisier-xo.jpg",
    description:
      "A refined cognac with flavors of vanilla, dried fruit, and chocolate.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.8,
    reviews: "A sophisticated cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Louis Royer VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/louis-royer-vsop.jpg",
    description: "A smooth cognac with flavors of apricot, vanilla, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Louis Royer",
    rating: 4.7,
    reviews: "A versatile cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Remy Martin VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/remy-martin-vsop.jpg",
    description:
      "A fine cognac with notes of apricot, vanilla, and floral aromas.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A sophisticated cognac with a smooth and well-balanced taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Courvoisier VS Cognac",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs.jpg",
    description:
      "A classic cognac with flavors of dried fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A well-rounded cognac that is perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Martell VS Cognac",
    price: 32.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/martell-vs.jpg",
    description: "A smooth cognac with notes of fresh fruit and rich oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.6,
    reviews: "A versatile cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "E&J VS Brandy",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/ej-vs.jpg",
    description:
      "A smooth and affordable brandy with notes of sweet fruit and vanilla.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "E&J",
    rating: 4.5,
    reviews: "A popular brandy that is great for mixing or sipping.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Paul Masson VS Brandy",
    price: 13.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/paul-masson-vs.jpg",
    description: "A rich and smooth brandy with notes of caramel and vanilla.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Paul Masson",
    rating: 4.4,
    reviews: "A great value brandy that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Hennessy Black Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/hennessy-black.jpg",
    description:
      "A smooth cognac with rich flavors of oak, vanilla, and fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.6,
    reviews: "A versatile cognac that is perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Martell Cordon Bleu Cognac",
    price: 169.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/martell-cordon-bleu.jpg",
    description:
      "A classic cognac with rich and complex flavors of fruit and spice.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Hine Rare VSOP Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-vsop.jpg",
    description: "A fine cognac with notes of vanilla, honey, and dried fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A sophisticated cognac with a smooth and well-balanced taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Pierre Ferrand Ambre Cognac",
    price: 49.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/pierre-ferrand-ambre.jpg",
    description: "A smooth cognac with flavors of vanilla, pear, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Pierre Ferrand",
    rating: 4.7,
    reviews: "A versatile cognac that is perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "D'Usse XO Cognac",
    price: 149.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dusse-xo.jpg",
    description:
      "A fine cognac with notes of cinnamon, honey, and dried fruit.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "D'Usse",
    rating: 4.7,
    reviews: "A smooth cognac that is great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Cardenal Mendoza Solera Gran Reserva Brandy",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cardenal-mendoza.jpg",
    description:
      "A Spanish brandy with rich and complex flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Cardenal Mendoza",
    rating: 4.8,
    reviews: "A sophisticated brandy that is perfect for sipping.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Torres 10 Gran Reserva Brandy",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/torres-10.jpg",
    description: "A Spanish brandy with flavors of vanilla, nuts, and spices.",
    category: "Brandy",
    abv: 38,
    size: "750ml",
    brand: "Torres",
    rating: 4.6,
    reviews: "A well-rounded brandy that is great for sipping or mixing.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Fundador Solera Reserva Brandy",
    price: 19.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/fundador-solera.jpg",
    description:
      "A smooth Spanish brandy with notes of caramel, vanilla, and oak.",
    category: "Brandy",
    abv: 36,
    size: "750ml",
    brand: "Fundador",
    rating: 4.5,
    reviews: "A great value brandy that is perfect for cocktails.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Carlos I Solera Gran Reserva Brandy",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/carlos-i.jpg",
    description:
      "A rich and smooth Spanish brandy with flavors of fruit, spice, and oak.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Carlos I",
    rating: 4.7,
    reviews: "A versatile brandy that is perfect for sipping or cocktails.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Metaxa 7 Star Brandy",
    price: 27.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/metaxa-7-star.jpg",
    description:
      "A Greek brandy with rich flavors of fruit, honey, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Metaxa",
    rating: 4.7,
    reviews: "A smooth and versatile brandy perfect for sipping or mixing.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Château de Laubade XO Armagnac",
    price: 89.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/chateau-de-laubade-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Château de Laubade",
    rating: 4.9,
    reviews: "A premium Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Cerbois XO Armagnac",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cerbois-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Cerbois",
    rating: 4.8,
    reviews: "A sophisticated Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Comte de Lauvia XO Armagnac",
    price: 69.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/comte-de-lauvia-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Comte de Lauvia",
    rating: 4.8,
    reviews: "A sophisticated Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Delord 25 Year Old Bas Armagnac",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/delord-25-year.jpg",
    description:
      "A luxurious French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Delord",
    rating: 4.9,
    reviews: "A premium Bas Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Domaine de Menard 10 Year Old Bas Armagnac",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/domaine-de-menard-10.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Domaine de Menard",
    rating: 4.8,
    reviews: "A sophisticated Bas Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Janneau XO Armagnac",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/janneau-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Janneau",
    rating: 4.8,
    reviews: "A premium Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Lhéraud XO Carafe Charles VII",
    price: 159.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/lheraud-xo.jpg",
    description:
      "A luxurious French cognac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Lhéraud",
    rating: 4.9,
    reviews: "A premium cognac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Marie Duffau Napoléon Bas Armagnac",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/marie-duffau-napoleon.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Marie Duffau",
    rating: 4.8,
    reviews: "A sophisticated Bas Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Samalens 15 Year Old Bas Armagnac",
    price: 59.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/samalens-15-year.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Samalens",
    rating: 4.8,
    reviews: "A sophisticated Bas Armagnac that is perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Tariquet XO Bas Armagnac",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/tariquet-xo.jpg",
    description:
      "A French Bas Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Tariquet",
    rating: 4.8,
    reviews: "A premium Bas Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Château de Laubade XO Armagnac",
    price: 89.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/chateau-de-laubade-xo.jpg",
    description:
      "A French Armagnac with rich flavors of fruit, vanilla, and spices.",
    category: "Brandy",
    abv: 40,
    size: "750ml",
    brand: "Château de Laubade",
    rating: 4.9,
    reviews: "A premium Armagnac that is perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
];

module.exports = brandies;
