const cognacs = [
  {
    id: 1,
    name: "Hennessy VS Cognac",
    price: 39.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vs.jpg",
    description: "A classic cognac with rich and robust flavors.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.6,
    reviews: "A versatile cognac that is great for mixing or sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Courvoisier VS Cognac",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs.jpg",
    description: "A well-balanced cognac with floral and fruity notes.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A popular choice for both mixing and sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Remy Martin VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/remy-martin-vsop.jpg",
    description: "Smooth and fruity with a hint of oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Martell VS Cognac",
    price: 32.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/martell-vs.jpg",
    description: "Fresh and fruity with notes of citrus and pear.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.6,
    reviews: "A versatile cognac great for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Hine Rare VSOP Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-vsop.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Louis Royer VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/louis-royer-vsop.jpg",
    description: "Smooth and balanced with flavors of apricot and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Louis Royer",
    rating: 4.7,
    reviews: "A versatile cognac great for sipping or cocktails.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Pierre Ferrand Ambre Cognac",
    price: 49.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/pierre-ferrand-ambre.jpg",
    description: "Elegant and floral with notes of pear and honey.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Pierre Ferrand",
    rating: 4.7,
    reviews: "A great cognac for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "D'Usse VSOP Cognac",
    price: 59.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/dusse-vsop.jpg",
    description: "Rich and smooth with notes of cinnamon and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "D'Usse",
    rating: 4.8,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Courvoisier XO Cognac",
    price: 179.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/courvoisier-xo.jpg",
    description:
      "Luxurious and rich with flavors of dried fruit and chocolate.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Hennessy XO Cognac",
    price: 199.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/hennessy-xo.jpg",
    description: "Deep and complex with notes of oak, spices, and dark fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.9,
    reviews: "A luxurious cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Martell Cordon Bleu Cognac",
    price: 169.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/martell-cordon-bleu.jpg",
    description: "Rich and complex with flavors of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.9,
    reviews: "A premium cognac perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Remy Martin XO Cognac",
    price: 229.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo.jpg",
    description: "Rich and complex with notes of fruit, spice, and oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A high-end cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Hine Antique XO Cognac",
    price: 159.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hine-antique-xo.jpg",
    description: "Smooth and elegant with notes of vanilla and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac with a smooth and well-balanced taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Delamain Pale & Dry XO Cognac",
    price: 129.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/delamain-pale-dry-xo.jpg",
    description: "Elegant and refined with flavors of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Delamain",
    rating: 4.8,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Hardy XO Rare Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/hardy-xo-rare.jpg",
    description: "Luxurious and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hardy",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Jean Fillioux La Pouyade Cognac",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jean-fillioux-la-pouyade.jpg",
    description: "Smooth and fruity with notes of apricot and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Jean Fillioux",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Pierre Ferrand 1840 Original Formula Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/pierre-ferrand-1840.jpg",
    description: "Rich and smooth with flavors of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Pierre Ferrand",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Prunier VSOP Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/prunier-vsop.jpg",
    description: "Smooth and well-balanced with flavors of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Prunier",
    rating: 4.7,
    reviews: "A sophisticated cognac perfect for sipping.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Richard Delisle XO Cognac",
    price: 109.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/richard-delisle-xo.jpg",
    description: "Rich and complex with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Richard Delisle",
    rating: 4.8,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Tesseron Lot No 90 XO Cognac",
    price: 159.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/tesseron-lot-90.jpg",
    description: "Luxurious and smooth with flavors of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Tesseron",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Vallein Tercinier XO Vieille Reserve Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vallein-tercinier-xo.jpg",
    description: "Luxurious and rich with flavors of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Vallein Tercinier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Hennessy Paradis Cognac",
    price: 999.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/hennessy-paradis.jpg",
    description:
      "An ultra-premium cognac with exceptional smoothness and complexity.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 5.0,
    reviews: "A top-shelf cognac perfect for the most special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Remy Martin Louis XIII Cognac",
    price: 3299.99,
    quantity: 2,
    imageUrl: "https://www.example.com/images/remy-martin-louis-xiii.jpg",
    description:
      "The pinnacle of cognac, with unparalleled richness and complexity.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 5.0,
    reviews: "A once-in-a-lifetime experience in every sip.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Courvoisier Initiale Extra Cognac",
    price: 499.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/courvoisier-initiale-extra.jpg",
    description: "A rare and exquisite blend of aged cognacs.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A luxurious cognac for the discerning connoisseur.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Hine Triomphe Cognac",
    price: 349.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/hine-triomphe.jpg",
    description:
      "A masterpiece of elegance and depth, with notes of dried fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.9,
    reviews: "A sophisticated cognac for the true connoisseur.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Frapin VIP XO Cognac",
    price: 199.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/frapin-vip-xo.jpg",
    description: "Rich and complex with notes of dried fruit and oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Frapin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Hennessy Pure White Cognac",
    price: 79.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/hennessy-pure-white.jpg",
    description: "Light and fruity with delicate floral notes.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A refreshing cognac perfect for warm weather.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Remy Martin Tercet Cognac",
    price: 99.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/remy-martin-tercet.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Cognac",
    abv: 42,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.8,
    reviews: "A sophisticated cognac with a unique flavor profile.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Courvoisier L'Essence de Courvoisier",
    price: 2499.99,
    quantity: 3,
    imageUrl: "https://www.example.com/images/courvoisier-lessence.jpg",
    description: "An exquisite blend of rare and aged eaux-de-vie.",
    category: "Cognac",
    abv: 42,
    size: "750ml",
    brand: "Courvoisier",
    rating: 5.0,
    reviews: "A luxurious cognac for the most special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Hennessy VSOP Privilege Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop.jpg",
    description: "Rich and smooth with flavors of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Remy Martin Club Cognac",
    price: 99.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/remy-martin-club.jpg",
    description: "Rich and complex with notes of fruit and oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Martell Blue Swift Cognac",
    price: 49.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/martell-blue-swift.jpg",
    description: "Smooth and elegant with notes of fruit and honey.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Hine Homage XO Cognac",
    price: 189.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/hine-homage-xo.jpg",
    description: "Elegant and refined with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Courvoisier VSOP Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/courvoisier-vsop.jpg",
    description: "Rich and smooth with flavors of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Hennessy Black Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/hennessy-black.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.6,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Remy Martin XO Excellence Cognac",
    price: 239.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/remy-martin-xo-excellence.jpg",
    description: "Rich and complex with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Martell XO Cognac",
    price: 189.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/martell-xo.jpg",
    description: "Elegant and refined with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Hine Bonneuil 2006 Cognac",
    price: 299.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/hine-bonneuil-2006.jpg",
    description: "Luxurious and complex with notes of fruit and oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Courvoisier VSOP Exclusif Cognac",
    price: 59.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/courvoisier-vsop-exclusif.jpg",
    description: "Rich and smooth with flavors of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Hennessy Privilege VSOP Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-privilege-vsop.jpg",
    description: "Rich and smooth with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Remy Martin VSOP Mature Cask Finish",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/remy-martin-vsop-mature.jpg",
    description: "Smooth and complex with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Martell VS Single Distillery Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/martell-vs-single.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Hine Rare VSOP Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-vsop.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Courvoisier Napoleon Fine Champagne Cognac",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/courvoisier-napoleon.jpg",
    description: "Rich and complex with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Hennessy VSOP Limited Edition Cognac",
    price: 69.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hennessy-vsop-limited.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A limited edition cognac perfect for collectors.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Remy Martin 1738 Accord Royal Cognac",
    price: 69.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/remy-martin-1738.jpg",
    description: "Rich and smooth with notes of fruit and oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.8,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Martell Caractere Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/martell-caractere.jpg",
    description: "Smooth and elegant with notes of fruit and honey.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Hine Bonneuil 2005 Cognac",
    price: 299.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/hine-bonneuil-2005.jpg",
    description: "Luxurious and complex with notes of fruit and oak.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Courvoisier 12 Year Old Cognac",
    price: 99.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/courvoisier-12-year.jpg",
    description: "Rich and smooth with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Hennessy Fine de Cognac",
    price: 69.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/hennessy-fine.jpg",
    description: "Smooth and elegant with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Remy Martin Carte Blanche Cognac",
    price: 299.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/remy-martin-carte-blanche.jpg",
    description: "Luxurious and complex with notes of fruit and spice.",
    category: "Cognac",
    abv: 42,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Martell Noblige Cognac",
    price: 79.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/martell-noblige.jpg",
    description: "Smooth and elegant with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Hine Triomphe Cognac",
    price: 349.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/hine-triomphe.jpg",
    description:
      "A masterpiece of elegance and depth, with notes of dried fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.9,
    reviews: "A sophisticated cognac for the true connoisseur.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Hennessy Paradis Impérial Cognac",
    price: 2999.99,
    quantity: 2,
    imageUrl: "https://www.example.com/images/hennessy-paradis-imperial.jpg",
    description:
      "An ultra-premium cognac with exceptional smoothness and complexity.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 5.0,
    reviews: "A top-shelf cognac perfect for the most special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Remy Martin Louis XIII Cognac",
    price: 3299.99,
    quantity: 2,
    imageUrl: "https://www.example.com/images/remy-martin-louis-xiii.jpg",
    description:
      "The pinnacle of cognac, with unparalleled richness and complexity.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 5.0,
    reviews: "A once-in-a-lifetime experience in every sip.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Courvoisier L'Essence de Courvoisier",
    price: 2499.99,
    quantity: 3,
    imageUrl: "https://www.example.com/images/courvoisier-lessence.jpg",
    description: "An exquisite blend of rare and aged eaux-de-vie.",
    category: "Cognac",
    abv: 42,
    size: "750ml",
    brand: "Courvoisier",
    rating: 5.0,
    reviews: "A luxurious cognac for the most special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Hennessy VS Limited Edition Cognac",
    price: 49.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/hennessy-vs-limited.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.7,
    reviews: "A limited edition cognac perfect for collectors.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Remy Martin VSOP Limited Edition Cognac",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/remy-martin-vsop-limited.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.8,
    reviews: "A limited edition cognac perfect for collectors.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Courvoisier VS Limited Edition Cognac",
    price: 49.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/courvoisier-vs-limited.jpg",
    description: "Smooth and rich with notes of fruit and spice.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A limited edition cognac perfect for collectors.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Hine Antique XO Limited Edition Cognac",
    price: 169.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/hine-antique-xo-limited.jpg",
    description: "Smooth and elegant with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A limited edition cognac perfect for collectors.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Remy Martin VSOP Fine Champagne Cognac",
    price: 49.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/remy-martin-vsop-fine.jpg",
    description: "Rich and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Martell VS Fine Champagne Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/martell-vs-fine.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Hennessy VSOP Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop-fine.jpg",
    description: "Rich and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Remy Martin XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/remy-martin-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Courvoisier XO Fine Champagne Cognac",
    price: 179.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/courvoisier-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Hine Rare Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-fine.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Remy Martin XO Special Edition Cognac",
    price: 249.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo-special.jpg",
    description: "Luxurious and complex with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Martell XO Special Edition Cognac",
    price: 199.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/martell-xo-special.jpg",
    description: "Elegant and refined with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Hine Antique XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hine-antique-xo-fine.jpg",
    description: "Smooth and elegant with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Courvoisier VS Fine Champagne Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs-fine.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Hennessy VSOP Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop-fine.jpg",
    description: "Rich and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Remy Martin XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/remy-martin-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Courvoisier XO Fine Champagne Cognac",
    price: 179.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/courvoisier-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Hine Rare Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-fine.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Remy Martin XO Special Edition Cognac",
    price: 249.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo-special.jpg",
    description: "Luxurious and complex with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Martell XO Special Edition Cognac",
    price: 199.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/martell-xo-special.jpg",
    description: "Elegant and refined with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Hine Antique XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hine-antique-xo-fine.jpg",
    description: "Smooth and elegant with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Courvoisier VS Fine Champagne Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs-fine.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Hennessy VSOP Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop-fine.jpg",
    description: "Rich and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Remy Martin XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/remy-martin-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Courvoisier XO Fine Champagne Cognac",
    price: 179.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/courvoisier-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Hine Rare Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-fine.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Remy Martin XO Special Edition Cognac",
    price: 249.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo-special.jpg",
    description: "Luxurious and complex with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Martell XO Special Edition Cognac",
    price: 199.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/martell-xo-special.jpg",
    description: "Elegant and refined with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Hine Antique XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hine-antique-xo-fine.jpg",
    description: "Smooth and elegant with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Courvoisier VS Fine Champagne Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs-fine.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Hennessy VSOP Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop-fine.jpg",
    description: "Rich and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Remy Martin XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/remy-martin-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Courvoisier XO Fine Champagne Cognac",
    price: 179.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/courvoisier-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Hine Rare Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-fine.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Remy Martin XO Special Edition Cognac",
    price: 249.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo-special.jpg",
    description: "Luxurious and complex with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Martell XO Special Edition Cognac",
    price: 199.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/martell-xo-special.jpg",
    description: "Elegant and refined with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Hine Antique XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hine-antique-xo-fine.jpg",
    description: "Smooth and elegant with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Courvoisier VS Fine Champagne Cognac",
    price: 39.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/courvoisier-vs-fine.jpg",
    description: "Smooth and rich with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.7,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Hennessy VSOP Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hennessy-vsop-fine.jpg",
    description: "Rich and smooth with notes of fruit and vanilla.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hennessy",
    rating: 4.8,
    reviews: "A versatile cognac perfect for sipping or mixing.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Remy Martin XO Fine Champagne Cognac",
    price: 159.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/remy-martin-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Courvoisier XO Fine Champagne Cognac",
    price: 179.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/courvoisier-xo-fine.jpg",
    description: "Rich and smooth with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Courvoisier",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Hine Rare Fine Champagne Cognac",
    price: 59.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/hine-rare-fine.jpg",
    description: "Elegant and smooth with notes of honey and dried fruit.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Hine",
    rating: 4.8,
    reviews: "A refined cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Remy Martin XO Special Edition Cognac",
    price: 249.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/remy-martin-xo-special.jpg",
    description: "Luxurious and complex with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Remy Martin",
    rating: 4.9,
    reviews: "A premium cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Martell XO Special Edition Cognac",
    price: 199.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/martell-xo-special.jpg",
    description: "Elegant and refined with notes of fruit and spices.",
    category: "Cognac",
    abv: 40,
    size: "750ml",
    brand: "Martell",
    rating: 4.8,
    reviews: "A sophisticated cognac perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
];

module.exports = cognacs;
