const seltzers = [
  {
    id: 1,
    name: "White Claw Hard Seltzer Black Cherry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/white-claw-black-cherry.jpg",
    description:
      "A crisp and refreshing hard seltzer with natural black cherry flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "White Claw",
    rating: 4.7,
    reviews: "A popular and refreshing seltzer with a natural cherry taste.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Truly Hard Seltzer Wild Berry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/truly-wild-berry.jpg",
    description:
      "A mix of wild berry flavors in a crisp and refreshing hard seltzer.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Truly",
    rating: 4.6,
    reviews: "A flavorful seltzer with a refreshing berry blend.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Bon & Viv Spiked Seltzer Grapefruit",
    price: 15.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/bon-viv-grapefruit.jpg",
    description: "A light and refreshing seltzer with a hint of grapefruit.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Bon & Viv",
    rating: 4.5,
    reviews:
      "A crisp and flavorful seltzer with a refreshing grapefruit taste.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Bud Light Seltzer Mango",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/bud-light-mango.jpg",
    description: "A refreshing seltzer with a sweet and juicy mango flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Bud Light",
    rating: 4.6,
    reviews: "A tropical and refreshing mango-flavored seltzer.",
    origin: "USA",
    pairing: "Tropical fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Vizzy Hard Seltzer Pineapple Mango",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/vizzy-pineapple-mango.jpg",
    description:
      "A unique seltzer with antioxidant vitamin C from acerola superfruit.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Vizzy",
    rating: 4.7,
    reviews:
      "A refreshing seltzer with a tropical blend and added antioxidants.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Corona Hard Seltzer Tropical Lime",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/corona-tropical-lime.jpg",
    description:
      "A crisp and refreshing hard seltzer with a tropical lime flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Corona",
    rating: 4.5,
    reviews: "A light and refreshing seltzer with a hint of lime.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Topo Chico Hard Seltzer Strawberry Guava",
    price: 17.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/topo-chico-strawberry-guava.jpg",
    description:
      "A bold and fruity seltzer with natural strawberry and guava flavors.",
    category: "Hard Seltzer",
    abv: 4.7,
    size: "12oz",
    brand: "Topo Chico",
    rating: 4.7,
    reviews: "A flavorful seltzer with a tropical twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Smirnoff Seltzer Red, White & Berry",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/smirnoff-red-white-berry.jpg",
    description:
      "A festive seltzer with a blend of cherry, citrus, and blue raspberry flavors.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A patriotic and refreshing seltzer perfect for celebrations.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Henry's Hard Sparkling Water Lemon Lime",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/henrys-lemon-lime.jpg",
    description:
      "A light and refreshing seltzer with a zesty lemon-lime flavor.",
    category: "Hard Seltzer",
    abv: 4.2,
    size: "12oz",
    brand: "Henry's",
    rating: 4.5,
    reviews: "A crisp and clean seltzer with a hint of citrus.",
    origin: "USA",
    pairing: "Seafood, light snacks",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Press Premium Blood Orange Chili",
    price: 18.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/press-blood-orange-chili.jpg",
    description:
      "A sophisticated seltzer with a blend of blood orange and chili.",
    category: "Hard Seltzer",
    abv: 4,
    size: "12oz",
    brand: "Press",
    rating: 4.7,
    reviews: "A unique and flavorful seltzer with a spicy kick.",
    origin: "USA",
    pairing: "Spicy foods, light snacks",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Crook & Marker Spiked & Sparkling Blackberry Lime",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/crook-marker-blackberry-lime.jpg",
    description: "A bold seltzer with a blend of blackberry and lime flavors.",
    category: "Hard Seltzer",
    abv: 4,
    size: "12oz",
    brand: "Crook & Marker",
    rating: 4.6,
    reviews: "A refreshing seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Nauti Seltzer Raspberry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/nauti-raspberry.jpg",
    description:
      "A crisp and refreshing seltzer with a natural raspberry flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Nauti",
    rating: 4.5,
    reviews: "A light and fruity seltzer perfect for any occasion.",
    origin: "USA",
    pairing: "Salads, light snacks",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Wild Basin Black Raspberry",
    price: 17.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/wild-basin-black-raspberry.jpg",
    description: "A flavorful seltzer with a hint of black raspberry.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Wild Basin",
    rating: 4.7,
    reviews: "A bold and refreshing seltzer with natural fruit flavors.",
    origin: "USA",
    pairing: "Light snacks, fruits",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Arctic Summer Black Cherry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/arctic-summer-black-cherry.jpg",
    description: "A refreshing seltzer with a natural black cherry flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Arctic Summer",
    rating: 4.6,
    reviews: "A crisp and clean seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Mighty Swell Peach",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/mighty-swell-peach.jpg",
    description: "A juicy and refreshing seltzer with a natural peach flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Mighty Swell",
    rating: 4.6,
    reviews: "A flavorful seltzer with a sweet peach taste.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Vizzy Hard Seltzer Blueberry Pomegranate",
    price: 17.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/vizzy-blueberry-pomegranate.jpg",
    description:
      "A unique seltzer with antioxidant vitamin C from acerola superfruit.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Vizzy",
    rating: 4.7,
    reviews: "A refreshing seltzer with a berry blend and added antioxidants.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "White Claw Hard Seltzer Raspberry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/white-claw-raspberry.jpg",
    description:
      "A crisp and refreshing seltzer with a natural raspberry flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "White Claw",
    rating: 4.7,
    reviews: "A popular and refreshing seltzer with a natural raspberry taste.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Truly Hard Seltzer Pineapple",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/truly-pineapple.jpg",
    description:
      "A tropical and refreshing seltzer with a natural pineapple flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Truly",
    rating: 4.6,
    reviews: "A flavorful seltzer with a refreshing pineapple taste.",
    origin: "USA",
    pairing: "Tropical fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Bon & Viv Spiked Seltzer Pear Elderflower",
    price: 15.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/bon-viv-pear-elderflower.jpg",
    description:
      "A light and refreshing seltzer with a hint of pear and elderflower.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Bon & Viv",
    rating: 4.5,
    reviews: "A crisp and flavorful seltzer with a unique blend of flavors.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Bud Light Seltzer Black Cherry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/bud-light-black-cherry.jpg",
    description:
      "A refreshing seltzer with a sweet and juicy black cherry flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Bud Light",
    rating: 4.6,
    reviews: "A crisp and refreshing black cherry-flavored seltzer.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Vizzy Hard Seltzer Watermelon Strawberry",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/vizzy-watermelon-strawberry.jpg",
    description:
      "A unique seltzer with antioxidant vitamin C from acerola superfruit.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Vizzy",
    rating: 4.7,
    reviews:
      "A refreshing seltzer with a blend of watermelon and strawberry flavors.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Corona Hard Seltzer Cherry",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/corona-cherry.jpg",
    description: "A crisp and refreshing hard seltzer with a cherry flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Corona",
    rating: 4.5,
    reviews: "A light and refreshing seltzer with a hint of cherry.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Topo Chico Hard Seltzer Exotic Pineapple",
    price: 17.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/topo-chico-exotic-pineapple.jpg",
    description: "A bold and fruity seltzer with natural pineapple flavors.",
    category: "Hard Seltzer",
    abv: 4.7,
    size: "12oz",
    brand: "Topo Chico",
    rating: 4.7,
    reviews: "A flavorful seltzer with a tropical twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Smirnoff Seltzer Peach",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/smirnoff-peach.jpg",
    description: "A crisp and refreshing seltzer with a natural peach flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A light and fruity seltzer perfect for any occasion.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Henry's Hard Sparkling Water Passion Fruit",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/henrys-passion-fruit.jpg",
    description: "A light and refreshing seltzer with a hint of passion fruit.",
    category: "Hard Seltzer",
    abv: 4.2,
    size: "12oz",
    brand: "Henry's",
    rating: 4.5,
    reviews: "A crisp and clean seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Seafood, light snacks",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Press Premium Pomegranate Ginger",
    price: 18.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/press-pomegranate-ginger.jpg",
    description:
      "A sophisticated seltzer with a blend of pomegranate and ginger.",
    category: "Hard Seltzer",
    abv: 4,
    size: "12oz",
    brand: "Press",
    rating: 4.7,
    reviews: "A unique and flavorful seltzer with a spicy kick.",
    origin: "USA",
    pairing: "Spicy foods, light snacks",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Crook & Marker Spiked & Sparkling Tangerine",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/crook-marker-tangerine.jpg",
    description: "A bold seltzer with a blend of tangerine flavors.",
    category: "Hard Seltzer",
    abv: 4,
    size: "12oz",
    brand: "Crook & Marker",
    rating: 4.6,
    reviews: "A refreshing seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Nauti Seltzer Lemon Lime",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/nauti-lemon-lime.jpg",
    description:
      "A crisp and refreshing seltzer with a natural lemon-lime flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Nauti",
    rating: 4.5,
    reviews: "A light and fruity seltzer perfect for any occasion.",
    origin: "USA",
    pairing: "Salads, light snacks",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Wild Basin Classic Lime",
    price: 17.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/wild-basin-classic-lime.jpg",
    description: "A flavorful seltzer with a hint of classic lime.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Wild Basin",
    rating: 4.7,
    reviews: "A bold and refreshing seltzer with natural fruit flavors.",
    origin: "USA",
    pairing: "Light snacks, fruits",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Arctic Summer Pineapple Pomelo",
    price: 16.99,
    quantity: 100,
    imageUrl:
      "https://www.example.com/images/arctic-summer-pineapple-pomelo.jpg",
    description:
      "A refreshing seltzer with a natural pineapple and pomelo flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Arctic Summer",
    rating: 4.6,
    reviews: "A crisp and clean seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Mighty Swell Watermelon Mint",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/mighty-swell-watermelon-mint.jpg",
    description:
      "A juicy and refreshing seltzer with a natural watermelon and mint flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Mighty Swell",
    rating: 4.6,
    reviews: "A flavorful seltzer with a refreshing twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Vizzy Hard Seltzer Pineapple Mango",
    price: 17.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/vizzy-pineapple-mango.jpg",
    description:
      "A unique seltzer with antioxidant vitamin C from acerola superfruit.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Vizzy",
    rating: 4.7,
    reviews:
      "A refreshing seltzer with a tropical blend and added antioxidants.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "White Claw Hard Seltzer Natural Lime",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/white-claw-natural-lime.jpg",
    description: "A crisp and refreshing seltzer with a natural lime flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "White Claw",
    rating: 4.7,
    reviews: "A popular and refreshing seltzer with a natural lime taste.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Truly Hard Seltzer Blueberry & Acai",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/truly-blueberry-acai.jpg",
    description:
      "A unique and refreshing seltzer with a blend of blueberry and acai flavors.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Truly",
    rating: 4.6,
    reviews: "A flavorful seltzer with a refreshing twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Bon & Viv Spiked Seltzer Cranberry",
    price: 15.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/bon-viv-cranberry.jpg",
    description: "A light and refreshing seltzer with a hint of cranberry.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Bon & Viv",
    rating: 4.5,
    reviews: "A crisp and flavorful seltzer with a unique blend of flavors.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Bud Light Seltzer Strawberry",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/bud-light-strawberry.jpg",
    description:
      "A refreshing seltzer with a sweet and juicy strawberry flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Bud Light",
    rating: 4.6,
    reviews: "A crisp and refreshing strawberry-flavored seltzer.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Vizzy Hard Seltzer Blackberry Lemon",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/vizzy-blackberry-lemon.jpg",
    description:
      "A unique seltzer with antioxidant vitamin C from acerola superfruit.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Vizzy",
    rating: 4.7,
    reviews:
      "A refreshing seltzer with a blend of blackberry and lemon flavors.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Corona Hard Seltzer Grapefruit",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/corona-grapefruit.jpg",
    description:
      "A crisp and refreshing hard seltzer with a grapefruit flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Corona",
    rating: 4.5,
    reviews: "A light and refreshing seltzer with a hint of grapefruit.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Topo Chico Hard Seltzer Lemon Lime",
    price: 17.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/topo-chico-lemon-lime.jpg",
    description: "A bold and fruity seltzer with natural lemon-lime flavors.",
    category: "Hard Seltzer",
    abv: 4.7,
    size: "12oz",
    brand: "Topo Chico",
    rating: 4.7,
    reviews: "A flavorful seltzer with a refreshing twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Smirnoff Seltzer Black Cherry",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/smirnoff-black-cherry.jpg",
    description:
      "A crisp and refreshing seltzer with a natural black cherry flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A light and fruity seltzer perfect for any occasion.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Henry's Hard Sparkling Water Blueberry Lemon",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/henrys-blueberry-lemon.jpg",
    description:
      "A light and refreshing seltzer with a hint of blueberry and lemon.",
    category: "Hard Seltzer",
    abv: 4.2,
    size: "12oz",
    brand: "Henry's",
    rating: 4.5,
    reviews: "A crisp and clean seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Seafood, light snacks",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Press Premium Lime Lemongrass",
    price: 18.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/press-lime-lemongrass.jpg",
    description: "A sophisticated seltzer with a blend of lime and lemongrass.",
    category: "Hard Seltzer",
    abv: 4,
    size: "12oz",
    brand: "Press",
    rating: 4.7,
    reviews: "A unique and flavorful seltzer with a refreshing twist.",
    origin: "USA",
    pairing: "Spicy foods, light snacks",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Crook & Marker Spiked & Sparkling Grapefruit",
    price: 17.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/crook-marker-grapefruit.jpg",
    description: "A bold seltzer with a blend of grapefruit flavors.",
    category: "Hard Seltzer",
    abv: 4,
    size: "12oz",
    brand: "Crook & Marker",
    rating: 4.6,
    reviews: "A refreshing seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Nauti Seltzer Mango",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/nauti-mango.jpg",
    description: "A crisp and refreshing seltzer with a natural mango flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Nauti",
    rating: 4.5,
    reviews: "A light and fruity seltzer perfect for any occasion.",
    origin: "USA",
    pairing: "Salads, light snacks",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Wild Basin Lemon Agave Hibiscus",
    price: 17.99,
    quantity: 95,
    imageUrl:
      "https://www.example.com/images/wild-basin-lemon-agave-hibiscus.jpg",
    description:
      "A flavorful seltzer with a hint of lemon, agave, and hibiscus.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Wild Basin",
    rating: 4.7,
    reviews: "A bold and refreshing seltzer with natural fruit flavors.",
    origin: "USA",
    pairing: "Light snacks, fruits",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Arctic Summer Ruby Red Grapefruit",
    price: 16.99,
    quantity: 100,
    imageUrl:
      "https://www.example.com/images/arctic-summer-ruby-red-grapefruit.jpg",
    description:
      "A refreshing seltzer with a natural ruby red grapefruit flavor.",
    category: "Hard Seltzer",
    abv: 4.5,
    size: "12oz",
    brand: "Arctic Summer",
    rating: 4.6,
    reviews: "A crisp and clean seltzer with a fruity twist.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Mighty Swell Cherry Lime",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/mighty-swell-cherry-lime.jpg",
    description:
      "A juicy and refreshing seltzer with a natural cherry and lime flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Mighty Swell",
    rating: 4.6,
    reviews: "A flavorful seltzer with a refreshing twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Vizzy Hard Seltzer Peach Mango",
    price: 17.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/vizzy-peach-mango.jpg",
    description:
      "A unique seltzer with antioxidant vitamin C from acerola superfruit.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Vizzy",
    rating: 4.7,
    reviews: "A refreshing seltzer with a blend of peach and mango flavors.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "White Claw Hard Seltzer Lemon",
    price: 16.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/white-claw-lemon.jpg",
    description: "A crisp and refreshing seltzer with a natural lemon flavor.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "White Claw",
    rating: 4.7,
    reviews: "A popular and refreshing seltzer with a natural lemon taste.",
    origin: "USA",
    pairing: "Light snacks, salads",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Truly Hard Seltzer Passion Fruit",
    price: 16.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/truly-passion-fruit.jpg",
    description:
      "A unique and refreshing seltzer with a blend of passion fruit flavors.",
    category: "Hard Seltzer",
    abv: 5,
    size: "12oz",
    brand: "Truly",
    rating: 4.6,
    reviews: "A flavorful seltzer with a refreshing twist.",
    origin: "USA",
    pairing: "Fruits, light snacks",
    availability: "In Stock",
  },
];

module.exports = seltzers;
