const anejos = [
  {
    id: 1,
    name: "Don Julio Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-anejo.jpg",
    description: "Rich and complex with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium aged tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Patrón Añejo Tequila",
    price: 54.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/patron-anejo.jpg",
    description: "Smooth and sweet with notes of oak and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.7,
    reviews: "A well-balanced tequila with a rich flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Casamigos Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/casamigos-anejo.jpg",
    description: "Smooth and full-bodied with notes of caramel and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casamigos",
    rating: 4.8,
    reviews: "A premium tequila with a rich, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Herradura Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/herradura-anejo.jpg",
    description: "Rich and smooth with notes of dried fruit and spices.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.7,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "1800 Añejo Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/1800-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and butterscotch.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.6,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "El Tesoro Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/el-tesoro-anejo.jpg",
    description: "Rich and full-bodied with notes of chocolate and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Cazadores Añejo Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/cazadores-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.7,
    reviews: "A well-balanced tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Milagro Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/milagro-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Clase Azul Añejo Tequila",
    price: 299.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/clase-azul-anejo.jpg",
    description: "Rich and full-bodied with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Olmeca Altos Añejo Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/olmeca-altos-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Espolòn Añejo Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/espolon-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Corralejo Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/corralejo-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Corralejo",
    rating: 4.7,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Avión Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/avion-anejo.jpg",
    description: "Rich and smooth with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.8,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Fortaleza Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/fortaleza-anejo.jpg",
    description: "Rich and full-bodied with notes of vanilla and butterscotch.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Tres Generaciones Añejo Tequila",
    price: 54.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/tres-generaciones-anejo.jpg",
    description: "Smooth and rich with notes of caramel and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Generaciones",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Cabo Wabo Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cabo-wabo-anejo.jpg",
    description: "Rich and smooth with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Azul Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/azul-anejo.jpg",
    description: "Smooth and rich with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Azul",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Maestro Dobel Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/maestro-dobel-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Maestro Dobel",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Tromba Añejo Tequila",
    price: 54.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/tromba-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tromba",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Don Pilar Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-pilar-anejo.jpg",
    description: "Rich and smooth with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Pilar",
    rating: 4.8,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Casa Noble Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/casa-noble-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casa Noble",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Exotico Añejo Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/exotico-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Exotico",
    rating: 4.6,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Codigo 1530 Añejo Tequila",
    price: 89.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/codigo-1530-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Codigo 1530",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Siete Leguas Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/siete-leguas-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "El Mayor Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/el-mayor-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Mayor",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Azunia Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/azunia-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Azunia",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Espíritu Lauro Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/espiritu-lauro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espíritu Lauro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Pueblo Viejo Añejo Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/pueblo-viejo-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Pueblo Viejo",
    rating: 4.6,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Gran Centenario Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gran-centenario-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Ocho Añejo Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ocho-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Ocho",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Riazul Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/riazul-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Riazul",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Herradura Selección Suprema",
    price: 349.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/herradura-seleccion-suprema.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 5.0,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Don Julio 1942 Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/don-julio-1942.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Patrón Extra Añejo Tequila",
    price: 89.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/patron-extra-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Clase Azul Ultra Añejo Tequila",
    price: 1699.99,
    quantity: 1,
    imageUrl: "https://www.example.com/images/clase-azul-ultra-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "El Tesoro Paradiso Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-tesoro-paradiso-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Cincoro Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/cincoro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cincoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Tears of Llorona Extra Añejo Tequila",
    price: 249.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/tears-of-llorona-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 43,
    size: "750ml",
    brand: "Tears of Llorona",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Don Abraham Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-abraham-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Abraham",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Don Fulano Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-fulano-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Fulano",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "El Tesoro Extra Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/el-tesoro-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Grand Mayan Ultra Aged Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/grand-mayan-ultra-aged-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Grand Mayan",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Chinaco Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chinaco-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Chinaco",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "San Matias Rey Sol Añejo Tequila",
    price: 219.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/san-matias-rey-sol-anejo.jpg",
    description: "Smooth and rich with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "San Matias",
    rating: 5.0,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Siembra Azul Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/siembra-azul-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siembra Azul",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Jose Cuervo Reserva de la Familia Añejo Tequila",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/jose-cuervo-reserva-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Don Julio Real Añejo Tequila",
    price: 349.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/don-julio-real-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "El Tesoro Paradiso Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-tesoro-paradiso-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Cincoro Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/cincoro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cincoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Tears of Llorona Extra Añejo Tequila",
    price: 249.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/tears-of-llorona-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 43,
    size: "750ml",
    brand: "Tears of Llorona",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Don Abraham Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-abraham-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Abraham",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Don Fulano Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-fulano-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Fulano",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "El Tesoro Extra Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/el-tesoro-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Grand Mayan Ultra Aged Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/grand-mayan-ultra-aged-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Grand Mayan",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Chinaco Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chinaco-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Chinaco",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "San Matias Rey Sol Añejo Tequila",
    price: 219.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/san-matias-rey-sol-anejo.jpg",
    description: "Smooth and rich with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "San Matias",
    rating: 5.0,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Siembra Azul Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/siembra-azul-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siembra Azul",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Jose Cuervo Reserva de la Familia Añejo Tequila",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/jose-cuervo-reserva-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Don Julio Real Añejo Tequila",
    price: 349.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/don-julio-real-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "El Tesoro Paradiso Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-tesoro-paradiso-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Cincoro Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/cincoro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cincoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Tears of Llorona Extra Añejo Tequila",
    price: 249.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/tears-of-llorona-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 43,
    size: "750ml",
    brand: "Tears of Llorona",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Don Abraham Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-abraham-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Abraham",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Don Fulano Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-fulano-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Fulano",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "El Tesoro Extra Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/el-tesoro-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Grand Mayan Ultra Aged Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/grand-mayan-ultra-aged-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Grand Mayan",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Chinaco Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chinaco-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Chinaco",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "San Matias Rey Sol Añejo Tequila",
    price: 219.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/san-matias-rey-sol-anejo.jpg",
    description: "Smooth and rich with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "San Matias",
    rating: 5.0,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Siembra Azul Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/siembra-azul-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siembra Azul",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Jose Cuervo Reserva de la Familia Añejo Tequila",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/jose-cuervo-reserva-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Don Julio Real Añejo Tequila",
    price: 349.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/don-julio-real-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "El Tesoro Paradiso Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-tesoro-paradiso-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Cincoro Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/cincoro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cincoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Tears of Llorona Extra Añejo Tequila",
    price: 249.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/tears-of-llorona-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 43,
    size: "750ml",
    brand: "Tears of Llorona",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Don Abraham Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-abraham-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Abraham",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Don Fulano Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-fulano-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Fulano",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "El Tesoro Extra Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/el-tesoro-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Grand Mayan Ultra Aged Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/grand-mayan-ultra-aged-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Grand Mayan",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Chinaco Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chinaco-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Chinaco",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "San Matias Rey Sol Añejo Tequila",
    price: 219.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/san-matias-rey-sol-anejo.jpg",
    description: "Smooth and rich with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "San Matias",
    rating: 5.0,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Siembra Azul Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/siembra-azul-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siembra Azul",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Jose Cuervo Reserva de la Familia Añejo Tequila",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/jose-cuervo-reserva-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Don Julio Real Añejo Tequila",
    price: 349.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/don-julio-real-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "El Tesoro Paradiso Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-tesoro-paradiso-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Cincoro Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/cincoro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cincoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Tears of Llorona Extra Añejo Tequila",
    price: 249.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/tears-of-llorona-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 43,
    size: "750ml",
    brand: "Tears of Llorona",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Don Abraham Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-abraham-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Abraham",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Don Fulano Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-fulano-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Fulano",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "El Tesoro Extra Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/el-tesoro-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Grand Mayan Ultra Aged Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/grand-mayan-ultra-aged-anejo.jpg",
    description: "Rich and smooth with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Grand Mayan",
    rating: 4.9,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Chinaco Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chinaco-anejo.jpg",
    description: "Smooth and rich with notes of vanilla and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Chinaco",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "San Matias Rey Sol Añejo Tequila",
    price: 219.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/san-matias-rey-sol-anejo.jpg",
    description: "Smooth and rich with notes of caramel and chocolate.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "San Matias",
    rating: 5.0,
    reviews: "A premium aged tequila with a deep, complex flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Siembra Azul Añejo Tequila",
    price: 59.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/siembra-azul-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siembra Azul",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Jose Cuervo Reserva de la Familia Añejo Tequila",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/jose-cuervo-reserva-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Don Julio Real Añejo Tequila",
    price: 349.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/don-julio-real-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "El Tesoro Paradiso Añejo Tequila",
    price: 99.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-tesoro-paradiso-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.9,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Cincoro Añejo Tequila",
    price: 129.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/cincoro-anejo.jpg",
    description: "Rich and smooth with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cincoro",
    rating: 4.9,
    reviews: "A premium aged tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Tears of Llorona Extra Añejo Tequila",
    price: 249.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/tears-of-llorona-extra-anejo.jpg",
    description: "Smooth and rich with notes of caramel and oak.",
    category: "Añejo Tequila",
    abv: 43,
    size: "750ml",
    brand: "Tears of Llorona",
    rating: 5.0,
    reviews: "A premium aged tequila with a distinctive flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Don Abraham Añejo Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-abraham-anejo.jpg",
    description: "Smooth and rich with notes of caramel and vanilla.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Abraham",
    rating: 4.7,
    reviews: "A premium tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Don Fulano Añejo Tequila",
    price: 64.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/don-fulano-anejo.jpg",
    description: "Smooth and aromatic with notes of vanilla and spice.",
    category: "Añejo Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Fulano",
    rating: 4.8,
    reviews: "A well-rounded tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
];

module.exports = anejos;
