const blancos = [
  {
    id: 1,
    name: "Don Julio Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-blanco.jpg",
    description: "Crisp agave flavor with hints of citrus and a clean finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium tequila with a smooth and clean profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Patrón Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/patron-silver.jpg",
    description: "Smooth and sweet with a light pepper finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Casamigos Blanco Tequila",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/casamigos-blanco.jpg",
    description: "Crisp and clean with hints of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casamigos",
    rating: 4.9,
    reviews: "A smooth tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Cazadores Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/cazadores-blanco.jpg",
    description: "Fresh and herbaceous with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A well-rounded tequila great for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Clase Azul Plata Tequila",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clase-azul-plata.jpg",
    description: "Smooth and sweet with hints of vanilla and fruit.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Herradura Silver Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/herradura-silver.jpg",
    description: "Smooth with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.8,
    reviews: "A well-balanced tequila with a crisp finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Espolòn Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-blanco.jpg",
    description: "Crisp and clear with notes of tropical fruit and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Olmeca Altos Plata Tequila",
    price: 27.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/olmeca-altos-plata.jpg",
    description: "Smooth and sweet with a herbal finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A high-quality tequila with a fresh agave flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Milagro Silver Tequila",
    price: 32.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/milagro-silver.jpg",
    description: "Smooth and fresh with hints of citrus and herbs.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "El Jimador Blanco Tequila",
    price: 22.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/el-jimador-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Jimador",
    rating: 4.5,
    reviews: "A popular tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Teremana Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/teremana-blanco.jpg",
    description: "Smooth and sweet with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Teremana",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Luna Azul Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/luna-azul-blanco.jpg",
    description: "Crisp and clean with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Luna Azul",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Tequila Ocho Plata",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-plata.jpg",
    description: "Crisp and fresh with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium tequila with a clean and refined profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Avión Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/avion-silver.jpg",
    description: "Smooth and crisp with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.7,
    reviews: "A well-balanced tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Gran Centenario Plata Tequila",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-plata.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "1800 Silver Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/1800-silver.jpg",
    description: "Smooth and sweet with notes of agave and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.6,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Cabo Wabo Blanco Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cabo-wabo-blanco.jpg",
    description: "Smooth and crisp with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.6,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Corazón Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/corazon-blanco.jpg",
    description: "Smooth and fresh with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Corazón",
    rating: 4.5,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "El Tesoro Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/el-tesoro-blanco.jpg",
    description: "Crisp and clean with hints of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Fortaleza Blanco Tequila",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fortaleza-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A high-quality tequila perfect for sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Siete Leguas Blanco Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/siete-leguas-blanco.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Casa Noble Crystal Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/casa-noble-crystal.jpg",
    description: "Smooth and fresh with notes of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casa Noble",
    rating: 4.8,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Tres Generaciones Plata Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tres-generaciones-plata.jpg",
    description: "Smooth and sweet with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Generaciones",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Don Julio 70 Añejo Claro Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/don-julio-70.jpg",
    description: "Smooth and crisp with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.9,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Tapatio Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tapatio-blanco.jpg",
    description: "Crisp and fresh with notes of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tapatio",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Cimarron Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cimarron-blanco.jpg",
    description: "Smooth and sweet with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cimarron",
    rating: 4.6,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Arette Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/arette-blanco.jpg",
    description: "Smooth and fresh with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Arette",
    rating: 4.5,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Maestro Dobel Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/maestro-dobel-silver.jpg",
    description: "Smooth and crisp with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Maestro Dobel",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Pasote Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/pasote-blanco.jpg",
    description: "Smooth and fresh with notes of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Pasote",
    rating: 4.6,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Gran Dovejo Blanco Tequila",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gran-dovejo-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Dovejo",
    rating: 4.8,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "El Velo Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/el-velo-blanco.jpg",
    description: "Smooth and sweet with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Velo",
    rating: 4.5,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Lunazul Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/lunazul-blanco.jpg",
    description: "Smooth and crisp with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Lunazul",
    rating: 4.6,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Espolòn Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-blanco.jpg",
    description: "Crisp and clear with notes of tropical fruit and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Avión Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/avion-silver.jpg",
    description: "Smooth and crisp with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.7,
    reviews: "A well-balanced tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Olmeca Altos Plata Tequila",
    price: 27.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/olmeca-altos-plata.jpg",
    description: "Smooth and sweet with a herbal finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A high-quality tequila with a fresh agave flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Don Julio Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-blanco.jpg",
    description: "Crisp agave flavor with hints of citrus and a clean finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium tequila with a smooth and clean profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Siete Leguas Blanco Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/siete-leguas-blanco.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Cazadores Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/cazadores-blanco.jpg",
    description: "Fresh and herbaceous with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A well-rounded tequila great for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Milagro Silver Tequila",
    price: 32.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/milagro-silver.jpg",
    description: "Smooth and fresh with hints of citrus and herbs.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Patrón Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/patron-silver.jpg",
    description: "Smooth and sweet with a light pepper finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Clase Azul Plata Tequila",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clase-azul-plata.jpg",
    description: "Smooth and sweet with hints of vanilla and fruit.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Herradura Silver Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/herradura-silver.jpg",
    description: "Smooth with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.8,
    reviews: "A well-balanced tequila with a crisp finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Cabo Wabo Blanco Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cabo-wabo-blanco.jpg",
    description: "Smooth and crisp with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.6,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Tequila Ocho Plata",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-plata.jpg",
    description: "Crisp and fresh with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium tequila with a clean and refined profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Casa Noble Crystal Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/casa-noble-crystal.jpg",
    description: "Smooth and fresh with notes of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casa Noble",
    rating: 4.8,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Tres Generaciones Plata Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tres-generaciones-plata.jpg",
    description: "Smooth and sweet with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Generaciones",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "El Tesoro Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/el-tesoro-blanco.jpg",
    description: "Crisp and clean with hints of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Gran Centenario Plata Tequila",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-plata.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Teremana Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/teremana-blanco.jpg",
    description: "Smooth and sweet with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Teremana",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Don Julio 70 Añejo Claro Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/don-julio-70.jpg",
    description: "Smooth and crisp with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.9,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Fortaleza Blanco Tequila",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fortaleza-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A high-quality tequila perfect for sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Luna Azul Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/luna-azul-blanco.jpg",
    description: "Crisp and clean with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Luna Azul",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Olmeca Altos Plata Tequila",
    price: 27.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/olmeca-altos-plata.jpg",
    description: "Smooth and sweet with a herbal finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A high-quality tequila with a fresh agave flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "El Jimador Blanco Tequila",
    price: 22.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/el-jimador-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Jimador",
    rating: 4.5,
    reviews: "A popular tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Pasote Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/pasote-blanco.jpg",
    description: "Smooth and fresh with notes of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Pasote",
    rating: 4.6,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Cimarron Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cimarron-blanco.jpg",
    description: "Smooth and sweet with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cimarron",
    rating: 4.6,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Don Julio Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-blanco.jpg",
    description: "Crisp agave flavor with hints of citrus and a clean finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium tequila with a smooth and clean profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Tequila Ocho Plata",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-plata.jpg",
    description: "Crisp and fresh with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium tequila with a clean and refined profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Gran Dovejo Blanco Tequila",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gran-dovejo-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Dovejo",
    rating: 4.8,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Clase Azul Plata Tequila",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clase-azul-plata.jpg",
    description: "Smooth and sweet with hints of vanilla and fruit.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Herradura Silver Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/herradura-silver.jpg",
    description: "Smooth with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.8,
    reviews: "A well-balanced tequila with a crisp finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "El Tesoro Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/el-tesoro-blanco.jpg",
    description: "Crisp and clean with hints of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Gran Centenario Plata Tequila",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-plata.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Milagro Silver Tequila",
    price: 32.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/milagro-silver.jpg",
    description: "Smooth and fresh with hints of citrus and herbs.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Fortaleza Blanco Tequila",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fortaleza-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A high-quality tequila perfect for sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Cimarron Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cimarron-blanco.jpg",
    description: "Smooth and sweet with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cimarron",
    rating: 4.6,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Siete Leguas Blanco Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/siete-leguas-blanco.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Clase Azul Plata Tequila",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clase-azul-plata.jpg",
    description: "Smooth and sweet with hints of vanilla and fruit.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Olmeca Altos Plata Tequila",
    price: 27.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/olmeca-altos-plata.jpg",
    description: "Smooth and sweet with a herbal finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A high-quality tequila with a fresh agave flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Pasote Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/pasote-blanco.jpg",
    description: "Smooth and fresh with notes of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Pasote",
    rating: 4.6,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Gran Dovejo Blanco Tequila",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gran-dovejo-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Dovejo",
    rating: 4.8,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Don Julio Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-blanco.jpg",
    description: "Crisp agave flavor with hints of citrus and a clean finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium tequila with a smooth and clean profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Patrón Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/patron-silver.jpg",
    description: "Smooth and sweet with a light pepper finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Avión Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/avion-silver.jpg",
    description: "Smooth and crisp with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.7,
    reviews: "A well-balanced tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "El Jimador Blanco Tequila",
    price: 22.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/el-jimador-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Jimador",
    rating: 4.5,
    reviews: "A popular tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Cabo Wabo Blanco Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cabo-wabo-blanco.jpg",
    description: "Smooth and crisp with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.6,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Milagro Silver Tequila",
    price: 32.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/milagro-silver.jpg",
    description: "Smooth and fresh with hints of citrus and herbs.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Espolòn Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-blanco.jpg",
    description: "Crisp and clear with notes of tropical fruit and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Teremana Blanco Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/teremana-blanco.jpg",
    description: "Smooth and sweet with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Teremana",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "El Velo Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/el-velo-blanco.jpg",
    description: "Smooth and sweet with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Velo",
    rating: 4.5,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Don Julio Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-blanco.jpg",
    description: "Crisp agave flavor with hints of citrus and a clean finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium tequila with a smooth and clean profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Clase Azul Plata Tequila",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clase-azul-plata.jpg",
    description: "Smooth and sweet with hints of vanilla and fruit.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Tequila Ocho Plata",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-plata.jpg",
    description: "Crisp and fresh with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium tequila with a clean and refined profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Luna Azul Blanco Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/luna-azul-blanco.jpg",
    description: "Crisp and clean with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Luna Azul",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Gran Centenario Plata Tequila",
    price: 34.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-plata.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Siete Leguas Blanco Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/siete-leguas-blanco.jpg",
    description: "Crisp and clean with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.7,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Tres Generaciones Plata Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tres-generaciones-plata.jpg",
    description: "Smooth and sweet with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Generaciones",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Don Julio 70 Añejo Claro Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/don-julio-70.jpg",
    description: "Smooth and crisp with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.9,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Olmeca Altos Plata Tequila",
    price: 27.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/olmeca-altos-plata.jpg",
    description: "Smooth and sweet with a herbal finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A high-quality tequila with a fresh agave flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Cimarron Blanco Tequila",
    price: 24.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cimarron-blanco.jpg",
    description: "Smooth and sweet with notes of agave and citrus.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cimarron",
    rating: 4.6,
    reviews: "A versatile tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Cabo Wabo Blanco Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/cabo-wabo-blanco.jpg",
    description: "Smooth and crisp with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.6,
    reviews: "A high-quality tequila with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Don Julio Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/don-julio-blanco.jpg",
    description: "Crisp agave flavor with hints of citrus and a clean finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium tequila with a smooth and clean profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Herradura Silver Tequila",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/herradura-silver.jpg",
    description: "Smooth with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.8,
    reviews: "A well-balanced tequila with a crisp finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Tequila Ocho Plata",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-plata.jpg",
    description: "Crisp and fresh with hints of citrus and sweet agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium tequila with a clean and refined profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Patrón Silver Tequila",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/patron-silver.jpg",
    description: "Smooth and sweet with a light pepper finish.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.7,
    reviews: "A high-quality tequila perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Clase Azul Plata Tequila",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/clase-azul-plata.jpg",
    description: "Smooth and sweet with hints of vanilla and fruit.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 5.0,
    reviews: "A premium tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "El Tesoro Blanco Tequila",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/el-tesoro-blanco.jpg",
    description: "Crisp and clean with hints of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Milagro Silver Tequila",
    price: 32.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/milagro-silver.jpg",
    description: "Smooth and fresh with hints of citrus and herbs.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A versatile tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Don Julio 70 Añejo Claro Tequila",
    price: 69.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/don-julio-70.jpg",
    description: "Smooth and crisp with notes of citrus and vanilla.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.9,
    reviews: "A premium tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Fortaleza Blanco Tequila",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fortaleza-blanco.jpg",
    description: "Smooth and crisp with notes of citrus and agave.",
    category: "Blanco Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A high-quality tequila perfect for sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
];

module.exports = blancos;
