const mezcal = [
  {
    id: 1,
    name: "Del Maguey Vida Mezcal",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/del-maguey-vida.jpg",
    description: "Fruity, smoky, and rich with a long finish.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Mezcal Amaras Espadin",
    price: 45.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/amaras-espadin.jpg",
    description: "Fresh and smooth with hints of fruit and smoke.",
    category: "Mezcal",
    abv: 41,
    size: "750ml",
    brand: "Amaras",
    rating: 4.7,
    reviews: "A well-balanced mezcal with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Mezcal Vago Elote",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vago-elote.jpg",
    description: "Unique and smoky with notes of roasted corn.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.8,
    reviews: "A premium mezcal with a distinctive flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Del Maguey Chichicapa Mezcal",
    price: 74.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/chichicapa.jpg",
    description: "Rich and smoky with hints of fruit and spice.",
    category: "Mezcal",
    abv: 46,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.9,
    reviews: "A high-quality mezcal with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Fidencio Clásico Mezcal",
    price: 36.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fidencio-clasico.jpg",
    description: "Fresh and herbaceous with notes of smoke and fruit.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Fidencio",
    rating: 4.6,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Bozal Ensamble Mezcal",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/bozal-ensamble.jpg",
    description: "Complex and smoky with hints of fruit and spice.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Bozal",
    rating: 4.7,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Wahaka Espadín Mezcal",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/wahaka-espadin.jpg",
    description: "Smooth and fresh with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Wahaka",
    rating: 4.5,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Real Minero Espadín Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/real-minero-espadin.jpg",
    description: "Rich and smoky with complex notes of fruit and herbs.",
    category: "Mezcal",
    abv: 49,
    size: "750ml",
    brand: "Real Minero",
    rating: 4.9,
    reviews: "A premium mezcal with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Lalocura Tobasiche Mezcal",
    price: 109.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/lalocura-tobasiche.jpg",
    description: "Unique and smoky with notes of herbs and earth.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Lalocura",
    rating: 4.8,
    reviews: "A distinctive mezcal with a bold flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Rey Campero Tepextate Mezcal",
    price: 89.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/rey-campero-tepextate.jpg",
    description: "Complex and earthy with notes of smoke and fruit.",
    category: "Mezcal",
    abv: 48,
    size: "750ml",
    brand: "Rey Campero",
    rating: 4.7,
    reviews: "A high-quality mezcal with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Pierde Almas Espadín Mezcal",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/pierde-almas-espadin.jpg",
    description: "Smooth and smoky with hints of citrus and herbs.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Pierde Almas",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Agave de Cortés Joven Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/agave-de-cortes.jpg",
    description: "Smooth and fresh with notes of smoke and citrus.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Agave de Cortés",
    rating: 4.6,
    reviews: "A well-balanced mezcal with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Nuestra Soledad San Luis del Rio Mezcal",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nuestra-soledad-san-luis.jpg",
    description: "Complex and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Nuestra Soledad",
    rating: 4.8,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Sacrificio Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sacrificio-joven.jpg",
    description: "Smooth and fresh with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Sacrificio",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Vago Ensamble en Barro Mezcal",
    price: 89.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/vago-ensamble-en-barro.jpg",
    description: "Rich and smoky with complex notes of fruit and spice.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.8,
    reviews: "A premium mezcal with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Del Maguey Santo Domingo Albarradas Mezcal",
    price: 74.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/santo-domingo-albarradas.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 48,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.8,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Ilegal Reposado Mezcal",
    price: 54.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-reposado.jpg",
    description: "Smooth and smoky with notes of vanilla and caramel.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Bozal Tobasiche Mezcal",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/bozal-tobasiche.jpg",
    description: "Unique and smoky with notes of herbs and earth.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Bozal",
    rating: 4.8,
    reviews: "A distinctive mezcal with a bold flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Mezcal Vago Elote",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vago-elote.jpg",
    description: "Unique and smoky with notes of roasted corn.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.8,
    reviews: "A premium mezcal with a distinctive flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Los Vecinos del Campo Espadin Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/los-vecinos-espadin.jpg",
    description: "Smooth and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Los Vecinos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "El Jolgorio Madrecuixe Mezcal",
    price: 149.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/el-jolgorio-madrecuixe.jpg",
    description: "Complex and rich with notes of smoke and earth.",
    category: "Mezcal",
    abv: 48,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Fidencio Pechuga Mezcal",
    price: 119.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/fidencio-pechuga.jpg",
    description: "Rich and smoky with hints of fruit and spice.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Fidencio",
    rating: 4.9,
    reviews: "A high-quality mezcal with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Nuestra Soledad San Luis del Rio Mezcal",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nuestra-soledad-san-luis.jpg",
    description: "Complex and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Nuestra Soledad",
    rating: 4.8,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Real Minero Largo Mezcal",
    price: 119.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/real-minero-largo.jpg",
    description: "Unique and complex with notes of herbs and smoke.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Real Minero",
    rating: 4.9,
    reviews: "A distinctive mezcal with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Sacrificio Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sacrificio-joven.jpg",
    description: "Smooth and fresh with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Sacrificio",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Mezcal Vago Tobala",
    price: 149.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/vago-tobala.jpg",
    description: "Rich and smoky with complex notes of fruit and herbs.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.9,
    reviews: "A premium mezcal with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Lalocura Espadín Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/lalocura-espadin.jpg",
    description: "Complex and rich with notes of smoke and fruit.",
    category: "Mezcal",
    abv: 48,
    size: "750ml",
    brand: "Lalocura",
    rating: 4.9,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Bozal Cuishe Mezcal",
    price: 79.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/bozal-cuishe.jpg",
    description: "Unique and smoky with notes of herbs and earth.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Bozal",
    rating: 4.8,
    reviews: "A distinctive mezcal with a bold flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Del Maguey Tobala Mezcal",
    price: 119.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/del-maguey-tobala.jpg",
    description: "Rich and complex with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.9,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Montelobos Ensamble Mezcal",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/montelobos-ensamble.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Mezcal Vago Elote",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vago-elote.jpg",
    description: "Unique and smoky with notes of roasted corn.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.8,
    reviews: "A premium mezcal with a distinctive flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Mezcal Amaras Espadin",
    price: 45.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/amaras-espadin.jpg",
    description: "Fresh and smooth with hints of fruit and smoke.",
    category: "Mezcal",
    abv: 41,
    size: "750ml",
    brand: "Amaras",
    rating: 4.7,
    reviews: "A well-balanced mezcal with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Fidencio Clásico Mezcal",
    price: 36.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fidencio-clasico.jpg",
    description: "Fresh and herbaceous with notes of smoke and fruit.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Fidencio",
    rating: 4.6,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Mezcal Vago Elote",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vago-elote.jpg",
    description: "Unique and smoky with notes of roasted corn.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.8,
    reviews: "A premium mezcal with a distinctive flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Bozal Ensamble Mezcal",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/bozal-ensamble.jpg",
    description: "Complex and smoky with hints of fruit and spice.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Bozal",
    rating: 4.7,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Mezcal Amaras Espadin",
    price: 45.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/amaras-espadin.jpg",
    description: "Fresh and smooth with hints of fruit and smoke.",
    category: "Mezcal",
    abv: 41,
    size: "750ml",
    brand: "Amaras",
    rating: 4.7,
    reviews: "A well-balanced mezcal with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Nuestra Soledad San Luis del Rio Mezcal",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nuestra-soledad-san-luis.jpg",
    description: "Complex and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Nuestra Soledad",
    rating: 4.8,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Sacrificio Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sacrificio-joven.jpg",
    description: "Smooth and fresh with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Sacrificio",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Montelobos Ensamble Mezcal",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/montelobos-ensamble.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Bozal Tobasiche Mezcal",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/bozal-tobasiche.jpg",
    description: "Unique and smoky with notes of herbs and earth.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Bozal",
    rating: 4.8,
    reviews: "A distinctive mezcal with a bold flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Del Maguey Vida Mezcal",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/del-maguey-vida.jpg",
    description: "Fruity, smoky, and rich with a long finish.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Mezcal Amaras Espadin",
    price: 45.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/amaras-espadin.jpg",
    description: "Fresh and smooth with hints of fruit and smoke.",
    category: "Mezcal",
    abv: 41,
    size: "750ml",
    brand: "Amaras",
    rating: 4.7,
    reviews: "A well-balanced mezcal with a clean finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Real Minero Espadín Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/real-minero-espadin.jpg",
    description: "Rich and smoky with complex notes of fruit and herbs.",
    category: "Mezcal",
    abv: 49,
    size: "750ml",
    brand: "Real Minero",
    rating: 4.9,
    reviews: "A premium mezcal with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Nuestra Soledad San Luis del Rio Mezcal",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nuestra-soledad-san-luis.jpg",
    description: "Complex and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Nuestra Soledad",
    rating: 4.8,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Del Maguey Vida Mezcal",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/del-maguey-vida.jpg",
    description: "Fruity, smoky, and rich with a long finish.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Del Maguey Vida Mezcal",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/del-maguey-vida.jpg",
    description: "Fruity, smoky, and rich with a long finish.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Fidencio Clásico Mezcal",
    price: 36.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fidencio-clasico.jpg",
    description: "Fresh and herbaceous with notes of smoke and fruit.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Fidencio",
    rating: 4.6,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Los Vecinos del Campo Espadin Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/los-vecinos-espadin.jpg",
    description: "Smooth and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Los Vecinos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Real Minero Espadín Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/real-minero-espadin.jpg",
    description: "Rich and smoky with complex notes of fruit and herbs.",
    category: "Mezcal",
    abv: 49,
    size: "750ml",
    brand: "Real Minero",
    rating: 4.9,
    reviews: "A premium mezcal with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Nuestra Soledad San Luis del Rio Mezcal",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nuestra-soledad-san-luis.jpg",
    description: "Complex and smoky with notes of fruit and herbs.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Nuestra Soledad",
    rating: 4.8,
    reviews: "A high-quality mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Fidencio Clásico Mezcal",
    price: 36.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fidencio-clasico.jpg",
    description: "Fresh and herbaceous with notes of smoke and fruit.",
    category: "Mezcal",
    abv: 45,
    size: "750ml",
    brand: "Fidencio",
    rating: 4.6,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Montelobos Ensamble Mezcal",
    price: 59.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/montelobos-ensamble.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Mezcal Vago Elote",
    price: 74.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/vago-elote.jpg",
    description: "Unique and smoky with notes of roasted corn.",
    category: "Mezcal",
    abv: 50,
    size: "750ml",
    brand: "Vago",
    rating: 4.8,
    reviews: "A premium mezcal with a distinctive flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Del Maguey Vida Mezcal",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/del-maguey-vida.jpg",
    description: "Fruity, smoky, and rich with a long finish.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Del Maguey",
    rating: 4.8,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Los Amantes Joven Mezcal",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/los-amantes-joven.jpg",
    description: "Fresh and smoky with hints of citrus and spice.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Los Amantes",
    rating: 4.7,
    reviews: "A smooth mezcal perfect for sipping or cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Ilegal Joven Mezcal",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ilegal-joven.jpg",
    description: "Herbaceous and smoky with a smooth finish.",
    category: "Mezcal",
    abv: 40,
    size: "750ml",
    brand: "Ilegal",
    rating: 4.8,
    reviews: "A high-quality mezcal with a unique flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Banhez Ensemble Mezcal",
    price: 39.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banhez-ensemble.jpg",
    description: "Smooth and smoky with hints of fruit and herbs.",
    category: "Mezcal",
    abv: 42,
    size: "750ml",
    brand: "Banhez",
    rating: 4.6,
    reviews: "A versatile mezcal perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "El Jolgorio Espadin Mezcal",
    price: 99.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/el-jolgorio-espadin.jpg",
    description: "Complex and balanced with notes of fruit and smoke.",
    category: "Mezcal",
    abv: 47,
    size: "750ml",
    brand: "El Jolgorio",
    rating: 4.9,
    reviews: "A premium mezcal with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Montelobos Espadin Mezcal",
    price: 37.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/montelobos-espadin.jpg",
    description: "Smooth and balanced with notes of citrus and smoke.",
    category: "Mezcal",
    abv: 43,
    size: "750ml",
    brand: "Montelobos",
    rating: 4.7,
    reviews: "A versatile mezcal perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
];

module.exports = mezcal;
