const reposadoTequila = [
  {
    id: 1,
    name: "Patrón Reposado Tequila",
    price: 49.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/patron-reposado.jpg",
    description: "Smooth and rich with notes of oak, vanilla, and honey.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.8,
    reviews: "A premium reposado tequila perfect for sipping or mixing.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Casamigos Reposado Tequila",
    price: 54.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/casamigos-reposado.jpg",
    description: "Smooth and slightly smoky with hints of caramel and cocoa.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casamigos",
    rating: 4.9,
    reviews: "A well-balanced reposado with a rich, smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Don Julio Reposado Tequila",
    price: 56.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/don-julio-reposado.jpg",
    description: "Rich and smooth with notes of caramel, spice, and chocolate.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium reposado tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Herradura Reposado Tequila",
    price: 44.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/herradura-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, oak, and cinnamon.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Espolòn Reposado Tequila",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-reposado.jpg",
    description:
      "Smooth and balanced with notes of caramel, vanilla, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Milagro Reposado Tequila",
    price: 38.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/milagro-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Avión Reposado Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/avion-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Olmeca Altos Reposado Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/olmeca-altos-reposado.jpg",
    description:
      "Smooth and balanced with notes of agave, citrus, and vanilla.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "1800 Reposado Tequila",
    price: 34.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/1800-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, spice, and caramel.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Cazadores Reposado Tequila",
    price: 29.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cazadores-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Sauza Hornitos Reposado Tequila",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/sauza-hornitos-reposado.jpg",
    description: "Smooth and rich with notes of oak, vanilla, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Sauza Hornitos",
    rating: 4.6,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Tres Agaves Reposado Tequila",
    price: 36.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/tres-agaves-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Agaves",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Fortaleza Reposado Tequila",
    price: 59.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/fortaleza-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Roca Patrón Reposado Tequila",
    price: 69.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/roca-patron-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Roca Patrón",
    rating: 4.9,
    reviews: "A premium reposado tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Corralejo Reposado Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/corralejo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Corralejo",
    rating: 4.7,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Mi Campo Reposado Tequila",
    price: 32.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/mi-campo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Mi Campo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Cabo Wabo Reposado Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/cabo-wabo-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Tequila Ocho Reposado",
    price: 54.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Siete Leguas Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/siete-leguas-reposado.jpg",
    description: "Smooth and balanced with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Azul Reposado Tequila",
    price: 39.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/azul-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Azul",
    rating: 4.7,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Tequila Casa Noble Reposado",
    price: 59.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/casa-noble-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casa Noble",
    rating: 4.9,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Jose Cuervo Tradicional Reposado",
    price: 29.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/jose-cuervo-tradicional-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Codigo 1530 Reposado Tequila",
    price: 79.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/codigo-1530-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Codigo 1530",
    rating: 4.9,
    reviews: "A premium reposado tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Pasote Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/pasote-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Pasote",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Mi Campo Reposado Tequila",
    price: 32.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/mi-campo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Mi Campo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Cabo Wabo Reposado Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/cabo-wabo-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Tequila Ocho Reposado",
    price: 54.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Patrón Reposado Tequila",
    price: 49.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/patron-reposado.jpg",
    description: "Smooth and rich with notes of oak, vanilla, and honey.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Patrón",
    rating: 4.8,
    reviews: "A premium reposado tequila perfect for sipping or mixing.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Milagro Reposado Tequila",
    price: 38.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/milagro-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Espolòn Reposado Tequila",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-reposado.jpg",
    description:
      "Smooth and balanced with notes of caramel, vanilla, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Herradura Reposado Tequila",
    price: 44.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/herradura-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, oak, and cinnamon.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Avión Reposado Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/avion-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Olmeca Altos Reposado Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/olmeca-altos-reposado.jpg",
    description:
      "Smooth and balanced with notes of agave, citrus, and vanilla.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "1800 Reposado Tequila",
    price: 34.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/1800-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, spice, and caramel.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Cazadores Reposado Tequila",
    price: 29.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cazadores-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Jose Cuervo Tradicional Reposado",
    price: 29.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/jose-cuervo-tradicional-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Siete Leguas Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/siete-leguas-reposado.jpg",
    description: "Smooth and balanced with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Tres Agaves Reposado Tequila",
    price: 36.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/tres-agaves-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Agaves",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Fortaleza Reposado Tequila",
    price: 59.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/fortaleza-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Fortaleza",
    rating: 4.9,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Roca Patrón Reposado Tequila",
    price: 69.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/roca-patron-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Roca Patrón",
    rating: 4.9,
    reviews: "A premium reposado tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Corralejo Reposado Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/corralejo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Corralejo",
    rating: 4.7,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Siete Leguas Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/siete-leguas-reposado.jpg",
    description: "Smooth and balanced with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Mi Campo Reposado Tequila",
    price: 32.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/mi-campo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Mi Campo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Don Julio Reposado Tequila",
    price: 56.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/don-julio-reposado.jpg",
    description: "Rich and smooth with notes of caramel, spice, and chocolate.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium reposado tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Roca Patrón Reposado Tequila",
    price: 69.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/roca-patron-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Roca Patrón",
    rating: 4.9,
    reviews: "A premium reposado tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Tres Agaves Reposado Tequila",
    price: 36.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/tres-agaves-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tres Agaves",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Tequila Ocho Reposado",
    price: 54.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/tequila-ocho-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Tequila Ocho",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Cabo Wabo Reposado Tequila",
    price: 44.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/cabo-wabo-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cabo Wabo",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Corralejo Reposado Tequila",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/corralejo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Corralejo",
    rating: 4.7,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Milagro Reposado Tequila",
    price: 38.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/milagro-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Espolòn Reposado Tequila",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-reposado.jpg",
    description:
      "Smooth and balanced with notes of caramel, vanilla, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Herradura Reposado Tequila",
    price: 44.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/herradura-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, oak, and cinnamon.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Herradura",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Avión Reposado Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/avion-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Olmeca Altos Reposado Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/olmeca-altos-reposado.jpg",
    description:
      "Smooth and balanced with notes of agave, citrus, and vanilla.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "1800 Reposado Tequila",
    price: 34.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/1800-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, spice, and caramel.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Cazadores Reposado Tequila",
    price: 29.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cazadores-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Tequila Casa Noble Reposado",
    price: 59.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/casa-noble-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Casa Noble",
    rating: 4.9,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Jose Cuervo Tradicional Reposado",
    price: 29.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/jose-cuervo-tradicional-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Milagro Reposado Tequila",
    price: 38.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/milagro-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Roca Patrón Reposado Tequila",
    price: 69.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/roca-patron-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Roca Patrón",
    rating: 4.9,
    reviews: "A premium reposado tequila with a complex flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Don Julio Reposado Tequila",
    price: 56.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/don-julio-reposado.jpg",
    description: "Rich and smooth with notes of caramel, spice, and chocolate.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Don Julio",
    rating: 4.8,
    reviews: "A premium reposado tequila with a refined flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Siete Leguas Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/siete-leguas-reposado.jpg",
    description: "Smooth and balanced with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Avión Reposado Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/avion-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Olmeca Altos Reposado Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/olmeca-altos-reposado.jpg",
    description:
      "Smooth and balanced with notes of agave, citrus, and vanilla.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "1800 Reposado Tequila",
    price: 34.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/1800-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, spice, and caramel.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Cazadores Reposado Tequila",
    price: 29.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cazadores-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Jose Cuervo Tradicional Reposado",
    price: 29.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/jose-cuervo-tradicional-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Mi Campo Reposado Tequila",
    price: 32.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/mi-campo-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Mi Campo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Siete Leguas Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/siete-leguas-reposado.jpg",
    description: "Smooth and balanced with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Siete Leguas",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Avión Reposado Tequila",
    price: 44.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/avion-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Avión",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Olmeca Altos Reposado Tequila",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/olmeca-altos-reposado.jpg",
    description:
      "Smooth and balanced with notes of agave, citrus, and vanilla.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Olmeca Altos",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "1800 Reposado Tequila",
    price: 34.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/1800-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, spice, and caramel.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "1800",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a balanced flavor.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Cazadores Reposado Tequila",
    price: 29.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/cazadores-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Cazadores",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Jose Cuervo Tradicional Reposado",
    price: 29.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/jose-cuervo-tradicional-reposado.jpg",
    description:
      "Smooth and balanced with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Jose Cuervo",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "El Tesoro Reposado Tequila",
    price: 49.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/el-tesoro-reposado.jpg",
    description: "Smooth and complex with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "El Tesoro",
    rating: 4.8,
    reviews: "A premium reposado tequila with a rich flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Gran Centenario Reposado Tequila",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gran-centenario-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and oak.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Gran Centenario",
    rating: 4.8,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Milagro Reposado Tequila",
    price: 38.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/milagro-reposado.jpg",
    description: "Smooth and rich with notes of vanilla, caramel, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Milagro",
    rating: 4.7,
    reviews: "A high-quality reposado tequila with a smooth finish.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Espolòn Reposado Tequila",
    price: 34.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/espolon-reposado.jpg",
    description:
      "Smooth and balanced with notes of caramel, vanilla, and spice.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Espolòn",
    rating: 4.6,
    reviews: "A versatile reposado tequila perfect for cocktails or sipping.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Clase Azul Reposado Tequila",
    price: 99.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/clase-azul-reposado.jpg",
    description:
      "Smooth and complex with notes of vanilla, caramel, and agave.",
    category: "Reposado Tequila",
    abv: 40,
    size: "750ml",
    brand: "Clase Azul",
    rating: 4.9,
    reviews: "A premium reposado tequila with an elegant flavor profile.",
    origin: "Mexico",
    availability: "In Stock",
  },
];

module.exports = reposadoTequila;
