const whiteWines = [
  {
    id: 1,
    name: "Chardonnay",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/chardonnay.jpg",
    description: "Rich and full-bodied with notes of apple, pear, and vanilla.",
    category: "White Wine",
    brand: "Napa Valley Vineyards",
    rating: 4.8,
    reviews: "A classic white wine, perfect for pairing with seafood.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Sauvignon Blanc",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/sauvignon-blanc.jpg",
    description: "Crisp and refreshing with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Marlborough Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with salads and light dishes.",
    origin: "New Zealand",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Pinot Grigio",
    price: 22.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pinot-grigio.jpg",
    description: "Light and crisp with notes of lemon and green apple.",
    category: "White Wine",
    brand: "Veneto Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, perfect for pairing with light pasta dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Riesling",
    price: 21.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/riesling.jpg",
    description: "Sweet and aromatic with notes of peach and apricot.",
    category: "White Wine",
    brand: "Mosel Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, excellent with spicy dishes.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Moscato",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/moscato.jpg",
    description: "Sweet and fruity with notes of peach and orange blossom.",
    category: "White Wine",
    brand: "Piedmont Vineyards",
    rating: 4.7,
    reviews: "A vibrant wine, great with desserts and fruit.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Gewurztraminer",
    price: 23.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gewurztraminer.jpg",
    description: "Aromatic and spicy with notes of lychee and rose petal.",
    category: "White Wine",
    brand: "Alsace Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for Asian cuisine.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Viognier",
    price: 24.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/viognier.jpg",
    description: "Rich and aromatic with notes of peach and honeysuckle.",
    category: "White Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with poultry and creamy sauces.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Chenin Blanc",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/chenin-blanc.jpg",
    description: "Crisp and fresh with notes of green apple and honey.",
    category: "White Wine",
    brand: "Loire Valley Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Semillon",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/semillon.jpg",
    description: "Rich and full-bodied with notes of lemon and honey.",
    category: "White Wine",
    brand: "Hunter Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for poultry and seafood.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Albarino",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/albarino.jpg",
    description: "Crisp and refreshing with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rias Baixas Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Gruner Veltliner",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/gruner-veltliner.jpg",
    description: "Crisp and zesty with notes of green apple and white pepper.",
    category: "White Wine",
    brand: "Wachau Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "Austria",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Vermentino",
    price: 22.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/vermentino.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Sardinia Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and light dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Torrontes",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/torrontes.jpg",
    description: "Aromatic and floral with notes of rose and citrus.",
    category: "White Wine",
    brand: "Salta Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for Asian cuisine.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Cortese",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/cortese.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Piedmont Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Fiano",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fiano.jpg",
    description: "Rich and aromatic with notes of honey and tropical fruit.",
    category: "White Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for poultry and creamy sauces.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Assyrtiko",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/assyrtiko.jpg",
    description:
      "Crisp and mineral-driven with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Santorini Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, great with seafood and salads.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Picpoul",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/picpoul.jpg",
    description: "Crisp and zesty with notes of lemon and green apple.",
    category: "White Wine",
    brand: "Languedoc Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, perfect for seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Muscat",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/muscat.jpg",
    description: "Aromatic and sweet with notes of orange blossom and peach.",
    category: "White Wine",
    brand: "Alsace Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, great with desserts and fruit.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Trebbiano",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/trebbiano.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Abruzzo Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Colombard",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/colombard.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Gascony Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Aligote",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aligote.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Burgundy Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Grenache Blanc",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/grenache-blanc.jpg",
    description: "Rich and aromatic with notes of pear and citrus.",
    category: "White Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, great with poultry and creamy sauces.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Malvasia",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/malvasia.jpg",
    description: "Aromatic and sweet with notes of peach and apricot.",
    category: "White Wine",
    brand: "Sicily Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts and fruit.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Vernaccia",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/vernaccia.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Tuscany Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Pedro Ximenez",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pedro-ximenez.jpg",
    description: "Sweet and rich with notes of dried fruit and caramel.",
    category: "White Wine",
    brand: "Jerez Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for desserts and cheese.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Garganega",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/garganega.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Veneto Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Palomino",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/palomino.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Andalusia Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Treixadura",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/treixadura.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rias Baixas Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Falanghina",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/falanghina.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Airen",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/airen.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Castilla-La Mancha Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Godello",
    price: 23.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/godello.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Galicia Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Macabeo",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/macabeo.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Catalonia Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Rkatsiteli",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/rkatsiteli.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Kakheti Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Georgia",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Bacchus",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bacchus.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rheinhessen Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Savagnin",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/savagnin.jpg",
    description: "Rich and aromatic with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Jura Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and light dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Viura",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/viura.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Rioja Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Furmint",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/furmint.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Tokaj Vineyards",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "Hungary",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Carricante",
    price: 22.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/carricante.jpg",
    description:
      "Crisp and mineral-driven with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Sicily Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Arneis",
    price: 23.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/arneis.jpg",
    description: "Light and aromatic with notes of pear and citrus.",
    category: "White Wine",
    brand: "Piedmont Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, perfect for seafood and light dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Verdejo",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/verdejo.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rueda Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Torrontes",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/torrontes.jpg",
    description: "Aromatic and floral with notes of rose and citrus.",
    category: "White Wine",
    brand: "Salta Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for Asian cuisine.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Verdelho",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/verdelho.jpg",
    description: "Crisp and zesty with notes of lemon and green apple.",
    category: "White Wine",
    brand: "Madeira Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, perfect for seafood and salads.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Muller-Thurgau",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/muller-thurgau.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Chenin Blanc",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/chenin-blanc.jpg",
    description: "Crisp and fresh with notes of green apple and honey.",
    category: "White Wine",
    brand: "Loire Valley Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Semillon",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/semillon.jpg",
    description: "Rich and full-bodied with notes of lemon and honey.",
    category: "White Wine",
    brand: "Hunter Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for poultry and seafood.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Albarino",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/albarino.jpg",
    description: "Crisp and refreshing with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rias Baixas Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Gruner Veltliner",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/gruner-veltliner.jpg",
    description: "Crisp and zesty with notes of green apple and white pepper.",
    category: "White Wine",
    brand: "Wachau Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "Austria",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Vermentino",
    price: 22.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/vermentino.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Sardinia Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and light dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Torrontes",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/torrontes.jpg",
    description: "Aromatic and floral with notes of rose and citrus.",
    category: "White Wine",
    brand: "Salta Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for Asian cuisine.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Cortese",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/cortese.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Piedmont Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Fiano",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fiano.jpg",
    description: "Rich and aromatic with notes of honey and tropical fruit.",
    category: "White Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for poultry and creamy sauces.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Assyrtiko",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/assyrtiko.jpg",
    description:
      "Crisp and mineral-driven with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Santorini Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, great with seafood and salads.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Picpoul",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/picpoul.jpg",
    description: "Crisp and zesty with notes of lemon and green apple.",
    category: "White Wine",
    brand: "Languedoc Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, perfect for seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Muscat",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/muscat.jpg",
    description: "Aromatic and sweet with notes of orange blossom and peach.",
    category: "White Wine",
    brand: "Alsace Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, great with desserts and fruit.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Trebbiano",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/trebbiano.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Abruzzo Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Colombard",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/colombard.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Gascony Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Aligote",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aligote.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Burgundy Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Grenache Blanc",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/grenache-blanc.jpg",
    description: "Rich and aromatic with notes of pear and citrus.",
    category: "White Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, great with poultry and creamy sauces.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Malvasia",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/malvasia.jpg",
    description: "Aromatic and sweet with notes of peach and apricot.",
    category: "White Wine",
    brand: "Sicily Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts and fruit.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Vernaccia",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/vernaccia.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Tuscany Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Pedro Ximenez",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pedro-ximenez.jpg",
    description: "Sweet and rich with notes of dried fruit and caramel.",
    category: "White Wine",
    brand: "Jerez Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for desserts and cheese.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Garganega",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/garganega.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Veneto Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Palomino",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/palomino.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Andalusia Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Treixadura",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/treixadura.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rias Baixas Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Falanghina",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/falanghina.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Airen",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/airen.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Castilla-La Mancha Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Godello",
    price: 23.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/godello.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Galicia Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Macabeo",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/macabeo.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Catalonia Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Rkatsiteli",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/rkatsiteli.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Kakheti Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Georgia",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Bacchus",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bacchus.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rheinhessen Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Savagnin",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/savagnin.jpg",
    description: "Rich and aromatic with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Jura Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and light dishes.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Viura",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/viura.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Rioja Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Furmint",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/furmint.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Tokaj Vineyards",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "Hungary",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Carricante",
    price: 22.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/carricante.jpg",
    description:
      "Crisp and mineral-driven with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Sicily Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Arneis",
    price: 23.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/arneis.jpg",
    description: "Light and aromatic with notes of pear and citrus.",
    category: "White Wine",
    brand: "Piedmont Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, perfect for seafood and light dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Verdejo",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/verdejo.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rueda Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Torrontes",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/torrontes.jpg",
    description: "Aromatic and floral with notes of rose and citrus.",
    category: "White Wine",
    brand: "Salta Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for Asian cuisine.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Verdelho",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/verdelho.jpg",
    description: "Crisp and zesty with notes of lemon and green apple.",
    category: "White Wine",
    brand: "Madeira Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, perfect for seafood and salads.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Muller-Thurgau",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/muller-thurgau.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Trentino-Alto Adige Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Chenin Blanc",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/chenin-blanc.jpg",
    description: "Crisp and fresh with notes of green apple and honey.",
    category: "White Wine",
    brand: "Loire Valley Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Semillon",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/semillon.jpg",
    description: "Rich and full-bodied with notes of lemon and honey.",
    category: "White Wine",
    brand: "Hunter Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for poultry and seafood.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Albarino",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/albarino.jpg",
    description: "Crisp and refreshing with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rias Baixas Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Gruner Veltliner",
    price: 21.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/gruner-veltliner.jpg",
    description: "Crisp and zesty with notes of green apple and white pepper.",
    category: "White Wine",
    brand: "Wachau Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "Austria",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Vermentino",
    price: 22.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/vermentino.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Sardinia Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and light dishes.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Torrontes",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/torrontes.jpg",
    description: "Aromatic and floral with notes of rose and citrus.",
    category: "White Wine",
    brand: "Salta Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for Asian cuisine.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Cortese",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/cortese.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Piedmont Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Fiano",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fiano.jpg",
    description: "Rich and aromatic with notes of honey and tropical fruit.",
    category: "White Wine",
    brand: "Campania Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for poultry and creamy sauces.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Assyrtiko",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/assyrtiko.jpg",
    description:
      "Crisp and mineral-driven with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Santorini Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, great with seafood and salads.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Picpoul",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/picpoul.jpg",
    description: "Crisp and zesty with notes of lemon and green apple.",
    category: "White Wine",
    brand: "Languedoc Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, perfect for seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Muscat",
    price: 21.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/muscat.jpg",
    description: "Aromatic and sweet with notes of orange blossom and peach.",
    category: "White Wine",
    brand: "Alsace Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, great with desserts and fruit.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Trebbiano",
    price: 18.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/trebbiano.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Abruzzo Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Colombard",
    price: 20.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/colombard.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Gascony Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Aligote",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aligote.jpg",
    description: "Light and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Burgundy Vineyards",
    rating: 4.8,
    reviews: "A vibrant wine, perfect for seafood and salads.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Grenache Blanc",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/grenache-blanc.jpg",
    description: "Rich and aromatic with notes of pear and citrus.",
    category: "White Wine",
    brand: "Rhone Valley Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, great with poultry and creamy sauces.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Malvasia",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/malvasia.jpg",
    description: "Aromatic and sweet with notes of peach and apricot.",
    category: "White Wine",
    brand: "Sicily Vineyards",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts and fruit.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Vernaccia",
    price: 23.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/vernaccia.jpg",
    description: "Crisp and fresh with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Tuscany Vineyards",
    rating: 4.7,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Pedro Ximenez",
    price: 21.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/pedro-ximenez.jpg",
    description: "Sweet and rich with notes of dried fruit and caramel.",
    category: "White Wine",
    brand: "Jerez Vineyards",
    rating: 4.8,
    reviews: "A smooth wine, perfect for desserts and cheese.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Garganega",
    price: 19.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/garganega.jpg",
    description: "Light and crisp with notes of green apple and citrus.",
    category: "White Wine",
    brand: "Veneto Vineyards",
    rating: 4.7,
    reviews: "A delightful wine, great with seafood and salads.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Palomino",
    price: 22.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/palomino.jpg",
    description: "Crisp and fresh with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Andalusia Vineyards",
    rating: 4.8,
    reviews: "A versatile wine, great with seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Treixadura",
    price: 20.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/treixadura.jpg",
    description: "Crisp and aromatic with notes of citrus and green apple.",
    category: "White Wine",
    brand: "Rias Baixas Vineyards",
    rating: 4.7,
    reviews: "A smooth wine, perfect for seafood and salads.",
    origin: "Spain",
    availability: "In Stock",
  },
];

module.exports = whiteWines;
