const vodkas = [
  {
    id: 1,
    name: "Grey Goose Vodka",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose.jpg",
    description: "A premium vodka known for its smooth and pure taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and crisp finish.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Absolut Vodka",
    price: 19.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/absolut.jpg",
    description:
      "A popular vodka with a rich, full-bodied flavor and a smooth finish.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.7,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Smirnoff No. 21 Vodka",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/smirnoff.jpg",
    description: "A classic vodka with a smooth and clean taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A reliable vodka that is great for any occasion.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Belvedere Vodka",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere.jpg",
    description:
      "A luxury vodka made from Polish rye, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a creamy and rich mouthfeel.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Ketel One Vodka",
    price: 24.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/ketel-one.jpg",
    description: "A Dutch vodka known for its crisp and clean flavor.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka perfect for sipping or mixing.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Ciroc Vodka",
    price: 34.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/ciroc.jpg",
    description:
      "A premium vodka distilled from French grapes, offering a unique flavor.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Ciroc",
    rating: 4.7,
    reviews: "A smooth vodka with a slightly sweet taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Skyy Vodka",
    price: 18.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/skyy.jpg",
    description: "A vodka known for its smooth and clean taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Stolichnaya Vodka",
    price: 21.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/stolichnaya.jpg",
    description: "A Russian vodka with a smooth and rich flavor.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Stolichnaya",
    rating: 4.7,
    reviews: "A high-quality vodka perfect for sipping or mixing.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Chopin Potato Vodka",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/chopin.jpg",
    description:
      "A premium vodka made from potatoes, offering a creamy and smooth taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Chopin",
    rating: 4.8,
    reviews: "A luxurious vodka with a rich mouthfeel.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Beluga Noble Russian Vodka",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/beluga.jpg",
    description:
      "A high-end Russian vodka known for its smooth and refined taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Beluga",
    rating: 4.9,
    reviews: "A premium vodka with a delicate and pure flavor.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Reyka Vodka",
    price: 24.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/reyka.jpg",
    description:
      "An Icelandic vodka made with glacial water, known for its purity.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Reyka",
    rating: 4.7,
    reviews: "A clean and crisp vodka with a smooth finish.",
    origin: "Iceland",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Finlandia Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/finlandia.jpg",
    description: "A Finnish vodka with a clean and pure taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Finlandia",
    rating: 4.6,
    reviews: "A smooth vodka that is perfect for cocktails.",
    origin: "Finland",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Svedka Vodka",
    price: 16.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/svedka.jpg",
    description: "A Swedish vodka with a smooth and clean taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Svedka",
    rating: 4.5,
    reviews: "A versatile vodka that is perfect for mixing.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Russian Standard Vodka",
    price: 22.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/russian-standard.jpg",
    description: "A Russian vodka with a smooth and rich flavor.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Russian Standard",
    rating: 4.7,
    reviews: "A high-quality vodka perfect for sipping or mixing.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Three Olives Vodka",
    price: 19.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/three-olives.jpg",
    description: "A British vodka with a smooth and clean taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Sobieski Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/sobieski.jpg",
    description: "A Polish vodka with a smooth and clean taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Sobieski",
    rating: 4.6,
    reviews: "A reliable vodka that is great for any occasion.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Zubrowka Bison Grass Vodka",
    price: 25.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/zubrowka.jpg",
    description:
      "A unique Polish vodka flavored with bison grass, offering a distinctive taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Zubrowka",
    rating: 4.7,
    reviews: "A flavorful vodka with a unique twist.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Crystal Head Vodka",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/crystal-head.jpg",
    description:
      "A premium vodka known for its purity, bottled in a distinctive skull-shaped bottle.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Crystal Head",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and crisp finish.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "New Amsterdam Vodka",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/new-amsterdam.jpg",
    description: "A smooth vodka with a clean and crisp taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "New Amsterdam",
    rating: 4.5,
    reviews: "A versatile vodka that is perfect for mixing.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Platinum 7X Vodka",
    price: 13.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/platinum-7x.jpg",
    description: "A smooth and clean vodka distilled seven times for purity.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Platinum 7X",
    rating: 4.4,
    reviews: "A high-quality vodka at an affordable price.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Effen Vodka",
    price: 29.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/effen.jpg",
    description: "A premium vodka known for its smooth and clean taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Effen",
    rating: 4.7,
    reviews: "A high-quality vodka perfect for sipping or mixing.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Ciroc Pineapple Vodka",
    price: 34.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/ciroc-pineapple.jpg",
    description: "A premium vodka infused with natural pineapple flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Ciroc",
    rating: 4.7,
    reviews: "A smooth vodka with a sweet and tropical taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Absolut Citron Vodka",
    price: 21.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/absolut-citron.jpg",
    description: "A flavored vodka with a natural lemon taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Van Gogh Espresso Vodka",
    price: 27.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/van-gogh-espresso.jpg",
    description: "A premium vodka infused with the rich flavor of espresso.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Van Gogh",
    rating: 4.7,
    reviews: "A smooth vodka with a bold coffee taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Stolichnaya Vanilla Vodka",
    price: 22.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/stolichnaya-vanilla.jpg",
    description: "A Russian vodka infused with natural vanilla flavor.",
    category: "Flavored Vodka",
    abv: 37.5,
    size: "750ml",
    brand: "Stolichnaya",
    rating: 4.6,
    reviews: "A smooth vodka with a rich vanilla taste.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Belvedere Citrus Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-citrus.jpg",
    description: "A luxury vodka infused with natural citrus flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing citrus taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Grey Goose L'Orange Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-orange.jpg",
    description: "A premium vodka infused with natural orange flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing orange taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Skyy Infusions Raspberry Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-raspberry.jpg",
    description: "A vodka infused with natural raspberry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Ketel One Citroen Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-citroen.jpg",
    description: "A Dutch vodka infused with natural lemon and lime flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing citrus taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Smirnoff Raspberry Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-raspberry.jpg",
    description: "A vodka infused with natural raspberry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Absolut Mango Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-mango.jpg",
    description: "A flavored vodka with a natural mango taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing mango flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Three Olives Cherry Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-cherry.jpg",
    description: "A British vodka infused with natural cherry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a rich cherry taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Belvedere Ginger Zest Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-ginger.jpg",
    description:
      "A luxury vodka infused with natural ginger and citrus flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing and spicy taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Grey Goose La Poire Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-poire.jpg",
    description: "A premium vodka infused with natural pear flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing pear taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Skyy Infusions Blood Orange Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-blood-orange.jpg",
    description: "A vodka infused with natural blood orange flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Ketel One Oranje Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-oranje.jpg",
    description: "A Dutch vodka infused with natural orange flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing orange taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Smirnoff Green Apple Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-green-apple.jpg",
    description: "A vodka infused with natural green apple flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Absolut Lime Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-lime.jpg",
    description: "A flavored vodka with a natural lime taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing lime flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Three Olives Grape Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-grape.jpg",
    description: "A British vodka infused with natural grape flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a rich grape taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Belvedere Peach Nectar Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-peach.jpg",
    description:
      "A luxury vodka infused with natural peach and apricot flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing and fruity taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Grey Goose Le Citron Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-citron.jpg",
    description: "A premium vodka infused with natural lemon flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing lemon taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Skyy Infusions Cherry Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-cherry.jpg",
    description: "A vodka infused with natural cherry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Ketel One Grapefruit & Rose Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-grapefruit-rose.jpg",
    description:
      "A Dutch vodka infused with natural grapefruit and rose flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing and floral taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Smirnoff Vanilla Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-vanilla.jpg",
    description: "A vodka infused with natural vanilla flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Absolut Peach Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-peach.jpg",
    description: "A flavored vodka with a natural peach taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing peach flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Three Olives Rose Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-rose.jpg",
    description: "A British vodka infused with natural rose flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a delicate rose taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Belvedere Wild Berry Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-wild-berry.jpg",
    description: "A luxury vodka infused with natural wild berry flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing and fruity taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Grey Goose Watermelon & Basil Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-watermelon.jpg",
    description:
      "A premium vodka infused with natural watermelon and basil flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing and unique taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Skyy Infusions Pineapple Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-pineapple.jpg",
    description: "A vodka infused with natural pineapple flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Ketel One Cucumber & Mint Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-cucumber-mint.jpg",
    description:
      "A Dutch vodka infused with natural cucumber and mint flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing and herbal taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Smirnoff Red, White & Berry Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-red-white-berry.jpg",
    description:
      "A vodka infused with natural cherry, citrus, and blue raspberry flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for summer cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Absolut Raspberri Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-raspberri.jpg",
    description: "A flavored vodka with a natural raspberry taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing raspberry flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Three Olives Watermelon Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-watermelon.jpg",
    description: "A British vodka infused with natural watermelon flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing watermelon taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Belvedere Black Raspberry Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-black-raspberry.jpg",
    description: "A luxury vodka infused with natural black raspberry flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing and fruity taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Grey Goose Cherry Noir Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-cherry-noir.jpg",
    description: "A premium vodka infused with natural cherry flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a rich cherry taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Skyy Infusions Passion Fruit Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-passion-fruit.jpg",
    description: "A vodka infused with natural passion fruit flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Ketel One Botanical Peach & Orange Blossom Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-peach-orange.jpg",
    description:
      "A Dutch vodka infused with natural peach and orange blossom flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing and fruity taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Smirnoff Coconut Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-coconut.jpg",
    description: "A vodka infused with natural coconut flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for tropical cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Absolut Pears Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-pears.jpg",
    description: "A flavored vodka with a natural pear taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing pear flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Three Olives Berry Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-berry.jpg",
    description: "A British vodka infused with natural berry flavors.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a rich berry taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Belvedere Citrus Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-citrus.jpg",
    description: "A luxury vodka infused with natural citrus flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing citrus taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Grey Goose La Poire Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-poire.jpg",
    description: "A premium vodka infused with natural pear flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing pear taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Skyy Infusions Citrus Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-citrus.jpg",
    description: "A vodka infused with natural citrus flavors.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Ketel One Citroen Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-citroen.jpg",
    description: "A Dutch vodka infused with natural lemon and lime flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing citrus taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Smirnoff Strawberry Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-strawberry.jpg",
    description: "A vodka infused with natural strawberry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Absolut Kurant Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-kurant.jpg",
    description: "A flavored vodka with a natural black currant taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing black currant flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Three Olives Pomegranate Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-pomegranate.jpg",
    description: "A British vodka infused with natural pomegranate flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a rich pomegranate taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Belvedere Orange Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-orange.jpg",
    description: "A luxury vodka infused with natural orange flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing orange taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Grey Goose Watermelon & Basil Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-watermelon.jpg",
    description:
      "A premium vodka infused with natural watermelon and basil flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing and unique taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Skyy Infusions Georgia Peach Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-georgia-peach.jpg",
    description: "A vodka infused with natural Georgia peach flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Ketel One Cucumber & Mint Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-cucumber-mint.jpg",
    description:
      "A Dutch vodka infused with natural cucumber and mint flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing and herbal taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Smirnoff Orange Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-orange.jpg",
    description: "A vodka infused with natural orange flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Absolut Mandrin Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-mandrin.jpg",
    description: "A flavored vodka with a natural mandarin orange taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a refreshing mandarin flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Three Olives Vanilla Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-vanilla.jpg",
    description: "A British vodka infused with natural vanilla flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a rich vanilla taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Belvedere Wild Berry Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-wild-berry.jpg",
    description: "A luxury vodka infused with natural wild berry flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing and fruity taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Grey Goose Cherry Noir Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-cherry-noir.jpg",
    description: "A premium vodka infused with natural cherry flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a rich cherry taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Skyy Infusions Citrus Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-citrus.jpg",
    description: "A vodka infused with natural citrus flavors.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Ketel One Botanical Grapefruit & Rose Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-grapefruit-rose.jpg",
    description:
      "A Dutch vodka infused with natural grapefruit and rose flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing and floral taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Smirnoff Whipped Cream Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-whipped-cream.jpg",
    description: "A vodka infused with natural whipped cream flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for dessert cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Absolut Vanilla Vodka",
    price: 21.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/absolut-vanilla.jpg",
    description: "A flavored vodka with a natural vanilla taste.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Absolut",
    rating: 4.6,
    reviews: "A smooth vodka with a rich vanilla flavor.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Three Olives Blueberry Vodka",
    price: 19.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/three-olives-blueberry.jpg",
    description: "A British vodka infused with natural blueberry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Three Olives",
    rating: 4.6,
    reviews: "A smooth vodka with a rich blueberry taste.",
    origin: "UK",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Belvedere Mango Passion Vodka",
    price: 32.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/belvedere-mango-passion.jpg",
    description:
      "A luxury vodka infused with natural mango and passion fruit flavors.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Belvedere",
    rating: 4.8,
    reviews: "A high-quality vodka with a refreshing and fruity taste.",
    origin: "Poland",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Grey Goose Le Melon Vodka",
    price: 35.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/grey-goose-le-melon.jpg",
    description: "A premium vodka infused with natural melon flavor.",
    category: "Flavored Vodka",
    abv: 40,
    size: "750ml",
    brand: "Grey Goose",
    rating: 4.8,
    reviews: "A smooth vodka with a refreshing melon taste.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Skyy Infusions Raspberry Vodka",
    price: 18.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/skyy-raspberry.jpg",
    description: "A vodka infused with natural raspberry flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Skyy",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Ketel One Botanical Peach & Orange Blossom Vodka",
    price: 25.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/ketel-one-peach-orange.jpg",
    description:
      "A Dutch vodka infused with natural peach and orange blossom flavors.",
    category: "Flavored Vodka",
    abv: 30,
    size: "750ml",
    brand: "Ketel One",
    rating: 4.7,
    reviews: "A smooth vodka with a refreshing and fruity taste.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Tito's Handmade Vodka",
    price: 22.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/titos.jpg",
    description:
      "A gluten-free vodka made from corn, known for its smoothness.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Tito's",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and pure taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Smirnoff Pineapple Vodka",
    price: 17.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/smirnoff-pineapple.jpg",
    description: "A vodka infused with natural pineapple flavor.",
    category: "Flavored Vodka",
    abv: 35,
    size: "750ml",
    brand: "Smirnoff",
    rating: 4.6,
    reviews: "A versatile vodka that is perfect for tropical cocktails.",
    origin: "Russia",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Absolut Elyx Vodka",
    price: 44.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/absolut-elyx.jpg",
    description:
      "A luxury vodka made from single estate wheat, offering a silky and smooth taste.",
    category: "Vodka",
    abv: 42.3,
    size: "750ml",
    brand: "Absolut",
    rating: 4.9,
    reviews: "A high-end vodka with a rich mouthfeel.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Crystal Head Vodka",
    price: 49.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/crystal-head.jpg",
    description:
      "A premium vodka known for its purity, bottled in a distinctive skull-shaped bottle.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Crystal Head",
    rating: 4.8,
    reviews: "A high-quality vodka with a clean and crisp finish.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "New Amsterdam Vodka",
    price: 15.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/new-amsterdam.jpg",
    description: "A smooth vodka with a clean and crisp taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "New Amsterdam",
    rating: 4.5,
    reviews: "A versatile vodka that is perfect for mixing.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Beluga Noble Russian Vodka",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/beluga.jpg",
    description:
      "A high-end Russian vodka known for its smooth and refined taste.",
    category: "Vodka",
    abv: 40,
    size: "750ml",
    brand: "Beluga",
    rating: 4.9,
    reviews: "A premium vodka with a delicate and pure flavor.",
    origin: "Russia",
    availability: "In Stock",
  },
];

module.exports = vodkas;
