const craftBeers = [
  {
    id: 1,
    name: "Sierra Nevada Pale Ale",
    price: 11.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/sierra-nevada-pale-ale.jpg",
    description: "A classic pale ale with a complex and hoppy flavor.",
    category: "Pale Ale",
    abv: 5.6,
    size: "12oz",
    brand: "Sierra Nevada",
    rating: 4.7,
    reviews: "A well-balanced and refreshing pale ale.",
    origin: "USA",
    pairing: "Grilled meats, salads",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Stone IPA",
    price: 12.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/stone-ipa.jpg",
    description:
      "A bold and hop-forward IPA with intense citrus and pine flavors.",
    category: "IPA",
    abv: 6.9,
    size: "12oz",
    brand: "Stone",
    rating: 4.8,
    reviews: "A strong and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Lagunitas IPA",
    price: 11.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/lagunitas-ipa.jpg",
    description: "A well-rounded and highly drinkable IPA with a hoppy finish.",
    category: "IPA",
    abv: 6.2,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.7,
    reviews: "A balanced and enjoyable IPA.",
    origin: "USA",
    pairing: "Burgers, spicy foods",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Bell's Two Hearted Ale",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/bells-two-hearted-ale.jpg",
    description: "A well-balanced American IPA with a strong hop presence.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "Bell's",
    rating: 4.8,
    reviews: "A highly acclaimed and flavorful IPA.",
    origin: "USA",
    pairing: "Grilled meats, spicy foods",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Founders All Day IPA",
    price: 10.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/founders-all-day-ipa.jpg",
    description: "A session IPA with a balanced and refreshing flavor.",
    category: "Session IPA",
    abv: 4.7,
    size: "12oz",
    brand: "Founders",
    rating: 4.6,
    reviews: "A perfect IPA for any time of day.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Dogfish Head 60 Minute IPA",
    price: 11.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/dogfish-head-60-minute-ipa.jpg",
    description:
      "A continually hopped IPA with a balanced bitterness and citrusy aroma.",
    category: "IPA",
    abv: 6,
    size: "12oz",
    brand: "Dogfish Head",
    rating: 4.7,
    reviews: "A well-crafted and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "New Belgium Fat Tire",
    price: 10.99,
    quantity: 110,
    imageUrl: "https://www.example.com/images/new-belgium-fat-tire.jpg",
    description:
      "A balanced amber ale with a toasty, biscuit-like malt flavor.",
    category: "Amber Ale",
    abv: 5.2,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.6,
    reviews: "A smooth and easy-drinking amber ale.",
    origin: "USA",
    pairing: "Pizza, roasted meats",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Deschutes Fresh Squeezed IPA",
    price: 12.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/deschutes-fresh-squeezed-ipa.jpg",
    description: "A juicy IPA with bold citrus and tropical fruit flavors.",
    category: "IPA",
    abv: 6.4,
    size: "12oz",
    brand: "Deschutes",
    rating: 4.8,
    reviews: "A refreshing and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Oskar Blues Dale's Pale Ale",
    price: 10.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/oskars-blues-dales-pale-ale.jpg",
    description: "A hoppy pale ale with a balanced malt backbone.",
    category: "Pale Ale",
    abv: 6.5,
    size: "12oz",
    brand: "Oskar Blues",
    rating: 4.7,
    reviews: "A well-balanced and flavorful pale ale.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Ballast Point Sculpin IPA",
    price: 14.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/ballast-point-sculpin-ipa.jpg",
    description:
      "A hoppy IPA with bright flavors of apricot, peach, mango, and lemon.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "Ballast Point",
    rating: 4.8,
    reviews: "A highly acclaimed and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Goose Island IPA",
    price: 11.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/goose-island-ipa.jpg",
    description: "A hoppy and balanced IPA with citrus and floral notes.",
    category: "IPA",
    abv: 5.9,
    size: "12oz",
    brand: "Goose Island",
    rating: 4.6,
    reviews: "A refreshing IPA with a smooth finish.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Lagunitas Little Sumpin' Sumpin' Ale",
    price: 12.99,
    quantity: 80,
    imageUrl:
      "https://www.example.com/images/lagunitas-little-sumpin-sumpin-ale.jpg",
    description: "A hoppy pale wheat ale with a smooth and refreshing finish.",
    category: "Pale Wheat Ale",
    abv: 7.5,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.8,
    reviews: "A unique and flavorful ale with a hoppy kick.",
    origin: "USA",
    pairing: "BBQ, spicy foods",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Firestone Walker Union Jack IPA",
    price: 12.99,
    quantity: 75,
    imageUrl:
      "https://www.example.com/images/firestone-walker-union-jack-ipa.jpg",
    description: "A hop-forward IPA with bold citrus and tropical flavors.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "Firestone Walker",
    rating: 4.7,
    reviews: "A flavorful and aromatic IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "New Belgium Voodoo Ranger IPA",
    price: 12.99,
    quantity: 75,
    imageUrl:
      "https://www.example.com/images/new-belgium-voodoo-ranger-ipa.jpg",
    description: "A bold IPA with juicy tropical and citrus flavors.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.7,
    reviews: "A flavorful and aromatic IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Great Divide Yeti Imperial Stout",
    price: 14.99,
    quantity: 65,
    imageUrl:
      "https://www.example.com/images/great-divide-yeti-imperial-stout.jpg",
    description:
      "A rich and robust stout with notes of chocolate, coffee, and caramel.",
    category: "Stout",
    abv: 9.5,
    size: "12oz",
    brand: "Great Divide",
    rating: 4.8,
    reviews: "A bold and flavorful stout.",
    origin: "USA",
    pairing: "Desserts, roasted meats",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Samuel Adams Boston Lager",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/samuel-adams-boston-lager.jpg",
    description: "A well-balanced lager with a full-bodied, malty flavor.",
    category: "Lager",
    abv: 5,
    size: "12oz",
    brand: "Samuel Adams",
    rating: 4.6,
    reviews: "A classic and reliable lager.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Founders Breakfast Stout",
    price: 14.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/founders-breakfast-stout.jpg",
    description:
      "A rich and robust stout with notes of coffee, chocolate, and oatmeal.",
    category: "Stout",
    abv: 8.3,
    size: "12oz",
    brand: "Founders",
    rating: 4.8,
    reviews: "A bold and flavorful stout.",
    origin: "USA",
    pairing: "Desserts, roasted meats",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Anchor Steam Beer",
    price: 11.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/anchor-steam-beer.jpg",
    description:
      "A unique beer with a blend of pale ale and lager characteristics.",
    category: "Steam Beer",
    abv: 4.9,
    size: "12oz",
    brand: "Anchor",
    rating: 4.6,
    reviews: "A well-balanced and flavorful beer.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Allagash White",
    price: 12.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/allagash-white.jpg",
    description:
      "A Belgian-style wheat beer with a balance of citrus and spice flavors.",
    category: "Wheat",
    abv: 5.2,
    size: "12oz",
    brand: "Allagash",
    rating: 4.7,
    reviews: "A refreshing and flavorful wheat beer.",
    origin: "USA",
    pairing: "Seafood, salads",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Three Floyds Zombie Dust",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/three-floyds-zombie-dust.jpg",
    description: "A hop-forward pale ale with intense citrus and pine flavors.",
    category: "Pale Ale",
    abv: 6.2,
    size: "12oz",
    brand: "Three Floyds",
    rating: 4.8,
    reviews: "A bold and flavorful pale ale.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Boulevard Tank 7 Farmhouse Ale",
    price: 12.99,
    quantity: 80,
    imageUrl:
      "https://www.example.com/images/boulevard-tank-7-farmhouse-ale.jpg",
    description: "A complex and fruity farmhouse ale with a dry finish.",
    category: "Farmhouse Ale",
    abv: 8.5,
    size: "12oz",
    brand: "Boulevard",
    rating: 4.7,
    reviews: "A well-balanced and refreshing farmhouse ale.",
    origin: "USA",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Avery White Rascal",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/avery-white-rascal.jpg",
    description:
      "A Belgian-style white ale with a balance of citrus and spice flavors.",
    category: "Wheat",
    abv: 5.6,
    size: "12oz",
    brand: "Avery",
    rating: 4.6,
    reviews: "A refreshing and flavorful wheat beer.",
    origin: "USA",
    pairing: "Seafood, salads",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "21st Amendment Brew Free! Or Die IPA",
    price: 11.99,
    quantity: 85,
    imageUrl:
      "https://www.example.com/images/21st-amendment-brew-free-or-die-ipa.jpg",
    description: "A hop-forward IPA with bright citrus and pine flavors.",
    category: "IPA",
    abv: 7,
    size: "12oz",
    brand: "21st Amendment",
    rating: 4.7,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Victory Golden Monkey",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/victory-golden-monkey.jpg",
    description: "A Belgian-style tripel with fruity and spicy flavors.",
    category: "Tripel",
    abv: 9.5,
    size: "12oz",
    brand: "Victory",
    rating: 4.8,
    reviews: "A strong and flavorful Belgian-style ale.",
    origin: "USA",
    pairing: "Cheese, roasted meats",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Terrapin Hopsecutioner IPA",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/terrapin-hopsecutioner-ipa.jpg",
    description: "A hop-forward IPA with a balance of citrus and pine flavors.",
    category: "IPA",
    abv: 7.3,
    size: "12oz",
    brand: "Terrapin",
    rating: 4.7,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Left Hand Milk Stout",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/left-hand-milk-stout.jpg",
    description: "A creamy stout with notes of coffee, chocolate, and caramel.",
    category: "Stout",
    abv: 6,
    size: "12oz",
    brand: "Left Hand",
    rating: 4.7,
    reviews: "A smooth and flavorful stout.",
    origin: "USA",
    pairing: "Desserts, roasted meats",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Russian River Pliny the Elder",
    price: 15.99,
    quantity: 60,
    imageUrl:
      "https://www.example.com/images/russian-river-pliny-the-elder.jpg",
    description: "A well-balanced double IPA with citrus and pine flavors.",
    category: "Double IPA",
    abv: 8,
    size: "12oz",
    brand: "Russian River",
    rating: 4.9,
    reviews: "A highly acclaimed and flavorful double IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Blue Moon Belgian White",
    price: 10.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/blue-moon-belgian-white.jpg",
    description:
      "A Belgian-style wheat beer with a hint of orange peel and coriander.",
    category: "Wheat",
    abv: 5.4,
    size: "12oz",
    brand: "Blue Moon",
    rating: 4.6,
    reviews: "A smooth and refreshing wheat beer.",
    origin: "USA",
    pairing: "Seafood, salads",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Rogue Dead Guy Ale",
    price: 12.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/rogue-dead-guy-ale.jpg",
    description:
      "A robust ale with a rich malt flavor and a touch of bitterness.",
    category: "Ale",
    abv: 6.8,
    size: "12oz",
    brand: "Rogue",
    rating: 4.7,
    reviews: "A well-balanced and flavorful ale.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Lagunitas Brown Shugga'",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/lagunitas-brown-shugga.jpg",
    description: "A strong ale with rich caramel and brown sugar flavors.",
    category: "Strong Ale",
    abv: 10,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.8,
    reviews: "A bold and flavorful strong ale.",
    origin: "USA",
    pairing: "Roasted meats, desserts",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Odell 90 Shilling Ale",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/odell-90-shilling-ale.jpg",
    description: "A smooth and balanced amber ale with a rich malt flavor.",
    category: "Amber Ale",
    abv: 5.3,
    size: "12oz",
    brand: "Odell",
    rating: 4.6,
    reviews: "A well-balanced and flavorful amber ale.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "SweetWater 420 Extra Pale Ale",
    price: 11.99,
    quantity: 95,
    imageUrl:
      "https://www.example.com/images/sweetwater-420-extra-pale-ale.jpg",
    description: "A crisp and refreshing pale ale with a balanced hop flavor.",
    category: "Pale Ale",
    abv: 5.7,
    size: "12oz",
    brand: "SweetWater",
    rating: 4.7,
    reviews: "A well-balanced and easy-drinking pale ale.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Cigar City Jai Alai IPA",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/cigar-city-jai-alai-ipa.jpg",
    description: "A bold IPA with flavors of citrus and tropical fruit.",
    category: "IPA",
    abv: 7.5,
    size: "12oz",
    brand: "Cigar City",
    rating: 4.8,
    reviews: "A highly acclaimed and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Green Flash West Coast IPA",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/green-flash-west-coast-ipa.jpg",
    description:
      "A hop-forward IPA with flavors of pine, citrus, and floral notes.",
    category: "IPA",
    abv: 8.1,
    size: "12oz",
    brand: "Green Flash",
    rating: 4.8,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Alaskan Amber",
    price: 11.99,
    quantity: 95,
    imageUrl: "https://www.example.com/images/alaskan-amber.jpg",
    description: "A smooth and balanced amber ale with a rich malt flavor.",
    category: "Amber Ale",
    abv: 5.3,
    size: "12oz",
    brand: "Alaskan",
    rating: 4.6,
    reviews: "A well-balanced and flavorful amber ale.",
    origin: "USA",
    pairing: "Burgers, grilled meats",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Bear Republic Racer 5 IPA",
    price: 13.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/bear-republic-racer-5-ipa.jpg",
    description: "A hoppy IPA with flavors of citrus and pine.",
    category: "IPA",
    abv: 7.5,
    size: "12oz",
    brand: "Bear Republic",
    rating: 4.8,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Boulevard Tank 7 Farmhouse Ale",
    price: 12.99,
    quantity: 85,
    imageUrl:
      "https://www.example.com/images/boulevard-tank-7-farmhouse-ale.jpg",
    description: "A complex and fruity farmhouse ale with a dry finish.",
    category: "Farmhouse Ale",
    abv: 8.5,
    size: "12oz",
    brand: "Boulevard",
    rating: 4.7,
    reviews: "A well-balanced and refreshing farmhouse ale.",
    origin: "USA",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Founders Centennial IPA",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/founders-centennial-ipa.jpg",
    description: "A well-balanced IPA with citrus and floral hop aromas.",
    category: "IPA",
    abv: 7.2,
    size: "12oz",
    brand: "Founders",
    rating: 4.7,
    reviews: "A smooth and refreshing IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Ninkasi Total Domination IPA",
    price: 12.99,
    quantity: 75,
    imageUrl: "https://www.example.com/images/ninkasi-total-domination-ipa.jpg",
    description: "A hop-forward IPA with flavors of citrus and pine.",
    category: "IPA",
    abv: 6.7,
    size: "12oz",
    brand: "Ninkasi",
    rating: 4.7,
    reviews: "A bold and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "21st Amendment Hell or High Watermelon",
    price: 11.99,
    quantity: 90,
    imageUrl:
      "https://www.example.com/images/21st-amendment-hell-or-high-watermelon.jpg",
    description: "A refreshing wheat beer with a hint of watermelon.",
    category: "Wheat",
    abv: 4.9,
    size: "12oz",
    brand: "21st Amendment",
    rating: 4.6,
    reviews: "A unique and refreshing wheat beer.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Avery Ellie's Brown Ale",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/avery-ellies-brown-ale.jpg",
    description:
      "A rich and malty brown ale with notes of chocolate and caramel.",
    category: "Brown Ale",
    abv: 5.5,
    size: "12oz",
    brand: "Avery",
    rating: 4.7,
    reviews: "A smooth and flavorful brown ale.",
    origin: "USA",
    pairing: "Burgers, roasted meats",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Victory Prima Pils",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/victory-prima-pils.jpg",
    description: "A crisp and refreshing pilsner with floral and spicy notes.",
    category: "Pilsner",
    abv: 5.3,
    size: "12oz",
    brand: "Victory",
    rating: 4.6,
    reviews: "A well-balanced and refreshing pilsner.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Sierra Nevada Hazy Little Thing IPA",
    price: 12.99,
    quantity: 80,
    imageUrl:
      "https://www.example.com/images/sierra-nevada-hazy-little-thing-ipa.jpg",
    description: "A juicy and hazy IPA with tropical fruit and citrus flavors.",
    category: "IPA",
    abv: 6.7,
    size: "12oz",
    brand: "Sierra Nevada",
    rating: 4.7,
    reviews: "A refreshing and flavorful IPA.",
    origin: "USA",
    pairing: "Spicy foods, grilled meats",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "New Belgium 1554 Black Lager",
    price: 11.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/new-belgium-1554-black-lager.jpg",
    description:
      "A smooth and malty black lager with roasted coffee and chocolate flavors.",
    category: "Black Lager",
    abv: 5.6,
    size: "12oz",
    brand: "New Belgium",
    rating: 4.7,
    reviews: "A well-balanced and flavorful black lager.",
    origin: "USA",
    pairing: "Burgers, roasted meats",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Deschutes Black Butte Porter",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/deschutes-black-butte-porter.jpg",
    description: "A rich and creamy porter with notes of chocolate and coffee.",
    category: "Porter",
    abv: 5.2,
    size: "12oz",
    brand: "Deschutes",
    rating: 4.7,
    reviews: "A smooth and flavorful porter.",
    origin: "USA",
    pairing: "Desserts, roasted meats",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Lagunitas DayTime IPA",
    price: 11.99,
    quantity: 90,
    imageUrl: "https://www.example.com/images/lagunitas-daytime-ipa.jpg",
    description: "A session IPA with a light and refreshing hop flavor.",
    category: "Session IPA",
    abv: 4,
    size: "12oz",
    brand: "Lagunitas",
    rating: 4.6,
    reviews: "A perfect IPA for any time of day.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Rogue Hazelnut Brown Nectar",
    price: 12.99,
    quantity: 85,
    imageUrl: "https://www.example.com/images/rogue-hazelnut-brown-nectar.jpg",
    description: "A rich and nutty brown ale with a smooth finish.",
    category: "Brown Ale",
    abv: 5.6,
    size: "12oz",
    brand: "Rogue",
    rating: 4.7,
    reviews: "A flavorful and well-balanced brown ale.",
    origin: "USA",
    pairing: "Burgers, roasted meats",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Great Lakes Edmund Fitzgerald Porter",
    price: 11.99,
    quantity: 90,
    imageUrl:
      "https://www.example.com/images/great-lakes-edmund-fitzgerald-porter.jpg",
    description: "A rich and robust porter with roasted malt flavors.",
    category: "Porter",
    abv: 6,
    size: "12oz",
    brand: "Great Lakes",
    rating: 4.7,
    reviews: "A smooth and flavorful porter.",
    origin: "USA",
    pairing: "Desserts, roasted meats",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "New Glarus Spotted Cow",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/new-glarus-spotted-cow.jpg",
    description: "A smooth and refreshing farmhouse ale with a hint of fruit.",
    category: "Farmhouse Ale",
    abv: 4.8,
    size: "12oz",
    brand: "New Glarus",
    rating: 4.7,
    reviews: "A well-balanced and flavorful farmhouse ale.",
    origin: "USA",
    pairing: "Salads, seafood",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "AleSmith Speedway Stout",
    price: 14.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/alesmith-speedway-stout.jpg",
    description:
      "A bold and rich imperial stout with notes of coffee and chocolate.",
    category: "Imperial Stout",
    abv: 12,
    size: "12oz",
    brand: "AleSmith",
    rating: 4.8,
    reviews: "A strong and flavorful stout.",
    origin: "USA",
    pairing: "Desserts, roasted meats",
    availability: "In Stock",
  },
];

module.exports = craftBeers;
