const sweetWines = [
  {
    id: 1,
    name: "Moscato d'Asti",
    price: 15.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/moscato-dasti.jpg",
    description: "Sweet and sparkling with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "La Spinetta",
    rating: 4.8,
    reviews: "A delightful sparkling wine, perfect for desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Tokaji Aszu",
    price: 45.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/tokaji-aszu.jpg",
    description:
      "Rich and luscious with flavors of apricot, honey, and citrus.",
    category: "Sweet Wine",
    brand: "Disznoko",
    rating: 4.9,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "Hungary",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Sauternes",
    price: 59.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sauternes.jpg",
    description:
      "Sweet and full-bodied with notes of honey, apricot, and vanilla.",
    category: "Sweet Wine",
    brand: "Chateau d'Yquem",
    rating: 4.9,
    reviews: "An exquisite wine, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Ice Wine",
    price: 49.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/ice-wine.jpg",
    description:
      "Intensely sweet with flavors of honey, lychee, and tropical fruit.",
    category: "Sweet Wine",
    brand: "Inniskillin",
    rating: 4.8,
    reviews: "A rare treat, excellent with fruit desserts.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Late Harvest Riesling",
    price: 25.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/late-harvest-riesling.jpg",
    description: "Sweet and aromatic with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Chateau Ste. Michelle",
    rating: 4.7,
    reviews: "A lovely wine, great with spicy dishes.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Pedro Ximenez Sherry",
    price: 35.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/pedro-ximenez-sherry.jpg",
    description: "Rich and syrupy with flavors of raisin, fig, and molasses.",
    category: "Sweet Wine",
    brand: "Bodegas Toro Albala",
    rating: 4.9,
    reviews: "A decadent dessert wine, perfect with chocolate.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Vin Santo",
    price: 44.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/vin-santo.jpg",
    description:
      "Sweet and nutty with notes of dried fruit, almond, and honey.",
    category: "Sweet Wine",
    brand: "Avignonesi",
    rating: 4.8,
    reviews: "A traditional Italian dessert wine, great with biscotti.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Port Wine",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/port-wine.jpg",
    description:
      "Rich and sweet with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Taylor Fladgate",
    rating: 4.7,
    reviews: "A classic dessert wine, excellent with cheese.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Sweet Riesling",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-riesling.jpg",
    description: "Sweet and crisp with notes of peach, apple, and honey.",
    category: "Sweet Wine",
    brand: "Dr. Loosen",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for spicy food.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Madeira",
    price: 39.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/madeira.jpg",
    description: "Sweet and rich with flavors of caramel, toffee, and nuts.",
    category: "Sweet Wine",
    brand: "Blandy's",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Sweet Muscat",
    price: 14.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/sweet-muscat.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Yalumba",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Demi-Sec Champagne",
    price: 49.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/demi-sec-champagne.jpg",
    description: "Sweet and bubbly with flavors of apple, pear, and brioche.",
    category: "Sweet Wine",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A luxurious sparkling wine, great for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Prosecco Dolce",
    price: 19.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/prosecco-dolce.jpg",
    description: "Sweet and sparkling with notes of apple, pear, and citrus.",
    category: "Sweet Wine",
    brand: "Villa Sandi",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for brunch.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Lambrusco Dolce",
    price: 12.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/lambrusco-dolce.jpg",
    description: "Sweet and sparkling with flavors of red berries and plum.",
    category: "Sweet Wine",
    brand: "Cavicchioli",
    rating: 4.7,
    reviews: "A refreshing wine, great with pizza.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Sweet Zinfandel",
    price: 17.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-zinfandel.jpg",
    description:
      "Sweet and fruity with notes of strawberry, raspberry, and spice.",
    category: "Sweet Wine",
    brand: "Beringer",
    rating: 4.6,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Brachetto d'Acqui",
    price: 16.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/brachetto-dacqui.jpg",
    description:
      "Sweet and sparkling with flavors of red berries and rose petals.",
    category: "Sweet Wine",
    brand: "Banfi",
    rating: 4.8,
    reviews: "A delightful wine, perfect for desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Dulce de Leche",
    price: 21.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dulce-de-leche.jpg",
    description: "Sweet and creamy with notes of caramel, vanilla, and cream.",
    category: "Sweet Wine",
    brand: "El Candado",
    rating: 4.7,
    reviews: "A decadent dessert wine, great with flan.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Sweet Cabernet Sauvignon",
    price: 22.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-cabernet-sauvignon.jpg",
    description:
      "Sweet and full-bodied with flavors of blackcurrant, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Apothic",
    rating: 4.7,
    reviews: "A rich wine, perfect for chocolate desserts.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Mavrodaphne of Patras",
    price: 19.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/mavrodaphne-of-patras.jpg",
    description: "Sweet and rich with flavors of raisin, fig, and spice.",
    category: "Sweet Wine",
    brand: "Parparoussis",
    rating: 4.8,
    reviews: "A delightful wine, great with nuts and cheese.",
    origin: "Greece",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Sweet Syrah",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-syrah.jpg",
    description: "Sweet and fruity with notes of blackberry, plum, and spice.",
    category: "Sweet Wine",
    brand: "Jam Jar",
    rating: 4.6,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Demi-Sec Cava",
    price: 15.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/demi-sec-cava.jpg",
    description: "Sweet and sparkling with notes of apple, pear, and citrus.",
    category: "Sweet Wine",
    brand: "Freixenet",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for celebrations.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Late Harvest Sauvignon Blanc",
    price: 23.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/late-harvest-sauvignon-blanc.jpg",
    description: "Sweet and aromatic with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Noble Hill",
    rating: 4.8,
    reviews: "A lovely wine, great with spicy dishes.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Sweet Gewurztraminer",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-gewurztraminer.jpg",
    description: "Sweet and aromatic with notes of lychee, rose, and spice.",
    category: "Sweet Wine",
    brand: "Trimbach",
    rating: 4.7,
    reviews: "A delightful wine, great with Asian cuisine.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Sweet Chenin Blanc",
    price: 16.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-chenin-blanc.jpg",
    description: "Sweet and fruity with notes of apple, pear, and honey.",
    category: "Sweet Wine",
    brand: "Ken Forrester",
    rating: 4.6,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Moscato Rosa",
    price: 27.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/moscato-rosa.jpg",
    description:
      "Sweet and floral with notes of rose petal, raspberry, and honey.",
    category: "Sweet Wine",
    brand: "Franz Haas",
    rating: 4.8,
    reviews: "A luxurious wine, perfect for desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Sweet Chardonnay",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-chardonnay.jpg",
    description: "Sweet and rich with flavors of apple, pear, and vanilla.",
    category: "Sweet Wine",
    brand: "Cupcake Vineyards",
    rating: 4.6,
    reviews: "A delightful wine, great with cheese and desserts.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Sweet Pinot Noir",
    price: 24.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-pinot-noir.jpg",
    description: "Sweet and fruity with notes of cherry, raspberry, and spice.",
    category: "Sweet Wine",
    brand: "Belle Glos",
    rating: 4.7,
    reviews: "A rich wine, perfect for chocolate desserts.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Late Harvest Semillon",
    price: 28.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/late-harvest-semillon.jpg",
    description:
      "Sweet and luscious with notes of apricot, honey, and vanilla.",
    category: "Sweet Wine",
    brand: "Chateau Suduiraut",
    rating: 4.9,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Sweet Merlot",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-merlot.jpg",
    description:
      "Sweet and fruity with flavors of plum, cherry, and chocolate.",
    category: "Sweet Wine",
    brand: "Roscato",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Dolcetto d'Alba",
    price: 21.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dolcetto-dalba.jpg",
    description: "Sweet and fruity with notes of blackberry, plum, and spice.",
    category: "Sweet Wine",
    brand: "Pio Cesare",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Sweet Shiraz",
    price: 22.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-shiraz.jpg",
    description:
      "Sweet and full-bodied with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Jam Jar",
    rating: 4.6,
    reviews: "A rich wine, perfect for chocolate desserts.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Sweet Viognier",
    price: 23.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-viognier.jpg",
    description: "Sweet and aromatic with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Yalumba",
    rating: 4.7,
    reviews: "A delightful wine, great with spicy dishes.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Passito di Pantelleria",
    price: 39.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/passito-di-pantelleria.jpg",
    description:
      "Sweet and rich with notes of apricot, honey, and dried fruit.",
    category: "Sweet Wine",
    brand: "Donnafugata",
    rating: 4.9,
    reviews: "A luxurious wine, great with desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Sweet Grenache",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-grenache.jpg",
    description:
      "Sweet and fruity with notes of strawberry, raspberry, and spice.",
    category: "Sweet Wine",
    brand: "Apothic",
    rating: 4.6,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Sweet Riesling Spatlese",
    price: 29.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-riesling-spatlese.jpg",
    description: "Sweet and crisp with notes of peach, apple, and honey.",
    category: "Sweet Wine",
    brand: "Dr. Loosen",
    rating: 4.8,
    reviews: "A refreshing wine, great with spicy food.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Sweet Petit Manseng",
    price: 31.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-petit-manseng.jpg",
    description:
      "Sweet and aromatic with notes of apricot, honey, and tropical fruit.",
    category: "Sweet Wine",
    brand: "Chateau Montus",
    rating: 4.8,
    reviews: "A lovely wine, great with cheese.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Sweet Furmint",
    price: 27.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-furmint.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and citrus.",
    category: "Sweet Wine",
    brand: "Royal Tokaji",
    rating: 4.9,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "Hungary",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Sweet Marsala",
    price: 22.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-marsala.jpg",
    description: "Sweet and rich with notes of raisin, fig, and caramel.",
    category: "Sweet Wine",
    brand: "Florio",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Sweet Muscat de Beaumes de Venise",
    price: 28.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/sweet-muscat-de-beaumes-de-venise.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Domaine des Bernardins",
    rating: 4.8,
    reviews: "A luxurious wine, perfect for desserts.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Sweet Banyuls",
    price: 32.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-banyuls.jpg",
    description:
      "Sweet and rich with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Domaine de la Rectorie",
    rating: 4.9,
    reviews: "A decadent wine, great with chocolate.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Sweet Lambrusco",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/sweet-lambrusco.jpg",
    description: "Sweet and sparkling with flavors of red berries and plum.",
    category: "Sweet Wine",
    brand: "Cavicchioli",
    rating: 4.7,
    reviews: "A refreshing wine, great with pizza.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Sweet Dolcetto",
    price: 19.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-dolcetto.jpg",
    description: "Sweet and fruity with notes of blackberry, plum, and spice.",
    category: "Sweet Wine",
    brand: "Pio Cesare",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Sweet White Zinfandel",
    price: 12.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/sweet-white-zinfandel.jpg",
    description:
      "Sweet and fruity with notes of strawberry, raspberry, and peach.",
    category: "Sweet Wine",
    brand: "Beringer",
    rating: 4.6,
    reviews: "A delightful wine, great for picnics.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Sweet Sangiovese",
    price: 21.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-sangiovese.jpg",
    description: "Sweet and fruity with notes of cherry, raspberry, and spice.",
    category: "Sweet Wine",
    brand: "Banfi",
    rating: 4.7,
    reviews: "A rich wine, perfect for chocolate desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Sweet Rose",
    price: 15.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/sweet-rose.jpg",
    description:
      "Sweet and refreshing with flavors of strawberry, raspberry, and peach.",
    category: "Sweet Wine",
    brand: "Barefoot",
    rating: 4.6,
    reviews: "A vibrant wine, great for summer.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Sweet Vidal Icewine",
    price: 44.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/sweet-vidal-icewine.jpg",
    description:
      "Intensely sweet with flavors of honey, lychee, and tropical fruit.",
    category: "Sweet Wine",
    brand: "Inniskillin",
    rating: 4.8,
    reviews: "A rare treat, excellent with fruit desserts.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Sweet Tempranillo",
    price: 17.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-tempranillo.jpg",
    description: "Sweet and fruity with notes of cherry, plum, and spice.",
    category: "Sweet Wine",
    brand: "Campo Viejo",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Sweet Malbec",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-malbec.jpg",
    description:
      "Sweet and fruity with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Alamos",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Sweet Garnacha",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-garnacha.jpg",
    description:
      "Sweet and fruity with notes of strawberry, raspberry, and spice.",
    category: "Sweet Wine",
    brand: "Borsao",
    rating: 4.6,
    reviews: "A delightful wine, great with cheese.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Sweet Carignan",
    price: 21.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-carignan.jpg",
    description:
      "Sweet and rich with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Gerard Bertrand",
    rating: 4.7,
    reviews: "A rich wine, perfect for chocolate desserts.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Sweet Zinfandel Rosé",
    price: 13.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/sweet-zinfandel-rose.jpg",
    description:
      "Sweet and fruity with notes of strawberry, raspberry, and peach.",
    category: "Sweet Wine",
    brand: "Sutter Home",
    rating: 4.6,
    reviews: "A delightful wine, great for picnics.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Sweet Barbera",
    price: 22.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-barbera.jpg",
    description: "Sweet and fruity with notes of cherry, raspberry, and spice.",
    category: "Sweet Wine",
    brand: "Pio Cesare",
    rating: 4.7,
    reviews: "A rich wine, perfect for chocolate desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Sweet Primitivo",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-primitivo.jpg",
    description:
      "Sweet and fruity with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Masseria Li Veli",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for barbecues.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Sweet Verdejo",
    price: 17.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-verdejo.jpg",
    description: "Sweet and fruity with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Naia",
    rating: 4.6,
    reviews: "A delightful wine, great with cheese.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Sweet Albariño",
    price: 23.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-albarino.jpg",
    description:
      "Sweet and refreshing with flavors of citrus, peach, and apricot.",
    category: "Sweet Wine",
    brand: "Mar de Frades",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for seafood.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Sweet Sauvignon Blanc",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-sauvignon-blanc.jpg",
    description: "Sweet and aromatic with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Noble Hill",
    rating: 4.7,
    reviews: "A lovely wine, great with spicy dishes.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Sweet Torrontés",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-torrontes.jpg",
    description: "Sweet and floral with notes of rose petal, peach, and honey.",
    category: "Sweet Wine",
    brand: "Crios",
    rating: 4.7,
    reviews: "A delightful wine, great with Asian cuisine.",
    origin: "Argentina",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Sweet Chenin Blanc",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-chenin-blanc.jpg",
    description: "Sweet and rich with flavors of apple, pear, and honey.",
    category: "Sweet Wine",
    brand: "Ken Forrester",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese and desserts.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Sweet Verdelho",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-verdelho.jpg",
    description: "Sweet and zesty with notes of lemon, lime, and honey.",
    category: "Sweet Wine",
    brand: "Herdade do Esporão",
    rating: 4.7,
    reviews: "A refreshing wine, great with seafood.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Sweet Riesling Ice Wine",
    price: 42.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-riesling-ice-wine.jpg",
    description:
      "Intensely sweet with flavors of honey, lychee, and tropical fruit.",
    category: "Sweet Wine",
    brand: "Inniskillin",
    rating: 4.8,
    reviews: "A rare treat, excellent with fruit desserts.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Sweet Pinot Grigio",
    price: 15.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-pinot-grigio.jpg",
    description: "Sweet and refreshing with notes of pear, apple, and citrus.",
    category: "Sweet Wine",
    brand: "Santa Margherita",
    rating: 4.6,
    reviews: "A delightful wine, great for summer.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Sweet Pinot Gris",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-pinot-gris.jpg",
    description: "Sweet and rich with flavors of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Willamette Valley Vineyards",
    rating: 4.7,
    reviews: "A lovely wine, great with cheese.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Sweet Chardonnay",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-chardonnay.jpg",
    description: "Sweet and rich with flavors of apple, pear, and vanilla.",
    category: "Sweet Wine",
    brand: "Cupcake Vineyards",
    rating: 4.6,
    reviews: "A delightful wine, great with cheese and desserts.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Sweet Muscat Blanc",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-muscat-blanc.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Rosenblum Cellars",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Sweet Riesling Kabinett",
    price: 23.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-riesling-kabinett.jpg",
    description: "Sweet and crisp with notes of peach, apple, and honey.",
    category: "Sweet Wine",
    brand: "Dr. Loosen",
    rating: 4.8,
    reviews: "A refreshing wine, great with spicy food.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Sweet Malvasia",
    price: 21.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-malvasia.jpg",
    description:
      "Sweet and aromatic with notes of apricot, honey, and tropical fruit.",
    category: "Sweet Wine",
    brand: "Planeta",
    rating: 4.8,
    reviews: "A lovely wine, great with cheese.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Sweet Chenin Blanc",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-chenin-blanc.jpg",
    description: "Sweet and rich with flavors of apple, pear, and honey.",
    category: "Sweet Wine",
    brand: "Ken Forrester",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese and desserts.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Sweet Moscato Giallo",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-moscato-giallo.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Alois Lageder",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Sweet Gewurztraminer Vendanges Tardives",
    price: 31.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/sweet-gewurztraminer-vendanges-tardives.jpg",
    description: "Sweet and aromatic with notes of lychee, rose, and honey.",
    category: "Sweet Wine",
    brand: "Zind-Humbrecht",
    rating: 4.8,
    reviews: "A delightful wine, great with Asian cuisine.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Sweet Albariño",
    price: 23.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-albarino.jpg",
    description:
      "Sweet and refreshing with flavors of citrus, peach, and apricot.",
    category: "Sweet Wine",
    brand: "Mar de Frades",
    rating: 4.7,
    reviews: "A vibrant wine, perfect for seafood.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Sweet Semillon",
    price: 22.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-semillon.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and vanilla.",
    category: "Sweet Wine",
    brand: "Chateau Coutet",
    rating: 4.7,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Sweet Chardonnay",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-chardonnay.jpg",
    description: "Sweet and rich with flavors of apple, pear, and vanilla.",
    category: "Sweet Wine",
    brand: "Cupcake Vineyards",
    rating: 4.6,
    reviews: "A delightful wine, great with cheese and desserts.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Sweet Muscat Ottonel",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-muscat-ottonel.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Weingut Brundlmayer",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "Austria",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Sweet Riesling Spätlese",
    price: 29.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-riesling-spatlese.jpg",
    description: "Sweet and crisp with notes of peach, apple, and honey.",
    category: "Sweet Wine",
    brand: "Dr. Loosen",
    rating: 4.8,
    reviews: "A refreshing wine, great with spicy food.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Sweet Malvasia Bianca",
    price: 21.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-malvasia-bianca.jpg",
    description:
      "Sweet and aromatic with notes of apricot, honey, and tropical fruit.",
    category: "Sweet Wine",
    brand: "Planeta",
    rating: 4.8,
    reviews: "A lovely wine, great with cheese.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Sweet Riesling",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-riesling.jpg",
    description: "Sweet and crisp with notes of peach, apple, and honey.",
    category: "Sweet Wine",
    brand: "Chateau Ste. Michelle",
    rating: 4.7,
    reviews: "A refreshing wine, great with spicy food.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Sweet Moscato d'Asti",
    price: 15.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-moscato-dasti.jpg",
    description: "Sweet and sparkling with notes of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "La Spinetta",
    rating: 4.8,
    reviews: "A delightful sparkling wine, perfect for desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Sweet Muscat Blanc à Petits Grains",
    price: 19.99,
    quantity: 35,
    imageUrl:
      "https://www.example.com/images/sweet-muscat-blanc-a-petits-grains.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Chateau de Campuget",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Sweet Roussanne",
    price: 24.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-roussanne.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and vanilla.",
    category: "Sweet Wine",
    brand: "Tablas Creek Vineyard",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Sweet Moscato Giallo",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-moscato-giallo.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Alois Lageder",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Sweet Pedro Ximénez",
    price: 32.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-pedro-ximenez.jpg",
    description: "Sweet and rich with notes of raisin, fig, and caramel.",
    category: "Sweet Wine",
    brand: "Bodegas Alvear",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Sweet Chenin Blanc",
    price: 20.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sweet-chenin-blanc.jpg",
    description: "Sweet and rich with flavors of apple, pear, and honey.",
    category: "Sweet Wine",
    brand: "Ken Forrester",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese and desserts.",
    origin: "South Africa",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Sweet Riesling Auslese",
    price: 35.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-riesling-auslese.jpg",
    description: "Sweet and rich with flavors of peach, apricot, and honey.",
    category: "Sweet Wine",
    brand: "Dr. Loosen",
    rating: 4.9,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Sweet Gewurztraminer",
    price: 19.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-gewurztraminer.jpg",
    description: "Sweet and aromatic with notes of lychee, rose, and spice.",
    category: "Sweet Wine",
    brand: "Trimbach",
    rating: 4.7,
    reviews: "A delightful wine, great with Asian cuisine.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Sweet Vidal",
    price: 24.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-vidal.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and citrus.",
    category: "Sweet Wine",
    brand: "Pelee Island Winery",
    rating: 4.8,
    reviews: "A lovely wine, great with cheese.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Sweet Roussanne",
    price: 24.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-roussanne.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and vanilla.",
    category: "Sweet Wine",
    brand: "Tablas Creek Vineyard",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Sweet Tokaji",
    price: 42.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-tokaji.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and citrus.",
    category: "Sweet Wine",
    brand: "Royal Tokaji",
    rating: 4.9,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "Hungary",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Sweet Muscat de Beaumes de Venise",
    price: 28.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/sweet-muscat-de-beaumes-de-venise.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Domaine des Bernardins",
    rating: 4.8,
    reviews: "A luxurious wine, perfect for desserts.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Sweet Banyuls",
    price: 32.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-banyuls.jpg",
    description:
      "Sweet and rich with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Domaine de la Rectorie",
    rating: 4.9,
    reviews: "A decadent wine, great with chocolate.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Sweet Sauternes",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-sauternes.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and vanilla.",
    category: "Sweet Wine",
    brand: "Chateau d'Yquem",
    rating: 4.9,
    reviews: "A luxurious dessert wine, great with blue cheese.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Sweet Port",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/sweet-port.jpg",
    description:
      "Sweet and rich with flavors of blackberry, plum, and chocolate.",
    category: "Sweet Wine",
    brand: "Taylor Fladgate",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts.",
    origin: "Portugal",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Sweet Sherry",
    price: 32.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-sherry.jpg",
    description: "Sweet and rich with notes of raisin, fig, and caramel.",
    category: "Sweet Wine",
    brand: "Bodegas Alvear",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Sweet Muscat",
    price: 14.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/sweet-muscat.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Yalumba",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Sweet Lambrusco",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/sweet-lambrusco.jpg",
    description: "Sweet and sparkling with flavors of red berries and plum.",
    category: "Sweet Wine",
    brand: "Cavicchioli",
    rating: 4.7,
    reviews: "A refreshing wine, great with pizza.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Sweet White Zinfandel",
    price: 12.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/sweet-white-zinfandel.jpg",
    description:
      "Sweet and fruity with notes of strawberry, raspberry, and peach.",
    category: "Sweet Wine",
    brand: "Beringer",
    rating: 4.6,
    reviews: "A delightful wine, great for picnics.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Sweet Muscat",
    price: 14.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/sweet-muscat.jpg",
    description:
      "Sweet and floral with notes of orange blossom, peach, and honey.",
    category: "Sweet Wine",
    brand: "Yalumba",
    rating: 4.7,
    reviews: "A refreshing wine, perfect for summer.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Sweet Moscato Rosa",
    price: 27.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/sweet-moscato-rosa.jpg",
    description:
      "Sweet and floral with notes of rose petal, raspberry, and honey.",
    category: "Sweet Wine",
    brand: "Franz Haas",
    rating: 4.8,
    reviews: "A luxurious wine, perfect for desserts.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Sweet Riesling",
    price: 18.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/sweet-riesling.jpg",
    description: "Sweet and crisp with notes of peach, apple, and honey.",
    category: "Sweet Wine",
    brand: "Chateau Ste. Michelle",
    rating: 4.7,
    reviews: "A refreshing wine, great with spicy food.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Sweet Pedro Ximénez",
    price: 32.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-pedro-ximenez.jpg",
    description: "Sweet and rich with notes of raisin, fig, and caramel.",
    category: "Sweet Wine",
    brand: "Bodegas Alvear",
    rating: 4.8,
    reviews: "A delightful wine, great with desserts.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Sweet Roussanne",
    price: 24.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/sweet-roussanne.jpg",
    description: "Sweet and rich with flavors of apricot, honey, and vanilla.",
    category: "Sweet Wine",
    brand: "Tablas Creek Vineyard",
    rating: 4.7,
    reviews: "A delightful wine, great with cheese.",
    origin: "USA",
    availability: "In Stock",
  },
];

module.exports = sweetWines;
