const gins = [
  {
    id: 1,
    name: "Bombay Sapphire Gin",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bombay-sapphire.jpg",
    description: "Aromatic and smooth with a blend of 10 botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Bombay Sapphire",
    rating: 4.7,
    reviews: "A classic gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Hendrick's Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/hendricks.jpg",
    description: "Infused with cucumber and rose petals for a unique taste.",
    category: "Gin",
    abv: 41.4,
    size: "750ml",
    brand: "Hendrick's",
    rating: 4.8,
    reviews: "A premium gin with a distinctive flavor.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Tanqueray London Dry Gin",
    price: 22.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/tanqueray.jpg",
    description: "A juniper-forward gin with a classic London dry profile.",
    category: "Gin",
    abv: 43.1,
    size: "750ml",
    brand: "Tanqueray",
    rating: 4.7,
    reviews: "Perfect for gin and tonic or martinis.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Beefeater London Dry Gin",
    price: 19.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/beefeater.jpg",
    description: "Crisp and clean with a blend of nine botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Beefeater",
    rating: 4.6,
    reviews: "A versatile gin great for a variety of cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Monkey 47 Schwarzwald Dry Gin",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/monkey47.jpg",
    description: "Complex and aromatic with 47 botanicals.",
    category: "Gin",
    abv: 47,
    size: "500ml",
    brand: "Monkey 47",
    rating: 4.9,
    reviews: "A unique gin with a rich flavor profile.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Plymouth Gin",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/plymouth.jpg",
    description: "Smooth and earthy with a blend of seven botanicals.",
    category: "Gin",
    abv: 41.2,
    size: "750ml",
    brand: "Plymouth",
    rating: 4.8,
    reviews: "A historic gin with a distinctive taste.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Aviation American Gin",
    price: 26.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/aviation.jpg",
    description: "Smooth and balanced with notes of juniper and spice.",
    category: "Gin",
    abv: 42,
    size: "750ml",
    brand: "Aviation",
    rating: 4.7,
    reviews: "A versatile gin great for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Nolet's Silver Dry Gin",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nolets.jpg",
    description:
      "Floral and fruity with notes of Turkish rose, peach, and raspberry.",
    category: "Gin",
    abv: 47.6,
    size: "750ml",
    brand: "Nolet's",
    rating: 4.8,
    reviews: "A luxurious gin with a unique flavor profile.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "The Botanist Islay Dry Gin",
    price: 37.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/botanist.jpg",
    description: "Rich and aromatic with 22 local botanicals.",
    category: "Gin",
    abv: 46,
    size: "750ml",
    brand: "The Botanist",
    rating: 4.8,
    reviews: "A complex gin with a distinct Islay character.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Sipsmith London Dry Gin",
    price: 34.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/sipsmith.jpg",
    description: "Bold and aromatic with a classic juniper-forward taste.",
    category: "Gin",
    abv: 41.6,
    size: "750ml",
    brand: "Sipsmith",
    rating: 4.8,
    reviews: "A premium gin perfect for martinis.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Tanqueray No. Ten Gin",
    price: 39.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/tanqueray-ten.jpg",
    description: "Citrusy and smooth with a blend of fresh botanicals.",
    category: "Gin",
    abv: 47.3,
    size: "750ml",
    brand: "Tanqueray",
    rating: 4.9,
    reviews: "A luxurious gin perfect for martinis and cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Roku Japanese Gin",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/roku.jpg",
    description: "Elegant and balanced with six Japanese botanicals.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Roku",
    rating: 4.8,
    reviews: "A refined gin with a unique Japanese twist.",
    origin: "Japan",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Gordon's London Dry Gin",
    price: 14.99,
    quantity: 100,
    imageUrl: "https://www.example.com/images/gordons.jpg",
    description: "Classic and juniper-forward with a clean finish.",
    category: "Gin",
    abv: 37.5,
    size: "750ml",
    brand: "Gordon's",
    rating: 4.5,
    reviews: "A budget-friendly gin perfect for mixing.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Seagram's Extra Dry Gin",
    price: 12.99,
    quantity: 80,
    imageUrl: "https://www.example.com/images/seagrams.jpg",
    description: "Smooth and mellow with a blend of botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Seagram's",
    rating: 4.4,
    reviews: "A versatile gin great for a variety of cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Caorunn Small Batch Scottish Gin",
    price: 32.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/caorunn.jpg",
    description: "Crisp and aromatic with five locally foraged botanicals.",
    category: "Gin",
    abv: 41.8,
    size: "750ml",
    brand: "Caorunn",
    rating: 4.7,
    reviews: "A unique gin with a distinct Scottish character.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Malfy Gin Con Limone",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/malfy-limone.jpg",
    description: "Zesty and refreshing with Italian lemons.",
    category: "Gin",
    abv: 41,
    size: "750ml",
    brand: "Malfy",
    rating: 4.8,
    reviews: "A bright and citrusy gin perfect for summer cocktails.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Brooklyn Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/brooklyn-gin.jpg",
    description:
      "Fresh and citrusy with hand-cut citrus peels and juniper berries.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Brooklyn Gin",
    rating: 4.7,
    reviews: "A craft gin with a refreshing taste.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Empress 1908 Gin",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/empress-1908.jpg",
    description: "Vibrant and floral with butterfly pea blossom.",
    category: "Gin",
    abv: 42.5,
    size: "750ml",
    brand: "Empress 1908",
    rating: 4.8,
    reviews: "A visually stunning gin perfect for cocktails.",
    origin: "Canada",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Gin Mare Mediterranean Gin",
    price: 36.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/gin-mare.jpg",
    description:
      "Herbaceous and savory with rosemary, thyme, olive, and basil.",
    category: "Gin",
    abv: 42.7,
    size: "750ml",
    brand: "Gin Mare",
    rating: 4.8,
    reviews: "A unique gin with Mediterranean botanicals.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Fords Gin",
    price: 26.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/fords-gin.jpg",
    description: "Balanced and versatile with nine botanicals.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Fords",
    rating: 4.7,
    reviews: "A gin crafted for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Bluecoat American Dry Gin",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/bluecoat.jpg",
    description: "Citrusy and spicy with organic botanicals.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Bluecoat",
    rating: 4.7,
    reviews: "A distinctive American gin.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Malfy Gin Rosa",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/malfy-rosa.jpg",
    description: "Fruity and floral with Sicilian pink grapefruit.",
    category: "Gin",
    abv: 41,
    size: "750ml",
    brand: "Malfy",
    rating: 4.8,
    reviews: "A delightful gin perfect for summer drinks.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Death's Door Gin",
    price: 34.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/deaths-door.jpg",
    description: "Bold and aromatic with juniper, coriander, and fennel.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Death's Door",
    rating: 4.6,
    reviews: "A robust gin with a unique flavor profile.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Silent Pool Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/silent-pool.jpg",
    description: "Complex and floral with 24 botanicals.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Silent Pool",
    rating: 4.9,
    reviews: "A premium gin with a rich and layered taste.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Four Pillars Rare Dry Gin",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/four-pillars.jpg",
    description: "Spicy and citrusy with native Australian botanicals.",
    category: "Gin",
    abv: 41.8,
    size: "750ml",
    brand: "Four Pillars",
    rating: 4.8,
    reviews: "A distinctive gin with a unique Australian character.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Bombay Dry Gin",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bombay-dry.jpg",
    description: "Clean and crisp with a classic botanical blend.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Bombay",
    rating: 4.6,
    reviews: "A classic gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Gin Lane 1751 London Dry Gin",
    price: 24.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/gin-lane-1751.jpg",
    description: "Traditional and balanced with a blend of eight botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Gin Lane 1751",
    rating: 4.7,
    reviews: "A versatile gin great for a variety of cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Hayman's Old Tom Gin",
    price: 26.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/haymans-old-tom.jpg",
    description: "Slightly sweet and rich with a classic Old Tom profile.",
    category: "Gin",
    abv: 41.4,
    size: "750ml",
    brand: "Hayman's",
    rating: 4.7,
    reviews: "A historic gin perfect for classic cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Citadelle Gin",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/citadelle.jpg",
    description: "Elegant and aromatic with 19 botanicals.",
    category: "Gin",
    abv: 44,
    size: "750ml",
    brand: "Citadelle",
    rating: 4.8,
    reviews: "A refined gin with a unique flavor profile.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Greenhook Ginsmiths American Dry Gin",
    price: 34.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/greenhook.jpg",
    description: "Fresh and crisp with organic botanicals.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Greenhook Ginsmiths",
    rating: 4.7,
    reviews: "A distinctive American gin.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Drumshanbo Gunpowder Irish Gin",
    price: 39.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/drumshanbo.jpg",
    description: "Exotic and complex with oriental botanicals.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Drumshanbo",
    rating: 4.8,
    reviews: "A unique gin with a rich flavor profile.",
    origin: "Ireland",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Boodles British Gin",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/boodles.jpg",
    description: "Classic and juniper-forward with a clean finish.",
    category: "Gin",
    abv: 45.2,
    size: "750ml",
    brand: "Boodles",
    rating: 4.7,
    reviews: "A traditional gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Old Raj Dry Gin",
    price: 44.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/old-raj.jpg",
    description: "Rich and complex with saffron.",
    category: "Gin",
    abv: 46,
    size: "750ml",
    brand: "Old Raj",
    rating: 4.8,
    reviews: "A premium gin with a unique flavor profile.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Junipero Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/junipero.jpg",
    description: "Bold and juniper-forward with a classic taste.",
    category: "Gin",
    abv: 49.3,
    size: "750ml",
    brand: "Junipero",
    rating: 4.7,
    reviews: "A distinctive gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Barr Hill Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/barr-hill.jpg",
    description: "Smooth and sweet with raw honey.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Barr Hill",
    rating: 4.8,
    reviews: "A unique gin with a distinctive flavor.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "The London No. 1 Original Blue Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/london-no-1.jpg",
    description: "Elegant and floral with a distinctive blue color.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "The London No. 1",
    rating: 4.8,
    reviews: "A luxurious gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Bulldog London Dry Gin",
    price: 24.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bulldog.jpg",
    description: "Smooth and balanced with 12 botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Bulldog",
    rating: 4.7,
    reviews: "A versatile gin great for a variety of cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Opihr Oriental Spiced Gin",
    price: 29.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/opihr.jpg",
    description: "Exotic and aromatic with oriental spices.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Opihr",
    rating: 4.8,
    reviews: "A unique gin with a rich flavor profile.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Pinkster Gin",
    price: 34.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/pinkster.jpg",
    description: "Fruity and floral with raspberries.",
    category: "Gin",
    abv: 37.5,
    size: "750ml",
    brand: "Pinkster",
    rating: 4.7,
    reviews: "A delightful gin perfect for summer drinks.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Bloom Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/bloom.jpg",
    description: "Floral and elegant with honeysuckle, chamomile, and pomelo.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Bloom",
    rating: 4.8,
    reviews: "A refined gin with a unique flavor profile.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Edinburgh Gin",
    price: 34.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/edinburgh.jpg",
    description: "Balanced and aromatic with 13 botanicals.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Edinburgh Gin",
    rating: 4.7,
    reviews: "A distinctive gin with a rich flavor profile.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Tanqueray Rangpur Gin",
    price: 29.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/tanqueray-rangpur.jpg",
    description: "Citrusy and smooth with Rangpur limes.",
    category: "Gin",
    abv: 41.3,
    size: "750ml",
    brand: "Tanqueray",
    rating: 4.8,
    reviews: "A bright and refreshing gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Spirit of Hven Organic Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/spirit-of-hven.jpg",
    description: "Complex and aromatic with 10 botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Spirit of Hven",
    rating: 4.8,
    reviews: "A luxurious gin with a unique flavor profile.",
    origin: "Sweden",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Ransom Old Tom Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/ransom-old-tom.jpg",
    description: "Slightly sweet and rich with a historic Old Tom profile.",
    category: "Gin",
    abv: 44,
    size: "750ml",
    brand: "Ransom",
    rating: 4.7,
    reviews: "A historic gin perfect for classic cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Rutte Celery Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/rutte-celery.jpg",
    description: "Herbaceous and savory with celery.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Rutte",
    rating: 4.7,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "St. George Terroir Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/st-george-terroir.jpg",
    description: "Earthy and aromatic with Douglas fir, bay laurel, and sage.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "St. George",
    rating: 4.8,
    reviews: "A unique gin with a distinct sense of place.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Dingle Original Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dingle.jpg",
    description: "Smooth and balanced with local botanicals.",
    category: "Gin",
    abv: 42.5,
    size: "750ml",
    brand: "Dingle",
    rating: 4.7,
    reviews: "A distinctive gin with a rich flavor profile.",
    origin: "Ireland",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Elephant Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/elephant.jpg",
    description: "Herbaceous and spicy with African botanicals.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Elephant Gin",
    rating: 4.8,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Old Tom Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/old-tom.jpg",
    description: "Slightly sweet and rich with a historic Old Tom profile.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Old Tom",
    rating: 4.7,
    reviews: "A historic gin perfect for classic cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Fifty Pounds Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fifty-pounds.jpg",
    description: "Smooth and balanced with a classic gin profile.",
    category: "Gin",
    abv: 43.5,
    size: "750ml",
    brand: "Fifty Pounds",
    rating: 4.8,
    reviews: "A premium gin with a rich flavor profile.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Audemus Pink Pepper Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/pink-pepper.jpg",
    description: "Spicy and aromatic with pink peppercorns.",
    category: "Gin",
    abv: 44,
    size: "750ml",
    brand: "Audemus",
    rating: 4.8,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Breuckelen Glorious Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/breuckelen.jpg",
    description: "Fresh and aromatic with locally sourced botanicals.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Breuckelen",
    rating: 4.7,
    reviews: "A unique gin with a distinct sense of place.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Cotswolds Dry Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/cotswolds.jpg",
    description: "Rich and aromatic with local botanicals.",
    category: "Gin",
    abv: 46,
    size: "750ml",
    brand: "Cotswolds",
    rating: 4.8,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Fifty Pounds Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fifty-pounds.jpg",
    description: "Smooth and balanced with a classic gin profile.",
    category: "Gin",
    abv: 43.5,
    size: "750ml",
    brand: "Fifty Pounds",
    rating: 4.8,
    reviews: "A premium gin with a rich flavor profile.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Nordés Atlantic Galician Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/nordes.jpg",
    description: "Fresh and aromatic with Galician botanicals.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Nordés",
    rating: 4.7,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Sipsmith V.J.O.P. Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/sipsmith-vjop.jpg",
    description: "Bold and juniper-forward with a classic taste.",
    category: "Gin",
    abv: 57.7,
    size: "750ml",
    brand: "Sipsmith",
    rating: 4.8,
    reviews: "A distinctive gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Edgerton Pink Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/edgerton.jpg",
    description: "Fruity and floral with a pink hue.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Edgerton",
    rating: 4.7,
    reviews: "A unique gin perfect for summer drinks.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Dorothy Parker American Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/dorothy-parker.jpg",
    description: "Smooth and balanced with a blend of botanicals.",
    category: "Gin",
    abv: 44,
    size: "750ml",
    brand: "Dorothy Parker",
    rating: 4.8,
    reviews: "A distinctive American gin.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Jodhpur Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jodhpur.jpg",
    description: "Smooth and aromatic with Indian botanicals.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Jodhpur",
    rating: 4.7,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Star of Bombay Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/star-of-bombay.jpg",
    description: "Elegant and smooth with a blend of 12 botanicals.",
    category: "Gin",
    abv: 47.5,
    size: "750ml",
    brand: "Bombay",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Plymouth Navy Strength Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/plymouth-navy.jpg",
    description: "Bold and robust with a classic gin profile.",
    category: "Gin",
    abv: 57,
    size: "750ml",
    brand: "Plymouth",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Beefeater 24 Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/beefeater-24.jpg",
    description: "Smooth and balanced with 12 botanicals.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Beefeater",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Fords Gin Officers' Reserve",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/fords-reserve.jpg",
    description: "Bold and robust with a classic gin profile.",
    category: "Gin",
    abv: 54.5,
    size: "750ml",
    brand: "Fords",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Bombay Sapphire East Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/bombay-east.jpg",
    description:
      "Exotic and aromatic with Thai lemongrass and Vietnamese black pepper.",
    category: "Gin",
    abv: 42,
    size: "750ml",
    brand: "Bombay",
    rating: 4.8,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Koval Dry Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/koval.jpg",
    description: "Smooth and aromatic with wildflowers.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Koval",
    rating: 4.7,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Hayman's London Dry Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/haymans-london-dry.jpg",
    description: "Smooth and balanced with a classic gin profile.",
    category: "Gin",
    abv: 41.2,
    size: "750ml",
    brand: "Hayman's",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Monkey 47 Sloe Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/monkey47-sloe.jpg",
    description: "Smooth and fruity with sloe berries.",
    category: "Gin",
    abv: 29,
    size: "500ml",
    brand: "Monkey 47",
    rating: 4.8,
    reviews: "A unique gin with a distinctive flavor profile.",
    origin: "Germany",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Aria Portland Dry Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/aria.jpg",
    description: "Smooth and balanced with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Aria",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Brooklyn Small Batch Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/brooklyn-small-batch.jpg",
    description: "Smooth and balanced with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Brooklyn",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Distillery No. 209 Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/no-209.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 46,
    size: "750ml",
    brand: "No. 209",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Bluecoat Barrel Finished Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/bluecoat-barrel.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Bluecoat",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Cadenhead's Old Raj Dry Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/cadenheads.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 55,
    size: "750ml",
    brand: "Cadenhead's",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Ginraw Gastronomic Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/ginraw.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 42.3,
    size: "750ml",
    brand: "Ginraw",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Beefeater London Garden Gin",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/beefeater-london-garden.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Beefeater",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Hendrick's Midsummer Solstice Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/hendricks-midsummer.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 43.4,
    size: "750ml",
    brand: "Hendrick's",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Greenhook Ginsmiths Beach Plum Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/greenhook-beach-plum.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 30,
    size: "750ml",
    brand: "Greenhook Ginsmiths",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Aviation Old Tom Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/aviation-old-tom.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 42,
    size: "750ml",
    brand: "Aviation",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Copper & Kings American Dry Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/copper-kings.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Copper & Kings",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Rogue Spruce Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/rogue.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Rogue",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Few American Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/few.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Few",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "St. Augustine New World Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/st-augustine.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "St. Augustine",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Uncle Val's Restorative Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/uncle-vals.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Uncle Val's",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Desert Juniper Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/desert-juniper.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Desert Juniper",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Oola Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/oola.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Oola",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Deschutes Brewery Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/deschutes.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Deschutes",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Widow Jane American Oak Aged Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/widow-jane.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Widow Jane",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Big Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/big-gin.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 47,
    size: "750ml",
    brand: "Big Gin",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Coppersea Excelsior Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/coppersea.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "Coppersea",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Adnams Copper House Dry Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/adnams.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Adnams",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "St. George Botanivore Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/st-george-botanivore.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 45,
    size: "750ml",
    brand: "St. George",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Brooklyn Small Batch Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/brooklyn-small-batch.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Brooklyn",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Scapegrace Gold Dry Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/scapegrace.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 42.2,
    size: "750ml",
    brand: "Scapegrace",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "New Zealand",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Junipero Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/junipero.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 49.3,
    size: "750ml",
    brand: "Junipero",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Farmer's Organic Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/farmers.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 46.7,
    size: "750ml",
    brand: "Farmer's",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Silent Pool Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/silent-pool.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Silent Pool",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "England",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Edinburgh Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/edinburgh.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 43,
    size: "750ml",
    brand: "Edinburgh",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Four Pillars Rare Dry Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/four-pillars.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 41.8,
    size: "750ml",
    brand: "Four Pillars",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Australia",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Brooklyn Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/brooklyn.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 40,
    size: "750ml",
    brand: "Brooklyn",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Hendrick's Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/hendricks.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 41.4,
    size: "750ml",
    brand: "Hendrick's",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Scotland",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Monkey 47 Schwarzwald Dry Gin",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/monkey47.jpg",
    description: "Smooth and aromatic with a classic gin profile.",
    category: "Gin",
    abv: 47,
    size: "500ml",
    brand: "Monkey 47",
    rating: 4.8,
    reviews: "A premium gin perfect for cocktails.",
    origin: "Germany",
    availability: "In Stock",
  },
];

module.exports = gins;
