const kegs = [
  {
    id: 1,
    name: "Bud Light Keg",
    price: 144.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/bud-light-keg.jpg",
    description: "A refreshing light beer with a crisp and clean finish.",
    category: "Light Lager",
    abv: 4.2,
    size: "15.5 Gal",
    brand: "Bud Light",
    rating: 4.5,
    reviews: "A popular choice for parties and events.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Coors Light Keg",
    price: 149.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/coors-light-keg.jpg",
    description: "A light beer with a crisp, refreshing taste.",
    category: "Light Lager",
    abv: 4.2,
    size: "15.5 Gal",
    brand: "Coors Light",
    rating: 4.4,
    reviews: "A smooth and easy-drinking light beer.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Miller Lite Keg",
    price: 144.99,
    quantity: 12,
    imageUrl: "https://www.example.com/images/miller-lite-keg.jpg",
    description: "A classic light beer with a smooth, refreshing taste.",
    category: "Light Lager",
    abv: 4.2,
    size: "15.5 Gal",
    brand: "Miller Lite",
    rating: 4.5,
    reviews: "A go-to choice for gatherings and events.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Heineken Keg",
    price: 159.99,
    quantity: 7,
    imageUrl: "https://www.example.com/images/heineken-keg.jpg",
    description: "A premium lager with a rich, balanced taste.",
    category: "Lager",
    abv: 5,
    size: "15.5 Gal",
    brand: "Heineken",
    rating: 4.6,
    reviews: "A popular and well-known premium lager.",
    origin: "Netherlands",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Guinness Draught Keg",
    price: 174.99,
    quantity: 6,
    imageUrl: "https://www.example.com/images/guinness-draught-keg.jpg",
    description: "A rich and creamy stout with a smooth finish.",
    category: "Stout",
    abv: 4.2,
    size: "15.5 Gal",
    brand: "Guinness",
    rating: 4.8,
    reviews: "A classic and beloved stout.",
    origin: "Ireland",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Blue Moon Belgian White Keg",
    price: 169.99,
    quantity: 9,
    imageUrl: "https://www.example.com/images/blue-moon-keg.jpg",
    description: "A Belgian-style wheat beer with a hint of orange peel.",
    category: "Wheat Beer",
    abv: 5.4,
    size: "15.5 Gal",
    brand: "Blue Moon",
    rating: 4.7,
    reviews: "A refreshing and flavorful wheat beer.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Samuel Adams Boston Lager Keg",
    price: 159.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/samuel-adams-keg.jpg",
    description: "A full-bodied lager with a rich, malty flavor.",
    category: "Lager",
    abv: 5,
    size: "15.5 Gal",
    brand: "Samuel Adams",
    rating: 4.6,
    reviews: "A well-balanced and flavorful lager.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Sierra Nevada Pale Ale Keg",
    price: 169.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/sierra-nevada-keg.jpg",
    description:
      "A classic pale ale with a bold hop flavor and a crisp finish.",
    category: "Pale Ale",
    abv: 5.6,
    size: "15.5 Gal",
    brand: "Sierra Nevada",
    rating: 4.7,
    reviews: "A highly regarded and flavorful pale ale.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Lagunitas IPA Keg",
    price: 174.99,
    quantity: 6,
    imageUrl: "https://www.example.com/images/lagunitas-ipa-keg.jpg",
    description: "A well-balanced IPA with a hoppy finish and citrus notes.",
    category: "IPA",
    abv: 6.2,
    size: "15.5 Gal",
    brand: "Lagunitas",
    rating: 4.8,
    reviews: "A popular and bold IPA.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Dos Equis Lager Keg",
    price: 154.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/dos-equis-keg.jpg",
    description: "A light and refreshing lager with a hint of malt.",
    category: "Lager",
    abv: 4.2,
    size: "15.5 Gal",
    brand: "Dos Equis",
    rating: 4.5,
    reviews: "A smooth and easy-drinking lager.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Stella Artois Keg",
    price: 164.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/stella-artois-keg.jpg",
    description: "A premium European lager with a crisp and refreshing taste.",
    category: "Lager",
    abv: 5,
    size: "15.5 Gal",
    brand: "Stella Artois",
    rating: 4.6,
    reviews: "A well-known and beloved lager.",
    origin: "Belgium",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Founders All Day IPA Keg",
    price: 169.99,
    quantity: 6,
    imageUrl: "https://www.example.com/images/founders-all-day-ipa-keg.jpg",
    description: "A session IPA with a light body and a hoppy finish.",
    category: "Session IPA",
    abv: 4.7,
    size: "15.5 Gal",
    brand: "Founders",
    rating: 4.7,
    reviews: "A refreshing and easy-drinking IPA.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "New Belgium Fat Tire Keg",
    price: 159.99,
    quantity: 7,
    imageUrl: "https://www.example.com/images/new-belgium-fat-tire-keg.jpg",
    description:
      "A balanced amber ale with a toasty, biscuit-like malt flavor.",
    category: "Amber Ale",
    abv: 5.2,
    size: "15.5 Gal",
    brand: "New Belgium",
    rating: 4.6,
    reviews: "A popular and flavorful amber ale.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Kona Big Wave Golden Ale Keg",
    price: 169.99,
    quantity: 9,
    imageUrl: "https://www.example.com/images/kona-big-wave-keg.jpg",
    description:
      "A smooth and easy-drinking golden ale with a tropical hop aroma.",
    category: "Golden Ale",
    abv: 4.4,
    size: "15.5 Gal",
    brand: "Kona",
    rating: 4.7,
    reviews: "A refreshing and flavorful ale.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Stone IPA Keg",
    price: 174.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/stone-ipa-keg.jpg",
    description:
      "A well-balanced IPA with a bold hop flavor and a crisp finish.",
    category: "IPA",
    abv: 6.9,
    size: "15.5 Gal",
    brand: "Stone",
    rating: 4.8,
    reviews: "A popular and bold IPA.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Modelo Especial Keg",
    price: 154.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/modelo-especial-keg.jpg",
    description: "A light and refreshing lager with a well-balanced flavor.",
    category: "Lager",
    abv: 4.4,
    size: "15.5 Gal",
    brand: "Modelo",
    rating: 4.5,
    reviews: "A smooth and easy-drinking lager.",
    origin: "Mexico",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Peroni Nastro Azzurro Keg",
    price: 164.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/peroni-keg.jpg",
    description: "A premium Italian lager with a crisp and refreshing taste.",
    category: "Lager",
    abv: 5.1,
    size: "15.5 Gal",
    brand: "Peroni",
    rating: 4.6,
    reviews: "A well-known and beloved lager.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Yuengling Traditional Lager Keg",
    price: 154.99,
    quantity: 9,
    imageUrl: "https://www.example.com/images/yuengling-lager-keg.jpg",
    description: "A rich amber lager with a well-balanced taste.",
    category: "Lager",
    abv: 4.5,
    size: "15.5 Gal",
    brand: "Yuengling",
    rating: 4.6,
    reviews: "A popular and flavorful lager.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Bell's Two Hearted Ale Keg",
    price: 179.99,
    quantity: 5,
    imageUrl: "https://www.example.com/images/bells-two-hearted-keg.jpg",
    description:
      "An American IPA with a strong hop aroma and a balanced malt profile.",
    category: "IPA",
    abv: 7,
    size: "15.5 Gal",
    brand: "Bell's",
    rating: 4.8,
    reviews: "A highly regarded and flavorful IPA.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Goose Island IPA Keg",
    price: 174.99,
    quantity: 6,
    imageUrl: "https://www.example.com/images/goose-island-ipa-keg.jpg",
    description: "A classic IPA with a bold hop flavor and a crisp finish.",
    category: "IPA",
    abv: 5.9,
    size: "15.5 Gal",
    brand: "Goose Island",
    rating: 4.7,
    reviews: "A popular and bold IPA.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Dogfish Head 60 Minute IPA Keg",
    price: 179.99,
    quantity: 5,
    imageUrl:
      "https://www.example.com/images/dogfish-head-60-minute-ipa-keg.jpg",
    description:
      "A continuously hopped IPA with a balanced bitterness and a citrusy finish.",
    category: "IPA",
    abv: 6,
    size: "15.5 Gal",
    brand: "Dogfish Head",
    rating: 4.8,
    reviews: "A unique and flavorful IPA.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Shock Top Belgian White Keg",
    price: 159.99,
    quantity: 7,
    imageUrl: "https://www.example.com/images/shock-top-keg.jpg",
    description: "A Belgian-style wheat beer with citrus and spice notes.",
    category: "Wheat Beer",
    abv: 5.2,
    size: "15.5 Gal",
    brand: "Shock Top",
    rating: 4.6,
    reviews: "A refreshing and flavorful wheat beer.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Brooklyn Lager Keg",
    price: 164.99,
    quantity: 6,
    imageUrl: "https://www.example.com/images/brooklyn-lager-keg.jpg",
    description:
      "A flavorful amber lager with a malty backbone and a hint of hops.",
    category: "Lager",
    abv: 5.2,
    size: "15.5 Gal",
    brand: "Brooklyn Brewery",
    rating: 4.7,
    reviews: "A well-balanced and flavorful lager.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Hoegaarden White Keg",
    price: 169.99,
    quantity: 6,
    imageUrl: "https://www.example.com/images/hoegaarden-white-keg.jpg",
    description:
      "A Belgian-style wheat beer with a light and refreshing taste.",
    category: "Wheat Beer",
    abv: 4.9,
    size: "15.5 Gal",
    brand: "Hoegaarden",
    rating: 4.7,
    reviews: "A popular and flavorful wheat beer.",
    origin: "Belgium",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Newcastle Brown Ale Keg",
    price: 159.99,
    quantity: 7,
    imageUrl: "https://www.example.com/images/newcastle-brown-ale-keg.jpg",
    description: "A smooth and malty brown ale with a balanced flavor.",
    category: "Brown Ale",
    abv: 4.7,
    size: "15.5 Gal",
    brand: "Newcastle",
    rating: 4.6,
    reviews: "A popular and well-known brown ale.",
    origin: "England",
    availability: "In Stock",
  },
];

module.exports = kegs;
