const products = [
  {
    id: 1,
    name: "Bulleit Bourbon",
    price: 29.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bulleit/bulleit-bourbon-whiskey.jpg?alt=1&w=511&h=1024&b=0xFFFFFF&q=100",
    description: "A bold, spicy rye backbone with a smooth, clean finish.",
    category: "Rye",
    abv: 45,
    size: "750ml",
    brand: "Bulleit",
    rating: 4.5,
    reviews: "Smooth and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Blanton's Original Single Barrel Bourbon",
    price: 69.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/blantons/blantons-original-single-barrel-whiskey.jpg?alt=1&w=617&h=1024&b=0xFFFFFF&q=100",
    description:
      "Rich and complex, with a balance of citrus, oak, and sweet vanilla.",
    category: "Single Barrel",
    abv: 46.5,
    size: "750ml",
    brand: "Blanton's",
    rating: 4.8,
    reviews: "Exceptional flavor, perfect for sipping neat.",
    origin: "Kentucky, USA",
    pairing: "Dark chocolate, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Buffalo Trace Bourbon",
    price: 29.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/buffalo-trace/buffalo-trace-whiskey.jpg?alt=1&w=496&h=1024&b=0xFFFFFF&q=100",
    description:
      "An aromatic, versatile bourbon known for its deep amber color and complex flavor profile.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Buffalo Trace",
    rating: 4.7,
    reviews: "Great value, smooth with a hint of spice.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Woodford Reserve Bourbon",
    price: 34.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/woodford-reserve/woodford-reserve-kentucky-bourbon-whiskey.jpg?alt=1&w=639&h=1024&b=0xFFFFFF&q=100",
    description:
      "Smooth and balanced with rich flavors of vanilla, honey, and a hint of spice.",
    category: "Small Batch",
    abv: 43.2,
    size: "750ml",
    brand: "Woodford Reserve",
    rating: 4.6,
    reviews: "Balanced and smooth, perfect for sipping or mixing.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, apple pie",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Eagle Rare 10 Year Old",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/eagle-rare/eagle-rare-10-year-old-whisky.jpg?alt=1&w=385&h=1024&b=0xFFFFFF&q=100",
    description:
      "A full-bodied bourbon offering tantalizing notes of toffee, orange peel, and herbs.",
    category: "Single Barrel",
    abv: 45,
    size: "750ml",
    brand: "Eagle Rare",
    rating: 4.9,
    reviews: "Complex and full-bodied, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Grilled lamb, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Elijah Craig Small Batch Bourbon",
    price: 39.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/elijah-craig/elijah-craig-small-batch-bourbon-whisky.jpg?alt=1&w=528&h=1024&b=0xFFFFFF&q=100",
    description:
      "Complex and smooth, with layers of vanilla, caramel, and nutmeg.",
    category: "Small Batch",
    abv: 47,
    size: "750ml",
    brand: "Elijah Craig",
    rating: 4.7,
    reviews: "Rich and spicy, great for neat or on the rocks.",
    origin: "Kentucky, USA",
    pairing: "Spicy sausage, aged cheese",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Four Roses Single Barrel Bourbon",
    price: 49.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/four-roses-single-barrel-bourbon-100-proof-whiskey.jpg?alt=1&w=488&h=1024&b=0xFFFFFF&q=100",
    description:
      "Delicate and fruity, offering distinct flavors of pear, apple, and honey.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Four Roses",
    rating: 4.8,
    reviews: "Fruity and floral, excellent sipping bourbon.",
    origin: "Kentucky, USA",
    pairing: "Pork chops, fruit salad",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Maker's Mark Bourbon",
    price: 24.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/makers-mark-whiskey.jpg?alt=1&w=526&h=1024&b=0xFFFFFF&q=100",
    description:
      "Sweet and balanced with caramel, vanilla, and fruity essences.",
    category: "Wheated",
    abv: 45,
    size: "750ml",
    brand: "Maker's Mark",
    rating: 4.5,
    reviews: "Classic bourbon, sweet and smooth.",
    origin: "Kentucky, USA",
    pairing: "Desserts, cheese board",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Knob Creek 9 Year Old Bourbon",
    price: 39.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knob-creek/knob-creek-kentucky-straight-bourbon-whiskey.jpg?alt=1&w=593&h=1024&b=0xFFFFFF&q=100",
    description:
      "Robust vanilla and caramel notes with long, warm, and rich finish.",
    category: "Small Batch",
    abv: 50,
    size: "750ml",
    brand: "Knob Creek",
    rating: 4.7,
    reviews: "Strong and bold, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Wild Turkey 101 Bourbon",
    price: 22.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-81-proof-whiskey.jpg?alt=1&w=421&h=1024&b=0xFFFFFF&q=100",
    description:
      "High proof and full of bold flavors, noted for its deep character and smooth finish.",
    category: "High Proof",
    abv: 50.5,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.6,
    reviews: "Bold and spicy, great in cocktails.",
    origin: "Kentucky, USA",
    pairing: "BBQ ribs, spicy food",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Old Forester 1920 Prohibition Style Bourbon",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-1920-prohibition-style-whiskey.jpg?alt=1&w=461&h=1024&b=0xFFFFFF&q=100",
    description:
      "A rich burst of chocolate and black cherry with a smoky, spicy finish.",
    category: "Prohibition Style",
    abv: 57.5,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.9,
    reviews: "Rich and complex, a must-try.",
    origin: "Kentucky, USA",
    pairing: "Dark chocolate, strong cheese",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "1792 Small Batch Bourbon",
    price: 29.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/barton-1792/1792-small-batch-whiskey.jpg?alt=1&w=640&h=1024&b=0xFFFFFF&q=100",
    description: "Spicy and sweet with notes of vanilla, toffee, and pepper.",
    category: "Small Batch",
    abv: 46.85,
    size: "750ml",
    brand: "1792",
    rating: 4.6,
    reviews: "Balanced and smooth, great value.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, roasted nuts",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Henry McKenna 10 Year Old Single Barrel Bourbon",
    price: 49.99,
    quantity: 5,
    imageUrl:
      "https://www.missionliquor.com/cdn/shop/files/Henry-McKenna-Single-Barrel.jpg?v=1691780984&width=1024",
    description:
      "Aged to perfection to produce tastes of vanilla, caramel, and seasoned oak.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Henry McKenna",
    rating: 4.8,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Basil Hayden's Bourbon",
    price: 39.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/basil-haydens/basil-haydens-bourbon-whiskey.jpg?alt=1&w=430&h=1024&b=0xFFFFFF&q=100",
    description:
      "Light-bodied with hints of spice and tea, an ideal choice for bourbon cocktails.",
    category: "Small Batch",
    abv: 40,
    size: "750ml",
    brand: "Basil Hayden's",
    rating: 4.5,
    reviews: "Light and smooth, great for mixing.",
    origin: "Kentucky, USA",
    pairing: "Light appetizers, seafood",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Angel's Envy Bourbon",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/angels-envy/angels-envy-whiskey.jpg?alt=1&w=542&h=1024&b=0xFFFFFF&q=100",
    description:
      "Finished in port wine barrels, offering unique flavors of wine and ripe fruit.",
    category: "Finished",
    abv: 43.3,
    size: "750ml",
    brand: "Angel's Envy",
    rating: 4.8,
    reviews: "Unique and smooth, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Booker's Bourbon",
    price: 89.99,
    quantity: 4,
    imageUrl:
      "https://www.thebarreltap.com/cdn/shop/files/booker-s-bourbon-batch-2018-04-kitchen-table-the-barrel-tap-www-thebarreltap-com-1_ef85b815-6da6-4576-8a96-0a06176cb437.jpg?v=1691179941&width=1800",
    description:
      "Unfiltered and uncut, this bourbon offers an intense flavor and remarkable complexity.",
    category: "Small Batch",
    abv: 62.5,
    size: "750ml",
    brand: "Booker's",
    rating: 4.9,
    reviews: "Bold and intense, for true bourbon lovers.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "George T. Stagg Bourbon",
    price: 249.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/george-t-stagg-bourbon/george-t-stagg-bourbon-2015-release.jpg?alt=1&w=359&h=1024&b=0xFFFFFF&q=100",
    description:
      "An unapologetically strong bourbon, known for its rich, sweet, chocolatey undernotes.",
    category: "High Proof",
    abv: 64.2,
    size: "750ml",
    brand: "George T. Stagg",
    rating: 4.9,
    reviews: "Powerful and complex, a must-try.",
    origin: "Kentucky, USA",
    pairing: "Dark chocolate, cigars",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Pappy Van Winkle's Family Reserve 15 Year Old",
    price: 999.99,
    quantity: 1,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pappy-van-winkles-family-reserve-bourbon-15-year-old-whiskey.jpg?alt=1&w=378&h=1024&b=0xFFFFFF&q=100",
    description:
      "Highly sought after for its dark, intensely flavored, deeply complex profile.",
    category: "Small Batch",
    abv: 53.5,
    size: "750ml",
    brand: "Pappy Van Winkle",
    rating: 5.0,
    reviews: "Unmatched complexity, truly exceptional.",
    origin: "Kentucky, USA",
    pairing: "Fine dining, special occasions",
    availability: "Out of Stock",
  },
  {
    id: 19,
    name: "Jefferson's Ocean Aged at Sea Bourbon",
    price: 79.99,
    quantity: 7,
    imageUrl:
      "https://d3omj40jjfp5tk.cloudfront.net/products/5e8cf76f32b79e35eb9da853/large.png",
    description:
      "Aged at sea, this unique bourbon is influenced by the sea climate, offering saline and caramel notes.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Jefferson's",
    rating: 4.7,
    reviews: "Unique flavor profile, very smooth.",
    origin: "Kentucky, USA",
    pairing: "Seafood, light appetizers",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "W.L. Weller Special Reserve Bourbon",
    price: 29.99,
    quantity: 10,
    imageUrl:
      "https://cdn11.bigcommerce.com/s-u9ww3di/images/stencil/1280x1280/products/8003/11442/weller_special_reserve_wheated_bourbon___97474.1535263434.png?c=2?imbypass=on",
    description:
      "A smooth, mild, wheated bourbon that serves as a perfect introduction to the world of premium bourbons.",
    category: "Wheated",
    abv: 45,
    size: "750ml",
    brand: "W.L. Weller",
    rating: 4.6,
    reviews: "Smooth and approachable, great value.",
    origin: "Kentucky, USA",
    pairing: "Light snacks, mild cheeses",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Evan Williams Black Label Bourbon",
    price: 17.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/evan-williams/evan-williams-white-label.jpg?alt=1&w=450&h=1024&b=0xFFFFFF&q=100",
    description:
      "Known for its approachable profile and excellent value, offering hints of nut, chocolate, and vanilla.",
    category: "Small Batch",
    abv: 43,
    size: "750ml",
    brand: "Evan Williams",
    rating: 4.5,
    reviews: "Great value, easy drinking.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, roasted nuts",
    availability: "In Stock",
  },

  {
    id: 22,
    name: "Old Grand-Dad 114 Bourbon",
    price: 29.99,
    quantity: 8,
    imageUrl:
      "https://www.totalwine.com/dynamic/x1000,sq/media/sys_master/twmmedia/hc1/h47/12343407214622.png",
    description:
      "A high-rye bourbon with a spicy kick, balanced by underlying notes of vanilla and oak.",
    category: "High Rye",
    abv: 57,
    size: "750ml",
    brand: "Old Grand-Dad",
    rating: 4.5,
    reviews: "Spicy and robust, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Rebel Yell 10 Year Old Single Barrel Bourbon",
    price: 59.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/rebell-yell/rebel-yell-10-year-old-single-barrel-whiskey.jpg?alt=1&w=700&h=1013&b=0xFFFFFF&q=100",
    description:
      "Single barrel that offers a smooth, buttery profile with a spicy, warm finish.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Rebel Yell",
    rating: 4.6,
    reviews: "Smooth and buttery, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roasted nuts, caramel desserts",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Wild Turkey Rare Breed Bourbon",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-rare-breed-bourbon-58-4-percent-whiskey.jpg?alt=1&w=700&h=926&b=0xFFFFFF&q=100",
    description:
      "A barrel-proof bourbon that provides rich, deep flavors of vanilla, oak, and pepper without dilution.",
    category: "Barrel Proof",
    abv: 58.4,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.7,
    reviews: "Rich and full-bodied, great for sipping neat.",
    origin: "Kentucky, USA",
    pairing: "Steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Jim Beam Double Oak",
    price: 34.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jim-beam/jim-beam-double-oak-whiskey.jpg?alt=1&w=700&h=926&b=0xFFFFFF&q=100",
    description:
      "Twice-barreled for extra richness and depth, with smooth caramel and toasty oak flavors.",
    category: "Double Oak",
    abv: 43,
    size: "750ml",
    brand: "Jim Beam",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping or mixing.",
    origin: "Kentucky, USA",
    pairing: "BBQ, grilled vegetables",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Old Forester 86 Proof Bourbon",
    price: 24.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-86-proof-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth and versatile bourbon with a rich flavor profile.",
    category: "Small Batch",
    abv: 43,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.5,
    reviews: "Versatile and smooth, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled chicken, roasted nuts",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Buffalo Trace White Dog Mash #1",
    price: 21.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/buffalo-trace/buffalo-trace-white-dog-mash-1-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Unaged and straight from the still, offering a raw and authentic bourbon experience.",
    category: "White Dog",
    abv: 62.5,
    size: "375ml",
    brand: "Buffalo Trace",
    rating: 4.3,
    reviews: "Raw and unaged, unique bourbon experience.",
    origin: "Kentucky, USA",
    pairing: "Smoked meats, BBQ",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "High West American Prairie Bourbon",
    price: 39.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/high-west/high-west-american-prairie-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A blend of straight bourbons with a rich and smooth profile.",
    category: "Blend",
    abv: 46,
    size: "750ml",
    brand: "High West",
    rating: 4.6,
    reviews: "Rich and smooth, perfect for any occasion.",
    origin: "Utah, USA",
    pairing: "Grilled steak, aged cheese",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Michters US*1 Bourbon",
    price: 49.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/michters/michters-us-1-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced bourbon with notes of caramel, vanilla, and fruit.",
    category: "Small Batch",
    abv: 45.7,
    size: "750ml",
    brand: "Michters",
    rating: 4.7,
    reviews: "Well-balanced and smooth, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, caramel desserts",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Four Roses Small Batch Bourbon",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/four-roses/four-roses-small-batch-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A blend of four original bourbon recipes, offering a mellow and rich flavor.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Four Roses",
    rating: 4.6,
    reviews: "Mellow and rich, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy foods",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Larceny Small Batch Bourbon",
    price: 26.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/larceny/larceny-small-batch-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A wheated bourbon with a smooth and slightly sweet profile.",
    category: "Small Batch",
    abv: 46,
    size: "750ml",
    brand: "Larceny",
    rating: 4.5,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Pork chops, apple pie",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "1792 Full Proof Bourbon",
    price: 59.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/1792/1792-full-proof-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Bottled at its original proof, offering a bold and robust flavor.",
    category: "Full Proof",
    abv: 62.5,
    size: "750ml",
    brand: "1792",
    rating: 4.8,
    reviews: "Bold and robust, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Old Elk Straight Bourbon",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-elk/old-elk-straight-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth and rich bourbon with notes of vanilla and caramel.",
    category: "Small Batch",
    abv: 44,
    size: "750ml",
    brand: "Old Elk",
    rating: 4.6,
    reviews: "Smooth and rich, great for any occasion.",
    origin: "Colorado, USA",
    pairing: "Roasted meats, desserts",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Baker's 7 Year Old Bourbon",
    price: 59.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bakers/bakers-7-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 7 years, offering a deep and complex flavor.",
    category: "Aged",
    abv: 53.5,
    size: "750ml",
    brand: "Baker's",
    rating: 4.8,
    reviews: "Deep and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, strong cheese",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "E.H. Taylor Small Batch Bourbon",
    price: 59.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/eh-taylor/eh-taylor-small-batch-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and complex bourbon with notes of caramel and spice.",
    category: "Small Batch",
    abv: 50,
    size: "750ml",
    brand: "E.H. Taylor",
    rating: 4.8,
    reviews: "Rich and complex, a must-try.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Fighting Cock Bourbon",
    price: 19.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/fighting-cock/fighting-cock-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof bourbon with a bold and spicy profile.",
    category: "High Proof",
    abv: 51.5,
    size: "750ml",
    brand: "Fighting Cock",
    rating: 4.4,
    reviews: "Bold and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Spicy foods, BBQ",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Willett Pot Still Reserve Bourbon",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/willett/willett-pot-still-reserve-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A unique bourbon with a smooth and rich flavor profile.",
    category: "Small Batch",
    abv: 47,
    size: "750ml",
    brand: "Willett",
    rating: 4.7,
    reviews: "Smooth and rich, unique flavor profile.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Kentucky Owl Confiscated Bourbon",
    price: 124.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kentucky-owl/kentucky-owl-confiscated-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-end bourbon with a rich and complex flavor profile.",
    category: "Small Batch",
    abv: 48.2,
    size: "750ml",
    brand: "Kentucky Owl",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Noah's Mill Bourbon",
    price: 59.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/noahs-mill/noahs-mill-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small-batch bourbon with a rich and full-bodied flavor.",
    category: "Small Batch",
    abv: 57.15,
    size: "750ml",
    brand: "Noah's Mill",
    rating: 4.8,
    reviews: "Full-bodied and rich, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Russell's Reserve 10 Year Old Bourbon",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/russells-reserve/russells-reserve-10-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 10 years, offering a smooth and rich flavor profile.",
    category: "Aged",
    abv: 45,
    size: "750ml",
    brand: "Russell's Reserve",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Old Fitzgerald Bottled in Bond 9 Year Old Bourbon",
    price: 89.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-fitzgerald/old-fitzgerald-bottled-in-bond-9-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 9 years and bottled in bond, offering a rich and complex flavor.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "Old Fitzgerald",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Elmer T. Lee Single Barrel Bourbon",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/elmer-t-lee/elmer-t-lee-single-barrel-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A single barrel bourbon with a smooth and rich flavor profile.",
    category: "Single Barrel",
    abv: 45,
    size: "750ml",
    brand: "Elmer T. Lee",
    rating: 4.8,
    reviews: "Smooth and rich, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Stagg Jr. Bourbon",
    price: 79.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/stagg-jr/stagg-jr-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof bourbon with a bold and rich flavor profile.",
    category: "High Proof",
    abv: 64.2,
    size: "750ml",
    brand: "Stagg Jr.",
    rating: 4.8,
    reviews: "Bold and rich, great for sipping neat.",
    origin: "Kentucky, USA",
    pairing: "Steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Jefferson's Reserve Very Old Bourbon",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jeffersons/jeffersons-reserve-very-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged and blended to perfection, offering a smooth and complex flavor profile.",
    category: "Small Batch",
    abv: 45.1,
    size: "750ml",
    brand: "Jefferson's",
    rating: 4.7,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Heaven Hill Bottled in Bond 7 Year Old Bourbon",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/heaven-hill/heaven-hill-bottled-in-bond-7-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 7 years and bottled in bond, offering a rich and complex flavor profile.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "Heaven Hill",
    rating: 4.8,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Calumet Farm 12 Year Old Bourbon",
    price: 99.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/calumet-farm/calumet-farm-12-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 12 years, offering a deep and complex flavor profile.",
    category: "Aged",
    abv: 50,
    size: "750ml",
    brand: "Calumet Farm",
    rating: 4.9,
    reviews: "Deep and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Bourbon Barrel Bourbon",
    price: 39.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bourbon-barrel/bourbon-barrel-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small-batch bourbon aged to perfection in bourbon barrels.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Bourbon Barrel",
    rating: 4.6,
    reviews: "Smooth and rich, great for any occasion.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Blood Oath Pact No. 6 Bourbon",
    price: 119.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/blood-oath/blood-oath-pact-no-6-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique blend of bourbons, offering a rich and complex flavor profile.",
    category: "Blend",
    abv: 49.3,
    size: "750ml",
    brand: "Blood Oath",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Widow Jane 10 Year Old Bourbon",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/widow-jane/widow-jane-10-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 10 years, offering a deep and complex flavor profile.",
    category: "Aged",
    abv: 45.5,
    size: "750ml",
    brand: "Widow Jane",
    rating: 4.8,
    reviews: "Deep and complex, perfect for special occasions.",
    origin: "New York, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Bourbon 30 Spirits Single Barrel Bourbon",
    price: 109.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bourbon-30-spirits/bourbon-30-spirits-single-barrel-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A single barrel bourbon with a rich and full-bodied flavor profile.",
    category: "Single Barrel",
    abv: 54.2,
    size: "750ml",
    brand: "Bourbon 30 Spirits",
    rating: 4.8,
    reviews: "Rich and full-bodied, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Bulleit Bourbon Batch 73",
    price: 28.99,
    quantity: 13,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bulleit/bulleit-bourbon-whiskey.jpg?alt=1&w=511&h=1024&b=0xFFFFFF&q=100",
    description: "A bold, spicy rye backbone with a smooth, clean finish.",
    category: "Rye",
    abv: 45,
    size: "750ml",
    brand: "Bulleit",
    rating: 4.5,
    reviews: "Smooth and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Blanton's Original Single Barrel Bourbon Batch 82",
    price: 72.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/blantons/blantons-original-single-barrel-whiskey.jpg?alt=1&w=617&h=1024&b=0xFFFFFF&q=100",
    description:
      "Rich and complex, with a balance of citrus, oak, and sweet vanilla.",
    category: "Single Barrel",
    abv: 46.5,
    size: "750ml",
    brand: "Blanton's",
    rating: 4.8,
    reviews: "Exceptional flavor, perfect for sipping neat.",
    origin: "Kentucky, USA",
    pairing: "Dark chocolate, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Buffalo Trace Bourbon Batch 91",
    price: 28.99,
    quantity: 13,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/buffalo-trace/buffalo-trace-whiskey.jpg?alt=1&w=496&h=1024&b=0xFFFFFF&q=100",
    description:
      "An aromatic, versatile bourbon known for its deep amber color and complex flavor profile.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Buffalo Trace",
    rating: 4.7,
    reviews: "Great value, smooth with a hint of spice.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Woodford Reserve Bourbon Batch 86",
    price: 35.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/woodford-reserve/woodford-reserve-kentucky-bourbon-whiskey.jpg?alt=1&w=639&h=1024&b=0xFFFFFF&q=100",
    description:
      "Smooth and balanced with rich flavors of vanilla, honey, and a hint of spice.",
    category: "Small Batch",
    abv: 43.2,
    size: "750ml",
    brand: "Woodford Reserve",
    rating: 4.6,
    reviews: "Balanced and smooth, perfect for sipping or mixing.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, apple pie",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Eagle Rare 10 Year Old Batch 74",
    price: 48.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/eagle-rare/eagle-rare-10-year-old-whisky.jpg?alt=1&w=385&h=1024&b=0xFFFFFF&q=100",
    description:
      "A full-bodied bourbon offering tantalizing notes of toffee, orange peel, and herbs.",
    category: "Single Barrel",
    abv: 45,
    size: "750ml",
    brand: "Eagle Rare",
    rating: 4.9,
    reviews: "Complex and full-bodied, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Grilled lamb, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Elijah Craig Small Batch Bourbon Batch 92",
    price: 38.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/elijah-craig/elijah-craig-small-batch-bourbon-whisky.jpg?alt=1&w=528&h=1024&b=0xFFFFFF&q=100",
    description:
      "Complex and smooth, with layers of vanilla, caramel, and nutmeg.",
    category: "Small Batch",
    abv: 47,
    size: "750ml",
    brand: "Elijah Craig",
    rating: 4.7,
    reviews: "Rich and spicy, great for neat or on the rocks.",
    origin: "Kentucky, USA",
    pairing: "Spicy sausage, aged cheese",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Four Roses Single Barrel Bourbon Batch 83",
    price: 48.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/four-roses-single-barrel-bourbon-100-proof-whiskey.jpg?alt=1&w=488&h=1024&b=0xFFFFFF&q=100",
    description:
      "Delicate and fruity, offering distinct flavors of pear, apple, and honey.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Four Roses",
    rating: 4.8,
    reviews: "Fruity and floral, excellent sipping bourbon.",
    origin: "Kentucky, USA",
    pairing: "Pork chops, fruit salad",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Maker's Mark Bourbon Batch 84",
    price: 23.99,
    quantity: 19,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/makers-mark-whiskey.jpg?alt=1&w=526&h=1024&b=0xFFFFFF&q=100",
    description:
      "Sweet and balanced with caramel, vanilla, and fruity essences.",
    category: "Wheated",
    abv: 45,
    size: "750ml",
    brand: "Maker's Mark",
    rating: 4.5,
    reviews: "Classic bourbon, sweet and smooth.",
    origin: "Kentucky, USA",
    pairing: "Desserts, cheese board",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Knob Creek 9 Year Old Bourbon Batch 85",
    price: 38.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knob-creek/knob-creek-kentucky-straight-bourbon-whiskey.jpg?alt=1&w=593&h=1024&b=0xFFFFFF&q=100",
    description:
      "Robust vanilla and caramel notes with long, warm, and rich finish.",
    category: "Small Batch",
    abv: 50,
    size: "750ml",
    brand: "Knob Creek",
    rating: 4.7,
    reviews: "Strong and bold, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Wild Turkey 101 Bourbon Batch 87",
    price: 21.99,
    quantity: 17,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-81-proof-whiskey.jpg?alt=1&w=421&h=1024&b=0xFFFFFF&q=100",
    description:
      "High proof and full of bold flavors, noted for its deep character and smooth finish.",
    category: "High Proof",
    abv: 50.5,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.6,
    reviews: "Bold and spicy, great in cocktails.",
    origin: "Kentucky, USA",
    pairing: "BBQ ribs, spicy food",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Old Forester 1920 Prohibition Style Bourbon Batch 88",
    price: 58.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-1920-prohibition-style-whiskey.jpg?alt=1&w=461&h=1024&b=0xFFFFFF&q=100",
    description:
      "A rich burst of chocolate and black cherry with a smoky, spicy finish.",
    category: "Prohibition Style",
    abv: 57.5,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.9,
    reviews: "Rich and complex, a must-try.",
    origin: "Kentucky, USA",
    pairing: "Dark chocolate, strong cheese",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "1792 Small Batch Bourbon Batch 89",
    price: 28.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/barton-1792/1792-small-batch-whiskey.jpg?alt=1&w=640&h=1024&b=0xFFFFFF&q=100",
    description: "Spicy and sweet with notes of vanilla, toffee, and pepper.",
    category: "Small Batch",
    abv: 46.85,
    size: "750ml",
    brand: "1792",
    rating: 4.6,
    reviews: "Balanced and smooth, great value.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, roasted nuts",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Henry McKenna 10 Year Old Single Barrel Bourbon Batch 90",
    price: 48.99,
    quantity: 4,
    imageUrl:
      "https://www.missionliquor.com/cdn/shop/files/Henry-McKenna-Single-Barrel.jpg?v=1691780984&width=1024",
    description:
      "Aged to perfection to produce tastes of vanilla, caramel, and seasoned oak.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Henry McKenna",
    rating: 4.8,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Basil Hayden's Bourbon Batch 75",
    price: 38.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/basil-haydens/basil-haydens-bourbon-whiskey.jpg?alt=1&w=430&h=1024&b=0xFFFFFF&q=100",
    description:
      "Light-bodied with hints of spice and tea, an ideal choice for bourbon cocktails.",
    category: "Small Batch",
    abv: 40,
    size: "750ml",
    brand: "Basil Hayden's",
    rating: 4.5,
    reviews: "Light and smooth, great for mixing.",
    origin: "Kentucky, USA",
    pairing: "Light appetizers, seafood",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Angel's Envy Bourbon Batch 79",
    price: 48.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/angels-envy/angels-envy-whiskey.jpg?alt=1&w=542&h=1024&b=0xFFFFFF&q=100",
    description:
      "Finished in port wine barrels, offering unique flavors of wine and ripe fruit.",
    category: "Finished",
    abv: 43.3,
    size: "750ml",
    brand: "Angel's Envy",
    rating: 4.8,
    reviews: "Unique and smooth, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Booker's Bourbon Batch 81",
    price: 88.99,
    quantity: 3,
    imageUrl:
      "https://www.thebarreltap.com/cdn/shop/files/booker-s-bourbon-batch-2018-04-kitchen-table-the-barrel-tap-www-thebarreltap-com-1_ef85b815-6da6-4576-8a96-0a06176cb437.jpg?v=1691179941&width=1800",
    description:
      "Unfiltered and uncut, this bourbon offers an intense flavor and remarkable complexity.",
    category: "Small Batch",
    abv: 62.5,
    size: "750ml",
    brand: "Booker's",
    rating: 4.9,
    reviews: "Bold and intense, for true bourbon lovers.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "George T. Stagg Bourbon Batch 80",
    price: 248.99,
    quantity: 2,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/george-t-stagg-bourbon/george-t-stagg-bourbon-2015-release.jpg?alt=1&w=359&h=1024&b=0xFFFFFF&q=100",
    description:
      "An unapologetically strong bourbon, known for its rich, sweet, chocolatey undernotes.",
    category: "High Proof",
    abv: 64.2,
    size: "750ml",
    brand: "George T. Stagg",
    rating: 4.9,
    reviews: "Powerful and complex, a must-try.",
    origin: "Kentucky, USA",
    pairing: "Dark chocolate, cigars",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Pappy Van Winkle's Family Reserve 15 Year Old Batch 77",
    price: 998.99,
    quantity: 1,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pappy-van-winkles-family-reserve-bourbon-15-year-old-whiskey.jpg?alt=1&w=378&h=1024&b=0xFFFFFF&q=100",
    description:
      "Highly sought after for its dark, intensely flavored, deeply complex profile.",
    category: "Small Batch",
    abv: 53.5,
    size: "750ml",
    brand: "Pappy Van Winkle",
    rating: 5.0,
    reviews: "Unmatched complexity, truly exceptional.",
    origin: "Kentucky, USA",
    pairing: "Fine dining, special occasions",
    availability: "Out of Stock",
  },
  {
    id: 69,
    name: "Jefferson's Ocean Aged at Sea Bourbon Batch 76",
    price: 78.99,
    quantity: 6,
    imageUrl:
      "https://d3omj40jjfp5tk.cloudfront.net/products/5e8cf76f32b79e35eb9da853/large.png",
    description:
      "Aged at sea, this unique bourbon is influenced by the sea climate, offering saline and caramel notes.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Jefferson's",
    rating: 4.7,
    reviews: "Unique flavor profile, very smooth.",
    origin: "Kentucky, USA",
    pairing: "Seafood, light appetizers",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "W.L. Weller Special Reserve Bourbon Batch 78",
    price: 28.99,
    quantity: 9,
    imageUrl:
      "https://cdn11.bigcommerce.com/s-u9ww3di/images/stencil/1280x1280/products/8003/11442/weller_special_reserve_wheated_bourbon___97474.1535263434.png?c=2?imbypass=on",
    description:
      "A smooth, mild, wheated bourbon that serves as a perfect introduction to the world of premium bourbons.",
    category: "Wheated",
    abv: 45,
    size: "750ml",
    brand: "W.L. Weller",
    rating: 4.6,
    reviews: "Smooth and approachable, great value.",
    origin: "Kentucky, USA",
    pairing: "Light snacks, mild cheeses",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Evan Williams Black Label Bourbon Batch 93",
    price: 16.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/evan-williams/evan-williams-white-label.jpg?alt=1&w=450&h=1024&b=0xFFFFFF&q=100",
    description:
      "Known for its approachable profile and excellent value, offering hints of nut, chocolate, and vanilla.",
    category: "Small Batch",
    abv: 43,
    size: "750ml",
    brand: "Evan Williams",
    rating: 4.5,
    reviews: "Great value, easy drinking.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, roasted nuts",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Old Grand-Dad 114 Bourbon Batch 94",
    price: 28.99,
    quantity: 7,
    imageUrl:
      "https://www.totalwine.com/dynamic/x1000,sq/media/sys_master/twmmedia/hc1/h47/12343407214622.png",
    description:
      "A high-rye bourbon with a spicy kick, balanced by underlying notes of vanilla and oak.",
    category: "High Rye",
    abv: 57,
    size: "750ml",
    brand: "Old Grand-Dad",
    rating: 4.5,
    reviews: "Spicy and robust, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Rebel Yell 10 Year Old Single Barrel Bourbon Batch 95",
    price: 58.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/rebell-yell/rebel-yell-10-year-old-single-barrel-whiskey.jpg?alt=1&w=700&h=1013&b=0xFFFFFF&q=100",
    description:
      "Single barrel that offers a smooth, buttery profile with a spicy, warm finish.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Rebel Yell",
    rating: 4.6,
    reviews: "Smooth and buttery, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roasted nuts, caramel desserts",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Wild Turkey Rare Breed Bourbon Batch 96",
    price: 48.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-rare-breed-bourbon-58-4-percent-whiskey.jpg?alt=1&w=700&h=926&b=0xFFFFFF&q=100",
    description:
      "A barrel-proof bourbon that provides rich, deep flavors of vanilla, oak, and pepper without dilution.",
    category: "Barrel Proof",
    abv: 58.4,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.7,
    reviews: "Rich and full-bodied, great for sipping neat.",
    origin: "Kentucky, USA",
    pairing: "Steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Jim Beam Double Oak Batch 97",
    price: 33.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jim-beam/jim-beam-double-oak-whiskey.jpg?alt=1&w=700&h=926&b=0xFFFFFF&q=100",
    description:
      "Twice-barreled for extra richness and depth, with smooth caramel and toasty oak flavors.",
    category: "Double Oak",
    abv: 43,
    size: "750ml",
    brand: "Jim Beam",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping or mixing.",
    origin: "Kentucky, USA",
    pairing: "BBQ, grilled vegetables",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Old Forester 86 Proof Bourbon Batch 98",
    price: 23.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-86-proof-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth and versatile bourbon with a rich flavor profile.",
    category: "Small Batch",
    abv: 43,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.5,
    reviews: "Versatile and smooth, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled chicken, roasted nuts",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Buffalo Trace White Dog Mash #1 Batch 99",
    price: 20.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/buffalo-trace/buffalo-trace-white-dog-mash-1-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Unaged and straight from the still, offering a raw and authentic bourbon experience.",
    category: "White Dog",
    abv: 62.5,
    size: "375ml",
    brand: "Buffalo Trace",
    rating: 4.3,
    reviews: "Raw and unaged, unique bourbon experience.",
    origin: "Kentucky, USA",
    pairing: "Smoked meats, BBQ",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "High West American Prairie Bourbon Batch 100",
    price: 38.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/high-west/high-west-american-prairie-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A blend of straight bourbons with a rich and smooth profile.",
    category: "Blend",
    abv: 46,
    size: "750ml",
    brand: "High West",
    rating: 4.6,
    reviews: "Rich and smooth, perfect for any occasion.",
    origin: "Utah, USA",
    pairing: "Grilled steak, aged cheese",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Michters US*1 Bourbon Batch 101",
    price: 48.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/michters/michters-us-1-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced bourbon with notes of caramel, vanilla, and fruit.",
    category: "Small Batch",
    abv: 45.7,
    size: "750ml",
    brand: "Michters",
    rating: 4.7,
    reviews: "Well-balanced and smooth, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, caramel desserts",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Four Roses Small Batch Bourbon Batch 102",
    price: 38.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/four-roses/four-roses-small-batch-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A blend of four original bourbon recipes, offering a mellow and rich flavor.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Four Roses",
    rating: 4.6,
    reviews: "Mellow and rich, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy foods",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Larceny Small Batch Bourbon Batch 103",
    price: 25.99,
    quantity: 13,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/larceny/larceny-small-batch-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A wheated bourbon with a smooth and slightly sweet profile.",
    category: "Small Batch",
    abv: 46,
    size: "750ml",
    brand: "Larceny",
    rating: 4.5,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Pork chops, apple pie",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "1792 Full Proof Bourbon Batch 104",
    price: 58.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/1792/1792-full-proof-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Bottled at its original proof, offering a bold and robust flavor.",
    category: "Full Proof",
    abv: 62.5,
    size: "750ml",
    brand: "1792",
    rating: 4.8,
    reviews: "Bold and robust, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Old Elk Straight Bourbon Batch 105",
    price: 48.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-elk/old-elk-straight-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth and rich bourbon with notes of vanilla and caramel.",
    category: "Small Batch",
    abv: 44,
    size: "750ml",
    brand: "Old Elk",
    rating: 4.6,
    reviews: "Smooth and rich, great for any occasion.",
    origin: "Colorado, USA",
    pairing: "Roasted meats, desserts",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Baker's 7 Year Old Bourbon Batch 106",
    price: 58.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bakers/bakers-7-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 7 years, offering a deep and complex flavor.",
    category: "Aged",
    abv: 53.5,
    size: "750ml",
    brand: "Baker's",
    rating: 4.8,
    reviews: "Deep and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, strong cheese",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "E.H. Taylor Small Batch Bourbon Batch 107",
    price: 58.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/eh-taylor/eh-taylor-small-batch-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and complex bourbon with notes of caramel and spice.",
    category: "Small Batch",
    abv: 50,
    size: "750ml",
    brand: "E.H. Taylor",
    rating: 4.8,
    reviews: "Rich and complex, a must-try.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Fighting Cock Bourbon Batch 108",
    price: 18.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/fighting-cock/fighting-cock-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof bourbon with a bold and spicy profile.",
    category: "High Proof",
    abv: 51.5,
    size: "750ml",
    brand: "Fighting Cock",
    rating: 4.4,
    reviews: "Bold and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Spicy foods, BBQ",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Willett Pot Still Reserve Bourbon Batch 109",
    price: 48.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/willett/willett-pot-still-reserve-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A unique bourbon with a smooth and rich flavor profile.",
    category: "Small Batch",
    abv: 47,
    size: "750ml",
    brand: "Willett",
    rating: 4.7,
    reviews: "Smooth and rich, unique flavor profile.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Kentucky Owl Confiscated Bourbon Batch 110",
    price: 123.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kentucky-owl/kentucky-owl-confiscated-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-end bourbon with a rich and complex flavor profile.",
    category: "Small Batch",
    abv: 48.2,
    size: "750ml",
    brand: "Kentucky Owl",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Noah's Mill Bourbon Batch 111",
    price: 58.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/noahs-mill/noahs-mill-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small-batch bourbon with a rich and full-bodied flavor.",
    category: "Small Batch",
    abv: 57.15,
    size: "750ml",
    brand: "Noah's Mill",
    rating: 4.8,
    reviews: "Full-bodied and rich, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Russell's Reserve 10 Year Old Bourbon Batch 112",
    price: 38.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/russells-reserve/russells-reserve-10-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 10 years, offering a smooth and rich flavor profile.",
    category: "Aged",
    abv: 45,
    size: "750ml",
    brand: "Russell's Reserve",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Old Fitzgerald Bottled in Bond 9 Year Old Bourbon Batch 113",
    price: 88.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-fitzgerald/old-fitzgerald-bottled-in-bond-9-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 9 years and bottled in bond, offering a rich and complex flavor.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "Old Fitzgerald",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Elmer T. Lee Single Barrel Bourbon Batch 114",
    price: 78.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/elmer-t-lee/elmer-t-lee-single-barrel-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A single barrel bourbon with a smooth and rich flavor profile.",
    category: "Single Barrel",
    abv: 45,
    size: "750ml",
    brand: "Elmer T. Lee",
    rating: 4.8,
    reviews: "Smooth and rich, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Stagg Jr. Bourbon Batch 115",
    price: 78.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/stagg-jr/stagg-jr-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof bourbon with a bold and rich flavor profile.",
    category: "High Proof",
    abv: 64.2,
    size: "750ml",
    brand: "Stagg Jr.",
    rating: 4.8,
    reviews: "Bold and rich, great for sipping neat.",
    origin: "Kentucky, USA",
    pairing: "Steak, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Jefferson's Reserve Very Old Bourbon Batch 116",
    price: 58.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jeffersons/jeffersons-reserve-very-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged and blended to perfection, offering a smooth and complex flavor profile.",
    category: "Small Batch",
    abv: 45.1,
    size: "750ml",
    brand: "Jefferson's",
    rating: 4.7,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Heaven Hill Bottled in Bond 7 Year Old Bourbon Batch 117",
    price: 38.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/heaven-hill/heaven-hill-bottled-in-bond-7-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 7 years and bottled in bond, offering a rich and complex flavor profile.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "Heaven Hill",
    rating: 4.8,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Calumet Farm 12 Year Old Bourbon Batch 118",
    price: 98.99,
    quantity: 2,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/calumet-farm/calumet-farm-12-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 12 years, offering a deep and complex flavor profile.",
    category: "Aged",
    abv: 50,
    size: "750ml",
    brand: "Calumet Farm",
    rating: 4.9,
    reviews: "Deep and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Bourbon Barrel Bourbon Batch 119",
    price: 38.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bourbon-barrel/bourbon-barrel-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small-batch bourbon aged to perfection in bourbon barrels.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Bourbon Barrel",
    rating: 4.6,
    reviews: "Smooth and rich, great for any occasion.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Blood Oath Pact No. 6 Bourbon Batch 120",
    price: 118.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/blood-oath/blood-oath-pact-no-6-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique blend of bourbons, offering a rich and complex flavor profile.",
    category: "Blend",
    abv: 49.3,
    size: "750ml",
    brand: "Blood Oath",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Steak, fine cheeses",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Widow Jane 10 Year Old Bourbon Batch 121",
    price: 78.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/widow-jane/widow-jane-10-year-old-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 10 years, offering a deep and complex flavor profile.",
    category: "Aged",
    abv: 45.5,
    size: "750ml",
    brand: "Widow Jane",
    rating: 4.8,
    reviews: "Deep and complex, perfect for special occasions.",
    origin: "New York, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Bourbon 30 Spirits Single Barrel Bourbon Batch 122",
    price: 108.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bourbon-30-spirits/bourbon-30-spirits-single-barrel-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A single barrel bourbon with a rich and full-bodied flavor profile.",
    category: "Single Barrel",
    abv: 54.2,
    size: "750ml",
    brand: "Bourbon 30 Spirits",
    rating: 4.8,
    reviews: "Rich and full-bodied, excellent for sipping.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
];
