const canadianWhiskeys = [
  {
    id: 1,
    name: "Crown Royal Deluxe",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-deluxe-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Forty Creek Double Barrel Reserve",
    price: 54.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/forty-creek/forty-creek-double-barrel-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, toffee, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Forty Creek",
    rating: 4.8,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Canadian Club 100% Rye",
    price: 24.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-club/canadian-club-100-percent-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Spicy and smooth with notes of rye, vanilla, and a hint of oak.",
    category: "Rye",
    abv: 40,
    size: "750ml",
    brand: "Canadian Club",
    rating: 4.7,
    reviews: "Spicy and smooth, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, BBQ",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Lot No. 40",
    price: 39.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lot-no-40/lot-no-40-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and spicy with notes of rye, caramel, and a hint of oak.",
    category: "Rye",
    abv: 43,
    size: "750ml",
    brand: "Lot No. 40",
    rating: 4.8,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "JP Wiser's 18 Year Old",
    price: 59.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jp-wisers/jp-wisers-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and elegant with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "JP Wiser's",
    rating: 4.9,
    reviews: "Smooth and elegant, great for special occasions.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Alberta Premium Cask Strength Rye",
    price: 69.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/alberta-premium/alberta-premium-cask-strength-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Bold and spicy with notes of rye, caramel, and a hint of oak.",
    category: "Rye",
    abv: 65.1,
    size: "750ml",
    brand: "Alberta Premium",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Pike Creek 10 Year Old Rum Barrel Finish",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pike-creek/pike-creek-10-year-old-rum-barrel-finish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, toffee, and a hint of rum.",
    category: "Blended",
    abv: 42,
    size: "750ml",
    brand: "Pike Creek",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Collingwood Canadian Whisky",
    price: 29.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/collingwood/collingwood-canadian-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Collingwood",
    rating: 4.6,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Shelter Point Single Malt",
    price: 59.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/shelter-point/shelter-point-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Shelter Point",
    rating: 4.8,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Caribou Crossing Single Barrel",
    price: 59.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/caribou-crossing/caribou-crossing-single-barrel-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of fruit.",
    category: "Single Barrel",
    abv: 40,
    size: "750ml",
    brand: "Caribou Crossing",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Canadian Mist",
    price: 19.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-mist/canadian-mist-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Canadian Mist",
    rating: 4.5,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Bearface Triple Oak",
    price: 44.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bearface/bearface-triple-oak-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 42.5,
    size: "750ml",
    brand: "Bearface",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Gooderham & Worts Four Grain",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/gooderham-worts/gooderham-worts-four-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 44.4,
    size: "750ml",
    brand: "Gooderham & Worts",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Pendleton Midnight",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pendleton/pendleton-midnight-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 45,
    size: "750ml",
    brand: "Pendleton",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Pine Creek Premium",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pine-creek/pine-creek-premium-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Pine Creek",
    rating: 4.6,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Forty Creek Barrel Select",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/forty-creek/forty-creek-barrel-select-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Forty Creek",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Crown Royal Northern Harvest Rye",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-northern-harvest-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and spicy with notes of rye, vanilla, and a hint of oak.",
    category: "Rye",
    abv: 45,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.8,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, BBQ",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "JP Wiser's Triple Barrel",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jp-wisers/jp-wisers-triple-barrel-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "JP Wiser's",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Crown Royal Apple",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-apple-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Flavored",
    abv: 35,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.6,
    reviews: "Smooth and fruity, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Canadian Club Classic 12 Year Old",
    price: 24.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-club/canadian-club-classic-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Canadian Club",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Bearface One Eleven Series",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bearface/bearface-one-eleven-series-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 49.5,
    size: "750ml",
    brand: "Bearface",
    rating: 4.7,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Gibson's Finest Bold",
    price: 29.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/gibsons-finest/gibsons-finest-bold-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and bold with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 43,
    size: "750ml",
    brand: "Gibson's Finest",
    rating: 4.6,
    reviews: "Smooth and bold, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Revel Stoke Spiced",
    price: 19.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/revel-stoke/revel-stoke-spiced-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and spiced with notes of vanilla, cinnamon, and a hint of oak.",
    category: "Flavored",
    abv: 35,
    size: "750ml",
    brand: "Revel Stoke",
    rating: 4.5,
    reviews: "Smooth and spiced, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Forty Creek Copper Pot",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/forty-creek/forty-creek-copper-pot-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 43,
    size: "750ml",
    brand: "Forty Creek",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Dillon's Rye Whisky",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dillons/dillons-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and spicy with notes of rye, vanilla, and a hint of oak.",
    category: "Rye",
    abv: 43,
    size: "750ml",
    brand: "Dillon's",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, BBQ",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Gibson's Finest 12 Year Old",
    price: 29.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/gibsons-finest/gibsons-finest-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Gibson's Finest",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Alberta Premium Rye",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/alberta-premium/alberta-premium-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Bold and spicy with notes of rye, caramel, and a hint of oak.",
    category: "Rye",
    abv: 40,
    size: "750ml",
    brand: "Alberta Premium",
    rating: 4.7,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Crown Royal Black",
    price: 34.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-black-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 45,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Canadian Club 9 Year Old Reserve",
    price: 24.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-club/canadian-club-9-year-old-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Canadian Club",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Forty Creek Confederation Oak",
    price: 69.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/forty-creek/forty-creek-confederation-oak-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Forty Creek",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "JP Wiser's Triple Barrel Rye",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jp-wisers/jp-wisers-triple-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and spicy with notes of rye, vanilla, and a hint of oak.",
    category: "Rye",
    abv: 40,
    size: "750ml",
    brand: "JP Wiser's",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, BBQ",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Pendleton Canadian Whisky",
    price: 24.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pendleton/pendleton-canadian-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Pendleton",
    rating: 4.6,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Gooderham & Worts 11 Souls",
    price: 64.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/gooderham-worts/gooderham-worts-11-souls-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 44.4,
    size: "750ml",
    brand: "Gooderham & Worts",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Crown Royal Reserve",
    price: 49.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Canadian Mist Black Diamond",
    price: 24.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-mist/canadian-mist-black-diamond-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Canadian Mist",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Forty Creek Three Grain",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/forty-creek/forty-creek-three-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Forty Creek",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Bearface Elementally Aged",
    price: 54.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bearface/bearface-elementally-aged-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 42.5,
    size: "750ml",
    brand: "Bearface",
    rating: 4.7,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Gooderham & Worts Eleven Souls",
    price: 69.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/gooderham-worts/gooderham-worts-eleven-souls-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 44.4,
    size: "750ml",
    brand: "Gooderham & Worts",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Crown Royal XO",
    price: 49.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-xo-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Canadian Club 6 Year Old Sherry Cask",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-club/canadian-club-6-year-old-sherry-cask-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of sherry.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Canadian Club",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "JP Wiser's Legacy",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jp-wisers/jp-wisers-legacy-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 45,
    size: "750ml",
    brand: "JP Wiser's",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Alberta Springs 10 Year Old",
    price: 29.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/alberta-springs/alberta-springs-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Alberta Springs",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Crown Royal Reserve",
    price: 49.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Canadian Club 100% Rye",
    price: 24.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/canadian-club/canadian-club-100-percent-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Spicy and smooth with notes of rye, vanilla, and a hint of oak.",
    category: "Rye",
    abv: 40,
    size: "750ml",
    brand: "Canadian Club",
    rating: 4.7,
    reviews: "Spicy and smooth, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, BBQ",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Forty Creek Double Barrel Reserve",
    price: 54.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/forty-creek/forty-creek-double-barrel-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, toffee, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Forty Creek",
    rating: 4.8,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Bearface One Eleven Series",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bearface/bearface-one-eleven-series-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 49.5,
    size: "750ml",
    brand: "Bearface",
    rating: 4.7,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Alberta Premium Cask Strength Rye",
    price: 69.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/alberta-premium/alberta-premium-cask-strength-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Bold and spicy with notes of rye, caramel, and a hint of oak.",
    category: "Rye",
    abv: 65.1,
    size: "750ml",
    brand: "Alberta Premium",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Pike Creek 10 Year Old Rum Barrel Finish",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pike-creek/pike-creek-10-year-old-rum-barrel-finish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, toffee, and a hint of rum.",
    category: "Blended",
    abv: 42,
    size: "750ml",
    brand: "Pike Creek",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Lot No. 40",
    price: 39.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lot-no-40/lot-no-40-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and spicy with notes of rye, caramel, and a hint of oak.",
    category: "Rye",
    abv: 43,
    size: "750ml",
    brand: "Lot No. 40",
    rating: 4.8,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Canada",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Crown Royal Maple",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-maple-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of maple, vanilla, and a hint of spice.",
    category: "Flavored",
    abv: 40,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.6,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Canada",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
];

module.exports = canadianWhiskeys;
