const irishWhiskeys = [
  {
    id: 1,
    name: "Jameson Irish Whiskey",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-irish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and balanced with notes of vanilla, spices, and sweet sherry.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.7,
    reviews: "Smooth and easy to drink, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Redbreast 12 Year Old",
    price: 69.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 40,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.9,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Bushmills 10 Year Old",
    price: 49.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, vanilla, and a hint of fruit.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.8,
    reviews: "Smooth and well-balanced, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Green Spot",
    price: 59.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 40,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Powers Gold Label",
    price: 39.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-gold-label-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and spicy with notes of honey, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 43.2,
    size: "750ml",
    brand: "Powers",
    rating: 4.7,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Teeling Single Malt",
    price: 54.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Teeling",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Connemara Peated Single Malt",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/connemara/connemara-peated-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Heavily peated with notes of smoke, fruit, and a hint of vanilla.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Connemara",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Ireland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Kilbeggan Single Grain",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kilbeggan/kilbeggan-single-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of vanilla, caramel, and a hint of spice.",
    category: "Single Grain",
    abv: 43,
    size: "750ml",
    brand: "Kilbeggan",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "The Sexton Single Malt",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-sexton/the-sexton-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of sherry, dried fruits, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "The Sexton",
    rating: 4.7,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Tullamore D.E.W. 12 Year Old Special Reserve",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tullamore-dew/tullamore-dew-12-year-old-special-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of sherry, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Tullamore D.E.W.",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Midleton Very Rare",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/midleton/midleton-very-rare-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Midleton",
    rating: 4.9,
    reviews: "Smooth and luxurious, great for special occasions.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Powers John's Lane Release 12 Year Old",
    price: 69.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-johns-lane-release-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Green Spot Château Léoville Barton",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-leoville-barton-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Redbreast Lustau Edition",
    price: 79.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-lustau-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.8,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Teeling Small Batch",
    price: 39.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-small-batch-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 46,
    size: "750ml",
    brand: "Teeling",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Bushmills Black Bush",
    price: 34.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-black-bush-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of sherry, dried fruits, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.7,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "The Irishman Single Malt",
    price: 54.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-irishman/the-irishman-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "The Irishman",
    rating: 4.7,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Kilbeggan Traditional",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kilbeggan/kilbeggan-traditional-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Kilbeggan",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Dingle Single Malt",
    price: 64.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dingle/dingle-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46.5,
    size: "750ml",
    brand: "Dingle",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Glendalough 13 Year Old",
    price: 79.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glendalough/glendalough-13-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Glendalough",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Powers Three Swallow Release",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-three-swallow-release-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 43.2,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Jameson Black Barrel",
    price: 39.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-black-barrel-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and intense with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.7,
    reviews: "Rich and intense, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Knappogue Castle 12 Year Old",
    price: 54.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knappogue-castle/knappogue-castle-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Knappogue Castle",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Writer's Tears Copper Pot",
    price: 44.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/writers-tears/writers-tears-copper-pot-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Writer's Tears",
    rating: 4.7,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Redbreast 15 Year Old",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-15-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.9,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Bushmills 16 Year Old",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-16-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Jameson Caskmates Stout Edition",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-caskmates-stout-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of chocolate, coffee, and a hint of vanilla.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Teeling Small Batch",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-small-batch-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 46,
    size: "750ml",
    brand: "Teeling",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Midleton Barry Crockett Legacy",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/midleton/midleton-barry-crockett-legacy-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, honey, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Midleton",
    rating: 4.9,
    reviews: "Smooth and luxurious, great for special occasions.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Green Spot Château Montelena",
    price: 99.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-montelena-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "The Dead Rabbit Irish Whiskey",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-dead-rabbit/the-dead-rabbit-irish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 44,
    size: "750ml",
    brand: "The Dead Rabbit",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Bushmills Red Bush",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-red-bush-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "The Dubliner Irish Whiskey",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-dubliner/the-dubliner-irish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of honey, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "The Dubliner",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Powers Signature Release",
    price: 79.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-signature-release-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Redbreast 21 Year Old",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-21-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.9,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Jameson Gold Reserve",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-gold-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "The Irishman Cask Strength",
    price: 149.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-irishman/the-irishman-cask-strength-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Single Malt",
    abv: 54,
    size: "750ml",
    brand: "The Irishman",
    rating: 4.9,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Tullamore D.E.W. 14 Year Old Single Malt",
    price: 74.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tullamore-dew/tullamore-dew-14-year-old-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 41.3,
    size: "750ml",
    brand: "Tullamore D.E.W.",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Bushmills 21 Year Old",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-21-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.9,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Jameson 18 Year Old Limited Reserve",
    price: 149.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-18-year-old-limited-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.9,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Connemara 12 Year Old",
    price: 79.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/connemara/connemara-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Heavily peated with notes of smoke, fruit, and a hint of vanilla.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Connemara",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Ireland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Powers Gold Label Distiller's Cut",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-gold-label-distillers-cut-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and spicy with notes of honey, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 43.2,
    size: "750ml",
    brand: "Powers",
    rating: 4.7,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Green Spot Château Léoville Barton",
    price: 99.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-leoville-barton-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Redbreast Lustau Edition",
    price: 79.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-lustau-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.8,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Teeling Brabazon Bottling Series 3",
    price: 74.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-brabazon-bottling-series-3-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 49.5,
    size: "750ml",
    brand: "Teeling",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "The Sexton Single Malt",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-sexton/the-sexton-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of sherry, dried fruits, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "The Sexton",
    rating: 4.7,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Tullamore D.E.W. 12 Year Old Special Reserve",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tullamore-dew/tullamore-dew-12-year-old-special-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of sherry, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Tullamore D.E.W.",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Midleton Very Rare",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/midleton/midleton-very-rare-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Midleton",
    rating: 4.9,
    reviews: "Smooth and luxurious, great for special occasions.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Powers John's Lane Release 12 Year Old",
    price: 69.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-johns-lane-release-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Green Spot Château Léoville Barton",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-leoville-barton-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Redbreast Lustau Edition",
    price: 79.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-lustau-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.8,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Teeling Small Batch",
    price: 39.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-small-batch-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 46,
    size: "750ml",
    brand: "Teeling",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Bushmills Black Bush",
    price: 34.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-black-bush-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of sherry, dried fruits, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.7,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "The Irishman Single Malt",
    price: 54.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-irishman/the-irishman-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "The Irishman",
    rating: 4.7,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Kilbeggan Traditional",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kilbeggan/kilbeggan-traditional-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Kilbeggan",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Dingle Single Malt",
    price: 64.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dingle/dingle-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46.5,
    size: "750ml",
    brand: "Dingle",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Glendalough 13 Year Old",
    price: 79.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glendalough/glendalough-13-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Glendalough",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Powers Three Swallow Release",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-three-swallow-release-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 43.2,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Jameson Black Barrel",
    price: 39.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-black-barrel-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and intense with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.7,
    reviews: "Rich and intense, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Knappogue Castle 12 Year Old",
    price: 54.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knappogue-castle/knappogue-castle-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Knappogue Castle",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Writer's Tears Copper Pot",
    price: 44.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/writers-tears/writers-tears-copper-pot-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Writer's Tears",
    rating: 4.7,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Redbreast 15 Year Old",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-15-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.9,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Bushmills 16 Year Old",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-16-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Jameson Caskmates Stout Edition",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-caskmates-stout-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of chocolate, coffee, and a hint of vanilla.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Teeling Small Batch",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-small-batch-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 46,
    size: "750ml",
    brand: "Teeling",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Midleton Barry Crockett Legacy",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/midleton/midleton-barry-crockett-legacy-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, honey, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Midleton",
    rating: 4.9,
    reviews: "Smooth and luxurious, great for special occasions.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Green Spot Château Montelena",
    price: 99.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-montelena-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "The Dead Rabbit Irish Whiskey",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-dead-rabbit/the-dead-rabbit-irish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 44,
    size: "750ml",
    brand: "The Dead Rabbit",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Bushmills Red Bush",
    price: 29.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-red-bush-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "The Dubliner Irish Whiskey",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-dubliner/the-dubliner-irish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of honey, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "The Dubliner",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Powers Signature Release",
    price: 79.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-signature-release-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Redbreast 21 Year Old",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-21-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.9,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Jameson Gold Reserve",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-gold-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "The Irishman Cask Strength",
    price: 149.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-irishman/the-irishman-cask-strength-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Single Malt",
    abv: 54,
    size: "750ml",
    brand: "The Irishman",
    rating: 4.9,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Tullamore D.E.W. 14 Year Old Single Malt",
    price: 74.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tullamore-dew/tullamore-dew-14-year-old-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 41.3,
    size: "750ml",
    brand: "Tullamore D.E.W.",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Bushmills 21 Year Old",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-21-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.9,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Jameson 18 Year Old Limited Reserve",
    price: 149.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-18-year-old-limited-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.9,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Connemara 12 Year Old",
    price: 79.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/connemara/connemara-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Heavily peated with notes of smoke, fruit, and a hint of vanilla.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Connemara",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Ireland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Powers Gold Label Distiller's Cut",
    price: 34.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-gold-label-distillers-cut-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and spicy with notes of honey, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 43.2,
    size: "750ml",
    brand: "Powers",
    rating: 4.7,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Green Spot Château Léoville Barton",
    price: 99.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-leoville-barton-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Redbreast Lustau Edition",
    price: 79.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-lustau-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.8,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Teeling Brabazon Bottling Series 3",
    price: 74.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-brabazon-bottling-series-3-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 49.5,
    size: "750ml",
    brand: "Teeling",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "The Sexton Single Malt",
    price: 39.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-sexton/the-sexton-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of sherry, dried fruits, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "The Sexton",
    rating: 4.7,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Tullamore D.E.W. 12 Year Old Special Reserve",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tullamore-dew/tullamore-dew-12-year-old-special-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of sherry, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Tullamore D.E.W.",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Midleton Very Rare",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/midleton/midleton-very-rare-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Midleton",
    rating: 4.9,
    reviews: "Smooth and luxurious, great for special occasions.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Powers John's Lane Release 12 Year Old",
    price: 69.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-johns-lane-release-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Green Spot Château Léoville Barton",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/green-spot/green-spot-chateau-leoville-barton-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Green Spot",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Redbreast Lustau Edition",
    price: 79.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-lustau-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.8,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Teeling Small Batch",
    price: 39.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/teeling/teeling-small-batch-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 46,
    size: "750ml",
    brand: "Teeling",
    rating: 4.7,
    reviews: "Smooth and well-balanced, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Bushmills Black Bush",
    price: 34.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-black-bush-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of sherry, dried fruits, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.7,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "The Irishman Single Malt",
    price: 54.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/the-irishman/the-irishman-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "The Irishman",
    rating: 4.7,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Kilbeggan Traditional",
    price: 29.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kilbeggan/kilbeggan-traditional-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of vanilla, caramel, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Kilbeggan",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Dingle Single Malt",
    price: 64.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dingle/dingle-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46.5,
    size: "750ml",
    brand: "Dingle",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Glendalough 13 Year Old",
    price: 79.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glendalough/glendalough-13-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Glendalough",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Powers Three Swallow Release",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/powers/powers-three-swallow-release-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of honey, vanilla, and a hint of spice.",
    category: "Single Pot Still",
    abv: 43.2,
    size: "750ml",
    brand: "Powers",
    rating: 4.8,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Jameson Black Barrel",
    price: 39.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jameson/jameson-black-barrel-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and intense with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Jameson",
    rating: 4.7,
    reviews: "Rich and intense, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Knappogue Castle 12 Year Old",
    price: 54.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knappogue-castle/knappogue-castle-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Knappogue Castle",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Writer's Tears Copper Pot",
    price: 44.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/writers-tears/writers-tears-copper-pot-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Writer's Tears",
    rating: 4.7,
    reviews: "Smooth and fruity, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Redbreast 15 Year Old",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redbreast/redbreast-15-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, nuts, and spices.",
    category: "Single Pot Still",
    abv: 46,
    size: "750ml",
    brand: "Redbreast",
    rating: 4.9,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Ireland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Bushmills 16 Year Old",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bushmills/bushmills-16-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bushmills",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Ireland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
];

module.exports = irishWhiskeys;
