const japaneseWhiskeys = [
  {
    id: 1,
    name: "Yamazaki 12 Year Old",
    price: 149.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/yamazaki/yamazaki-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, orange, and a hint of spice.",
    category: "Single Malt",
    abv: 43,
    size: "700ml",
    brand: "Yamazaki",
    rating: 4.9,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, sushi",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Hibiki Japanese Harmony",
    price: 99.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hibiki/hibiki-japanese-harmony-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Elegant and complex with notes of honey, orange, and white chocolate.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Hibiki",
    rating: 4.8,
    reviews: "Elegant and complex, great for special occasions.",
    origin: "Japan",
    pairing: "Seafood, cheese",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Nikka Coffey Grain",
    price: 69.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-coffey-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of caramel, vanilla, and a hint of fruit.",
    category: "Grain",
    abv: 45,
    size: "700ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Hakushu 12 Year Old",
    price: 129.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hakushu/hakushu-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Fresh and herbal with notes of green apple, mint, and a hint of smoke.",
    category: "Single Malt",
    abv: 43,
    size: "700ml",
    brand: "Hakushu",
    rating: 4.8,
    reviews: "Fresh and herbal, great for sipping.",
    origin: "Japan",
    pairing: "Seafood, light salads",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Nikka From The Barrel",
    price: 59.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-from-the-barrel-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and full-bodied with notes of caramel, spices, and a hint of oak.",
    category: "Blended",
    abv: 51.4,
    size: "500ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Chita Single Grain",
    price: 54.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/chita/chita-single-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and mild with notes of honey, vanilla, and a hint of floral.",
    category: "Grain",
    abv: 43,
    size: "700ml",
    brand: "Chita",
    rating: 4.7,
    reviews: "Smooth and mild, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light desserts",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Mars Shinshu Iwai Tradition",
    price: 64.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/mars-shinshu/mars-shinshu-iwai-tradition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of caramel, vanilla, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Mars Shinshu",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Akashi White Oak",
    price: 39.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/akashi/akashi-white-oak-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of fruit, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "500ml",
    brand: "Akashi",
    rating: 4.6,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light salads",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Fuji Sanroku Signature Blend",
    price: 74.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/fuji-sanroku/fuji-sanroku-signature-blend-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 46,
    size: "700ml",
    brand: "Fuji Sanroku",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, sushi",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Kavalan Single Malt",
    price: 69.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kavalan/kavalan-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of tropical fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "700ml",
    brand: "Kavalan",
    rating: 4.8,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Taiwan",
    pairing: "Cheese, fruit desserts",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Suntory Toki",
    price: 49.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/suntory/suntory-toki-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Light and refreshing with notes of green apple, vanilla, and a hint of mint.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Suntory",
    rating: 4.6,
    reviews: "Light and refreshing, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Miyagikyo Single Malt",
    price: 119.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/miyagikyo/miyagikyo-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smooth with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 45,
    size: "700ml",
    brand: "Miyagikyo",
    rating: 4.8,
    reviews: "Rich and smooth, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Kujira Ryukyu 20 Year Old",
    price: 399.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kujira/kujira-ryukyu-20-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Exquisite and complex with notes of dark chocolate, vanilla, and a hint of oak.",
    category: "Single Grain",
    abv: 43,
    size: "700ml",
    brand: "Kujira",
    rating: 4.9,
    reviews: "Exquisite and complex, great for special occasions.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Yoichi Single Malt",
    price: 119.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/yoichi/yoichi-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 45,
    size: "700ml",
    brand: "Yoichi",
    rating: 4.8,
    reviews: "Rich and smoky, great for sipping.",
    origin: "Japan",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Kurayoshi 12 Year Old",
    price: 99.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kurayoshi/kurayoshi-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, dried fruits, and a hint of spice.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Kurayoshi",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Nikka Pure Malt Black",
    price: 79.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-pure-malt-black-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and full-bodied with notes of caramel, spices, and a hint of smoke.",
    category: "Blended Malt",
    abv: 43,
    size: "500ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Rich and full-bodied, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Ichiro's Malt & Grain",
    price: 89.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/ichiros/ichiros-malt-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 46,
    size: "700ml",
    brand: "Ichiro's",
    rating: 4.8,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Kirin Fuji-Sanroku",
    price: 49.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kirin/kirin-fuji-sanroku-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of vanilla, caramel, and a hint of fruit.",
    category: "Blended",
    abv: 50,
    size: "700ml",
    brand: "Kirin",
    rating: 4.6,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Hakushu Distiller's Reserve",
    price: 89.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hakushu/hakushu-distillers-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Fresh and herbal with notes of green apple, mint, and a hint of smoke.",
    category: "Single Malt",
    abv: 43,
    size: "700ml",
    brand: "Hakushu",
    rating: 4.8,
    reviews: "Fresh and herbal, great for sipping.",
    origin: "Japan",
    pairing: "Seafood, light salads",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Kamiki Blended Malt",
    price: 69.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kamiki/kamiki-blended-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 48,
    size: "500ml",
    brand: "Kamiki",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Nikka Miyagikyo Apple Brandy Wood Finish",
    price: 99.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-miyagikyo-apple-brandy-wood-finish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 47,
    size: "700ml",
    brand: "Nikka",
    rating: 4.8,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, fruit desserts",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Suntory Royal",
    price: 79.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/suntory/suntory-royal-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and elegant with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Suntory",
    rating: 4.7,
    reviews: "Smooth and elegant, great for special occasions.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Kujira Ryukyu 20 Year Old",
    price: 399.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kujira/kujira-ryukyu-20-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Exquisite and complex with notes of dark chocolate, vanilla, and a hint of oak.",
    category: "Single Grain",
    abv: 43,
    size: "700ml",
    brand: "Kujira",
    rating: 4.9,
    reviews: "Exquisite and complex, great for special occasions.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Akashi Single Malt",
    price: 59.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/akashi/akashi-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of sherry, dried fruits, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "500ml",
    brand: "Akashi",
    rating: 4.7,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Chichibu The Peated",
    price: 179.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/chichibu/chichibu-the-peated-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 54.5,
    size: "700ml",
    brand: "Chichibu",
    rating: 4.9,
    reviews: "Rich and smoky, great for sipping.",
    origin: "Japan",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Nikka Tailored",
    price: 89.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-tailored-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, spices, and a hint of fruit.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Nikka",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Hakushu 18 Year Old",
    price: 249.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hakushu/hakushu-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Fresh and herbal with notes of green apple, mint, and a hint of smoke.",
    category: "Single Malt",
    abv: 43,
    size: "700ml",
    brand: "Hakushu",
    rating: 4.9,
    reviews: "Fresh and herbal, great for sipping.",
    origin: "Japan",
    pairing: "Seafood, light salads",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Nikka Coffey Malt",
    price: 74.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-coffey-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and sweet with notes of caramel, vanilla, and a hint of fruit.",
    category: "Malt",
    abv: 45,
    size: "700ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Smooth and sweet, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Fuji Sanroku Signature Blend",
    price: 74.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/fuji-sanroku/fuji-sanroku-signature-blend-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 46,
    size: "700ml",
    brand: "Fuji Sanroku",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, sushi",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Kavalan Single Malt",
    price: 69.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kavalan/kavalan-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of tropical fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "700ml",
    brand: "Kavalan",
    rating: 4.8,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Taiwan",
    pairing: "Cheese, fruit desserts",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Chita Single Grain",
    price: 54.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/chita/chita-single-grain-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and mild with notes of honey, vanilla, and a hint of floral.",
    category: "Grain",
    abv: 43,
    size: "700ml",
    brand: "Chita",
    rating: 4.7,
    reviews: "Smooth and mild, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light desserts",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Mars Shinshu Iwai Tradition",
    price: 64.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/mars-shinshu/mars-shinshu-iwai-tradition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of caramel, vanilla, and a hint of fruit.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Mars Shinshu",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Akashi White Oak",
    price: 39.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/akashi/akashi-white-oak-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of fruit, vanilla, and a hint of oak.",
    category: "Blended",
    abv: 40,
    size: "500ml",
    brand: "Akashi",
    rating: 4.6,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light salads",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Miyagikyo Single Malt",
    price: 119.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/miyagikyo/miyagikyo-single-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smooth with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 45,
    size: "700ml",
    brand: "Miyagikyo",
    rating: 4.8,
    reviews: "Rich and smooth, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Yamazaki Distiller's Reserve",
    price: 109.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/yamazaki/yamazaki-distillers-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, honey, and a hint of fruit.",
    category: "Single Malt",
    abv: 43,
    size: "700ml",
    brand: "Yamazaki",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, sushi",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Hibiki 17 Year Old",
    price: 349.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hibiki/hibiki-17-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Elegant and complex with notes of honey, orange, and white chocolate.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Hibiki",
    rating: 4.9,
    reviews: "Elegant and complex, great for special occasions.",
    origin: "Japan",
    pairing: "Seafood, cheese",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Nikka Pure Malt Red",
    price: 79.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-pure-malt-red-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and fruity with notes of red berries, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 43,
    size: "500ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Rich and fruity, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Chichibu The First",
    price: 199.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/chichibu/chichibu-the-first-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 61,
    size: "700ml",
    brand: "Chichibu",
    rating: 4.9,
    reviews: "Rich and complex, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Suntory Old Whisky",
    price: 54.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/suntory/suntory-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and elegant with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Suntory",
    rating: 4.7,
    reviews: "Smooth and elegant, great for special occasions.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Kurayoshi Sherry Cask",
    price: 89.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kurayoshi/kurayoshi-sherry-cask-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 46,
    size: "700ml",
    brand: "Kurayoshi",
    rating: 4.8,
    reviews: "Rich and sherried, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Nikka Taketsuru Pure Malt",
    price: 79.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-taketsuru-pure-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of caramel, vanilla, and a hint of fruit.",
    category: "Blended Malt",
    abv: 43,
    size: "700ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Hakushu 25 Year Old",
    price: 1499.99,
    quantity: 2,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hakushu/hakushu-25-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Exquisite and complex with notes of dried fruits, vanilla, and a hint of smoke.",
    category: "Single Malt",
    abv: 43,
    size: "700ml",
    brand: "Hakushu",
    rating: 4.9,
    reviews: "Exquisite and complex, great for special occasions.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Akashi Red",
    price: 44.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/akashi/akashi-red-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of red berries, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "500ml",
    brand: "Akashi",
    rating: 4.6,
    reviews: "Smooth and fruity, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Suntory Kakubin",
    price: 49.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/suntory/suntory-kakubin-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and elegant with notes of vanilla, honey, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "700ml",
    brand: "Suntory",
    rating: 4.6,
    reviews: "Smooth and elegant, great for special occasions.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Nikka Days",
    price: 59.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-days-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Light and fruity with notes of apple, vanilla, and a hint of citrus.",
    category: "Blended",
    abv: 40,
    size: "700ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Light and fruity, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Kurayoshi 18 Year Old",
    price: 199.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kurayoshi/kurayoshi-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 46,
    size: "700ml",
    brand: "Kurayoshi",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Japan",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Nikka Miyagikyo Peated",
    price: 119.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-miyagikyo-peated-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "700ml",
    brand: "Nikka",
    rating: 4.8,
    reviews: "Rich and smoky, great for sipping.",
    origin: "Japan",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Hibiki Blossom Harmony",
    price: 299.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hibiki/hibiki-blossom-harmony-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Elegant and complex with notes of cherry blossom, vanilla, and white chocolate.",
    category: "Blended",
    abv: 43,
    size: "700ml",
    brand: "Hibiki",
    rating: 4.9,
    reviews: "Elegant and complex, great for special occasions.",
    origin: "Japan",
    pairing: "Seafood, cheese",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Akashi Blended Malt",
    price: 49.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/akashi/akashi-blended-malt-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of red berries, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 40,
    size: "500ml",
    brand: "Akashi",
    rating: 4.6,
    reviews: "Smooth and fruity, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Nikka Coffey Vodka",
    price: 59.99,
    quantity: 16,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/nikka/nikka-coffey-vodka-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and clean with notes of vanilla, citrus, and a hint of spice.",
    category: "Vodka",
    abv: 40,
    size: "700ml",
    brand: "Nikka",
    rating: 4.7,
    reviews: "Smooth and clean, great for cocktails.",
    origin: "Japan",
    pairing: "Cheese, light appetizers",
    availability: "In Stock",
  },
];

module.exports = japaneseWhiskeys;
