const ryeWhiskeys = [
  {
    id: 1,
    name: "Bulleit Rye",
    price: 29.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bulleit/bulleit-95-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich, oaky aroma with hints of vanilla, spice, and honey.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Bulleit",
    rating: 4.7,
    reviews: "Smooth and spicy, perfect for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "WhistlePig 10 Year Old Rye",
    price: 89.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/whistlepig/whistlepig-10-year-old-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 10 years, offering a bold and spicy flavor.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "WhistlePig",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Vermont, USA",
    pairing: "Spicy foods, BBQ",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Rittenhouse Rye",
    price: 24.99,
    quantity: 20,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/rittenhouse/rittenhouse-straight-rye-100-proof-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A full-bodied rye with notes of cinnamon, nutmeg, and spices.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "Rittenhouse",
    rating: 4.6,
    reviews: "Spicy and bold, excellent for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "High West Double Rye",
    price: 39.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/high-west/high-west-double-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A blend of young and old rye whiskeys, offering a spicy and complex flavor.",
    category: "Blend",
    abv: 46,
    size: "750ml",
    brand: "High West",
    rating: 4.7,
    reviews: "Spicy and complex, great for sipping.",
    origin: "Utah, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Sazerac Rye",
    price: 29.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/sazerac/sazerac-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced rye with notes of vanilla, clove, and pepper.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Sazerac",
    rating: 4.8,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Michter's US*1 Single Barrel Straight Rye",
    price: 49.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/michters/michters-us1-single-barrel-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a smooth and rich flavor profile.",
    category: "Single Barrel",
    abv: 42.4,
    size: "750ml",
    brand: "Michter's",
    rating: 4.7,
    reviews: "Rich and smooth, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Pikesville Straight Rye",
    price: 49.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pikesville/pikesville-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof rye with a bold and spicy flavor.",
    category: "Straight Rye",
    abv: 55,
    size: "750ml",
    brand: "Pikesville",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Maryland, USA",
    pairing: "Spicy foods, BBQ",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Knob Creek Rye",
    price: 39.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knob-creek/knob-creek-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold rye with notes of spice, vanilla, and oak.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "Knob Creek",
    rating: 4.7,
    reviews: "Bold and rich, perfect for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Templeton Rye 6 Year Old",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/templeton/templeton-rye-6-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 6 years, offering a rich and smooth flavor.",
    category: "Straight Rye",
    abv: 45.75,
    size: "750ml",
    brand: "Templeton",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Iowa, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Redemption Rye",
    price: 29.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redemption/redemption-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A classic rye with notes of spice, citrus, and vanilla.",
    category: "Straight Rye",
    abv: 46,
    size: "750ml",
    brand: "Redemption",
    rating: 4.5,
    reviews: "Spicy and smooth, great for cocktails.",
    origin: "Indiana, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Old Forester Rye",
    price: 24.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and balanced rye with notes of caramel and spice.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.7,
    reviews: "Balanced and smooth, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Woodford Reserve Rye",
    price: 34.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/woodford-reserve/woodford-reserve-kentucky-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced rye with notes of honey, vanilla, and spices.",
    category: "Straight Rye",
    abv: 45.2,
    size: "750ml",
    brand: "Woodford Reserve",
    rating: 4.8,
    reviews: "Smooth and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Wild Turkey 101 Rye",
    price: 28.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-101-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof rye with a bold and spicy flavor profile.",
    category: "High Proof",
    abv: 50.5,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.7,
    reviews: "Bold and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "George Dickel Rye",
    price: 26.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/george-dickel/george-dickel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth rye with notes of caramel, vanilla, and spices.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "George Dickel",
    rating: 4.6,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Tennessee, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Old Overholt Rye",
    price: 19.99,
    quantity: 18,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-overholt/old-overholt-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A classic rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 40,
    size: "750ml",
    brand: "Old Overholt",
    rating: 4.5,
    reviews: "Classic and smooth, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "New Riff Bottled in Bond Rye",
    price: 49.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/new-riff/new-riff-bottled-in-bond-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bottled in bond rye with a rich and spicy flavor profile.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "New Riff",
    rating: 4.7,
    reviews: "Rich and spicy, perfect for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Dad's Hat Pennsylvania Rye",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dads-hat/dads-hat-pennsylvania-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A Pennsylvania-style rye with notes of spice, vanilla, and caramel.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Dad's Hat",
    rating: 4.6,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Pennsylvania, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Russell's Reserve 6 Year Old Rye",
    price: 44.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/russells-reserve/russells-reserve-6-year-old-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Aged for 6 years, offering a rich and complex flavor profile.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Russell's Reserve",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Balcones Texas Rye",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/balcones/balcones-texas-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold and spicy rye with notes of caramel and oak.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "Balcones",
    rating: 4.7,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Texas, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Catoctin Creek Roundstone Rye",
    price: 44.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/catoctin-creek/catoctin-creek-roundstone-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of vanilla and caramel.",
    category: "Straight Rye",
    abv: 46,
    size: "750ml",
    brand: "Catoctin Creek",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Virginia, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Journeyman Last Feather Rye",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/journeyman/journeyman-last-feather-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small batch rye with a rich and complex flavor profile.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Journeyman",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Michigan, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Smooth Ambler Old Scout Rye",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/smooth-ambler/smooth-ambler-old-scout-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A classic rye with notes of spice, vanilla, and caramel.",
    category: "Straight Rye",
    abv: 49.5,
    size: "750ml",
    brand: "Smooth Ambler",
    rating: 4.6,
    reviews: "Spicy and smooth, great for cocktails.",
    origin: "West Virginia, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Angel's Envy Rye",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/angels-envy/angels-envy-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Finished in Caribbean rum casks, offering a unique flavor profile.",
    category: "Finished",
    abv: 50,
    size: "750ml",
    brand: "Angel's Envy",
    rating: 4.8,
    reviews: "Unique and smooth, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Jack Daniel's Tennessee Rye",
    price: 29.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/jack-daniels/jack-daniels-tennessee-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth and balanced rye with notes of caramel and spice.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Jack Daniel's",
    rating: 4.6,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Tennessee, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Ragtime Rye",
    price: 45.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/ragtime/ragtime-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of vanilla and caramel.",
    category: "Straight Rye",
    abv: 45.2,
    size: "750ml",
    brand: "Ragtime",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "New York, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  // Adding 75 more rye whiskeys
  {
    id: 26,
    name: "Basil Hayden's Dark Rye",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/basil-haydens/basil-haydens-dark-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and complex rye with notes of dried fruit and spice.",
    category: "Blend",
    abv: 40,
    size: "750ml",
    brand: "Basil Hayden's",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Crown Royal Northern Harvest Rye",
    price: 29.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/crown-royal/crown-royal-northern-harvest-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A Canadian rye with notes of vanilla, caramel, and spice.",
    category: "Canadian Rye",
    abv: 45,
    size: "750ml",
    brand: "Crown Royal",
    rating: 4.6,
    reviews: "Smooth and spicy, great for cocktails.",
    origin: "Canada",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Dad's Hat Rye Finished in Vermouth Barrels",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dads-hat/dads-hat-vermouth-barrel-finished-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in vermouth barrels, offering a complex flavor.",
    category: "Finished",
    abv: 47,
    size: "750ml",
    brand: "Dad's Hat",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Pennsylvania, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "George Dickel Bottled in Bond Rye",
    price: 34.99,
    quantity: 13,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/george-dickel/george-dickel-bottled-in-bond-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bottled in bond rye with a rich and spicy flavor.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "George Dickel",
    rating: 4.7,
    reviews: "Rich and spicy, great for cocktails.",
    origin: "Tennessee, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "High West Rendezvous Rye",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/high-west/high-west-rendezvous-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A blend of straight rye whiskeys, offering a bold and spicy flavor.",
    category: "Blend",
    abv: 46,
    size: "750ml",
    brand: "High West",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Utah, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Hillrock Estate Distillery Double Cask Rye",
    price: 89.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hillrock/hillrock-double-cask-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A double cask rye with a rich and complex flavor profile.",
    category: "Double Cask",
    abv: 45,
    size: "750ml",
    brand: "Hillrock Estate",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "New York, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Hudson Manhattan Rye",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/hudson/hudson-manhattan-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small batch rye with notes of vanilla, caramel, and spice.",
    category: "Small Batch",
    abv: 46,
    size: "750ml",
    brand: "Hudson",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "New York, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "James E. Pepper 1776 Rye",
    price: 34.99,
    quantity: 14,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/james-e-pepper/james-e-pepper-1776-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "James E. Pepper",
    rating: 4.7,
    reviews: "Bold and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Koval Single Barrel Rye",
    price: 49.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/koval/koval-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a rich and smooth flavor profile.",
    category: "Single Barrel",
    abv: 40,
    size: "750ml",
    brand: "Koval",
    rating: 4.7,
    reviews: "Smooth and rich, perfect for sipping.",
    origin: "Illinois, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Lock Stock & Barrel 16 Year Old Straight Rye",
    price: 149.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lock-stock-and-barrel/lock-stock-and-barrel-16-year-old-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 16 years, offering a rich and complex flavor.",
    category: "Aged",
    abv: 53.5,
    size: "750ml",
    brand: "Lock Stock & Barrel",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Pennsylvania, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Minor Case Straight Rye",
    price: 44.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/minor-case/minor-case-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A straight rye with a smooth and rich flavor profile.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Minor Case",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "New York Distilling Company Ragtime Rye",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/new-york-distilling-company/new-york-distilling-company-ragtime-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of vanilla and caramel.",
    category: "Straight Rye",
    abv: 45.2,
    size: "750ml",
    brand: "New York Distilling Company",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "New York, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Old Forester Single Barrel Rye",
    price: 54.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Peerless Straight Rye",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/peerless/peerless-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A rich and complex rye with notes of caramel, vanilla, and spice.",
    category: "Straight Rye",
    abv: 55,
    size: "750ml",
    brand: "Peerless",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Redemption Barrel Proof Rye",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redemption/redemption-barrel-proof-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof rye with a bold and spicy flavor profile.",
    category: "High Proof",
    abv: 55.1,
    size: "750ml",
    brand: "Redemption",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Indiana, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Rittenhouse Bottled in Bond Rye",
    price: 34.99,
    quantity: 13,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/rittenhouse/rittenhouse-bottled-in-bond-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bottled in bond rye with a rich and spicy flavor profile.",
    category: "Bottled in Bond",
    abv: 50,
    size: "750ml",
    brand: "Rittenhouse",
    rating: 4.7,
    reviews: "Rich and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Russell's Reserve Single Barrel Rye",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/russells-reserve/russells-reserve-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 52,
    size: "750ml",
    brand: "Russell's Reserve",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Templeton Rye 4 Year Old",
    price: 34.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/templeton/templeton-rye-4-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 4 years, offering a rich and smooth flavor.",
    category: "Straight Rye",
    abv: 45.75,
    size: "750ml",
    brand: "Templeton",
    rating: 4.6,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Iowa, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Thomas H. Handy Sazerac Rye",
    price: 199.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/thomas-h-handy/thomas-h-handy-sazerac-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof rye with a bold and complex flavor profile.",
    category: "High Proof",
    abv: 63.8,
    size: "750ml",
    brand: "Thomas H. Handy",
    rating: 4.9,
    reviews: "Bold and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "WhistlePig 12 Year Old World Rye",
    price: 129.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/whistlepig/whistlepig-12-year-old-world-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A 12-year-old rye with a rich and complex flavor profile.",
    category: "Aged",
    abv: 43,
    size: "750ml",
    brand: "WhistlePig",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Vermont, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Willett Family Estate Bottled Rye",
    price: 89.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/willett/willett-family-estate-bottled-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A rich and complex rye with notes of caramel, vanilla, and spice.",
    category: "Straight Rye",
    abv: 54,
    size: "750ml",
    brand: "Willett",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Woodinville Straight Rye",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/woodinville/woodinville-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of vanilla and caramel.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Woodinville",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Washington, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Yellowstone Select Rye",
    price: 39.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/yellowstone/yellowstone-select-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 46.5,
    size: "750ml",
    brand: "Yellowstone",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Wild Turkey Kentucky Spirit Rye",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-kentucky-spirit-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 50.5,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Angel's Envy Rye Finished in Caribbean Rum Casks",
    price: 89.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/angels-envy/angels-envy-rye-finished-in-caribbean-rum-casks-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Finished in Caribbean rum casks, offering a unique flavor profile.",
    category: "Finished",
    abv: 50,
    size: "750ml",
    brand: "Angel's Envy",
    rating: 4.9,
    reviews: "Unique and smooth, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Balcones Texas Rye Finished in Rum Casks",
    price: 69.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/balcones/balcones-texas-rye-finished-in-rum-casks-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in rum casks, offering a complex flavor.",
    category: "Finished",
    abv: 50,
    size: "750ml",
    brand: "Balcones",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Texas, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Basil Hayden's Rye",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/basil-haydens/basil-haydens-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth rye with notes of vanilla, caramel, and spice.",
    category: "Straight Rye",
    abv: 40,
    size: "750ml",
    brand: "Basil Hayden's",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Black Maple Hill Rye",
    price: 69.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/black-maple-hill/black-maple-hill-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of caramel and vanilla.",
    category: "Straight Rye",
    abv: 47.5,
    size: "750ml",
    brand: "Black Maple Hill",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Oregon, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Bowman Brothers Pioneer Spirit Rye",
    price: 34.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bowman-brothers/bowman-brothers-pioneer-spirit-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Bowman Brothers",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Virginia, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Buffalo Trace Experimental Rye",
    price: 129.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/buffalo-trace/buffalo-trace-experimental-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "An experimental rye with a rich and complex flavor profile.",
    category: "Experimental",
    abv: 45,
    size: "750ml",
    brand: "Buffalo Trace",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Clyde May's Rye",
    price: 39.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/clyde-mays/clyde-mays-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth rye with notes of vanilla, caramel, and spice.",
    category: "Straight Rye",
    abv: 47,
    size: "750ml",
    brand: "Clyde May's",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Alabama, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Copper Fox Rye",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/copper-fox/copper-fox-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A unique rye with notes of fruit, spice, and oak.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Copper Fox",
    rating: 4.7,
    reviews: "Smooth and unique, great for sipping.",
    origin: "Virginia, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Corsair Ryemageddon",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/corsair/corsair-ryemageddon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold and spicy rye with a rich and complex flavor profile.",
    category: "Straight Rye",
    abv: 46,
    size: "750ml",
    brand: "Corsair",
    rating: 4.8,
    reviews: "Bold and complex, great for sipping.",
    origin: "Tennessee, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Dad's Hat Port Finished Rye",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dads-hat/dads-hat-port-finished-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in port barrels, offering a complex flavor.",
    category: "Finished",
    abv: 47,
    size: "750ml",
    brand: "Dad's Hat",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Pennsylvania, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Few Spirits Rye",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/few/few-spirits-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold and spicy rye with notes of caramel and vanilla.",
    category: "Straight Rye",
    abv: 46.5,
    size: "750ml",
    brand: "Few Spirits",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Illinois, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "High West Yippee Ki-Yay",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/high-west/high-west-yippee-ki-yay-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in wine barrels, offering a complex flavor.",
    category: "Finished",
    abv: 46,
    size: "750ml",
    brand: "High West",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Utah, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Journeyman Last Feather Rye",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/journeyman/journeyman-last-feather-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small batch rye with a rich and complex flavor profile.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Journeyman",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Michigan, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Knob Creek Single Barrel Rye",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knob-creek/knob-creek-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 55,
    size: "750ml",
    brand: "Knob Creek",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Laws Whiskey House San Luis Valley Rye",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/laws-whiskey-house/laws-whiskey-house-san-luis-valley-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A unique rye with a rich and complex flavor profile.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "Laws Whiskey House",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Colorado, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Lock Stock & Barrel 18 Year Old Straight Rye",
    price: 199.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lock-stock-and-barrel/lock-stock-and-barrel-18-year-old-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 18 years, offering a rich and complex flavor.",
    category: "Aged",
    abv: 54.5,
    size: "750ml",
    brand: "Lock Stock & Barrel",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Pennsylvania, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Michter's 10 Year Old Single Barrel Rye",
    price: 149.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/michters/michters-10-year-old-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 10 years, offering a rich and smooth flavor.",
    category: "Single Barrel",
    abv: 46.4,
    size: "750ml",
    brand: "Michter's",
    rating: 4.9,
    reviews: "Smooth and rich, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "New Riff Single Barrel Rye",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/new-riff/new-riff-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 50,
    size: "750ml",
    brand: "New Riff",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Old Forester Statesman Rye",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-forester/old-forester-statesman-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 47.5,
    size: "750ml",
    brand: "Old Forester",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Old Potrero Straight Rye",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-potrero/old-potrero-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of caramel and vanilla.",
    category: "Straight Rye",
    abv: 48.5,
    size: "750ml",
    brand: "Old Potrero",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "California, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Peerless Single Barrel Rye",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/peerless/peerless-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a rich and complex flavor profile.",
    category: "Single Barrel",
    abv: 54,
    size: "750ml",
    brand: "Peerless",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Pinhook Rye'd On",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/pinhook/pinhook-ryed-on-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of vanilla and caramel.",
    category: "Straight Rye",
    abv: 46.75,
    size: "750ml",
    brand: "Pinhook",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Redemption High Rye Bourbon",
    price: 39.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/redemption/redemption-high-rye-bourbon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high rye bourbon with a bold and spicy flavor profile.",
    category: "High Rye",
    abv: 46,
    size: "750ml",
    brand: "Redemption",
    rating: 4.7,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Indiana, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Rittenhouse Rye 100 Proof",
    price: 29.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/rittenhouse/rittenhouse-rye-100-proof-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high proof rye with a bold and spicy flavor profile.",
    category: "High Proof",
    abv: 50,
    size: "750ml",
    brand: "Rittenhouse",
    rating: 4.7,
    reviews: "Bold and spicy, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Russell's Reserve Single Barrel Rye",
    price: 59.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/russells-reserve/russells-reserve-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a rich and complex flavor profile.",
    category: "Single Barrel",
    abv: 52,
    size: "750ml",
    brand: "Russell's Reserve",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Sagamore Spirit Rye",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/sagamore-spirit/sagamore-spirit-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth rye with notes of caramel, vanilla, and spice.",
    category: "Straight Rye",
    abv: 41.5,
    size: "750ml",
    brand: "Sagamore Spirit",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Maryland, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Sazerac 18 Year Old Rye",
    price: 199.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/sazerac/sazerac-18-year-old-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 18 years, offering a rich and complex flavor.",
    category: "Aged",
    abv: 45,
    size: "750ml",
    brand: "Sazerac",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Smooth Ambler Old Scout Rye",
    price: 39.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/smooth-ambler/smooth-ambler-old-scout-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A classic rye with notes of spice, vanilla, and caramel.",
    category: "Straight Rye",
    abv: 49.5,
    size: "750ml",
    brand: "Smooth Ambler",
    rating: 4.6,
    reviews: "Spicy and smooth, great for cocktails.",
    origin: "West Virginia, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Templeton Rye Special Reserve",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/templeton/templeton-rye-special-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A special reserve rye with a rich and smooth flavor profile.",
    category: "Special Reserve",
    abv: 46,
    size: "750ml",
    brand: "Templeton",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Iowa, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Thomas H. Handy Sazerac Rye",
    price: 199.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/thomas-h-handy/thomas-h-handy-sazerac-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A high-proof rye with a bold and complex flavor profile.",
    category: "High Proof",
    abv: 63.8,
    size: "750ml",
    brand: "Thomas H. Handy",
    rating: 4.9,
    reviews: "Bold and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "WhistlePig 12 Year Old World Rye",
    price: 129.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/whistlepig/whistlepig-12-year-old-world-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A 12-year-old rye with a rich and complex flavor profile.",
    category: "Aged",
    abv: 43,
    size: "750ml",
    brand: "WhistlePig",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Vermont, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Willett Family Estate Bottled Rye",
    price: 89.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/willett/willett-family-estate-bottled-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A rich and complex rye with notes of caramel, vanilla, and spice.",
    category: "Straight Rye",
    abv: 54,
    size: "750ml",
    brand: "Willett",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Woodinville Straight Rye",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/woodinville/woodinville-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of vanilla and caramel.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Woodinville",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Washington, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Yellowstone Select Rye",
    price: 39.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/yellowstone/yellowstone-select-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 46.5,
    size: "750ml",
    brand: "Yellowstone",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Wild Turkey Kentucky Spirit Rye",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wild-turkey/wild-turkey-kentucky-spirit-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 50.5,
    size: "750ml",
    brand: "Wild Turkey",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Angel's Envy Rye Finished in Caribbean Rum Casks",
    price: 89.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/angels-envy/angels-envy-rye-finished-in-caribbean-rum-casks-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Finished in Caribbean rum casks, offering a unique flavor profile.",
    category: "Finished",
    abv: 50,
    size: "750ml",
    brand: "Angel's Envy",
    rating: 4.9,
    reviews: "Unique and smooth, a real treat.",
    origin: "Kentucky, USA",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Balcones Texas Rye Finished in Rum Casks",
    price: 69.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/balcones/balcones-texas-rye-finished-in-rum-casks-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in rum casks, offering a complex flavor.",
    category: "Finished",
    abv: 50,
    size: "750ml",
    brand: "Balcones",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Texas, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Basil Hayden's Rye",
    price: 44.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/basil-haydens/basil-haydens-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth rye with notes of vanilla, caramel, and spice.",
    category: "Straight Rye",
    abv: 40,
    size: "750ml",
    brand: "Basil Hayden's",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Kentucky, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Black Maple Hill Rye",
    price: 69.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/black-maple-hill/black-maple-hill-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A rich and spicy rye with notes of caramel and vanilla.",
    category: "Straight Rye",
    abv: 47.5,
    size: "750ml",
    brand: "Black Maple Hill",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Oregon, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Bowman Brothers Pioneer Spirit Rye",
    price: 34.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bowman-brothers/bowman-brothers-pioneer-spirit-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A well-balanced rye with notes of spice, caramel, and vanilla.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Bowman Brothers",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Virginia, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Buffalo Trace Experimental Rye",
    price: 129.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/buffalo-trace/buffalo-trace-experimental-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "An experimental rye with a rich and complex flavor profile.",
    category: "Experimental",
    abv: 45,
    size: "750ml",
    brand: "Buffalo Trace",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Kentucky, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Clyde May's Rye",
    price: 39.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/clyde-mays/clyde-mays-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A smooth rye with notes of vanilla, caramel, and spice.",
    category: "Straight Rye",
    abv: 47,
    size: "750ml",
    brand: "Clyde May's",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Alabama, USA",
    pairing: "Grilled meats, spicy dishes",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Copper Fox Rye",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/copper-fox/copper-fox-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A unique rye with notes of fruit, spice, and oak.",
    category: "Straight Rye",
    abv: 45,
    size: "750ml",
    brand: "Copper Fox",
    rating: 4.7,
    reviews: "Smooth and unique, great for sipping.",
    origin: "Virginia, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Corsair Ryemageddon",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/corsair/corsair-ryemageddon-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold and spicy rye with a rich and complex flavor profile.",
    category: "Straight Rye",
    abv: 46,
    size: "750ml",
    brand: "Corsair",
    rating: 4.8,
    reviews: "Bold and complex, great for sipping.",
    origin: "Tennessee, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Dad's Hat Port Finished Rye",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dads-hat/dads-hat-port-finished-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in port barrels, offering a complex flavor.",
    category: "Finished",
    abv: 47,
    size: "750ml",
    brand: "Dad's Hat",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Pennsylvania, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Few Spirits Rye",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/few/few-spirits-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A bold and spicy rye with notes of caramel and vanilla.",
    category: "Straight Rye",
    abv: 46.5,
    size: "750ml",
    brand: "Few Spirits",
    rating: 4.7,
    reviews: "Smooth and spicy, great for sipping.",
    origin: "Illinois, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "High West Yippee Ki-Yay",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/high-west/high-west-yippee-ki-yay-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A unique rye finished in wine barrels, offering a complex flavor.",
    category: "Finished",
    abv: 46,
    size: "750ml",
    brand: "High West",
    rating: 4.8,
    reviews: "Complex and unique, perfect for sipping.",
    origin: "Utah, USA",
    pairing: "Cheese, cured meats",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Journeyman Last Feather Rye",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/journeyman/journeyman-last-feather-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A small batch rye with a rich and complex flavor profile.",
    category: "Small Batch",
    abv: 45,
    size: "750ml",
    brand: "Journeyman",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Michigan, USA",
    pairing: "Roast beef, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Knob Creek Single Barrel Rye",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/knob-creek/knob-creek-single-barrel-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A single barrel rye with a bold and spicy flavor profile.",
    category: "Single Barrel",
    abv: 55,
    size: "750ml",
    brand: "Knob Creek",
    rating: 4.8,
    reviews: "Bold and spicy, great for sipping.",
    origin: "Kentucky, USA",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Laws Whiskey House San Luis Valley Rye",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/laws-whiskey-house/laws-whiskey-house-san-luis-valley-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "A unique rye with a rich and complex flavor profile.",
    category: "Straight Rye",
    abv: 50,
    size: "750ml",
    brand: "Laws Whiskey House",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Colorado, USA",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Lock Stock & Barrel 18 Year Old Straight Rye",
    price: 199.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lock-stock-and-barrel/lock-stock-and-barrel-18-year-old-straight-rye-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Aged for 18 years, offering a rich and complex flavor.",
    category: "Aged",
    abv: 54.5,
    size: "750ml",
    brand: "Lock Stock & Barrel",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Pennsylvania, USA",
    pairing: "Prime rib, dark chocolate",
    availability: "In Stock",
  },
];

module.exports = ryeWhiskeys;
