const scotchWhiskies = [
  {
    id: 1,
    name: "Glenfiddich 12 Year Old",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenfiddich/glenfiddich-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "A smooth and balanced single malt with notes of fresh pear and subtle oak.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenfiddich",
    rating: 4.7,
    reviews: "Smooth and balanced, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Macallan 12 Year Old Sherry Oak",
    price: 69.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/macallan/macallan-12-year-old-sherry-oak-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, sherry, and wood smoke.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Macallan",
    rating: 4.8,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Lagavulin 16 Year Old",
    price: 89.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lagavulin/lagavulin-16-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Intense peat smoke with hints of vanilla and dried fruits.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Lagavulin",
    rating: 4.9,
    reviews: "Smoky and rich, a must-try for peat lovers.",
    origin: "Scotland",
    pairing: "Smoked salmon, BBQ",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Laphroaig 10 Year Old",
    price: 54.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/laphroaig/laphroaig-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Full-bodied, smoky, with a hint of seaweed and sweetness.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Laphroaig",
    rating: 4.7,
    reviews: "Bold and smoky, great for sipping.",
    origin: "Scotland",
    pairing: "Oysters, blue cheese",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Highland Park 12 Year Old",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/highland-park/highland-park-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Well-balanced, smoky, with hints of honey and fruit.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Highland Park",
    rating: 4.7,
    reviews: "Smooth and smoky, great for sipping.",
    origin: "Scotland",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Glenlivet 12 Year Old",
    price: 49.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenlivet/glenlivet-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Fruity and floral with notes of apple and vanilla.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenlivet",
    rating: 4.7,
    reviews: "Smooth and fruity, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Ardbeg 10 Year Old",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/ardbeg/ardbeg-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Heavily peated with notes of citrus, chocolate, and peat smoke.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Ardbeg",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Balvenie DoubleWood 12 Year Old",
    price: 64.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/balvenie/balvenie-doublewood-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of dried fruit, nut, and cinnamon.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Balvenie",
    rating: 4.8,
    reviews: "Smooth and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Glenmorangie Original 10 Year Old",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenmorangie/glenmorangie-original-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and mellow with notes of citrus, peach, and vanilla.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenmorangie",
    rating: 4.7,
    reviews: "Smooth and mellow, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Talisker 10 Year Old",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/talisker/talisker-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Peaty and smoky with notes of sea salt and pepper.",
    category: "Single Malt",
    abv: 45.8,
    size: "750ml",
    brand: "Talisker",
    rating: 4.8,
    reviews: "Bold and smoky, great for sipping.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  // Continue to add 90 more entries in a similar fashion...
  {
    id: 11,
    name: "Oban 14 Year Old",
    price: 79.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/oban/oban-14-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and full-bodied with notes of dried fruit and a hint of smoke.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Oban",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Dalmore 12 Year Old",
    price: 69.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dalmore/dalmore-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and smooth with notes of citrus, sherry, and vanilla.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Dalmore",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "GlenDronach 12 Year Old",
    price: 64.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glendronach/glendronach-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "GlenDronach",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Bowmore 12 Year Old",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bowmore/bowmore-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Peaty and smoky with a touch of lemon and honey.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Bowmore",
    rating: 4.7,
    reviews: "Smooth and smoky, great for sipping.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Springbank 10 Year Old",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/springbank/springbank-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, malt, and a hint of peat.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Springbank",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Aberlour 12 Year Old",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/aberlour/aberlour-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and rich with notes of sherry, vanilla, and spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Aberlour",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Cardhu 12 Year Old",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/cardhu/cardhu-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and sweet with notes of honey, fruit, and malt.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Cardhu",
    rating: 4.7,
    reviews: "Smooth and sweet, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Clynelish 14 Year Old",
    price: 69.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/clynelish/clynelish-14-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of wax, honey, and a hint of smoke.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Clynelish",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Cragganmore 12 Year Old",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/cragganmore/cragganmore-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, fruit, and a hint of smoke.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Cragganmore",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Glenfarclas 12 Year Old",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenfarclas/glenfarclas-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Glenfarclas",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Highland Park 18 Year Old",
    price: 129.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/highland-park/highland-park-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of honey, fruit, and a hint of peat.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Highland Park",
    rating: 4.9,
    reviews: "Rich and smoky, great for special occasions.",
    origin: "Scotland",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Johnnie Walker Blue Label",
    price: 199.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/johnnie-walker/johnnie-walker-blue-label-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and complex with notes of honey, vanilla, and a hint of smoke.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Johnnie Walker",
    rating: 4.9,
    reviews: "Smooth and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Chivas Regal 12 Year Old",
    price: 39.99,
    quantity: 12,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/chivas-regal/chivas-regal-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and balanced with notes of honey, fruit, and vanilla.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Chivas Regal",
    rating: 4.7,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Dewars 12 Year Old",
    price: 39.99,
    quantity: 11,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dewars/dewars-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, vanilla, and a hint of smoke.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Dewars",
    rating: 4.7,
    reviews: "Smooth and rich, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Famous Grouse",
    price: 29.99,
    quantity: 15,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/famous-grouse/famous-grouse-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and balanced with notes of fruit, malt, and a hint of smoke.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Famous Grouse",
    rating: 4.6,
    reviews: "Smooth and balanced, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Monkey Shoulder",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/monkey-shoulder/monkey-shoulder-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of vanilla, honey, and a hint of spice.",
    category: "Blended Malt",
    abv: 40,
    size: "750ml",
    brand: "Monkey Shoulder",
    rating: 4.7,
    reviews: "Smooth and rich, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Compass Box Peat Monster",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-peat-monster-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Blended Malt",
    abv: 46,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Johnny Walker Green Label 15 Year Old",
    price: 69.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/johnnie-walker/johnnie-walker-green-label-15-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of vanilla, honey, and a hint of smoke.",
    category: "Blended Malt",
    abv: 43,
    size: "750ml",
    brand: "Johnny Walker",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Big Peat",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/big-peat/big-peat-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Blended Malt",
    abv: 46,
    size: "750ml",
    brand: "Big Peat",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Compass Box Spice Tree",
    price: 59.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-spice-tree-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and spicy with notes of vanilla, clove, and nutmeg.",
    category: "Blended Malt",
    abv: 46,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.8,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Compass Box Hedonism",
    price: 89.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-hedonism-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and creamy with notes of vanilla, toffee, and coconut.",
    category: "Grain",
    abv: 43,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.9,
    reviews: "Rich and creamy, great for special occasions.",
    origin: "Scotland",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Haig Club",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/haig-club/haig-club-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and light with notes of vanilla, toffee, and spice.",
    category: "Grain",
    abv: 40,
    size: "750ml",
    brand: "Haig Club",
    rating: 4.7,
    reviews: "Smooth and light, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Invergordon 25 Year Old",
    price: 129.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/invergordon/invergordon-25-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and complex with notes of vanilla, toffee, and coconut.",
    category: "Grain",
    abv: 46,
    size: "750ml",
    brand: "Invergordon",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Girvan Patent Still 25 Year Old",
    price: 149.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/girvan/girvan-patent-still-25-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and rich with notes of vanilla, toffee, and spice.",
    category: "Grain",
    abv: 42,
    size: "750ml",
    brand: "Girvan",
    rating: 4.8,
    reviews: "Smooth and rich, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Port Dundas 18 Year Old",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/port-dundas/port-dundas-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and creamy with notes of vanilla, toffee, and coconut.",
    category: "Grain",
    abv: 46,
    size: "750ml",
    brand: "Port Dundas",
    rating: 4.8,
    reviews: "Rich and creamy, great for sipping.",
    origin: "Scotland",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Cambus 25 Year Old",
    price: 199.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/cambus/cambus-25-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and complex with notes of vanilla, toffee, and coconut.",
    category: "Grain",
    abv: 46,
    size: "750ml",
    brand: "Cambus",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Desserts, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Glenfiddich 18 Year Old",
    price: 109.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenfiddich/glenfiddich-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and complex with notes of apple, cinnamon, and oak.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenfiddich",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Macallan 18 Year Old Sherry Oak",
    price: 299.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/macallan/macallan-18-year-old-sherry-oak-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, sherry, and wood smoke.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Macallan",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Glenlivet 18 Year Old",
    price: 109.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenlivet/glenlivet-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of toffee, nuts, and a hint of oak.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Glenlivet",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Balvenie 14 Year Old Caribbean Cask",
    price: 79.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/balvenie/balvenie-14-year-old-caribbean-cask-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of tropical fruit, vanilla, and toffee.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Balvenie",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Glenmorangie Quinta Ruban 14 Year Old",
    price: 74.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenmorangie/glenmorangie-quinta-ruban-14-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dark chocolate, mint, and orange.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Glenmorangie",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Dark chocolate, desserts",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Talisker 18 Year Old",
    price: 149.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/talisker/talisker-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of dried fruit, pepper, and sea salt.",
    category: "Single Malt",
    abv: 45.8,
    size: "750ml",
    brand: "Talisker",
    rating: 4.9,
    reviews: "Rich and smoky, perfect for special occasions.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Ardbeg Corryvreckan",
    price: 89.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/ardbeg/ardbeg-corryvreckan-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Heavily peated with notes of black pepper, chocolate, and tar.",
    category: "Single Malt",
    abv: 57.1,
    size: "750ml",
    brand: "Ardbeg",
    rating: 4.9,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Laphroaig Lore",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/laphroaig/laphroaig-lore-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of chocolate, vanilla, and a hint of seaweed.",
    category: "Single Malt",
    abv: 48,
    size: "750ml",
    brand: "Laphroaig",
    rating: 4.8,
    reviews: "Rich and smoky, great for sipping.",
    origin: "Scotland",
    pairing: "Oysters, blue cheese",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Lagavulin Distillers Edition",
    price: 109.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lagavulin/lagavulin-distillers-edition-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of sherry, dried fruit, and a hint of chocolate.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Lagavulin",
    rating: 4.9,
    reviews: "Rich and smoky, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "GlenDronach 18 Year Old",
    price: 149.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glendronach/glendronach-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "GlenDronach",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Aberfeldy 12 Year Old",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/aberfeldy/aberfeldy-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Aberfeldy",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "BenRiach 12 Year Old Sherry Wood",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/benriach/benriach-12-year-old-sherry-wood-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "BenRiach",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Benromach 10 Year Old",
    price: 54.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/benromach/benromach-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of sherry, dried fruit, and a hint of chocolate.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Benromach",
    rating: 4.7,
    reviews: "Rich and smoky, great for sipping.",
    origin: "Scotland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Bruichladdich Classic Laddie",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bruichladdich/bruichladdich-classic-laddie-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of smoke.",
    category: "Single Malt",
    abv: 50,
    size: "750ml",
    brand: "Bruichladdich",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Bunnahabhain 12 Year Old",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/bunnahabhain/bunnahabhain-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, nuts, and a hint of smoke.",
    category: "Single Malt",
    abv: 46.3,
    size: "750ml",
    brand: "Bunnahabhain",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Caol Ila 12 Year Old",
    price: 64.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/caol-ila/caol-ila-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Caol Ila",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Craigellachie 13 Year Old",
    price: 74.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/craigellachie/craigellachie-13-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, spice, and a hint of smoke.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Craigellachie",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Deanston 12 Year Old",
    price: 49.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/deanston/deanston-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of honey, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46.3,
    size: "750ml",
    brand: "Deanston",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Edradour 10 Year Old",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/edradour/edradour-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, spice, and a hint of smoke.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Edradour",
    rating: 4.7,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "GlenDronach 15 Year Old Revival",
    price: 89.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glendronach/glendronach-15-year-old-revival-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "GlenDronach",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Glengoyne 10 Year Old",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glengoyne/glengoyne-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glengoyne",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Glenkinchie 12 Year Old",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenkinchie/glenkinchie-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and light with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Glenkinchie",
    rating: 4.7,
    reviews: "Smooth and light, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Glenlivet Founder's Reserve",
    price: 49.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenlivet/glenlivet-founders-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and fruity with notes of apple, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenlivet",
    rating: 4.7,
    reviews: "Smooth and fruity, great for cocktails.",
    origin: "Scotland",
    pairing: "Cheese, seafood",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Glenmorangie Lasanta 12 Year Old",
    price: 69.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenmorangie/glenmorangie-lasanta-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Glenmorangie",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Glenturret 10 Year Old",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenturret/glenturret-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenturret",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Highland Park 15 Year Old Viking Heart",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/highland-park/highland-park-15-year-old-viking-heart-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of dried fruit, honey, and a hint of peat.",
    category: "Single Malt",
    abv: 44,
    size: "750ml",
    brand: "Highland Park",
    rating: 4.9,
    reviews: "Rich and smoky, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Isle of Jura 10 Year Old",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/isle-of-jura/isle-of-jura-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of smoke.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Isle of Jura",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Kilchoman Machir Bay",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/kilchoman/kilchoman-machir-bay-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Kilchoman",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Lagavulin 8 Year Old",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/lagavulin/lagavulin-8-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Single Malt",
    abv: 48,
    size: "750ml",
    brand: "Lagavulin",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Laphroaig Quarter Cask",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/laphroaig/laphroaig-quarter-cask-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Single Malt",
    abv: 48,
    size: "750ml",
    brand: "Laphroaig",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Macallan Double Cask 12 Year Old",
    price: 69.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/macallan/macallan-double-cask-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Macallan",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Oban Little Bay",
    price: 74.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/oban/oban-little-bay-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of smoke.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Oban",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Old Pulteney 12 Year Old",
    price: 54.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/old-pulteney/old-pulteney-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Old Pulteney",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Port Charlotte 10 Year Old",
    price: 74.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/port-charlotte/port-charlotte-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Single Malt",
    abv: 50,
    size: "750ml",
    brand: "Port Charlotte",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Royal Brackla 12 Year Old",
    price: 59.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/royal-brackla/royal-brackla-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Royal Brackla",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Scapa Skiren",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/scapa/scapa-skiren-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Scapa",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Speyburn 10 Year Old",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/speyburn/speyburn-10-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Speyburn",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Strathisla 12 Year Old",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/strathisla/strathisla-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Strathisla",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Tomatin 12 Year Old",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tomatin/tomatin-12-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Tomatin",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Tullibardine 500 Sherry Cask Finish",
    price: 59.99,
    quantity: 8,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/tullibardine/tullibardine-500-sherry-cask-finish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Tullibardine",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Wolfburn Aurora",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/wolfburn/wolfburn-aurora-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Single Malt",
    abv: 46,
    size: "750ml",
    brand: "Wolfburn",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Macallan Rare Cask",
    price: 299.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/macallan/macallan-rare-cask-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of dried fruits, sherry, and wood smoke.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Macallan",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Dark chocolate, cheese",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Balvenie 21 Year Old PortWood",
    price: 249.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/balvenie/balvenie-21-year-old-portwood-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and rich with notes of fruit, vanilla, and port wine.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Balvenie",
    rating: 4.9,
    reviews: "Smooth and rich, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Glenfarclas 21 Year Old",
    price: 179.99,
    quantity: 4,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenfarclas/glenfarclas-21-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and sherried with notes of dried fruits, nuts, and spices.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Glenfarclas",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Glenfiddich 21 Year Old Reserva Rum Cask Finish",
    price: 239.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenfiddich/glenfiddich-21-year-old-reserva-rum-cask-finish-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and rich with notes of fruit, vanilla, and rum.",
    category: "Single Malt",
    abv: 40,
    size: "750ml",
    brand: "Glenfiddich",
    rating: 4.9,
    reviews: "Smooth and rich, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, fruit tarts",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Glenlivet 21 Year Old Archive",
    price: 229.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/glenlivet/glenlivet-21-year-old-archive-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of oak.",
    category: "Single Malt",
    abv: 43,
    size: "750ml",
    brand: "Glenlivet",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Highland Park 25 Year Old",
    price: 599.99,
    quantity: 2,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/highland-park/highland-park-25-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and smoky with notes of dried fruit, honey, and a hint of peat.",
    category: "Single Malt",
    abv: 45.7,
    size: "750ml",
    brand: "Highland Park",
    rating: 4.9,
    reviews: "Rich and smoky, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Grilled meats, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Johnnie Walker Platinum Label 18 Year Old",
    price: 129.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/johnnie-walker/johnnie-walker-platinum-label-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of smoke.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Johnnie Walker",
    rating: 4.8,
    reviews: "Smooth and rich, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Chivas Regal 18 Year Old",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/chivas-regal/chivas-regal-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Chivas Regal",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Dewars 18 Year Old",
    price: 74.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/dewars/dewars-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of smoke.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Dewars",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Famous Grouse 18 Year Old",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/famous-grouse/famous-grouse-18-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Famous Grouse",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Royal Salute 21 Year Old",
    price: 249.99,
    quantity: 3,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/royal-salute/royal-salute-21-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Royal Salute",
    rating: 4.9,
    reviews: "Smooth and rich, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Compass Box The General",
    price: 399.99,
    quantity: 2,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-the-general-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of smoke.",
    category: "Blended",
    abv: 43,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Monkey Shoulder Smokey Monkey",
    price: 49.99,
    quantity: 9,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/monkey-shoulder/monkey-shoulder-smokey-monkey-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Smooth and rich with notes of smoke, fruit, and vanilla.",
    category: "Blended Malt",
    abv: 40,
    size: "750ml",
    brand: "Monkey Shoulder",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, smoked meats",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Compass Box No Name",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-no-name-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Blended Malt",
    abv: 48.9,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.9,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Douglas Laing Rock Oyster",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/douglas-laing/douglas-laing-rock-oyster-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Blended Malt",
    abv: 46.8,
    size: "750ml",
    brand: "Douglas Laing",
    rating: 4.8,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Johnnie Walker Gold Label Reserve",
    price: 89.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/johnnie-walker/johnnie-walker-gold-label-reserve-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Johnnie Walker",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Ballantine's 17 Year Old",
    price: 79.99,
    quantity: 6,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/ballantines/ballantines-17-year-old-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Ballantine's",
    rating: 4.8,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Compass Box Spice Tree Extravaganza",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-spice-tree-extravaganza-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Rich and spicy with notes of vanilla, clove, and nutmeg.",
    category: "Blended Malt",
    abv: 46,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.9,
    reviews: "Rich and spicy, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Johnnie Walker Blue Label Ghost and Rare",
    price: 399.99,
    quantity: 2,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/johnnie-walker/johnnie-walker-blue-label-ghost-and-rare-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of smoke.",
    category: "Blended",
    abv: 43.8,
    size: "750ml",
    brand: "Johnnie Walker",
    rating: 4.9,
    reviews: "Rich and complex, perfect for special occasions.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Famous Grouse Mellow Gold",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/famous-grouse/famous-grouse-mellow-gold-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended",
    abv: 40,
    size: "750ml",
    brand: "Famous Grouse",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Monkey Shoulder 100% Malt Scotch Whisky",
    price: 39.99,
    quantity: 10,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/monkey-shoulder/monkey-shoulder-100-malt-scotch-whisky.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Smooth and rich with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 40,
    size: "750ml",
    brand: "Monkey Shoulder",
    rating: 4.7,
    reviews: "Smooth and rich, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, desserts",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Compass Box Flaming Heart",
    price: 99.99,
    quantity: 5,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/compass-box/compass-box-flaming-heart-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description: "Heavily peated with notes of smoke, citrus, and vanilla.",
    category: "Blended Malt",
    abv: 48.9,
    size: "750ml",
    brand: "Compass Box",
    rating: 4.9,
    reviews: "Bold and smoky, great for peat lovers.",
    origin: "Scotland",
    pairing: "BBQ, smoked meats",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Douglas Laing Scallywag",
    price: 64.99,
    quantity: 7,
    imageUrl:
      "https://www.masterofmalt.com/whiskies/douglas-laing/douglas-laing-scallywag-whiskey.jpg?alt=1&w=600&h=800&b=0xFFFFFF&q=100",
    description:
      "Rich and complex with notes of fruit, vanilla, and a hint of spice.",
    category: "Blended Malt",
    abv: 46,
    size: "750ml",
    brand: "Douglas Laing",
    rating: 4.8,
    reviews: "Rich and complex, great for sipping.",
    origin: "Scotland",
    pairing: "Cheese, dark chocolate",
    availability: "In Stock",
  },
];

module.exports = scotchWhiskies;
