const champagnes = [
  {
    id: 1,
    name: "Moet & Chandon Imperial Brut",
    price: 59.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-imperial-brut.jpg",
    description:
      "A vibrant, generous, and alluring champagne with a perfect balance of flavors.",
    category: "Champagne",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Veuve Clicquot Yellow Label Brut",
    price: 49.99,
    quantity: 30,
    imageUrl:
      "https://www.example.com/images/veuve-clicquot-yellow-label-brut.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Champagne",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Dom Perignon Vintage",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-vintage.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Laurent-Perrier La Cuvee Brut",
    price: 44.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/laurent-perrier-la-cuvee-brut.jpg",
    description:
      "A delicate and fresh champagne with elegant floral and citrus notes.",
    category: "Champagne",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Perrier-Jouet Grand Brut",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-grand-brut.jpg",
    description:
      "A lively and elegant champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite champagne, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Taittinger Brut Reserve",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/taittinger-brut-reserve.jpg",
    description:
      "A refined and balanced champagne with delicate aromas of peach and white flowers.",
    category: "Champagne",
    brand: "Taittinger",
    rating: 4.7,
    reviews: "A sophisticated champagne, ideal for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Bollinger Special Cuvee Brut",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bollinger-special-cuvee-brut.jpg",
    description:
      "A full-bodied and complex champagne with flavors of pear, brioche, and walnut.",
    category: "Champagne",
    brand: "Bollinger",
    rating: 4.9,
    reviews: "A robust and elegant champagne, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Pol Roger Brut Reserve",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/pol-roger-brut-reserve.jpg",
    description:
      "A well-balanced champagne with notes of white fruit, floral aromas, and brioche.",
    category: "Champagne",
    brand: "Pol Roger",
    rating: 4.8,
    reviews: "A refined champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Krug Grande Cuvee Brut",
    price: 179.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/krug-grande-cuvee-brut.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Krug",
    rating: 5.0,
    reviews: "An exceptional champagne, perfect for the finest occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Louis Roederer Cristal Brut",
    price: 249.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/louis-roederer-cristal-brut.jpg",
    description:
      "A luxurious champagne with a rich and creamy texture and elegant flavors.",
    category: "Champagne",
    brand: "Louis Roederer",
    rating: 5.0,
    reviews:
      "A world-class champagne, perfect for the most special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "Ruinart Blanc de Blancs",
    price: 89.99,
    quantity: 12,
    imageUrl: "https://www.example.com/images/ruinart-blanc-de-blancs.jpg",
    description:
      "A pure and refined champagne with delicate floral and citrus notes.",
    category: "Champagne",
    brand: "Ruinart",
    rating: 4.9,
    reviews: "A sophisticated champagne, perfect for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Charles Heidsieck Brut Reserve",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/charles-heidsieck-brut-reserve.jpg",
    description: "A well-balanced champagne with rich and complex flavors.",
    category: "Champagne",
    brand: "Charles Heidsieck",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Piper-Heidsieck Cuvee Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/piper-heidsieck-cuvee-brut.jpg",
    description:
      "A lively and fresh champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Piper-Heidsieck",
    rating: 4.7,
    reviews: "A classic champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "G.H. Mumm Cordon Rouge Brut",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gh-mumm-cordon-rouge-brut.jpg",
    description:
      "A vibrant and dynamic champagne with notes of fresh fruit and caramel.",
    category: "Champagne",
    brand: "G.H. Mumm",
    rating: 4.7,
    reviews: "A lively champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Ayala Brut Majeur",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ayala-brut-majeur.jpg",
    description:
      "A refined and balanced champagne with delicate floral and fruity notes.",
    category: "Champagne",
    brand: "Ayala",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Nicolas Feuillatte Brut Reserve",
    price: 34.99,
    quantity: 35,
    imageUrl:
      "https://www.example.com/images/nicolas-feuillatte-brut-reserve.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Nicolas Feuillatte",
    rating: 4.6,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Deutz Brut Classic",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/deutz-brut-classic.jpg",
    description:
      "A refined and elegant champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Deutz",
    rating: 4.8,
    reviews: "A sophisticated champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Lanson Black Label Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lanson-black-label-brut.jpg",
    description:
      "A fresh and vibrant champagne with a perfect balance of fruit and acidity.",
    category: "Champagne",
    brand: "Lanson",
    rating: 4.7,
    reviews: "A lively champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Canard-Duchene Cuvee Leonie Brut",
    price: 44.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/canard-duchene-cuvee-leonie-brut.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Canard-Duchene",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Henriot Brut Souverain",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/henriot-brut-souverain.jpg",
    description:
      "A refined and elegant champagne with notes of white fruit and citrus.",
    category: "Champagne",
    brand: "Henriot",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Gosset Grand Reserve Brut",
    price: 64.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/gosset-grand-reserve-brut.jpg",
    description:
      "A rich and full-bodied champagne with flavors of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Gosset",
    rating: 4.9,
    reviews: "An exceptional champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Jacquart Brut Mosaique",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jacquart-brut-mosaique.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Jacquart",
    rating: 4.7,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Palmer & Co Brut Reserve",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/palmer-co-brut-reserve.jpg",
    description:
      "A refined and balanced champagne with notes of white fruit and brioche.",
    category: "Champagne",
    brand: "Palmer & Co",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Bruno Paillard Premiere Cuvee Brut",
    price: 54.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/bruno-paillard-premiere-cuvee-brut.jpg",
    description:
      "A refined and elegant champagne with notes of citrus, white fruit, and brioche.",
    category: "Champagne",
    brand: "Bruno Paillard",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Alfred Gratien Brut Classique",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/alfred-gratien-brut-classique.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Alfred Gratien",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Moet & Chandon Nectar Imperial",
    price: 59.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-nectar-imperial.jpg",
    description:
      "A vibrant, generous, and alluring champagne with a perfect balance of flavors.",
    category: "Champagne",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Veuve Clicquot Rich",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/veuve-clicquot-rich.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Champagne",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Dom Perignon Rose",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-rose.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Laurent-Perrier Ultra Brut",
    price: 44.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/laurent-perrier-ultra-brut.jpg",
    description:
      "A delicate and fresh champagne with elegant floral and citrus notes.",
    category: "Champagne",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Perrier-Jouet Belle Epoque",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-belle-epoque.jpg",
    description:
      "A lively and elegant champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite champagne, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Taittinger Comtes de Champagne",
    price: 49.99,
    quantity: 30,
    imageUrl:
      "https://www.example.com/images/taittinger-comtes-de-champagne.jpg",
    description:
      "A refined and balanced champagne with delicate aromas of peach and white flowers.",
    category: "Champagne",
    brand: "Taittinger",
    rating: 4.7,
    reviews: "A sophisticated champagne, ideal for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Bollinger La Grande Annee",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bollinger-la-grande-annee.jpg",
    description:
      "A full-bodied and complex champagne with flavors of pear, brioche, and walnut.",
    category: "Champagne",
    brand: "Bollinger",
    rating: 4.9,
    reviews: "A robust and elegant champagne, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Pol Roger Sir Winston Churchill",
    price: 54.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/pol-roger-sir-winston-churchill.jpg",
    description:
      "A well-balanced champagne with notes of white fruit, floral aromas, and brioche.",
    category: "Champagne",
    brand: "Pol Roger",
    rating: 4.8,
    reviews: "A refined champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Krug Rose",
    price: 179.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/krug-rose.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Krug",
    rating: 5.0,
    reviews: "An exceptional champagne, perfect for the finest occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Louis Roederer Brut Premier",
    price: 249.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/louis-roederer-brut-premier.jpg",
    description:
      "A luxurious champagne with a rich and creamy texture and elegant flavors.",
    category: "Champagne",
    brand: "Louis Roederer",
    rating: 5.0,
    reviews:
      "A world-class champagne, perfect for the most special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Ruinart Rose",
    price: 89.99,
    quantity: 12,
    imageUrl: "https://www.example.com/images/ruinart-rose.jpg",
    description:
      "A pure and refined champagne with delicate floral and citrus notes.",
    category: "Champagne",
    brand: "Ruinart",
    rating: 4.9,
    reviews: "A sophisticated champagne, perfect for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Charles Heidsieck Rose Reserve",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/charles-heidsieck-rose-reserve.jpg",
    description: "A well-balanced champagne with rich and complex flavors.",
    category: "Champagne",
    brand: "Charles Heidsieck",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Piper-Heidsieck Rose Sauvage",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/piper-heidsieck-rose-sauvage.jpg",
    description:
      "A lively and fresh champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Piper-Heidsieck",
    rating: 4.7,
    reviews: "A classic champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "G.H. Mumm Grand Cordon Rose",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gh-mumm-grand-cordon-rose.jpg",
    description:
      "A vibrant and dynamic champagne with notes of fresh fruit and caramel.",
    category: "Champagne",
    brand: "G.H. Mumm",
    rating: 4.7,
    reviews: "A lively champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Ayala Rose Majeur",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ayala-rose-majeur.jpg",
    description:
      "A refined and balanced champagne with delicate floral and fruity notes.",
    category: "Champagne",
    brand: "Ayala",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Nicolas Feuillatte Brut Rose",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/nicolas-feuillatte-brut-rose.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Nicolas Feuillatte",
    rating: 4.6,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Deutz Brut Rose",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/deutz-brut-rose.jpg",
    description:
      "A refined and elegant champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Deutz",
    rating: 4.8,
    reviews: "A sophisticated champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Lanson Rose Label Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lanson-rose-label-brut.jpg",
    description:
      "A fresh and vibrant champagne with a perfect balance of fruit and acidity.",
    category: "Champagne",
    brand: "Lanson",
    rating: 4.7,
    reviews: "A lively champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Canard-Duchene Cuvee Leonie Rose",
    price: 44.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/canard-duchene-cuvee-leonie-rose.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Canard-Duchene",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Henriot Brut Rose",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/henriot-brut-rose.jpg",
    description:
      "A refined and elegant champagne with notes of white fruit and citrus.",
    category: "Champagne",
    brand: "Henriot",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Gosset Grand Rose Brut",
    price: 64.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/gosset-grand-rose-brut.jpg",
    description:
      "A rich and full-bodied champagne with flavors of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Gosset",
    rating: 4.9,
    reviews: "An exceptional champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Jacquart Rose Mosaique",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jacquart-rose-mosaique.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Jacquart",
    rating: 4.7,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Palmer & Co Rose Reserve",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/palmer-co-rose-reserve.jpg",
    description:
      "A refined and balanced champagne with notes of white fruit and brioche.",
    category: "Champagne",
    brand: "Palmer & Co",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Bruno Paillard Rose Premiere Cuvee",
    price: 54.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/bruno-paillard-rose-premiere-cuvee.jpg",
    description:
      "A refined and elegant champagne with notes of citrus, white fruit, and brioche.",
    category: "Champagne",
    brand: "Bruno Paillard",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Alfred Gratien Rose",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/alfred-gratien-rose.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Alfred Gratien",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Moet & Chandon Grand Vintage",
    price: 59.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-grand-vintage.jpg",
    description:
      "A vibrant, generous, and alluring champagne with a perfect balance of flavors.",
    category: "Champagne",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Veuve Clicquot Vintage Brut",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/veuve-clicquot-vintage-brut.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Champagne",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Dom Perignon P2",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-p2.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Laurent-Perrier Brut Millesime",
    price: 44.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/laurent-perrier-brut-millesime.jpg",
    description:
      "A delicate and fresh champagne with elegant floral and citrus notes.",
    category: "Champagne",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Perrier-Jouet Blason Rose",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-blason-rose.jpg",
    description:
      "A lively and elegant champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite champagne, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Taittinger Prelude Grands Crus",
    price: 49.99,
    quantity: 30,
    imageUrl:
      "https://www.example.com/images/taittinger-prelude-grands-crus.jpg",
    description:
      "A refined and balanced champagne with delicate aromas of peach and white flowers.",
    category: "Champagne",
    brand: "Taittinger",
    rating: 4.7,
    reviews: "A sophisticated champagne, ideal for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Bollinger RD Extra Brut",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bollinger-rd-extra-brut.jpg",
    description:
      "A full-bodied and complex champagne with flavors of pear, brioche, and walnut.",
    category: "Champagne",
    brand: "Bollinger",
    rating: 4.9,
    reviews: "A robust and elegant champagne, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Pol Roger Pure Extra Brut",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/pol-roger-pure-extra-brut.jpg",
    description:
      "A well-balanced champagne with notes of white fruit, floral aromas, and brioche.",
    category: "Champagne",
    brand: "Pol Roger",
    rating: 4.8,
    reviews: "A refined champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "Krug Collection",
    price: 179.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/krug-collection.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Krug",
    rating: 5.0,
    reviews: "An exceptional champagne, perfect for the finest occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Louis Roederer Carte Blanche",
    price: 249.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/louis-roederer-carte-blanche.jpg",
    description:
      "A luxurious champagne with a rich and creamy texture and elegant flavors.",
    category: "Champagne",
    brand: "Louis Roederer",
    rating: 5.0,
    reviews:
      "A world-class champagne, perfect for the most special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Ruinart Brut",
    price: 89.99,
    quantity: 12,
    imageUrl: "https://www.example.com/images/ruinart-brut.jpg",
    description:
      "A pure and refined champagne with delicate floral and citrus notes.",
    category: "Champagne",
    brand: "Ruinart",
    rating: 4.9,
    reviews: "A sophisticated champagne, perfect for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Charles Heidsieck Brut Millesime",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/charles-heidsieck-brut-millesime.jpg",
    description: "A well-balanced champagne with rich and complex flavors.",
    category: "Champagne",
    brand: "Charles Heidsieck",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Piper-Heidsieck Rare Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/piper-heidsieck-rare-brut.jpg",
    description:
      "A lively and fresh champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Piper-Heidsieck",
    rating: 4.7,
    reviews: "A classic champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "G.H. Mumm Demi-Sec",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gh-mumm-demi-sec.jpg",
    description:
      "A vibrant and dynamic champagne with notes of fresh fruit and caramel.",
    category: "Champagne",
    brand: "G.H. Mumm",
    rating: 4.7,
    reviews: "A lively champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Ayala Blanc de Blancs",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ayala-blanc-de-blancs.jpg",
    description:
      "A refined and balanced champagne with delicate floral and fruity notes.",
    category: "Champagne",
    brand: "Ayala",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Nicolas Feuillatte Palmes d'Or",
    price: 34.99,
    quantity: 35,
    imageUrl:
      "https://www.example.com/images/nicolas-feuillatte-palmes-dor.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Nicolas Feuillatte",
    rating: 4.6,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Deutz Amour de Deutz",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/deutz-amour-de-deutz.jpg",
    description:
      "A refined and elegant champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Deutz",
    rating: 4.8,
    reviews: "A sophisticated champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Lanson Gold Label Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lanson-gold-label-brut.jpg",
    description:
      "A fresh and vibrant champagne with a perfect balance of fruit and acidity.",
    category: "Champagne",
    brand: "Lanson",
    rating: 4.7,
    reviews: "A lively champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Canard-Duchene Authentic Brut",
    price: 44.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/canard-duchene-authentic-brut.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Canard-Duchene",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Henriot Blanc de Blancs",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/henriot-blanc-de-blancs.jpg",
    description:
      "A refined and elegant champagne with notes of white fruit and citrus.",
    category: "Champagne",
    brand: "Henriot",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Gosset Celebris",
    price: 64.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/gosset-celebris.jpg",
    description:
      "A rich and full-bodied champagne with flavors of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Gosset",
    rating: 4.9,
    reviews: "An exceptional champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Jacquart Alpha",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jacquart-alpha.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Jacquart",
    rating: 4.7,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Palmer & Co Blanc de Noirs",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/palmer-co-blanc-de-noirs.jpg",
    description:
      "A refined and balanced champagne with notes of white fruit and brioche.",
    category: "Champagne",
    brand: "Palmer & Co",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Bruno Paillard Dosage Zero",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bruno-paillard-dosage-zero.jpg",
    description:
      "A refined and elegant champagne with notes of citrus, white fruit, and brioche.",
    category: "Champagne",
    brand: "Bruno Paillard",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Alfred Gratien Millesime",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/alfred-gratien-millesime.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Alfred Gratien",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Moet & Chandon Ice Imperial",
    price: 59.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-ice-imperial.jpg",
    description:
      "A vibrant, generous, and alluring champagne with a perfect balance of flavors.",
    category: "Champagne",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Veuve Clicquot Demi-Sec",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/veuve-clicquot-demi-sec.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Champagne",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Dom Perignon Luminous",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-luminous.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Laurent-Perrier Grand Siecle",
    price: 44.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/laurent-perrier-grand-siecle.jpg",
    description:
      "A delicate and fresh champagne with elegant floral and citrus notes.",
    category: "Champagne",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Perrier-Jouet Brut Millesime",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-brut-millesime.jpg",
    description:
      "A lively and elegant champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite champagne, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Taittinger Nocturne",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/taittinger-nocturne.jpg",
    description:
      "A refined and balanced champagne with delicate aromas of peach and white flowers.",
    category: "Champagne",
    brand: "Taittinger",
    rating: 4.7,
    reviews: "A sophisticated champagne, ideal for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Bollinger PNVZ 16",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bollinger-pnvz-16.jpg",
    description:
      "A full-bodied and complex champagne with flavors of pear, brioche, and walnut.",
    category: "Champagne",
    brand: "Bollinger",
    rating: 4.9,
    reviews: "A robust and elegant champagne, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Pol Roger Vintage",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/pol-roger-vintage.jpg",
    description:
      "A well-balanced champagne with notes of white fruit, floral aromas, and brioche.",
    category: "Champagne",
    brand: "Pol Roger",
    rating: 4.8,
    reviews: "A refined champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "Krug Vintage",
    price: 179.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/krug-vintage.jpg",
    description:
      "A prestigious champagne with a rich and complex flavor profile.",
    category: "Champagne",
    brand: "Krug",
    rating: 5.0,
    reviews: "An exceptional champagne, perfect for the finest occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Louis Roederer Vintage",
    price: 249.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/louis-roederer-vintage.jpg",
    description:
      "A luxurious champagne with a rich and creamy texture and elegant flavors.",
    category: "Champagne",
    brand: "Louis Roederer",
    rating: 5.0,
    reviews:
      "A world-class champagne, perfect for the most special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Ruinart Blanc de Blancs Vintage",
    price: 89.99,
    quantity: 12,
    imageUrl:
      "https://www.example.com/images/ruinart-blanc-de-blancs-vintage.jpg",
    description:
      "A pure and refined champagne with delicate floral and citrus notes.",
    category: "Champagne",
    brand: "Ruinart",
    rating: 4.9,
    reviews: "A sophisticated champagne, perfect for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Charles Heidsieck Blanc des Millenaires",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/charles-heidsieck-blanc-des-millenaires.jpg",
    description: "A well-balanced champagne with rich and complex flavors.",
    category: "Champagne",
    brand: "Charles Heidsieck",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Piper-Heidsieck Sublime Demi-Sec",
    price: 39.99,
    quantity: 30,
    imageUrl:
      "https://www.example.com/images/piper-heidsieck-sublime-demi-sec.jpg",
    description:
      "A lively and fresh champagne with a harmonious blend of flavors.",
    category: "Champagne",
    brand: "Piper-Heidsieck",
    rating: 4.7,
    reviews: "A classic champagne, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "G.H. Mumm Grand Cordon Vintage",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gh-mumm-grand-cordon-vintage.jpg",
    description:
      "A vibrant and dynamic champagne with notes of fresh fruit and caramel.",
    category: "Champagne",
    brand: "G.H. Mumm",
    rating: 4.7,
    reviews: "A lively champagne, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Ayala Brut Nature",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ayala-brut-nature.jpg",
    description:
      "A refined and balanced champagne with delicate floral and fruity notes.",
    category: "Champagne",
    brand: "Ayala",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Nicolas Feuillatte Cuvee 225",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/nicolas-feuillatte-cuvee-225.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Nicolas Feuillatte",
    rating: 4.6,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Deutz Blanc de Blancs Millesime",
    price: 54.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/deutz-blanc-de-blancs-millesime.jpg",
    description:
      "A refined and elegant champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Deutz",
    rating: 4.8,
    reviews: "A sophisticated champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Lanson Noble Cuvee Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lanson-noble-cuvee-brut.jpg",
    description:
      "A fresh and vibrant champagne with a perfect balance of fruit and acidity.",
    category: "Champagne",
    brand: "Lanson",
    rating: 4.7,
    reviews: "A lively champagne, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Canard-Duchene Charles VII Brut",
    price: 44.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/canard-duchene-charles-vii-brut.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Canard-Duchene",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Henriot Enchanteleurs",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/henriot-enchanteleurs.jpg",
    description:
      "A refined and elegant champagne with notes of white fruit and citrus.",
    category: "Champagne",
    brand: "Henriot",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Gosset Grand Millesime",
    price: 64.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/gosset-grand-millesime.jpg",
    description:
      "A rich and full-bodied champagne with flavors of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Gosset",
    rating: 4.9,
    reviews: "An exceptional champagne, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Jacquart Millesime",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jacquart-millesime.jpg",
    description:
      "A fresh and lively champagne with notes of apple, pear, and citrus.",
    category: "Champagne",
    brand: "Jacquart",
    rating: 4.7,
    reviews: "A delightful champagne, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Palmer & Co Vintage",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/palmer-co-vintage.jpg",
    description:
      "A refined and balanced champagne with notes of white fruit and brioche.",
    category: "Champagne",
    brand: "Palmer & Co",
    rating: 4.8,
    reviews: "A sophisticated champagne, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Bruno Paillard NPU",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bruno-paillard-npu.jpg",
    description:
      "A refined and elegant champagne with notes of citrus, white fruit, and brioche.",
    category: "Champagne",
    brand: "Bruno Paillard",
    rating: 4.8,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Alfred Gratien Cuvee Paradis",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/alfred-gratien-cuvee-paradis.jpg",
    description:
      "A rich and complex champagne with notes of apple, pear, and brioche.",
    category: "Champagne",
    brand: "Alfred Gratien",
    rating: 4.7,
    reviews: "A delightful champagne, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
];

module.exports = champagnes;
