const sparklingWines = [
  {
    id: 1,
    name: "La Marca Prosecco",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/la-marca-prosecco.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "La Marca",
    rating: 4.7,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Mionetto Prosecco Brut",
    price: 12.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/mionetto-prosecco-brut.jpg",
    description: "A vibrant and fruity prosecco with a hint of sweetness.",
    category: "Sparkling Wine",
    brand: "Mionetto",
    rating: 4.6,
    reviews: "A refreshing and easy-to-drink sparkling wine.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Segura Viudas Cava Brut",
    price: 9.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/segura-viudas-cava-brut.jpg",
    description: "Crisp and clean with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Segura Viudas",
    rating: 4.5,
    reviews: "An excellent value cava, great for toasts and celebrations.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Freixenet Cordon Negro Brut",
    price: 10.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/freixenet-cordon-negro-brut.jpg",
    description: "Smooth and light with a hint of honey and apple.",
    category: "Sparkling Wine",
    brand: "Freixenet",
    rating: 4.4,
    reviews: "A classic cava, perfect for any occasion.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Cavicchioli 1928 Prosecco",
    price: 13.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/cavicchioli-1928-prosecco.jpg",
    description: "Light and refreshing with notes of pear and apple.",
    category: "Sparkling Wine",
    brand: "Cavicchioli",
    rating: 4.5,
    reviews: "A delightful prosecco, ideal for toasts and celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 6,
    name: "Chandon Brut Classic",
    price: 19.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/chandon-brut-classic.jpg",
    description: "Crisp and refreshing with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Chandon",
    rating: 4.7,
    reviews: "A refined sparkling wine, perfect for any celebration.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Zonin Prosecco",
    price: 11.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/zonin-prosecco.jpg",
    description: "Fruity and floral with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Zonin",
    rating: 4.5,
    reviews: "A refreshing prosecco, great for any occasion.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Villa Sandi Prosecco",
    price: 15.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/villa-sandi-prosecco.jpg",
    description: "Elegant and fruity with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Villa Sandi",
    rating: 4.6,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 9,
    name: "Roederer Estate Brut",
    price: 25.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/roederer-estate-brut.jpg",
    description: "Rich and complex with notes of pear and hazelnut.",
    category: "Sparkling Wine",
    brand: "Roederer Estate",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 10,
    name: "Gruet Brut",
    price: 15.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/gruet-brut.jpg",
    description: "Crisp and lively with notes of apple and citrus.",
    category: "Sparkling Wine",
    brand: "Gruet",
    rating: 4.7,
    reviews: "A refreshing sparkling wine, perfect for any occasion.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 11,
    name: "J Vineyards Brut Cuvee 20",
    price: 27.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/j-vineyards-brut-cuvee-20.jpg",
    description: "Elegant and balanced with notes of green apple and pear.",
    category: "Sparkling Wine",
    brand: "J Vineyards",
    rating: 4.8,
    reviews: "A refined sparkling wine, perfect for celebrations.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 12,
    name: "Piper Sonoma Brut",
    price: 18.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/piper-sonoma-brut.jpg",
    description: "Crisp and refreshing with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Piper Sonoma",
    rating: 4.6,
    reviews: "A delightful sparkling wine, great for any occasion.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 13,
    name: "Gloria Ferrer Blanc de Noirs",
    price: 22.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/gloria-ferrer-blanc-de-noirs.jpg",
    description: "Rich and fruity with notes of raspberry and strawberry.",
    category: "Sparkling Wine",
    brand: "Gloria Ferrer",
    rating: 4.7,
    reviews: "A sophisticated sparkling wine, perfect for celebrations.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 14,
    name: "Luc Belaire Rare Rose",
    price: 29.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/luc-belaire-rare-rose.jpg",
    description: "Elegant and fruity with notes of blackberry and raspberry.",
    category: "Sparkling Wine",
    brand: "Luc Belaire",
    rating: 4.8,
    reviews: "A refined sparkling wine, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 15,
    name: "Cavicchioli 1928 Sparkling Rose",
    price: 13.99,
    quantity: 55,
    imageUrl:
      "https://www.example.com/images/cavicchioli-1928-sparkling-rose.jpg",
    description: "Light and refreshing with notes of strawberry and raspberry.",
    category: "Sparkling Wine",
    brand: "Cavicchioli",
    rating: 4.5,
    reviews:
      "A delightful sparkling wine, perfect for toasts and celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 16,
    name: "Santa Margherita Prosecco Superiore",
    price: 19.99,
    quantity: 40,
    imageUrl:
      "https://www.example.com/images/santa-margherita-prosecco-superiore.jpg",
    description: "Crisp and refreshing with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Santa Margherita",
    rating: 4.7,
    reviews: "A refined prosecco, perfect for any celebration.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 17,
    name: "Cantine Maschio Prosecco",
    price: 10.99,
    quantity: 65,
    imageUrl: "https://www.example.com/images/cantine-maschio-prosecco.jpg",
    description: "Smooth and light with a hint of honey and apple.",
    category: "Sparkling Wine",
    brand: "Cantine Maschio",
    rating: 4.4,
    reviews: "A classic prosecco, perfect for any occasion.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 18,
    name: "Mumm Napa Brut Prestige",
    price: 24.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/mumm-napa-brut-prestige.jpg",
    description: "Rich and complex with notes of pear and hazelnut.",
    category: "Sparkling Wine",
    brand: "Mumm Napa",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 19,
    name: "Ruffino Prosecco",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/ruffino-prosecco.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "Ruffino",
    rating: 4.7,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 20,
    name: "Cleto Chiarli Brut de Noir Rose",
    price: 11.99,
    quantity: 60,
    imageUrl:
      "https://www.example.com/images/cleto-chiarli-brut-de-noir-rose.jpg",
    description:
      "A vibrant and fruity sparkling rose with a hint of sweetness.",
    category: "Sparkling Wine",
    brand: "Cleto Chiarli",
    rating: 4.6,
    reviews: "A refreshing and easy-to-drink sparkling wine.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 21,
    name: "Ferrari Brut",
    price: 19.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/ferrari-brut.jpg",
    description: "Elegant and balanced with notes of green apple and pear.",
    category: "Sparkling Wine",
    brand: "Ferrari",
    rating: 4.7,
    reviews: "A refined sparkling wine, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 22,
    name: "Jaume Serra Cristalino Cava Brut",
    price: 8.99,
    quantity: 70,
    imageUrl:
      "https://www.example.com/images/jaume-serra-cristalino-cava-brut.jpg",
    description: "Crisp and clean with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Jaume Serra",
    rating: 4.5,
    reviews: "An excellent value cava, great for toasts and celebrations.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 23,
    name: "Tiamo Organic Prosecco",
    price: 13.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/tiamo-organic-prosecco.jpg",
    description: "Light and refreshing with notes of pear and apple.",
    category: "Sparkling Wine",
    brand: "Tiamo",
    rating: 4.5,
    reviews: "A delightful prosecco, ideal for toasts and celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 24,
    name: "Lucien Albrecht Cremant d'Alsace Brut",
    price: 19.99,
    quantity: 40,
    imageUrl:
      "https://www.example.com/images/lucien-albrecht-cremant-d'alsace-brut.jpg",
    description: "Crisp and refreshing with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Lucien Albrecht",
    rating: 4.7,
    reviews: "A refined sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 25,
    name: "Schramsberg Blanc de Blancs",
    price: 32.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/schramsberg-blanc-de-blancs.jpg",
    description: "Elegant and fruity with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Schramsberg",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 26,
    name: "Nino Franco Rustico Prosecco",
    price: 17.99,
    quantity: 45,
    imageUrl: "https://www.example.com/images/nino-franco-rustico-prosecco.jpg",
    description: "Fruity and floral with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Nino Franco",
    rating: 4.6,
    reviews: "A delightful prosecco, great for any occasion.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 27,
    name: "Bisol Jeio Prosecco",
    price: 15.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/bisol-jeio-prosecco.jpg",
    description: "Elegant and fruity with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Bisol",
    rating: 4.6,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 28,
    name: "Bellissima Zero Sugar Sparkling Wine",
    price: 19.99,
    quantity: 40,
    imageUrl:
      "https://www.example.com/images/bellissima-zero-sugar-sparkling-wine.jpg",
    description: "Crisp and refreshing with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Bellissima",
    rating: 4.7,
    reviews: "A refined sparkling wine, perfect for any celebration.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 29,
    name: "Cinzano Asti",
    price: 11.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/cinzano-asti.jpg",
    description: "Smooth and light with a hint of honey and apple.",
    category: "Sparkling Wine",
    brand: "Cinzano",
    rating: 4.4,
    reviews: "A classic sparkling wine, perfect for any occasion.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 30,
    name: "Riondo Prosecco",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/riondo-prosecco.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "Riondo",
    rating: 4.7,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 31,
    name: "Martini & Rossi Asti",
    price: 13.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/martini-rossi-asti.jpg",
    description: "Light and refreshing with notes of pear and apple.",
    category: "Sparkling Wine",
    brand: "Martini & Rossi",
    rating: 4.5,
    reviews: "A delightful sparkling wine, ideal for toasts and celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 32,
    name: "Cantina Montelliana Prosecco",
    price: 12.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/cantina-montelliana-prosecco.jpg",
    description: "A vibrant and fruity prosecco with a hint of sweetness.",
    category: "Sparkling Wine",
    brand: "Cantina Montelliana",
    rating: 4.6,
    reviews: "A refreshing and easy-to-drink sparkling wine.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 33,
    name: "Korbel Brut",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/korbel-brut.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "Korbel",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for celebrations.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 34,
    name: "Brut d'Argent Blanc de Blancs",
    price: 12.99,
    quantity: 55,
    imageUrl:
      "https://www.example.com/images/brut-d'argent-blanc-de-blancs.jpg",
    description: "Light and refreshing with notes of pear and apple.",
    category: "Sparkling Wine",
    brand: "Brut d'Argent",
    rating: 4.5,
    reviews: "A delightful sparkling wine, ideal for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 35,
    name: "Ferrari Perle",
    price: 29.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ferrari-perle.jpg",
    description: "Elegant and fruity with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Ferrari",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 36,
    name: "Louis Bouillot Perle d'Aurore Brut Rose",
    price: 17.99,
    quantity: 45,
    imageUrl:
      "https://www.example.com/images/louis-bouillot-perle-d'aurore-brut-rose.jpg",
    description: "Fruity and floral with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Louis Bouillot",
    rating: 4.6,
    reviews: "A delightful sparkling wine, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 37,
    name: "Anna de Codorniu Brut Rose",
    price: 15.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/anna-de-codorniu-brut-rose.jpg",
    description: "Elegant and fruity with a crisp finish.",
    category: "Sparkling Wine",
    brand: "Anna de Codorniu",
    rating: 4.6,
    reviews: "A delightful sparkling wine, perfect for celebrations.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 38,
    name: "Zardetto Prosecco Brut",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/zardetto-prosecco-brut.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "Zardetto",
    rating: 4.7,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 39,
    name: "Conde de Caralt Cava Brut",
    price: 9.99,
    quantity: 70,
    imageUrl: "https://www.example.com/images/conde-de-caralt-cava-brut.jpg",
    description: "Crisp and clean with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Conde de Caralt",
    rating: 4.5,
    reviews: "An excellent value cava, great for toasts and celebrations.",
    origin: "Spain",
    availability: "In Stock",
  },
  {
    id: 40,
    name: "Francois Montand Brut",
    price: 12.99,
    quantity: 60,
    imageUrl: "https://www.example.com/images/francois-montand-brut.jpg",
    description: "Smooth and light with a hint of honey and apple.",
    category: "Sparkling Wine",
    brand: "Francois Montand",
    rating: 4.4,
    reviews: "A classic sparkling wine, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 41,
    name: "Banfi Rosa Regale",
    price: 19.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/banfi-rosa-regale.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "Banfi",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 42,
    name: "Gancia Asti",
    price: 13.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/gancia-asti.jpg",
    description: "Light and refreshing with notes of pear and apple.",
    category: "Sparkling Wine",
    brand: "Gancia",
    rating: 4.5,
    reviews: "A delightful sparkling wine, ideal for toasts and celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 43,
    name: "Scharffenberger Brut",
    price: 19.99,
    quantity: 40,
    imageUrl: "https://www.example.com/images/scharffenberger-brut.jpg",
    description: "Crisp and refreshing with notes of green apple and citrus.",
    category: "Sparkling Wine",
    brand: "Scharffenberger",
    rating: 4.7,
    reviews: "A refined sparkling wine, perfect for any celebration.",
    origin: "USA",
    availability: "In Stock",
  },
  {
    id: 44,
    name: "Adami Garbel Prosecco Brut",
    price: 14.99,
    quantity: 50,
    imageUrl: "https://www.example.com/images/adami-garbel-prosecco-brut.jpg",
    description: "Delicate and aromatic with a crisp, refreshing finish.",
    category: "Sparkling Wine",
    brand: "Adami",
    rating: 4.7,
    reviews: "A delightful prosecco, perfect for celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 45,
    name: "Mionetto Il Prosecco",
    price: 12.99,
    quantity: 55,
    imageUrl: "https://www.example.com/images/mionetto-il-prosecco.jpg",
    description: "Light and refreshing with notes of pear and apple.",
    category: "Sparkling Wine",
    brand: "Mionetto",
    rating: 4.5,
    reviews: "A delightful sparkling wine, ideal for toasts and celebrations.",
    origin: "Italy",
    availability: "In Stock",
  },
  {
    id: 46,
    name: "Moet & Chandon Ice Imperial",
    price: 59.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-ice-imperial.jpg",
    description:
      "A vibrant, generous, and alluring sparkling wine with a perfect balance of flavors.",
    category: "Sparkling Wine",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant sparkling wine, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 47,
    name: "Veuve Clicquot Demi-Sec",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/veuve-clicquot-demi-sec.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Sparkling Wine",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional sparkling wine, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 48,
    name: "Dom Perignon Luminous",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-luminous.jpg",
    description:
      "A prestigious sparkling wine with a rich and complex flavor profile.",
    category: "Sparkling Wine",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 49,
    name: "Laurent-Perrier Grand Siecle",
    price: 44.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/laurent-perrier-grand-siecle.jpg",
    description:
      "A delicate and fresh sparkling wine with elegant floral and citrus notes.",
    category: "Sparkling Wine",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews:
      "A delightful sparkling wine, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 50,
    name: "Perrier-Jouet Brut Millesime",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-brut-millesime.jpg",
    description:
      "A lively and elegant sparkling wine with a harmonious blend of flavors.",
    category: "Sparkling Wine",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite sparkling wine, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 51,
    name: "Taittinger Nocturne",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/taittinger-nocturne.jpg",
    description:
      "A refined and balanced sparkling wine with delicate aromas of peach and white flowers.",
    category: "Sparkling Wine",
    brand: "Taittinger",
    rating: 4.7,
    reviews: "A sophisticated sparkling wine, ideal for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 52,
    name: "Bollinger PNVZ 16",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bollinger-pnvz-16.jpg",
    description:
      "A full-bodied and complex sparkling wine with flavors of pear, brioche, and walnut.",
    category: "Sparkling Wine",
    brand: "Bollinger",
    rating: 4.9,
    reviews:
      "A robust and elegant sparkling wine, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 53,
    name: "Pol Roger Vintage",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/pol-roger-vintage.jpg",
    description:
      "A well-balanced sparkling wine with notes of white fruit, floral aromas, and brioche.",
    category: "Sparkling Wine",
    brand: "Pol Roger",
    rating: 4.8,
    reviews: "A refined sparkling wine, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 54,
    name: "Krug Vintage",
    price: 179.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/krug-vintage.jpg",
    description:
      "A prestigious sparkling wine with a rich and complex flavor profile.",
    category: "Sparkling Wine",
    brand: "Krug",
    rating: 5.0,
    reviews: "An exceptional sparkling wine, perfect for the finest occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 55,
    name: "Louis Roederer Vintage",
    price: 249.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/louis-roederer-vintage.jpg",
    description:
      "A luxurious sparkling wine with a rich and creamy texture and elegant flavors.",
    category: "Sparkling Wine",
    brand: "Louis Roederer",
    rating: 5.0,
    reviews:
      "A world-class sparkling wine, perfect for the most special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 56,
    name: "Ruinart Blanc de Blancs Vintage",
    price: 89.99,
    quantity: 12,
    imageUrl:
      "https://www.example.com/images/ruinart-blanc-de-blancs-vintage.jpg",
    description:
      "A pure and refined sparkling wine with delicate floral and citrus notes.",
    category: "Sparkling Wine",
    brand: "Ruinart",
    rating: 4.9,
    reviews: "A sophisticated sparkling wine, perfect for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 57,
    name: "Charles Heidsieck Blanc des Millenaires",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/charles-heidsieck-blanc-des-millenaires.jpg",
    description:
      "A well-balanced sparkling wine with rich and complex flavors.",
    category: "Sparkling Wine",
    brand: "Charles Heidsieck",
    rating: 4.8,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 58,
    name: "Piper-Heidsieck Sublime Demi-Sec",
    price: 39.99,
    quantity: 30,
    imageUrl:
      "https://www.example.com/images/piper-heidsieck-sublime-demi-sec.jpg",
    description:
      "A lively and fresh sparkling wine with a harmonious blend of flavors.",
    category: "Sparkling Wine",
    brand: "Piper-Heidsieck",
    rating: 4.7,
    reviews: "A classic sparkling wine, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 59,
    name: "G.H. Mumm Grand Cordon Vintage",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gh-mumm-grand-cordon-vintage.jpg",
    description:
      "A vibrant and dynamic sparkling wine with notes of fresh fruit and caramel.",
    category: "Sparkling Wine",
    brand: "G.H. Mumm",
    rating: 4.7,
    reviews: "A lively sparkling wine, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 60,
    name: "Ayala Brut Nature",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ayala-brut-nature.jpg",
    description:
      "A refined and balanced sparkling wine with delicate floral and fruity notes.",
    category: "Sparkling Wine",
    brand: "Ayala",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 61,
    name: "Nicolas Feuillatte Cuvee 225",
    price: 34.99,
    quantity: 35,
    imageUrl: "https://www.example.com/images/nicolas-feuillatte-cuvee-225.jpg",
    description:
      "A fresh and lively sparkling wine with notes of apple, pear, and citrus.",
    category: "Sparkling Wine",
    brand: "Nicolas Feuillatte",
    rating: 4.6,
    reviews: "A delightful sparkling wine, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 62,
    name: "Deutz Blanc de Blancs Millesime",
    price: 54.99,
    quantity: 20,
    imageUrl:
      "https://www.example.com/images/deutz-blanc-de-blancs-millesime.jpg",
    description:
      "A refined and elegant sparkling wine with notes of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Deutz",
    rating: 4.8,
    reviews:
      "A sophisticated sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 63,
    name: "Lanson Noble Cuvee Brut",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lanson-noble-cuvee-brut.jpg",
    description:
      "A fresh and vibrant sparkling wine with a perfect balance of fruit and acidity.",
    category: "Sparkling Wine",
    brand: "Lanson",
    rating: 4.7,
    reviews: "A lively sparkling wine, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 64,
    name: "Canard-Duchene Charles VII Brut",
    price: 44.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/canard-duchene-charles-vii-brut.jpg",
    description:
      "A rich and complex sparkling wine with notes of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Canard-Duchene",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 65,
    name: "Henriot Enchanteleurs",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/henriot-enchanteleurs.jpg",
    description:
      "A refined and elegant sparkling wine with notes of white fruit and citrus.",
    category: "Sparkling Wine",
    brand: "Henriot",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 66,
    name: "Gosset Grand Millesime",
    price: 64.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/gosset-grand-millesime.jpg",
    description:
      "A rich and full-bodied sparkling wine with flavors of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Gosset",
    rating: 4.9,
    reviews: "An exceptional sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 67,
    name: "Jacquart Millesime",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jacquart-millesime.jpg",
    description:
      "A fresh and lively sparkling wine with notes of apple, pear, and citrus.",
    category: "Sparkling Wine",
    brand: "Jacquart",
    rating: 4.7,
    reviews: "A delightful sparkling wine, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 68,
    name: "Palmer & Co Vintage",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/palmer-co-vintage.jpg",
    description:
      "A refined and balanced sparkling wine with notes of white fruit and brioche.",
    category: "Sparkling Wine",
    brand: "Palmer & Co",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 69,
    name: "Bruno Paillard NPU",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bruno-paillard-npu.jpg",
    description:
      "A refined and elegant sparkling wine with notes of citrus, white fruit, and brioche.",
    category: "Sparkling Wine",
    brand: "Bruno Paillard",
    rating: 4.8,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 70,
    name: "Alfred Gratien Cuvee Paradis",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/alfred-gratien-cuvee-paradis.jpg",
    description:
      "A rich and complex sparkling wine with notes of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Alfred Gratien",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 71,
    name: "Moet & Chandon Nectar Imperial",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-nectar-imperial.jpg",
    description:
      "A vibrant, generous, and alluring sparkling wine with a perfect balance of flavors.",
    category: "Sparkling Wine",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant sparkling wine, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 72,
    name: "Veuve Clicquot Brut Yellow Label",
    price: 54.99,
    quantity: 30,
    imageUrl:
      "https://www.example.com/images/veuve-clicquot-brut-yellow-label.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Sparkling Wine",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional sparkling wine, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 73,
    name: "Dom Perignon Vintage",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-vintage.jpg",
    description:
      "A prestigious sparkling wine with a rich and complex flavor profile.",
    category: "Sparkling Wine",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 74,
    name: "Laurent-Perrier Cuvee Rose",
    price: 69.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/laurent-perrier-cuvee-rose.jpg",
    description:
      "A delicate and fresh sparkling wine with elegant floral and citrus notes.",
    category: "Sparkling Wine",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews:
      "A delightful sparkling wine, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 75,
    name: "Perrier-Jouet Belle Epoque",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-belle-epoque.jpg",
    description:
      "A lively and elegant sparkling wine with a harmonious blend of flavors.",
    category: "Sparkling Wine",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite sparkling wine, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 76,
    name: "Taittinger Brut Reserve",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/taittinger-brut-reserve.jpg",
    description:
      "A refined and balanced sparkling wine with delicate aromas of peach and white flowers.",
    category: "Sparkling Wine",
    brand: "Taittinger",
    rating: 4.7,
    reviews: "A sophisticated sparkling wine, ideal for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 77,
    name: "Bollinger Special Cuvee",
    price: 59.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bollinger-special-cuvee.jpg",
    description:
      "A full-bodied and complex sparkling wine with flavors of pear, brioche, and walnut.",
    category: "Sparkling Wine",
    brand: "Bollinger",
    rating: 4.9,
    reviews:
      "A robust and elegant sparkling wine, perfect for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 78,
    name: "Pol Roger Reserve",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/pol-roger-reserve.jpg",
    description:
      "A well-balanced sparkling wine with notes of white fruit, floral aromas, and brioche.",
    category: "Sparkling Wine",
    brand: "Pol Roger",
    rating: 4.8,
    reviews: "A refined sparkling wine, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 79,
    name: "Krug Grande Cuvee",
    price: 179.99,
    quantity: 10,
    imageUrl: "https://www.example.com/images/krug-grande-cuvee.jpg",
    description:
      "A prestigious sparkling wine with a rich and complex flavor profile.",
    category: "Sparkling Wine",
    brand: "Krug",
    rating: 5.0,
    reviews: "An exceptional sparkling wine, perfect for the finest occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 80,
    name: "Louis Roederer Cristal",
    price: 249.99,
    quantity: 8,
    imageUrl: "https://www.example.com/images/louis-roederer-cristal.jpg",
    description:
      "A luxurious sparkling wine with a rich and creamy texture and elegant flavors.",
    category: "Sparkling Wine",
    brand: "Louis Roederer",
    rating: 5.0,
    reviews:
      "A world-class sparkling wine, perfect for the most special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 81,
    name: "Ruinart Rose",
    price: 89.99,
    quantity: 12,
    imageUrl: "https://www.example.com/images/ruinart-rose.jpg",
    description:
      "A pure and refined sparkling wine with delicate floral and citrus notes.",
    category: "Sparkling Wine",
    brand: "Ruinart",
    rating: 4.9,
    reviews: "A sophisticated sparkling wine, perfect for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 82,
    name: "Charles Heidsieck Rose Reserve",
    price: 49.99,
    quantity: 25,
    imageUrl:
      "https://www.example.com/images/charles-heidsieck-rose-reserve.jpg",
    description:
      "A well-balanced sparkling wine with rich and complex flavors.",
    category: "Sparkling Wine",
    brand: "Charles Heidsieck",
    rating: 4.8,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 83,
    name: "Piper-Heidsieck Rose Sauvage",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/piper-heidsieck-rose-sauvage.jpg",
    description:
      "A lively and fresh sparkling wine with a harmonious blend of flavors.",
    category: "Sparkling Wine",
    brand: "Piper-Heidsieck",
    rating: 4.7,
    reviews: "A classic sparkling wine, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 84,
    name: "G.H. Mumm Rose",
    price: 49.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/gh-mumm-rose.jpg",
    description:
      "A vibrant and dynamic sparkling wine with notes of fresh fruit and caramel.",
    category: "Sparkling Wine",
    brand: "G.H. Mumm",
    rating: 4.7,
    reviews: "A lively sparkling wine, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 85,
    name: "Ayala Rose Majeur",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/ayala-rose-majeur.jpg",
    description:
      "A refined and balanced sparkling wine with delicate floral and fruity notes.",
    category: "Sparkling Wine",
    brand: "Ayala",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for elegant occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 86,
    name: "Nicolas Feuillatte Reserve Exclusive Rose",
    price: 34.99,
    quantity: 35,
    imageUrl:
      "https://www.example.com/images/nicolas-feuillatte-reserve-exclusive-rose.jpg",
    description:
      "A fresh and lively sparkling wine with notes of apple, pear, and citrus.",
    category: "Sparkling Wine",
    brand: "Nicolas Feuillatte",
    rating: 4.6,
    reviews: "A delightful sparkling wine, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 87,
    name: "Deutz Rose",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/deutz-rose.jpg",
    description:
      "A refined and elegant sparkling wine with notes of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Deutz",
    rating: 4.8,
    reviews:
      "A sophisticated sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 88,
    name: "Lanson Rose Label",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/lanson-rose-label.jpg",
    description:
      "A fresh and vibrant sparkling wine with a perfect balance of fruit and acidity.",
    category: "Sparkling Wine",
    brand: "Lanson",
    rating: 4.7,
    reviews: "A lively sparkling wine, ideal for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 89,
    name: "Canard-Duchene Rose",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/canard-duchene-rose.jpg",
    description:
      "A rich and complex sparkling wine with notes of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Canard-Duchene",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 90,
    name: "Henriot Rose Noire",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/henriot-rose-noire.jpg",
    description:
      "A refined and elegant sparkling wine with notes of white fruit and citrus.",
    category: "Sparkling Wine",
    brand: "Henriot",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 91,
    name: "Gosset Rose",
    price: 64.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/gosset-rose.jpg",
    description:
      "A rich and full-bodied sparkling wine with flavors of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Gosset",
    rating: 4.9,
    reviews: "An exceptional sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 92,
    name: "Jacquart Rose",
    price: 39.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/jacquart-rose.jpg",
    description:
      "A fresh and lively sparkling wine with notes of apple, pear, and citrus.",
    category: "Sparkling Wine",
    brand: "Jacquart",
    rating: 4.7,
    reviews: "A delightful sparkling wine, great for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 93,
    name: "Palmer & Co Rose Solera",
    price: 44.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/palmer-co-rose-solera.jpg",
    description:
      "A refined and balanced sparkling wine with notes of white fruit and brioche.",
    category: "Sparkling Wine",
    brand: "Palmer & Co",
    rating: 4.8,
    reviews: "A sophisticated sparkling wine, ideal for special occasions.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 94,
    name: "Bruno Paillard Rose",
    price: 54.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/bruno-paillard-rose.jpg",
    description:
      "A refined and elegant sparkling wine with notes of citrus, white fruit, and brioche.",
    category: "Sparkling Wine",
    brand: "Bruno Paillard",
    rating: 4.8,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 95,
    name: "Alfred Gratien Rose",
    price: 49.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/alfred-gratien-rose.jpg",
    description:
      "A rich and complex sparkling wine with notes of apple, pear, and brioche.",
    category: "Sparkling Wine",
    brand: "Alfred Gratien",
    rating: 4.7,
    reviews: "A delightful sparkling wine, perfect for any celebration.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 96,
    name: "Moet & Chandon Rose Imperial",
    price: 54.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/moet-chandon-rose-imperial.jpg",
    description:
      "A vibrant, generous, and alluring sparkling wine with a perfect balance of flavors.",
    category: "Sparkling Wine",
    brand: "Moet & Chandon",
    rating: 4.8,
    reviews: "A classic and elegant sparkling wine, perfect for celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 97,
    name: "Veuve Clicquot Rose",
    price: 54.99,
    quantity: 30,
    imageUrl: "https://www.example.com/images/veuve-clicquot-rose.jpg",
    description:
      "A harmonious blend of powerful and complex flavors with a long-lasting finish.",
    category: "Sparkling Wine",
    brand: "Veuve Clicquot",
    rating: 4.9,
    reviews: "An exceptional sparkling wine, ideal for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 98,
    name: "Dom Perignon Rose",
    price: 199.99,
    quantity: 15,
    imageUrl: "https://www.example.com/images/dom-perignon-rose.jpg",
    description:
      "A prestigious sparkling wine with a rich and complex flavor profile.",
    category: "Sparkling Wine",
    brand: "Dom Perignon",
    rating: 5.0,
    reviews: "A luxurious sparkling wine, perfect for special celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 99,
    name: "Laurent-Perrier Rose",
    price: 69.99,
    quantity: 20,
    imageUrl: "https://www.example.com/images/laurent-perrier-rose.jpg",
    description:
      "A delicate and fresh sparkling wine with elegant floral and citrus notes.",
    category: "Sparkling Wine",
    brand: "Laurent-Perrier",
    rating: 4.7,
    reviews:
      "A delightful sparkling wine, perfect for toasts and celebrations.",
    origin: "France",
    availability: "In Stock",
  },
  {
    id: 100,
    name: "Perrier-Jouet Blason Rose",
    price: 149.99,
    quantity: 25,
    imageUrl: "https://www.example.com/images/perrier-jouet-blason-rose.jpg",
    description:
      "A lively and elegant sparkling wine with a harmonious blend of flavors.",
    category: "Sparkling Wine",
    brand: "Perrier-Jouet",
    rating: 4.8,
    reviews: "An exquisite sparkling wine, perfect for any occasion.",
    origin: "France",
    availability: "In Stock",
  },
];

module.exports = sparklingWines;
